### ISSUE TITLE
Output interval specification

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMPy#10]
Currently one can only specify a fixed output interval for ME simulation.
It would be beneficial to have a possibility to to also get output values at events.
So it would be best to have the following options:

- constant output interval (current implementation)
- all output values
- Constant output interval + event points

**Comment by t-sommer** [comment]
Option 3 is is actually the default for ME: sample after every step and (additionally) sample after every event. Please re-open if you need extra options.
