### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by t-sommer** [CATIA-Systems/FMPy#100]
Python 2 is being sunsetted by the PSF, and many projects are following suit: https://python3statement.org/.

Some of our dependencies (e.g. numpy) have dropped support for Python 2 in new releases at the end of 2018. We may want to follow suit.

A few questions:

- When should we end python 2.7 support? Is Jan 1 2019 too soon?
- Is this something that downstream projects will be fine with?
- Do we want to do a clean break (my vote) or continue with bugfix releases/LTS for python 2 for a while?

See also #64

Pros:

- we can have [type hints](https://www.python.org/dev/peps/pep-0484/)
- simplified build matrix in CI

**Comment by hugovk** [comment]
About NumPy, see also "NEP 29 — Recommend Python and Numpy version support as a community policy standard":

* https://numpy.org/neps/nep-0029-deprecation_policy.html

**Comment by chrbertsch** [comment]
For us ending python2 support is ok.

**Comment by t-sommer** [comment]
Droped with 407f08a403c6dbf11b8773ddb001d5688b0c60aa.
