### ISSUE TITLE
Exception handling of CVODE 

### ISSUE THREAD

**Issue by FabiJa** [CATIA-Systems/FMPy#102]
As far as I have experienced so far, error during numerical integration with CVODE are only printed to console, but no exception is raised within fmpy. This makes error handling of integration errors impossible.
Therefore I would like to see some error management implemented, at least raising an error within Python, that can be handled in custom code.

**Comment by t-sommer** [comment]
Can you share an FMU with parameters to reproduce the problem?

**Comment by FabiJa** [comment]
I'll try to find a minimal example.

**Comment by chrbertsch** [comment]
Here is an example coming from @FabiJa 
[PT2.zip](https://github.com/CATIA-Systems/FMPy/files/3834955/PT2.zip)

Code: 
```
from fmpy import dump, simulate_fmu
dump('PT2.fmu')
result = simulate_fmu('PT2.fmu', stop_time=100)
```

Error by CVode in Console



[CVODE ERROR]  CVode
  At t = 99.9817, mxstep steps taken before reaching tout.

**Comment by t-sommer** [comment]
Can you try 0650aec5ac21a482bdc71e43edb89224097eb983?

**Comment by t-sommer** [comment]
@chrbertsch, @FabiJa, did you get to try 0650aec5ac21a482bdc71e43edb89224097eb983?
