### ISSUE TITLE
Cryptic error message in fmpy.gui for illegal causality and variability combinations

### ISSUE THREAD

**Issue by markaren** [CATIA-Systems/FMPy#108]
E.g. loading an FMU using fmpy.gui that defines ScalarVariable with causality=calculatedParameter and ~vairiability=fixed~ variability=constant will produce the error: Failed to load path/to/fmu.fmu'. 'calculatedParameter'

**Comment by t-sommer** [comment]
Can you share an FMU to reproduce the problem?

**Comment by markaren** [comment]
Note that I wrote the wrong variability when posting the issue. Updated now. Note that fmpy is right in issuing the error since the causality and variability combination is illegal. However the error message does not directly say why it produces an error. Can share an FMU soon.
