### ISSUE TITLE
Unable to simulate FMU  (using __int__ is deprecated)

### ISSUE THREAD

**Issue by FlorianKarg** [CATIA-Systems/FMPy#109]
I tried to simulate a FMU with the fmpy.gui and got the following message:

Python38\site-packages\fmpy\gui\__main__.py :19: DeprecationWarning: an integer is required (got type Alignment). Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
 sys.exit(app.exec_())

This is the FMU:
--------------------------------------------------------------------------------------------------------
Model Info

  FMI Version       2.0
  FMI Type          Co-Simulation
  Model Name        PID
  Description       A simple PID-Controller
  Platforms         linux64, win64
  Continuous States 0
  Event Indicators  0
  Variables         6
  Generation Tool   PythonFMU
  Generation Date   2020-01-27T15:27:59Z

--------------------------------------------------------------------------------------------------------

Python version: 3.8.1
Mabey this is the reason for the error?

**Comment by t-sommer** [comment]
@FlorianKarg, did you solve the issue?

**Comment by FlorianKarg** [comment]
@t-sommer, no, actually not.
I thought I've fixed it but the problem is still there.

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by FlorianKarg** [comment]
[PID.zip](https://github.com/CATIA-Systems/FMPy/files/4133226/PID.zip)

**Comment by FlorianKarg** [comment]
I'm getting the following error when I'm trying to Simulate the FMU in Python with:
result = simulate_fmu(fmu)

>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\karg\AppData\Roaming\Python\Python38\site-packages\fmpy\simulation.py", line 573, in simulate_fmu
    result = simulateCS(model_description, fmu_args, start_time, stop_time, relative_tolerance, start_values, apply_defa
ult_start_values, input, output, output_interval, timeout, callbacks, debug_logging, visible, step_finished)
  File "C:\Users\karg\AppData\Roaming\Python\Python38\site-packages\fmpy\simulation.py", line 807, in simulateCS
    fmu.instantiate(visible=visible, callbacks=callbacks, loggingOn=debug_logging)
  File "C:\Users\karg\AppData\Roaming\Python\Python38\site-packages\fmpy\fmi2.py", line 246, in instantiate
    self.component = self.fmi2Instantiate(self.instanceName.encode('utf-8'),
  File "C:\Users\karg\AppData\Roaming\Python\Python38\site-packages\fmpy\fmi2.py", line 201, in w
    res = f(*args)
OSError: exception: access violation reading 0x0000000000000010

**Comment by t-sommer** [comment]
Your FMU depends on `python38.dll`. I assume this is the same Python environment you're running it from and that doesn't work. You might be able to run it from another Python environment.

**Comment by FlorianKarg** [comment]
@t-sommer, I am able to run it from Python 3.7
Thank you very much!

But there is still an error message:



>Error processing line 1 of C:\Users\karg\AppData\Roaming\Python\Python38\site-packages\matplotlib-3.1.2-py3.8-nspkg.pth: 
Traceback (most recent call last): 
File "C:\Users\karg\AppData\Local\Programs\Python\Python37\lib\site.py", line 168, in addpackage exec(line) 
File "<string>", line 1, in <module> 
File "C:\Users\karg\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 51, in <module> _w_long = _bootstrap_external._w_long AttributeError: module 'importlib._bootstrap_external' has no attribute '_w_long' Remainder of file ignored

**Comment by t-sommer** [comment]
@FlorianKarg, can you please open a new issue with steps to reproduce the problem?
