### ISSUE TITLE
FMPy segfault after 1020 simulations in Python 3 (but not Python 2)

### ISSUE THREAD

**Issue by Claire-Eleutheriane** [CATIA-Systems/FMPy#110]
I use FMPy to simulate a FMU made with OpenModelica (it consists in 3 equations, no more).
In Python 3 environment, after 1020 or so simulations, the script crashes due to a segmentation error.
This however does not happen in Python 2 environment.
It does not happen at all when simulating the FMU with PyFMI library.
[bug_fmpy_python3_openmodelica.zip](https://github.com/CATIA-Systems/FMPy/files/4134184/bug_fmpy_python3_openmodelica.zip)

**Comment by t-sommer** [comment]
Can you provide the crash dump, so we can see where the access violation originates?

**Comment by Claire-Eleutheriane** [comment]
![segfault_fmpy_openmodelica](https://user-images.githubusercontent.com/40564064/73524894-5be22680-440e-11ea-82b5-1085e5685d75.png)
Please find attached the error I get in command line.

**Comment by dafred94** [comment]
For me (Ubuntu 18.04, Python 3.8), it the segfault happens at simulation 1017. I used ipdb to see where exactly the it happens and I think it is in fmu2instantiate.

Any guidance on extracting a crash dump to upload it here?

**Comment by t-sommer** [comment]
@Claire-Eleutheriane, @dafred94, can you contact the OpenModelica people? I assume that the problem originates somewhere in the FMU, since FMPy only forwards the memory management calls to the native functions of the OS.

**Comment by Claire-Eleutheriane** [comment]
Issue opened at OpenModelica:


Ticket URL: <https://trac.openmodelica.org/OpenModelica/ticket/5894>
OpenModelica <https://trac.openmodelica.org/OpenModelica>



De : Torsten Sommer <notifications@github.com>
Envoyé : vendredi 20 mars 2020 21:07:21
À : CATIA-Systems/FMPy
Cc : Claire-Eleutheriane Gerrer | Phimeca; Mention
Objet : Re: [CATIA-Systems/FMPy] FMPy segfault after 1020 simulations in Python 3 (but not Python 2) (#110)
 



@Claire-Eleutheriane,

@dafred94, can you contact the OpenModelica people? I assume that the problem originates somewhere in the FMU, since FMPy only forwards the memory management calls to the native functions of the OS.
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CATIA-Systems/FMPy/issues/110#issuecomment-601888745",
"url": "https://github.com/CATIA-Systems/FMPy/issues/110#issuecomment-601888745",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dafred94** [comment]
Thank you @Claire-Eleutheriane ! If you need a temporary workaround for this issue, I suggest you try multiprocessing.Pool to simulate in parallel in different processes. This helped me sidestep this issue.

**Comment by Claire-Eleutheriane** [comment]
Thank you for your advise!
Until now I bypassed the issue using Python 2.



De : dafred94 <notifications@github.com>
Envoyé : vendredi 27 mars 2020 10:56:50
À : CATIA-Systems/FMPy
Cc : Claire-Eleutheriane Gerrer | Phimeca; Mention
Objet : Re: [CATIA-Systems/FMPy] FMPy segfault after 1020 simulations in Python 3 (but not Python 2) (#110)
 



Thank you 
@Claire-Eleutheriane ! If you need a temporary workaround for this issue, I suggest you try multiprocessing.Pool to simulate in parallel in different processes. This helped me sidestep this issue.
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CATIA-Systems/FMPy/issues/110#issuecomment-604913291",
"url": "https://github.com/CATIA-Systems/FMPy/issues/110#issuecomment-604913291",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by t-sommer** [comment]
The `instantiate_fmu()` function that we'll introduce in the next release might also be an elegant workaround for your problem (see [efficient_loops.py](https://github.com/CATIA-Systems/FMPy/blob/develop/fmpy/examples/efficient_loops.py) for an example).

**Comment by Claire-Eleutheriane** [comment]
Thank you! When is the next release going to occur?



De : Torsten Sommer <notifications@github.com>
Envoyé : vendredi 3 avril 2020 15:54:59
À : CATIA-Systems/FMPy
Cc : Claire-Eleutheriane Gerrer | Phimeca; Mention
Objet : Re: [CATIA-Systems/FMPy] FMPy segfault after 1020 simulations in Python 3 (but not Python 2) (#110)
 



The instantiate_fmu() function that we'll introduce in the next release might also be an elegant workaround for your problem (see

efficient_loops.py for an example).
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CATIA-Systems/FMPy/issues/110#issuecomment-608446781",
"url": "https://github.com/CATIA-Systems/FMPy/issues/110#issuecomment-608446781",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by t-sommer** [comment]
> When is the next release going to occur?

Hopefully within a few days.

**Comment by t-sommer** [comment]
A workaround exist now in `v0.2.18` with `instantiate_fmu()` and keeping the FMU instance. Please reopen if you've found the root cause for the segmentation fault.
