### ISSUE TITLE
solver step size specification is without effect

### ISSUE THREAD

**Issue by Claire-Eleutheriane** [CATIA-Systems/FMPy#111]
I have a model which requires a small step size to converge.
This model simulates without trouble on OpenModelica, and I export it as a  Model-Exchange FMU.
However, it diverges when simulated with FMPy.
Specifying Euler solver with step size has no effect, nor does specifying CVode solver with relative tolerance.
But specifying the output interval enables to get the small step size required and the FMU converges.
Please find attached the corresponding files: _simulate_fmpy.py_ plots the result when specifying solver&step size (unsatisfying) vs when specifying output_interval (satisfying).
[bug_stepsize_Euler.zip](https://github.com/CATIA-Systems/FMPy/files/4138411/bug_stepsize_Euler.zip)

**Comment by t-sommer** [comment]
Your FMU supports both Model Exchange and Co-Simulation. If you don't specify an FMI type, FMPy will use Co-Simulation by default. Use

```python
simulate_fmu(..., fmi_type='ModelExchange')
```

to use Model Exchange.
