### ISSUE TITLE
Error while simulate SSP with with Integer inputs

### ISSUE THREAD

**Issue by fmahiant** [CATIA-Systems/FMPy#112]
If FMU's in SSP have input variable of type "Integer" then simulate_ssp ends with exception: "'NoneType' object is not subscriptable"

see traceback:
```
    simulate_ssp(ssp_file, step_size=step_size, stop_time=stop_time)
  File "/usr/local/lib/python3.7/site-packages/fmpy/ssp/simulation.py", line 200, in simulate_ssp
    do_step(component, time, step_size)
  File "/usr/local/lib/python3.7/site-packages/fmpy/ssp/simulation.py", line 129, in do_step
    set_value(component, connector.name, connector.value)
  File "/usr/local/lib/python3.7/site-packages/fmpy/ssp/simulation.py", line 37, in set_value
    component.fmu.setInteger(vr, [int(value)])[0]
```

FMUs embedded in ssp are Co-simulation 2.0 . Integer Variable are describe like this:
```
<ScalarVariable name="Probe 3" valueReference="3" description="Integer probe" causality="input" variability="continuous">
   <Integer/>
</ScalarVariable>
```

I suspect the [0] at the end of the line https://github.com/CATIA-Systems/FMPy/blob/d6f042a47d3725cdbdd87aeb4f87d28d290f071a/fmpy/ssp/simulation.py#L37 

Regards,

**Comment by t-sommer** [comment]
Can you share an example SSP to reproduce the problem?
