### ISSUE TITLE
Undefined Variables by FMU import from OpenModelica

### ISSUE THREAD

**Issue by Henrik-AI** [CATIA-Systems/FMPy#113]
By running any FMU created with Openmodelica (OMEdit) with voltages and currents inside, i always receive the error message: 

`Exception: The unit "A" of variable "ground.p.i" (line 100) is not defined.`

`Model Info

  FMI Version       2.0
  FMI Type          Model Exchange
  Model Name        sinevoltage
  Description       
  Platforms         c-code, win64
  Continuous States 0
  Event Indicators  1
  Variables         33
  Generation Tool   OpenModelica Compiler OpenModelica v1.16.0-dev-182-g3c9b7b2a4 (64-bit)
  Generation Date   2020-02-13T18:03:36Z

Default Experiment

  Stop Time         1
  Tolerance         1e-06

Variables (input, output)

Name                Causality              Start Value  Unit     Description`

The Model runs ( with units) in OMEdit, importing and simulating with PyFMI works. But for some reason, the unit transfer to FMPy does not work properly.

Would be thankful for any idea how to fix this :-)

Best regards,

Henrik

**Comment by calbaker** [comment]
This issue affects me but with a temperature variable.

**Comment by t-sommer** [comment]
see #81, #96

**Comment by lochel** [comment]
This was a problem with the OpenModelica FMUs which we finally fixed. Please checkout the upcoming 1.16 release or a nightly build if you are interested in OpenModelica FMUs.
