### ISSUE TITLE
output_interval bypassed by pulses

### ISSUE THREAD

**Issue by Claire-Eleutheriane** [CATIA-Systems/FMPy#114]
The model pulse.mo in attachment uses a pulse current: on for 2.5 seconds, off for 7.5 seconds.
Whatever the output_interval I demand to fmpy.simulate_fmu, I get the output every 2.5 then 7.5 seconds.
It would be nice if output_interval command could supersede this inner clocking.
[output_interval.zip](https://github.com/CATIA-Systems/FMPy/files/4244446/output_interval.zip)

**Comment by t-sommer** [comment]
If you simulate the FMU with 

```python
result = simulate_fmu(..., fmi_type='CoSimulation')
```

you should get exactly the time grid you want.

**Comment by Claire-Eleutheriane** [comment]
Hi Torsten,


I hope your holidays were not disturbed due to lockdowns.


Thanks for your answer, it works! 



Claire-Eleuthèriane



De : Torsten Sommer <notifications@github.com>
Envoyé : vendredi 20 mars 2020 21:02:31
À : CATIA-Systems/FMPy
Cc : Claire-Eleutheriane Gerrer | Phimeca; Author
Objet : Re: [CATIA-Systems/FMPy] output_interval bypassed by pulses (#114)
 



If you simulate the FMU with

result = simulate_fmu(..., fmi_type='CoSimulation')

you should get exactly the time grid you want.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CATIA-Systems/FMPy/issues/114#issuecomment-601887096",
"url": "https://github.com/CATIA-Systems/FMPy/issues/114#issuecomment-601887096",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
