### ISSUE TITLE
FMU logs are not appearing correctly

### ISSUE THREAD

**Issue by tomaszG247** [CATIA-Systems/FMPy#115]
Hi, 

thank you for you work on FMPy. 
 I have been using FMPy to simulate a Modelica FMU with FMPy and it runs for a while before failing with the not so helpful message
`Exception: fmi2DoStep failed with status 3.`

I tried to activate the logs of the FMU setting `loggingOn = True` in the instantiate method call.
The logs are only showing:
```
[OK] %s
[WARNING] %s
[WARNING] %s
[WARNING] %s
[ERROR] %s
[ERROR] %s
[ERROR] %s
```
That suggests something is wrong with the logging routine. I have observed the same issue with some EnergyPlus FMUs.
I don't know another way to see the details of what is going, so please let me know is there is a fix for this or please suggest another way to debug the model.

Best

**Comment by t-sommer** [comment]
The reason for this is that the FMI callback to log messages uses variadic arguments (`...`) that cannot be passed to Python by ctypes:

```C
typedef void      (*fmi2CallbackLogger)        (fmi2ComponentEnvironment componentEnvironment,
                                                fmi2String instanceName,
                                                fmi2Status status,
                                                fmi2String category,
                                                fmi2String message,
                                                ...);
```

The only solution I see to make variadic arguments work is to add a native library to FMPy that calls `vsnprintf()` and forwards the string to Python.

An FMU can easily build the `message` string directly by calling `vsnprintf()`. In FMI 3.0 the variadic arguments will be removed, so this won't be an issue any more.

**Comment by t-sommer** [comment]
Looking at the the output, I'm wondering why the FMU doesn't pass the string directly (as argument `message`) since it seems to be the only variadic argument.

**Comment by tomaszG247** [comment]
Thanks for the prompt reply. If I understand correctly this means it can't be corrected from FMPy side for FMUs version 2.0 ? Any suggestions on options to understand what is going on ?

**Comment by t-sommer** [comment]
@tomaszG247, can you give 98caaeaa47d37404c39c01a84ed743308826679b a spin?

**Comment by tomaszG247** [comment]
Hi, 
I may be doing something wrong but it is giving me
`fatal: reference is not a tree: 98caaeaa47d37404c39c01a84ed743308826679b`

**Comment by tomaszG247** [comment]
Sorry, @t-sommer . Any ideas on this one ?

**Comment by t-sommer** [comment]
Can you share the FMU that causes the problem?

**Comment by tomaszG247** [comment]
[modelica_HP1room_srcmo_Rad_1room_u_HP_Carnot.zip](https://github.com/CATIA-Systems/FMPy/files/4403644/modelica_HP1room_srcmo_Rad_1room_u_HP_Carnot.zip)

**Comment by t-sommer** [comment]
I can run the above FMU without problems:

```python
from fmpy import *

result = simulate_fmu('modelica_HP1room_srcmo_Rad_1room_u_HP_Carnot.fmu', stop_time=1000, output_interval=100)

plot_result(result)
```

Please open a new issue if the problem persists and provide steps to reproduce.
