### ISSUE TITLE
Modestpy support

### ISSUE THREAD

**Issue by IvannikovG** [CATIA-Systems/FMPy#117]
Hello. This issue is only indirectly related to FMPy.
There is a library called modest-py here is the link: https://github.com/sdu-cfei/modest-py.
This library provides parameter estimation using FMUs.

I hope some people are already using modest-py with FMPy and if so i think this will be a good place to share your knowledge here for other people who are looking for the way how to do it.

**Comment by t-sommer** [comment]
So what exactly is the issue?

**Comment by chrbertsch** [comment]
There is a related ticket in the modespy github repo, https://github.com/sdu-cfei/modest-py/issues/52, but I see the effort completely on the modestpy side.

**Comment by t-sommer** [comment]
Closing this in favor of https://github.com/sdu-cfei/modest-py/issues/52. Please open a new issue if you have a concrete problem.
