### ISSUE TITLE
Use 32bit FMUs in 64bit Windows

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMPy#119]
We have FMUs that can only be compiled for 32bit (they contain code meant for a 32bit microcontroller). We have a small cosimulation tool based on fmpy, and want to run these 32bit FMUs together with proper 64bit FMUs. It would be great if fmpy would directly support this, (as for example Silver does), so we don't have to write our own 32bit to 64bit wrapper code.

**Comment by t-sommer** [comment]
I've created a prototype in https://github.com/CATIA-Systems/FMPy/tree/remoting that let's you simulate `win32` FMI 2.0 Co-Simulation FMUs in a 64-bit Python.

**Comment by fajansen** [comment]
Closed with 0.2.18
