### ISSUE TITLE
Add license information in utils.add_remoting

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMPy#121]
When using the add_remoting function, the precompiled client.dll and server.exe are added to the FMU. These are licensed according to the LICENSE.txt. To make complying with clause 2 of the license easy, the license information should be added to the FMU automatically together with the client.dll and the server.exe

**Comment by t-sommer** [comment]
@fajansen, does bbe567567747711fca5dc3a36a441abee424bdeb work for you?

**Comment by fajansen** [comment]
Looks good :)
