### ISSUE TITLE
fmi2SetupExperiment is no longer being called for CS

### ISSUE THREAD

**Issue by clegaard** [CATIA-Systems/FMPy#122]
It appears that fmi2SetupExperiment is no longer being called before fmi2EnterInitializationMode, which was previously the case.

This appears to have happened in version 0.2.18:
https://github.com/CATIA-Systems/FMPy/blob/bc6f9243dc1ec7fe1ac4890cc44816a050e1496d/fmpy/simulation.py#L914-L921

The standard specifies this function must be called before fmi2EnterIntilizationMode (2.1.16, p.22) :
```
This function must be called after fmi2Instantiate and before fmi2EnterInitializationMode is called.
Arguments toleranceDefined and tolerance depend on the FMU type:
```

**Comment by t-sommer** [comment]
@clegaard, can you check if dc6d01ba5787b4f3863750afa7d8490ba4be928c works for you?

**Comment by clegaard** [comment]
@t-sommer it seems like the changes did the trick.
Thank you for resolving the issue so quickly :)
