### ISSUE TITLE
Uptate hint in release notes of fmpy 0.2.10 w.r.t. to availability on conda-forge for win64

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMPy#130]
at least for win64 fmpy is available on conda-forge https://anaconda.org/conda-forge/fmpy but fmpy-base is not https://anaconda.org/conda-forge/fmpy-base

**Comment by t-sommer** [comment]
Fixed with https://github.com/conda-forge/fmpy-feedstock/commit/97f0857bd31972f39bf7ac7c17e5268a8162f275
