### ISSUE TITLE
Associaiton of gui with *.fmu files does not work

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMPy#131]
I had previously the used this feature of for fmpy being the default application to open FMUs (with fmpy 0.2.17 from an Anaconda virtual environment)

Now with  fmpy  (0.2.19, installed in a different  Anaconda virtual environment) I invoked "Associaition with *.fmu" again. But now it does not work; double-clicking on an FMU file shows no reaction. 

Could this be a problem with the activation of virtual environments of Anaconda Python?

**Comment by t-sommer** [comment]
@chrbertsch, can you give 964280f1085d9d524c233609d67875e7b052a7f0 a try?

**Comment by chrbertsch** [comment]
> @chrbertsch, can you give [964280f](https://github.com/CATIA-Systems/FMPy/commit/964280f1085d9d524c233609d67875e7b052a7f0) a try?

works like a charm 👍
