### ISSUE TITLE
fmpy.gui does not allow setting of tolerance under Python3

### ISSUE THREAD

**Issue by christiankral** [CATIA-Systems/FMPy#132]
I installed FMPy under Python2 and Python3 on my Linux Mint 19 machine. Even though the Python2 version works just fine, the Python3 version does not allow to set the tolerance in the GUI. I tested this behavior with the same Linux FMU `Rectifier.fmu`.

Python2 settings obtained by `python -m fmpy.gui`

![image](https://user-images.githubusercontent.com/4184218/80858999-c436e300-8c5d-11ea-9f51-a410954921ef.png)

Python3 settings obtained by `python3 -m fmpy.gui`

![image](https://user-images.githubusercontent.com/4184218/80859019-e16bb180-8c5d-11ea-8259-33a41db9c1da.png)

However, when I operate FMPy from the Python3 environment I can run the simulation with a tolerance different than the default one:

```python
result = simulate_fmu(fmu, relative_tolerance = 1E-6)
```

**Comment by t-sommer** [comment]
@christiankral, can you reproduce this problem with the latest version of FMPy?

**Comment by christiankral** [comment]
I checked the installed version:

```bash
> pip3 list | grep FMPy
FMPy                  0.2.19
``` 

and started `$> python3 -m fmpy.gui`

![image](https://user-images.githubusercontent.com/4184218/80943675-0d1aa300-8de8-11ea-8501-85078db4a36b.png)

OK, why version 2.10? After half an hour of fiddling around with uninstalling, installing and upgrading packages it is now OK.

![image](https://user-images.githubusercontent.com/4184218/80945619-78ff0a80-8dec-11ea-9109-ba3ceb9cc768.png)

@t-sommer Thanks for your hint. This solved my problem. It seems to have been an issue of my particular installation. I am closing the issue then.
