### ISSUE TITLE
Save trajectories as csv?

### ISSUE THREAD

**Issue by AHaumer** [CATIA-Systems/FMPy#137]
I'd like to propose an enhancement: Would it be possible to save trajectories as csv?

**Comment by t-sommer** [comment]
This is already supported:

### GUI:

`File > Save Result`

### CLI:

`fmpy simulate MyModel.fmu --output-file MyModel_out.csv`

### Python:

```Python
from fmpy import *
result = simulate_fmu('MyModel.fmu')
write_csv('MyModel_out.csv', result)
```

**Comment by AHaumer** [comment]
Thanks for the hint - I didn't figure that out. 
But I don't want to save ALL results - only plotted - this gives an error (#138).
Looking forward to the bugfix ...
Once again: great tool!
