### ISSUE TITLE
File > Save Plotted Result fails

### ISSUE THREAD

**Issue by t-sommer** [CATIA-Systems/FMPy#138]
with the following error "Failed to write ... no field of name"

**Comment by AHaumer** [comment]
Just installed the latest version, still receiving the same error message when using "Save Plotted Result":
"Failed to write xxx, no field of name".

**Comment by t-sommer** [comment]
To use features that have not been released yet, you have to install FMPy from the `develop` branch:

```
python -m pip install https://github.com/CATIA-Systems/FMPy/archive/develop.zip
```
