### ISSUE TITLE
Instantiation creates segfault

### ISSUE THREAD

**Issue by Claire-Eleutheriane** [CATIA-Systems/FMPy#140]
While trying FMPy 0.2.19, I found out that FMUs produced by OpenModelica are not standard-conform (the UnitDefinition part of the .xml does not exist).
FMPy raises an error in instantiation due to this.
I circumvented the error by editing the FMPy code so that only warnings are printed.
I can thus instantiate my FMU without trouble but... I get a segfault after one simulation!
Please find attached the FMU and code showing this.

[fmpy.zip](https://github.com/CATIA-Systems/FMPy/files/4634720/fmpy.zip)

**Comment by t-sommer** [comment]
Does this FMU run in any other tool?

**Comment by Claire-Eleutheriane** [comment]
Yes, it does with FMPy 0.2.17 ( segfaults only happen after 1024 runs).



De : Torsten Sommer <notifications@github.com>
Envoyé : samedi 16 mai 2020 22:24:31
À : CATIA-Systems/FMPy
Cc : Claire-Eleutheriane Gerrer | Phimeca; Author
Objet : Re: [CATIA-Systems/FMPy] Instantiation creates segfault (#140)
 



Does this FMU run in any other tool?
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CATIA-Systems/FMPy/issues/140#issuecomment-629701344",
"url": "https://github.com/CATIA-Systems/FMPy/issues/140#issuecomment-629701344",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by t-sommer** [comment]
@Claire-Eleutheriane, have you tried to re-use the FMU instance? See [efficient_loops.py](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/efficient_loops.py) for an example.

**Comment by Claire-Eleutheriane** [comment]
Yes. I initiate before the loop. In the loop, I apply fmu_instance.reset() and simulate_fmu(unzipdir, fmu_instance=fmu_instance).


I bet the segfault happens due to fmu_instance.reset(). 

If I place the reset before the simulate_fmu command, 0 simulation is performed.
If I place it after the simulate_fmu command, 1 simulation is performed.



De : Torsten Sommer <notifications@github.com>
Envoyé : lundi 18 mai 2020 16:34:13
À : CATIA-Systems/FMPy
Cc : Claire-Eleutheriane Gerrer | Phimeca; Mention
Objet : Re: [CATIA-Systems/FMPy] Instantiation creates segfault (#140)
 



@Claire-Eleutheriane,
 have you tried to re-use the FMU instance? See 
efficient_loops.py for an example.
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CATIA-Systems/FMPy/issues/140#issuecomment-630223495",
"url": "https://github.com/CATIA-Systems/FMPy/issues/140#issuecomment-630223495",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by t-sommer** [comment]
This seems to be a problem with the FMU. Please open an issue on https://github.com/OpenModelica/OpenModelica.
