### ISSUE TITLE
Time Event Detection

### ISSUE THREAD

**Issue by dieggar** [CATIA-Systems/FMPy#141]
Thanks in advance for the support. Sorry if this is not the forum to ask this question.

I would like to know how does the time event detections work in FMPY for Model Exchange. Debugging my project, I have realised that if I plan the following time event, for example, at 2.5 seconds (using fmi2eventInfo struct in fmi2NewDiscreteStates function), the integration does not directly integ to this time instant when the integration is near the time event.

However, it iterates and takes steps after and before the time event (I have realised that by debugging the fmi2SetTime function calls) and finally the integrator calls the fmi2EnterEventMode function at the time instant of the time event.

Is this correct or am I doing something wrong?

**Comment by t-sommer** [comment]
> However, it iterates and takes steps after and before the time event (I have realised that by debugging the fmi2SetTime function calls) and finally the integrator calls the fmi2EnterEventMode function at the time instant of the time event.

>Is this correct or am I doing something wrong?

The step size is determined by the solver, so what you describe is the expected behaviour.
However fmi2EnterEventMode is called by FMPy (not the solver).

**Comment by t-sommer** [comment]
If you want to reduce intermediate solver steps you can set `output_interval == stop_time` in `simulate_fmu()`.
