### ISSUE TITLE
ModelDesciption verification issue with ScheduledCoSimulation

### ISSUE THREAD

**Issue by GaneshShenoy** [CATIA-Systems/FMPy#142]
I was trying to debug the clock https://github.com/modelica/Reference-FMUs/tree/master/Clocks with develop branch of FMpy using gui, i get the below message.

Failed to load D:/playground/modelica/Reference-FMUs/fmi30_86/dist/Clocks.fmu. Variable "inClock1" (line 14) has an illegal combination of causality="input" and variability="clock".

**Comment by t-sommer** [comment]
FMPy has no support for Scheduled Execution FMUs at the moment. I'll leave this issue open as a reminder.

**Comment by t-sommer** [comment]
Fixed with 18aae741b28dd913c58ac10c2906376d547185f9
