### ISSUE TITLE
doStep equivalent for ME FMU

### ISSUE THREAD

**Issue by githubfrond** [CATIA-Systems/FMPy#143]
Great library and setup, really getting alot out of using it. Thanks for creating.
My 'issue' is not really a problem with the package, and I'm not yet knowledgeable enough to suggest it as a 'feature' request.  

There is no obvious doStep equivalent for the ME FMU, so I am having to dissect the library to make one, or write an inefficient iterator around simulate_fmu.  I hope I haven't missed anything obvious.

I think I can look very carefully into the way the simulateME is structured, and eventually I will determine how to "rip out" something like a doStep action over a defined time interval, but it seems to me that there might be some utility for others in being able to have access to an efficient doStep for an ME FMU, without having to write special harnesses.  I'm not sure just using an iterator around simulate_fmu is very efficient, which is how I'm approaching it now.  Apologies if I have missed some obvious function in the code to do this.

Feel free to down grade or dismiss this issue, as I may be the only one dealing with this right now. 
Thanks , Craig

**Comment by t-sommer** [comment]
@githubfrond, can you describe your use case, maybe with some example code? If you want to interact with the FMU after every step, you can use the [`step_finished()`](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/simulation.py#L449) callback.

**Comment by hewsond** [comment]
Hi, I have a similar usecase in mind and am also currently trying to follow through the simulateME function. For my usecase it probably might be the case that it just makes sense to write a besboke sim function. 

The usecase is as follows, we would like to run FMUs in a psuedoparallel fashion. Now obviously there are huge constraints about the algebraic loops and relations between the variables. In this specific case I have some system which we know has relations between the inputs and outputs. However choosing a solver such as a forward euler with sufficient dt we know that the system can be simulated. Therefore I'd like to be able to:

1. Spin up in either two threads, processes or whatever FMUs that need to be connected.
2. Connect them together with some interface.
3. Share 'boundary conditions' between the two FMUs.
4. Advance forwards in time
5. While before end time goto step 3

There's probably alot of you really shouldn't do that which is fair but that's the usecase I'm looking at doing.

**Comment by t-sommer** [comment]
@hewsond, for your usecase (a master algorithm with multiple connected Model Exchange FMUs) you're probably better off writing your own simulation loop. Also keep in mind that running multiple FMUs in the same process using multithreading proved problematic with a lot of models.
