### ISSUE TITLE
[Enhancement] FMPy core build as C library

### ISSUE THREAD

**Issue by andre2007** [CATIA-Systems/FMPy#144]
It would be highly interesting if the core of FMPy would be written as C library with a thin python layer on top. The python package `FMPy` would profit due to better performance. For the `FMPy` python user base nothing would change from a usability / interface perspective.

But the major impact would be, that every programming language, able to call a C library, now would have access to your great library `FMPy`.

In my case it is not even a performance question but a security / vulnerability question. By having your library in a compiled form with C interface I would be able to run simulations in so called docker `scratch` containers.

**Comment by t-sommer** [comment]
> It would be highly interesting if the core of FMPy would be written as C library with a thin python layer on top.

Take a look at [PyFMY](https://github.com/modelon-community/PyFMI). They're doing exactly that.

> The python package FMPy would profit due to better performance.

How?

> But the major impact would be, that every programming language, able to call a C library, now would have access to your great library FMPy.

FMI _is_ a C interface. What would be the point of wrapping it in another C interface?

**Comment by andre2007** [comment]
In your python code where you have while loops containing complex coding, you would gain some speed, like here: https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/simulation.py#L938-L953

While FMI has a C interface the functions are quite low level. You need a deep knowledge how they interact with each other. It is quite impossible to find an example.
On the other hand you wrote a library with a quite nice high level API. If this API would also be available from a C library, this would allow to easily interact with FMU from almost any programming language, not just from python only.

**Comment by t-sommer** [comment]
FMPy is (and will remain) a Python library that is tightly integrated with Python (ctypes) and popular libraries (e.g. NumPy). It intentionally uses as little native code as possible to provide maximum flexibility for prototyping and customization.

There are plenty of FMI libraries for other languages (see e.g. https://github.com/traversaro/awesome-fmi).
