### ISSUE TITLE
Fmu crashes the python interpreter on freelibrary

### ISSUE THREAD

**Issue by filip-jezek** [CATIA-Systems/FMPy#147]
I have certain FMU2 CS generated from Dymola 2021, which does strangely break the anaconda python runtime. Tested in jupyter {kills the kernel) and running as separate python module in anaconda prompt (ends prematurely without any exception or error code).

After some investigation, I found the break point to be self.freeLibrary() in freeInstance method of fmi2.py 

Strange enough, when stepping through line by line with VS CODE, the computation works. When running F5, it breaks.

The FMU can be grabbed from here https://drive.google.com/file/d/14iGfSHms4Xhk_P0v-kdXVPYCc6M98Rob/view?usp=sharing and the code at https://gist.github.com/filip-jezek/94664540f9ed7d03cde4824c71fefae9

I am running win10 64b with conda 4.8.3 and python 3.7.7, however I reproduced this in different machine as well.

Is a workaround option not to unload the library? I plan on calling the script hundreds times from external optimization tool, so memory leak might be a catch here.

Thanks for resolving, workaround or any help.

**Comment by t-sommer** [comment]
As a quick workaround you could simply monkey patch the FMU instance and replace freeInstance() with a noop.

**Comment by filip-jezek** [comment]
Thanks for the workaround. Do you think that having hundreds of dangling instances of the same class would cause troubles? I need to call all this via external batch, so I cannot really reuse the instance.

Thanks!

**Comment by t-sommer** [comment]
With the "efficient_loops" approach it would only be one instance that is being re-used for each run, so I would not expect it to cause a lot of problems.

**Comment by t-sommer** [comment]
I have forwarded the issue to @karlwernersson of the Dymola team, so they can fix the problem in the FMU export.

**Comment by filip-jezek** [comment]
Well, I am familiar with the efficient loops example, but when the script is called from an outside command-line caller (GenOpt optimization) a hundred times, the instance could not be reused (or could it? How?) 

Strangely, when running from fmpy.gui, the FMU is simulated (and apparently also released) correctly. So I am unsure if it really is a Dymola's problem. 

In searching for workaround I found, that running the model in ME mode (with CVODE and same settings - tolerance 1e-7, output interval 0.02) is about five fold slower and stops with an error: 
CVode error (code -3) in module CVODE, function CVode: At t = 3.97864 and h = 1.92358e-10, the error test failed repeatedly or with |h| = hmin. Clearly, the cvode here is then different (less robust) from the CVODE in Dymola. Is it meant to have the same CVODE capabilities, or should we just use the co-simulation instead?

thanks!
F/

**Comment by t-sommer** [comment]
@filip-jezek, can we close this issue?

**Comment by filip-jezek** [comment]
I think its basically the same issue. For future readers, the bug is related to Dymola CVODE export and should be resolved in 2022 version. It has been suggested elsewhere not to use Advanced.SparseActivate=true for Dymola CVODE translation. 

Closing.
