### ISSUE TITLE
CVode stalling

### ISSUE THREAD

**Issue by Tony607** [CATIA-Systems/FMPy#149]
Hi,
Thank you for your work on FMPy. I have been able to use FMPy to simulate several model exchange FMUs, however given one FMU and inputs, CVode stalls around a specific time point where the step size becomes very small and unable to get out of the time point.
If you force to stop the program it prints,
```shell
RuntimeError: CVode error (code -12) in module CVODE, function cvRcheck3: At t = 0.250002, the rootfinding routine failed in an unrecoverable manner.
```
- FMPy version: 0.2.19
- Python version:  3.6.7
- OS: Linux64

To reproduce the issue, download the attached file, unizip it and run the python script.

[FMpy_stall_issue.zip](https://github.com/CATIA-Systems/FMPy/files/4817781/FMpy_stall_issue.zip)
```
python3 FMpy_2in_2out.py
```
I also tried simulating the same FMU with the [PyFMI](https://github.com/modelon-community/PyFMI) library calling CVode solver and can finish the simulation within a second. The PyFMI test script is also provided for comparison.
```
python3 FMpy_2in_2out.py
```
Best

**Comment by t-sommer** [comment]
I assume this is because Assimulo uses different default settings for CVode (see https://github.com/modelon-community/Assimulo/blob/master/src/solvers/sundials.pyx#L1469). Do you have a suggestions which parameter might make a difference here?

**Comment by t-sommer** [comment]
@Tony607, can you try to export the same FMU without inputs (i.e. generate them internally) to see if #150 would solve the problem?

**Comment by Tony607** [comment]
> @Tony607, can you try to export the same FMU without inputs (i.e. generate them internally) to see if #150 would solve the problem?

@t-sommer Thanks for the quick replay. As you expected, exporting the same FMU without inputs (i.e. generate them internally) solves the stalling issue.

Attached the newly exported FMU as well as the test scripts for both FMPy and PyFMI.

[FMpy_stall_issue_interal_inputs.zip](https://github.com/CATIA-Systems/FMPy/files/4822819/FMpy_stall_issue_interal_inputs.zip)

Simulating the FMU with external inputs by setting either Newton or FixedPoint as CVode's Nonlinear solver in PyFMI(Assimulo) has no problem.

**Comment by Tony607** [comment]
I also found by changing this line https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/simulation.py#L821 from
```python
input.apply(time, discrete=False)
```
to
```python
input.apply(t_next, discrete=False)
```
also solves the stalling problem for FMU with external inputs. But there might be a better way to solve the problem.

Best

**Comment by t-sommer** [comment]
@Tony607, can you give 79d01cc7b8020a54be3adc559b5b051c2338605f at try?

Note that the binaries are not included in the repo any more, so you have to build them yourself or install[ a development build](https://github.com/CATIA-Systems/FMPy/blob/150-extrapolate-inputs/docs/faq.md#how-do-i-install-a-development-build).

**Comment by Tony607** [comment]
> @Tony607, can you give [79d01cc](https://github.com/CATIA-Systems/FMPy/commit/79d01cc7b8020a54be3adc559b5b051c2338605f) at try?
> 
> Note that the binaries are not included in the repo any more, so you have to build them yourself or install[ a development build](https://github.com/CATIA-Systems/FMPy/blob/150-extrapolate-inputs/docs/faq.md#how-do-i-install-a-development-build).

Worked like a charm, thanks for your hard work!
