### ISSUE TITLE
Question: Output all variables

### ISSUE THREAD

**Issue by AnHeuermann** [CATIA-Systems/FMPy#155]
Is it possible to output all variables to the result file?

Without ` --output-variables` set only variables with causality output will be saved. Of course I can simply add all variables to my call:
```bash
$fmpy simulate someFMU.fmu --output-file someFMU_res.csv --output-variables "var1" "var2"
```
But that is a bit inconvenient when there are a lot of variables.

**Comment by t-sommer** [comment]
To save the trajectories of all variables to a CSV file you can simulate your FMU in the FMPy GUI and select `File > Save Result...`.

**Comment by AnHeuermann** [comment]
Is it possible to do from the shell as well? I want to use it inside some script to verify our FMUs for fmi-cross-check before running `python -m fmpy.cross_check.validate_vendor_repo --clean-up` on everything.

**Comment by t-sommer** [comment]
This should do what you want:

```python
from fmpy import *
import os
import sys

# first argument is the path to the FMU
filename = sys.argv[1]

# save the CVS next to the FMU
csv_file, _ = os.path.splitext(filename)
csv_file += '_out.csv'

model_description = read_model_description(filename)

output = []

# collect the variables to log
for variable in model_description.modelVariables:
    if variable.causality in {'input', 'output', 'local'}:
        output.append(variable.name)

# simulate the FMU
result = simulate_fmu(filename, output=output)

# write the CSV
write_csv(csv_file, result)
```

Save it as `log_variables.py` and run it with

```
python log_variables.py /path/to/my.fmu
```
