### ISSUE TITLE
FMPy.gui clear simulation settings

### ISSUE THREAD

**Issue by Maplesoft-fmigroup** [CATIA-Systems/FMPy#157]
The simulation settings (such as "Apply default start values" or "Input") should go back to 'default' values when a new .fmu is opened.  Currently, if you open a new FMU it runs with the settings used in a previous model.

**Comment by t-sommer** [comment]
As a workaround you can open the other FMU in a new Window `File > New Window`or `CRTL+SHIFT+N`.
