### ISSUE TITLE
ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by Flancis** [CATIA-Systems/FMPy#16]
Hi,

While trying to run the [example](https://github.com/CATIA-Systems/FMPy) with the option "Simulate an FMU in Python", it gives the following error.
>>> plot_result(result)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\fmpy\util.py", line 299, in plot_result
    fig.set_size_inches(w=8, h=1.5 * len(names), forward=True)
  File "C:\Python27\lib\site-packages\matplotlib\figure.py", line 667, in set_size_inches
    w, h = args
ValueError: need more than 0 values to unpack

**Comment by t-sommer** [comment]
Does the variable `result` contain any data? It should look like this:

```
>>> result = simulate_fmu(fmu)
>>> result
array([( 0.    ,  282.84271247), ( 0.0002,  279.50415444),
       ( 0.0004,  276.18412444), ( 0.0006,  272.91586236),
       ( 0.001 ,  266.55164241), ( 0.0012,  263.4007149 ),
       ...
       ( 0.0996,  260.10610442), ( 0.0998,  259.08044638),
       ( 0.1   ,  258.51461355)],
      dtype=[('time', '<f8'), ('outputs', '<f8')])
>>>
```

**Comment by Flancis** [comment]
It has the following data.

`>>> result = simulate_fmu(fmu)
>>> result
array([(0.    , 282.84271247), (0.0002, 279.50415444),
       (0.0004, 276.18412444), (0.0006, 272.91586236),
       (0.001 , 266.55164241), (0.0012, 263.4007149 ),
       (0.0014, 260.19377457), (0.0016, 256.87504161),
       (0.0018, 253.53799044), (0.002 , 250.20858021),
       (0.0022, 247.01749935), (0.0024, 244.18026082),
       (0.0026, 241.88397056), (0.0028, 240.2794737 ),
       (0.003 , 239.47773394), (0.0032, 239.5472031 ),
       (0.0034, 240.51223707), (0.0036, 242.35259046),
       (0.0038, 245.00399805), (0.0042, 252.27375638),
       (0.0046, 261.01497737), (0.005 , 269.42317064),
       (0.0054, 275.39020966), (0.0058, 277.25939464),
       (0.0062, 275.17100521), (0.0066, 272.91953161),
       (0.007 , 271.29753011), (0.0074, 270.31267704),
       (0.0078, 269.52698295), (0.008 , 268.96145533),
       (0.0082, 268.10649508), (0.0084, 266.81081651),
       (0.0086, 264.91479581), (0.0088, 262.34360277),
       (0.009 , 259.45860928), (0.0092, 256.73718458),
       (0.0094, 254.34878737), (0.0096, 252.43099968),
       (0.0098, 251.08624922), (0.01  , 250.37941614),
       (0.0102, 250.336376  ), (0.0104, 250.94350864),
       (0.0106, 252.14818085), (0.0108, 253.86018865),
       (0.011 , 255.9541234 ), (0.0112, 258.27260543),
       (0.0114, 260.63030917), (0.0116, 262.81868644),
       (0.0118, 264.61127883), (0.012 , 265.78672249),
       (0.0122, 266.23146127), (0.0124, 265.87308203),
       (0.0126, 264.7369423 ), (0.0128, 263.62011937),
       (0.013 , 262.78756536), (0.0132, 262.31015135),
       (0.0134, 262.22607217), (0.0136, 262.5399964 ),
       (0.0138, 263.22305901), (0.014 , 264.21369409),
       (0.0142, 265.41928612), (0.0144, 266.71859972),
       (0.0146, 267.96493044), (0.0148, 268.98990285),
       (0.015 , 269.60782794), (0.0152, 269.62051919),
       (0.0154, 268.85249454), (0.0156, 267.25228466),
       (0.0158, 264.99788403), (0.0162, 260.87791262),
       (0.0166, 258.19791691), (0.017 , 257.44483644),
       (0.0174, 258.54125894), (0.0178, 260.85806454),
       (0.0182, 263.28164485), (0.0186, 264.33372312),
       (0.019 , 262.797355  ), (0.0194, 259.58732051),
       (0.0198, 257.68811966), (0.0202, 257.71191517),
       (0.0206, 259.64363002), (0.021 , 262.90955208),
       (0.0214, 266.43768875), (0.0218, 268.76760378),
       (0.0222, 268.34458253), (0.0226, 264.93387873),
       (0.023 , 261.73386583), (0.0234, 260.02276105),
       (0.0238, 260.07157856), (0.0242, 261.60311052),
       (0.0246, 263.82408922), (0.025 , 265.50862646),
       (0.0254, 265.17109163), (0.0258, 262.05269836),
       (0.0262, 258.71659896), (0.0266, 257.00529199),
       (0.027 , 257.31929709), (0.0274, 259.48670739),
       (0.0278, 262.78419728), (0.0282, 266.01252382),
       (0.0286, 267.62130663), (0.029 , 266.27997825),
       (0.0294, 262.81205134), (0.0298, 260.35160284),
       (0.0302, 259.58368556), (0.0306, 260.56438494),
       (0.031 , 262.80468396), (0.0314, 265.32327942),
       (0.0318, 266.74840368), (0.0322, 265.62959835),
       (0.0326, 261.98333276), (0.033 , 258.95930677),
       (0.0334, 257.66699862), (0.0338, 258.33897062),
       (0.0342, 260.64184963), (0.0346, 263.71354666),
       (0.035 , 266.25283289), (0.0354, 266.69319922),
       (0.0358, 264.11067101), (0.0362, 260.84604467),
       (0.0366, 259.01847532), (0.037 , 259.03996205),
       (0.0374, 260.76550016), (0.0378, 263.51161998),
       (0.0382, 266.12829688), (0.0386, 267.11959256),
       (0.039 , 265.22157792), (0.0394, 261.5317121 ),
       (0.0398, 259.01202254), (0.0402, 258.30305931),
       (0.0406, 259.45493306), (0.041 , 261.96282356),
       (0.0414, 264.82125148), (0.0418, 266.62808209),
       (0.0422, 265.89853096), (0.0426, 262.51102052),
       (0.043 , 259.60937348), (0.0434, 258.38146073),
       (0.0438, 259.05456964), (0.0442, 261.29565021),
       (0.0446, 264.24846879), (0.045 , 266.62263217),
       (0.0454, 266.86539335), (0.0458, 264.08390881),
       (0.0462, 260.70862975), (0.0466, 258.78323166),
       (0.047 , 258.72823066), (0.0474, 260.4052054 ),
       (0.0478, 263.13476999), (0.0482, 265.76814149),
       (0.0486, 266.80789643), (0.049 , 264.9913679 ),
       (0.0494, 261.37440836), (0.0498, 258.93529779),
       (0.0502, 258.31312153), (0.0506, 259.55031693),
       (0.051 , 262.1345706 ), (0.0514, 265.05374799),
       (0.0518, 266.90047665), (0.0522, 266.18342489),
       (0.0526, 262.77558214), (0.053 , 259.82894977),
       (0.0534, 258.53704365), (0.0538, 259.1329057 ),
       (0.0542, 261.29036745), (0.0546, 264.16059105),
       (0.055 , 266.46043961), (0.0554, 266.64451856),
       (0.0558, 263.8336005 ), (0.0562, 260.47046813),
       (0.0566, 258.57807876), (0.057 , 258.57390625),
       (0.0574, 260.31494036), (0.0578, 263.1160735 ),
       (0.0582, 265.82217897), (0.0586, 266.92935583),
       (0.059 , 265.16641876), (0.0594, 261.56234163),
       (0.0598, 259.11535282), (0.0602, 258.4695175 ),
       (0.0606, 259.66945906), (0.061 , 262.20623106),
       (0.0614, 265.07194274), (0.0618, 266.86396331),
       (0.0622, 266.09643707), (0.0626, 262.65992709),
       (0.0628, 261.0114037 ), (0.063 , 259.70669771),
       (0.0632, 258.82693602), (0.0634, 258.41898921),
       (0.0636, 258.49443467), (0.0638, 259.02940218),
       (0.064 , 259.96530247), (0.0642, 261.21041932),
       (0.0644, 262.64232635), (0.0646, 264.11107117),
       (0.0648, 265.44305235), (0.065 , 266.4454991 ),
       (0.0652, 266.91147005), (0.0654, 266.66520561),
       (0.0656, 265.64954662), (0.0658, 263.88429697),
       (0.066 , 262.07257119), (0.0662, 260.53256704),
       (0.0664, 259.36713535), (0.0666, 258.64604303),
       (0.0668, 258.4043605 ), (0.067 , 258.64172007),
       (0.0672, 259.32245906), (0.0674, 260.37664138),
       (0.0676, 261.70193168), (0.0678, 263.16627679),
       (0.068 , 264.61133122), (0.0682, 265.85654671),
       (0.0684, 266.70383122), (0.0686, 266.94495988),
       (0.0688, 266.44465807), (0.069 , 265.16178624),
       (0.0692, 263.28355213), (0.0694, 261.54617729),
       (0.0696, 260.11785232), (0.0698, 259.09070751),
       (0.07  , 258.52316565), (0.0702, 258.43861517),
       (0.0704, 258.82496082), (0.0706, 259.63505903),
       (0.0708, 260.78802545), (0.071 , 262.17138177),
       (0.0712, 263.64399098), (0.0714, 265.03971174),
       (0.0716, 266.17168693), (0.0718, 266.83716739),
       (0.072 , 266.83610946), (0.0722, 266.07766358),
       (0.0724, 264.52484809), (0.0726, 262.64909406),
       (0.0728, 261.00390244), (0.073 , 259.70268316),
       (0.0732, 258.8264854 ), (0.0734, 258.42210056),
       (0.0736, 258.50102716), (0.0738, 259.03931817),
       (0.074 , 259.97831124), (0.0742, 261.22622244),
       (0.0744, 262.66056452), (0.0746, 264.13133237),
       (0.0748, 265.46488114), (0.075 , 266.46840685),
       (0.0752, 266.93494525), (0.0754, 266.68862563),
       (0.0756, 265.67222058), (0.0758, 263.90567005),
       (0.076 , 262.09232757), (0.0762, 260.55027464),
       (0.0764, 259.38240893), (0.0766, 258.65855252),
       (0.0768, 258.41383814), (0.077 , 258.64796616),
       (0.0772, 259.3253461 ), (0.0774, 260.3761167 ),
       (0.0776, 261.69801832), (0.0778, 263.15907277),
       (0.078 , 264.60100707), (0.0782, 265.84334152),
       (0.0784, 266.68804705), (0.0786, 266.92696615),
       (0.0788, 266.42497226), (0.079 , 265.14099488),
       (0.0792, 263.26271045), (0.0794, 261.525972  ),
       (0.0796, 260.09872872), (0.0798, 259.07308544),
       (0.08  , 258.50743031), (0.0802, 258.42510869),
       (0.0804, 258.81397481), (0.0806, 259.62682833),
       (0.0808, 260.78272307), (0.081 , 262.16911534),
       (0.0812, 263.64480051), (0.0814, 265.04356899),
       (0.0816, 266.17849629), (0.0818, 266.84676817),
       (0.082 , 266.84825694), (0.0822, 266.09199306),
       (0.0824, 264.54090983), (0.0826, 262.66546204),
       (0.0828, 261.02021319), (0.083 , 259.71857568),
       (0.0832, 258.84160916), (0.0834, 258.43612325),
       (0.0836, 258.51364194), (0.0838, 259.05025042),
       (0.084 , 259.98732451), (0.0842, 261.23312358),
       (0.0844, 262.66520777), (0.0846, 264.13362249),
       (0.0848, 265.46477529), (0.085 , 266.4659154 ),
       (0.0852, 266.93013149), (0.0854, 266.68162728),
       (0.0856, 265.66325147), (0.0858, 263.89534126),
       (0.086 , 262.08152002), (0.0862, 260.53922927),
       (0.0864, 259.37137112), (0.0866, 258.64776666),
       (0.0868, 258.40354223), (0.087 , 258.63838655),
       (0.0872, 259.31669253), (0.0874, 260.36857768),
       (0.0876, 261.69175707), (0.0878, 263.15422364),
       (0.088 , 264.59767273), (0.0882, 265.84159072),
       (0.0884, 266.68791326), (0.0886, 266.92844625),
       (0.0888, 266.42801777), (0.089 , 265.1455107 ),
       (0.0892, 263.26806112), (0.0894, 261.53180256),
       (0.0896, 260.10490845), (0.0898, 259.07947632),
       (0.09  , 258.51389012), (0.0902, 258.43149415),
       (0.0904, 258.82014477), (0.0906, 259.63264688),
       (0.0908, 260.78806255), (0.091 , 262.17385911),
       (0.0912, 263.64884553), (0.0914, 265.04682802),
       (0.0916, 266.1808998 ), (0.0918, 266.8482658 ),
       (0.092 , 266.8488164 ), (0.0922, 266.09160131),
       (0.0924, 264.53959021), (0.0926, 262.66370033),
       (0.0928, 261.01804988), (0.093 , 259.71606002),
       (0.0932, 258.83879805), (0.0934, 258.43307991),
       (0.0936, 258.51043455), (0.0938, 259.04695054),
       (0.094 , 259.98400554), (0.0942, 261.22985907),
       (0.0944, 262.66206983), (0.0946, 264.13068018),
       (0.0948, 265.46209311), (0.095 , 266.46355187),
       (0.0952, 266.92813794), (0.0954, 266.68005467),
       (0.0956, 265.66214479), (0.0958, 263.89465322),
       (0.096 , 262.08112287), (0.0962, 260.53913082),
       (0.0964, 259.37157255), (0.0966, 258.64826251),
       (0.0968, 258.40432054), (0.097 , 258.63942912),
       (0.0972, 259.3179754 ), (0.0974, 260.37007164),
       (0.0976, 261.69342832), (0.0978, 263.15603459),
       (0.098 , 264.59958281), (0.0982, 265.84355729),
       (0.0984, 266.68989259), (0.0986, 266.9303932 ),
       (0.0988, 266.42987746), (0.099 , 265.14722855),
       (0.0992, 263.26962693), (0.0994, 261.53319863),
       (0.0996, 260.10610442), (0.0998, 259.08044638),
       (0.1   , 258.51461355)],
      dtype=[('time', '<f8'), ('outputs', '<f8')])`

**Comment by Flancis** [comment]
It seems like the problem was caused by an old version `matplotlib`. After updating the latest version, I can see the figure without error now.

Thanks.
