### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by tinrabuzin** [CATIA-Systems/FMPy#162]
Hi, 

I was trying to do a parameter sweep with an FMU generated from OpenModelica (2.0 both me and cs) but whenever I reset the fmu I get the following error:

`Traceback (most recent call last):
  File "c:/Users/trabu/Documents/dev/dyneq_pf/examples/other/generate_fmu.py", line 24, in <module>
    res = model.simulate(experiment_settings)
  File ".\dyneq\models.py", line 74, in simulate
    validate=False, input=self.input, output=self.output, start_values=self.start_values, **experiment_settings)
  File "C:\Users\trabu\Documents\dev\dyneq_pf\venv\lib\site-packages\fmpy\simulation.py", line 573, in simulate_fmu
    result = simulateCS(model_description, fmu, start_time, stop_time, relative_tolerance, start_values, apply_default_start_values, input, output, output_interval, timeout, step_finished)
  File "C:\Users\trabu\Documents\dev\dyneq_pf\venv\lib\site-packages\fmpy\simulation.py", line 972, in simulateCS
    fmu.exitInitializationMode()
  File "C:\Users\trabu\Documents\dev\dyneq_pf\venv\lib\site-packages\fmpy\fmi2.py", line 286, in exitInitializationMode
    return self.fmi2ExitInitializationMode(self.component)
  File "C:\Users\trabu\Documents\dev\dyneq_pf\venv\lib\site-packages\fmpy\fmi2.py", line 206, in w
    res = f(*args)
OSError: exception: access violation writing 0x0000000000000000`

The following is an example of an FMU with which I get the error: [DynEq.ReferenceModel.zip](https://github.com/CATIA-Systems/FMPy/files/5048193/DynEq.ReferenceModel.zip)

Could you help me solve this issue?

**Comment by t-sommer** [comment]
Can you share some code to reproduce the problem?

**Comment by tinrabuzin** [comment]
For instance, the code below generates the same exception.

```
import fmpy

fmu_path = '' # SET THE PATH HERE
model_description = fmpy.read_model_description(fmu_path))
unzipdir = fmpy.extract(fmu_path)
fmu=fmpy.instantiate_fmu(unzipdir, model_description, 'ModelExchange')

for i in range(2):
    fmu.reset()
    res1 = fmpy.simulation.simulate_fmu(unzipdir, fmu_instance=fmu, model_description=model_description,
                                    validate=False, output=['source.P'])
```

**Comment by t-sommer** [comment]
This seems to be a bug in the FMU's `fmi2Reset()` function.
Please report this issue to https://github.com/OpenModelica/OpenModelica.
