### ISSUE TITLE
Changing parameters does not affect the simulation results

### ISSUE THREAD

**Issue by h-bode** [CATIA-Systems/FMPy#163]
Is it not possible to change parameters of a model, like the resistance of a resistor?

I build an easy model in OpenModelica:

![model_fmpy](https://user-images.githubusercontent.com/63717517/90021365-6e88c280-dcb1-11ea-949d-59dc89e9edd5.png)

Afterwards, i created an FMU out of it 
```

OpenModelica.Scripting.loadFile("noinput2.mo"); getErrorString();
setCommandLineOptions("-d=newInst"); getErrorString();
setCommandLineOptions("-d=initialization"); getErrorString();
//setCommandLineOptions("--simCodeTarget=Cpp"); getErrorString();
setCommandLineOptions("-d=-disableDirectionalDerivatives"); getErrorString();
OpenModelica.Scripting.translateModelFMU(noinput2, version="2.0", fmuType = "cs"); getErrorString();
```

Then i simulated the model with following python code (based on the example simulate custom input).

```
`

from fmpy import read_model_description, extract
from fmpy.fmi2 import FMU2Slave
from fmpy.util import plot_result
import numpy as np
import shutil
import matplotlib.pyplot as plt


def simulate_custom_input(show_plot=True):

    fmu_filename = 'noinput2.fmu'
    start_time = 0.0

    stop_time = 2.0
    step_size = 1e-3

    model_description = read_model_description(fmu_filename)
    vrs = {}
    for variable in model_description.modelVariables:
        vrs[variable.name] = variable.valueReference

    # get the value references for the variables we want to get/set
    vr_inputs   = vrs['u']
    vr_outputs4 = vrs['resistor.i']
    vr_param = vrs['resistor.R']

    # extract the FMU
    unzipdir = extract(fmu_filename)

    fmu = FMU2Slave(guid=model_description.guid,
                    unzipDirectory=unzipdir,
                    modelIdentifier='noinput2',
                    instanceName='instance1')

    # initialize
    fmu.instantiate()
    fmu.setupExperiment(startTime=start_time)
    fmu.enterInitializationMode()
    fmu.exitInitializationMode()

    time = start_time

    res = [] # current through the resistor
    res2 = [] # value of the resistor

    # simulation loop
    while time < stop_time:

        # set the input
        fmu.setReal([vr_inputs], [1 if time < 10 else 10])
        fmu.setReal([vr_param], [0.5 if time < 1 else 1])
        # perform one step
        fmu.doStep(currentCommunicationPoint=time, communicationStepSize=step_size)


        outputs = fmu.getReal([vr_outputs4])
        params = fmu.getReal([vr_param])

        # append the results
        res.append((outputs))
        res2.append((params))


        # advance the time
        time += step_size

    plt.plot(res) # current through resistor (blue)
    plt.plot(res2) # value of resistor (orange)
    fmu.terminate()
    fmu.freeInstance()

    # clean up
    shutil.rmtree(unzipdir, ignore_errors=True)

    # convert the results to a structured NumPy array
    result = np.array(res, dtype=np.dtype([('time', np.float64), ('vr_inputs', np.float64), ('outputs[4]', np.float64)]))
   # result = np.array(rows, dtype=np.dtype([('time', np.float64), ('outputs[4]', np.float64)]))

    # plot the results
    if show_plot:
        plot_result(result)

    return time


if __name__ == '__main__':

    simulate_custom_input()`
```

The default value of the model is 10 Ohm. At the neginning of the simulation, i change it to 0.5 Ohm, after 1 second, I change it to 1 Ohm. Since the voltage is 1 V, the current in the resistor should be 2 A, and after 1 second 1 A. But is is all the time just 0.1 A, which fits to the default of 10 Ohm value which is set in OpenModelica. 

Following plot shows the value resistor.R (orange) and resistor.i (blue) over the timesteps. 

![resistor_fmpy](https://user-images.githubusercontent.com/63717517/90022570-fa4f1e80-dcb2-11ea-95da-5df262c8c3d1.png)

Any hint if such a variation of the parameters is possible at all, and if this is true, how it can be done, is really welcome :-)

**Comment by h-bode** [comment]
The interesting lines in the python code might be the following: 

```
        # set the input
        fmu.setReal([vr_inputs], [1 if time < 10 else 10])
        fmu.setReal([vr_param], [0.5 if time < 1 else 1])
```

**Comment by t-sommer** [comment]
If you start fresh I would recommend to base your code on [examples/efficient_loops.py](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/efficient_loops.py) and use [instantiate_fmu()](https://github.com/CATIA-Systems/FMPy/blob/a79cf68f02b1df58cf196e1ac25497652ba6bd3a/fmpy/simulation.py#L588) instead of calling the constructor directly. It also lets you set `fmi_call_logger=print` that allows you to check whether `fmi2SetReal()` is called.

**Comment by h-bode** [comment]
Thanks for this hint, i think this will help for my general programming :-)

But for setting the parameters (like the resistance of a resistor), that does not help. I can say for sure `that fmi2SetReal()` is called, since the value of the resistor `params = fmu.getReal([vr_param])` changes (orange line in the plot).

But the change of the resistor does not affect the simulation. The current through this resistor (blue line) should change, too, but nothing happens. Is there a way that the new values of a parameter (like the resistance) will the taken to get the result, and not only the default ones which are set in the FMU?

**Comment by t-sommer** [comment]
> Is there a way that the new values of a parameter (like the resistance) will the taken to get the result, and not only the default ones which are set in the FMU?

This seems to be a problem with the FMU.
Please report this issue to https://github.com/OpenModelica/OpenModelica.
