### ISSUE TITLE
CMake project does not contain link arguments

### ISSUE THREAD

**Issue by trinamic-sw** [CATIA-Systems/FMPy#165]
The CMakeLists seems to be unaware of library flags. For example, the attached fmu, generated by openmodelica, links to openblas. Building the fmu binary with cmake works, but the simulation terminates with the following error:

`OSError: /tmp/tmp2mtvdb3t/binaries/linux64/simexample.so: undefined symbol: dgesv_`

The problem does not occur when openblas is manually added to the cmake file via target_link_libraries().

[simexample.zip](https://github.com/CATIA-Systems/FMPy/files/5136934/simexample.zip)

**Comment by t-sommer** [comment]
With FMI 2.0 it is currently not possible to provide this information to importers (like FMPy). FMI 3.0 will introduce [build configurations](https://fmi-standard.org/docs/3.0-dev/#_library) that allow the exporter to communicate this type of dependency.
