### ISSUE TITLE
[ERROR] GUID of model is not correct

### ISSUE THREAD

**Issue by sentient-jgallegocalderon** [CATIA-Systems/FMPy#167]
Hi,

When trying to simulate an FMU, I get the following error: `[ERROR] GUID of model is not correct`. Note the this works on my machine (MAC) and the error happens in a windows machine. We try removing the binaries for debian and matching the FMPy versions (0.2.17) but had no luck. This is the Traceback corresponding to FMPy:

`File "C:\Python37\lib\site-packages\fmpy\simulation.py", line 565, in simulate_fmu
    fmu = instantiate_fmu(unzipdir, model_description, fmi_type, visible, debug_logging, logger, fmi_call_logger, use_remoting)
  File "C:\Python37\lib\site-packages\fmpy\simulation.py", line 641, in instantiate_fmu
    fmu.instantiate(visible=visible, callbacks=callbacks, loggingOn=debug_logging)
  File "C:\Python37\lib\site-packages\fmpy\fmi2.py", line 260, in instantiate
    raise Exception("Failed to instantiate model")
Exception: Failed to instantiate model`

Any advice? Thanks,
Juan

**Comment by t-sommer** [comment]
Can you share the model that causes the problem?
