### ISSUE TITLE
start_values doesn't work

### ISSUE THREAD

**Issue by SenHuang19** [CATIA-Systems/FMPy#168]
I tried to use the simulate_fmu to run a model exchange fmu with the following code but found the start_times seems to be not working:

`filename="./fmu/wrapped.fmu"`
`result = simulate_fmu(`
`         filename = filename,`
`        start_time=0,`
`        stop_time=1,`
`        output= ['mod.cap.T'],`
`        start_values={'mod.cap.T': 283.15})`

The result is shown as below:

> [(0.00000000e+00, 293.15      ) (1.13629293e-07, 293.15      )
 (1.13629293e-07, 293.15      ) ... (9.98000000e-01, 293.15000054)
 (9.99000000e-01, 293.15000054) (1.00000000e+00, 293.15000054)]

Any advices?

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by SenHuang19** [comment]
Sure. 
[wrapped.zip](https://github.com/CATIA-Systems/FMPy/files/5216071/wrapped.zip)

**Comment by t-sommer** [comment]
If I simulate with `simulate_fmu(..., fmi_call_logger=print)` I get

```
fmi2Instantiate(instanceName="wrapped", fmuType=0, guid="f3b968ade9b3a0739668d690308cf547", resourceLocation="file:///tmp/tmpkbhnzzs_/resources", callbacks=<fmpy.fmi2.fmi2CallbackFunctions object at 0x7f76d41cdea0>, visible=0, loggingOn=0) -> 0x7fffd2d0ca80
fmi2SetupExperiment(component=0x7fffd2d0ca80, toleranceDefined=0, tolerance=0.0, startTime=0, stopTimeDefined=0, stopTime=0.0) -> OK
fmi2SetReal(component=0x7fffd2d0ca80, vr=[90], nvr=1, value=[283.15]) -> OK
fmi2EnterInitializationMode(component=0x7fffd2d0ca80) -> OK
fmi2ExitInitializationMode(component=0x7fffd2d0ca80) -> OK
fmi2NewDiscreteStates(component=0x7fffd2d0ca80, eventInfo=<fmpy.fmi2.fmi2EventInfo object at 0x7f76d4199400>) -> OK
fmi2EnterContinuousTimeMode(component=0x7fffd2d0ca80) -> OK
fmi2GetContinuousStates(component=0x7fffd2d0ca80, x=[293.15], nx=1) -> OK
fmi2GetReal(component=0x7fffd2d0ca80, vr=[90], nvr=1, value=[293.15]) -> OK
```

so the variable is being set correctly. Note however that `mod.cap.T` is a local variable, so setting it might not have the desired effect. You could try to expose it as a parameter.
