### ISSUE TITLE
No module named fmpy.gui

### ISSUE THREAD

**Issue by Flancis** [CATIA-Systems/FMPy#17]
Hi,

When trying to open the gui, it gives the following error.
`No module named fmpy.gui`.

Also, in the installation folder, there is no `gui` folder as the one in github.

Any idea why?

Thanks in advance.

**Comment by Flancis** [comment]
May it is related to the installed version? Using the `conda install -c conda-forge fmpy` command, the latest version `v0.2.0` should be installed. Instead, version `v0.1.2` was installed. So how to install the latest version?

**Comment by t-sommer** [comment]
You did everything right. There is currently a problem with the conda forge build that fails on Windows for all Python versions except 3.5. You can find a list of the available conda packages [here](https://anaconda.org/conda-forge/fmpy/files). In the meantime you can install the latest version via pip or directly from github (see [README.md](https://github.com/CATIA-Systems/FMPy#installation)).

**Comment by t-sommer** [comment]
The issue is [resolved](https://github.com/conda-forge/fmpy-feedstock/commit/a41ea51065287fe75a52afe43a56772fd5dc4ddb). You should be able to install the latest version with conda now.

**Comment by Flancis** [comment]
Also, maybe the conda command could be updated to `conda install -c conda-forge fmpy`.

**Comment by t-sommer** [comment]
Fix with 63187719. Thanks for reporting!
