### ISSUE TITLE
Include source code in distributions

### ISSUE THREAD

**Issue by trulede** [CATIA-Systems/FMPy#173]
Would it be possible to package the source code with distributions? Something like:

`python setup.py sdist --formats=gztar,zip
`

This is to allow building/installing the FMPy package with specific compiler options.  Currently, if you try to do pip install --compile, then pip is downloading an older version of FMPy (0.0.9 IIRC).

**Comment by t-sommer** [comment]
The build process is fairly complex (see https://github.com/CATIA-Systems/FMPy/blob/master/azure-pipelines.yml for details).
What compiler options do you want to change?
