### ISSUE TITLE
Display Value References in GUI

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMPy#175]
As a suggestion: As we use the FMPy GUI for debugging as well, it would be quite good to have the value references displayed in a column along the parameter names, initial values etc.

**Comment by t-sommer** [comment]
To display the value references in the GUI right-click on a variable and select `Columns > Value Reference`. You can also copy the value references and names of all selected variables by selecting `Copy Value Reference` or `Copy Variable Name`.

![Unbenannt](https://user-images.githubusercontent.com/2453858/94552087-a397a700-0256-11eb-8642-f40a857c2ae0.PNG)
