### ISSUE TITLE
Simulation Loop: Identical order of callbacks in CS and ME

### ISSUE THREAD

**Issue by pamagister** [CATIA-Systems/FMPy#176]
**Description of the usecase**
Currently we are working on the implementation of the feature to stimulate input signals with time courses.

We noticed a possible difference in the processing order of recorder.sample, input.apply, doStep and time.increment between simulateME and simulateCS. According to our observation the difference is especially in the time when the reference time is incremented (time++) and when recorder.samples takes place in relation to the updated inputs (inputs.apply) and the actual simulation step (doStep).

**ME**:
- before loop:
  - input.apply(time)
- within loop:
  - time++
  - input.apply(time)
  - doStep
  - recorder.sample(time)
  - if step_finished: break
- after loop:
  - nop

**CS**:
- before loop:
  - input.apply(time)
- within loop:
  - recorder.sample(time)
  - input.apply(time)
  - doStep
  - if step_finished: break
  - time++
- after loop:
 - recorder.sample(time)

In CS this leads to the behavior that changes of the inputs are only considered with the next time step and can be observed in the recording. See diagram (orange: input signal recorded with recorder.sample; grey dashed: signal used for stimulation and as a static reference)

![image](https://user-images.githubusercontent.com/72438098/95177972-2375c200-07bf-11eb-835a-10eeaa26a41b.png)

**Feature request:**
Would it be possible to adapt the behaviour of simulateCS to the lifecycle of simulateME, so that inputs.apply updates the inputs first, then the calculation step propagates the changes and finally recorder.sample records the new data according to the same time step?

**Comment by t-sommer** [comment]
It seems like this is a duplicate of #89.

**Comment by t-sommer** [comment]
FMI 3.0 Co-Simulation will support events, so there will be direct feed-through at least for discrete signals (like in your example above).

**Comment by t-sommer** [comment]
@pamagister, @fajansen, can we close this issue?

**Comment by pamagister** [comment]
Issue closed. Nevertheless, we will have to pursue an internal solution for the time offset of stimulated signals and the response of directly dependent output signals.
