### ISSUE TITLE
"[WARNING] fmi2DoStep: currentCommunicationPoint" warnings when start_time > 0 (Windows only)

### ISSUE THREAD

**Issue by krzysztofarendt** [CATIA-Systems/FMPy#179]
Hello, I am about to replace PyFMI with FMPy in [modest-py](https://github.com/sdu-cfei/modest-py). It works great, so thanks for this package!

I noticed one issue so far - when I simulate an FMU with `start_time > 0`, as in [this example](https://github.com/sdu-cfei/modest-py/blob/issue_57_parallelize/modestpy/fmi/fmpy_warning_example.py) I get the following warnings: `[WARNING] fmi2DoStep: currentCommunicationPoint = ..., expected ...`. The warnings are printed only under Windows 10. I tested the same script on Linux (WSL2, Ubuntu 18.04) and no warnings were printed. I'm not sure if the warnings come from FMPy or the FMU.

Is this an expected behavior?

Full output for `start_time = 360`:
```
D:\code\modest-py>python modestpy\fmi\fmpy_warning_example.py

Model Info

  FMI Version       2.0
  FMI Type          Co-Simulation
  Model Name        Simple2R1C
  Description       None
  Platforms         win64
  Continuous States 1
  Event Indicators  0
  Variables         36
  Generation Tool   Dymola Version 2018 FD01 (64-bit), 2017-10-11
  Generation Date   2018-11-23T12:30:51Z

Default Experiment

  Stop Time         1
  Tolerance         0.0001

Variables (input, output)

Name                Causality              Start Value  Unit     Description
Ti2                 input                       288.15
T                   output
Ti1                 input                       288.15
[WARNING] fmi2DoStep: currentCommunicationPoint = 60.0000000000000000, expected 420.0000000000000000
[WARNING] fmi2DoStep: currentCommunicationPoint = 120.0000000000000000, expected 420.0000000000000000
[WARNING] fmi2DoStep: currentCommunicationPoint = 180.0000000000000000, expected 420.0000000000000000
[WARNING] fmi2DoStep: currentCommunicationPoint = 240.0000000000000000, expected 420.0000000000000000
[WARNING] fmi2DoStep: currentCommunicationPoint = 300.0000000000000000, expected 420.0000000000000000
[WARNING] fmi2DoStep: currentCommunicationPoint = 360.0000000000000000, expected 420.0000000000000000
```

**Comment by t-sommer** [comment]
It looks like these messages are coming from `printf()`s inside the FMU. Maybe Linux re-directs stdout, so you can see them on the console. Can you share the FMU the very the behaviour?

**Comment by krzysztofarendt** [comment]
Yes, the Windows version is here: https://github.com/sdu-cfei/modest-py/blob/issue_57_parallelize/examples/simple/resources/Simple2R1C_ic_linux64.fmu

The Linux version: https://github.com/sdu-cfei/modest-py/blob/issue_57_parallelize/examples/simple/resources/Simple2R1C_ic_linux64.fmu

Modelica model: https://github.com/sdu-cfei/modest-py/blob/issue_57_parallelize/examples/simple/resources/Simple2R1C_ic.mo

**Comment by t-sommer** [comment]
With 

```python
from fmpy import *

result = simulate_fmu('Simple2R1C_ic_win64.fmu', start_time=0.1, stop_time=1.0, fmi_call_logger=print)
```

I get the following log

```
fmi2Instantiate(instanceName="Simple2R1C", fmuType=1, guid="{0a008dfb-5882-4576-aed5-e19213d71558}", resourceLocation="file:///C:/Users/xxx/AppData/Local/Temp/tmp_4_b13vs/resources", callbacks=<fmpy.fmi2.fmi2CallbackFunctions object at 0x000001C0FFCA9948>, visible=0, loggingOn=0) -> 0x1c0fc8871e0
fmi2SetupExperiment(component=0x1c0fc8871e0, toleranceDefined=1, tolerance=0.0001, startTime=0.1, stopTimeDefined=0, stopTime=0.0) -> OK
fmi2EnterInitializationMode(component=0x1c0fc8871e0) -> OK
fmi2ExitInitializationMode(component=0x1c0fc8871e0) -> OK
fmi2GetReal(component=0x1c0fc8871e0, vr=[335544320], nvr=1, value=[20.0]) -> OK
fmi2DoStep(component=0x1c0fc8871e0, currentCommunicationPoint=0.1, communicationStepSize=0.001, noSetFMUStatePriorToCurrentPoint=1) -> OK
[WARNING] fmi2DoStep: currentCommunicationPoint = 0.0010000000000000, expected 0.1010000000000000
fmi2DoStep(component=0x1c0fc8871e0, currentCommunicationPoint=0.001, communicationStepSize=0.001, noSetFMUStatePriorToCurrentPoint=1) -> WARNING
[WARNING] fmi2DoStep: currentCommunicationPoint = 0.0020000000000000, expected 0.1010000000000000
```

It seems like the FMU is not setting the start time.

@KarlWernersson, can you take a look at this?

**Comment by KarlWernersson** [comment]
Hi

I will fix this issue in Dymola fmu export.
I would recommend you to contact Dymola support so it gets propely tracked. 
If you want a fix pack you neet to contact us there too.
