### ISSUE TITLE
Closed loop simulation

### ISSUE THREAD

**Issue by Flancis** [CATIA-Systems/FMPy#18]
I see that one can simulate several FMUs with SSP. Is there a similar procedure for closed loop simulation? For example, a controller designed directly in Python and an FMU plant?

**Comment by t-sommer** [comment]
You could adapt the [custom_input.py](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/custom_input.py) example and use the get*() / set*() functions to interact with the FMU.

**Comment by Flancis** [comment]
Thanks. Will try that.
