### ISSUE TITLE
Use a previous state of fmu for running a new simulation

### ISSUE THREAD

**Issue by anki-ntnu** [CATIA-Systems/FMPy#180]
Hi,
I am using FMPy for running my simulations. I want to pass my first set of input data (100s long), then save the state of fmu at 100s and then pass next set of input data (100s long), and the fmu for the second input set of data should start simulation by using the state at 100s from the first input set of data.

**Comment by t-sommer** [comment]
This is already possible with get/set FMUState (see https://github.com/CATIA-Systems/FMPy/issues/178#issuecomment-706165169).
