### ISSUE TITLE
Using fmu_instance does not give correct results

### ISSUE THREAD

**Issue by anki-ntnu** [CATIA-Systems/FMPy#183]
Please download test.py and run python test.py in anaconda shell (or any python terminal). FMU is built using Dymola.
[test.zip](https://github.com/CATIA-Systems/FMPy/files/5444108/test.zip)

```
import numpy as np
import pandas as pd
from fmpy import read_model_description, extract
from fmpy.simulation import instantiate_fmu
from fmpy.simulation import simulate_fmu


def create_processor(fmu_file_path):
    unzipdir = extract(fmu_file_path)
    model_description = read_model_description(fmu_file_path, validate=False)
    fmu = instantiate_fmu(unzipdir, model_description, fmi_type=None, visible=False,
                          debug_logging=False, logger=None, fmi_call_logger=None,
                          use_remoting=False)

    def process(*args, step_size=None):
        df_in = args[0]
        start_time = df_in.index[0]
        stop_time = df_in.index[-1]

        df_in = pd.DataFrame.to_records(df_in)
        df_out = simulate_fmu(fmu_file_path, validate=False, input=df_in, step_size=step_size,
                              start_values={}, output_interval=0.5, start_time=start_time,
                              stop_time=stop_time, debug_logging=False, fmu_instance=fmu)
        df_out = pd.DataFrame.from_records(df_out).set_index('time')
        print(df_out)
        return df_out
    return process

def main():
    df_window1 = pd.DataFrame(data=np.array(
        [[0.0, 0.0], [0.5, 0.0]], np.double), columns=['time', 'step2']).set_index('time')
    df_window2 = pd.DataFrame(data=np.array(
        [[1.0, 1.0], [1.5, 1.0]], np.double), columns=['time', 'step2']).set_index('time')

    processor = create_processor('CoupledClutches.fmu')
    processor(df_window1, 0.5)
    processor(df_window2, 0.5)


if __name__ == '__main__':
    main()

```
Argument fmu_instance is used in function simulate_fmu to process 2 windows. On second window, data is processed but multiple warnings are thrown and the results from the second window are not correct. They are same as the results from last value of the first window.

> J1_w      J2_w  J3_w          J4_w
> time                                         
> 0.0   10.000000  0.000000   0.0  0.000000e+00
> 0.5    5.953323  3.678609   1.0 -3.330669e-15
> [WARNING] fmi2SetTime: not allowed in this state
> [WARNING] model cannot be initialized in current state(7)
> [WARNING] fmiExitInitializationMode: may only called in initialization mode
> [WARNING] fmi2DoStep: model is terminated
> [WARNING] fmi2DoStep: model is terminated
> [WARNING] fmi2DoStep: model is terminated
> [WARNING] fmi2Terminate: already terminated, ignoring call
>  J1_w      J2_w  J3_w          J4_w
> time                                        
> 1.0   5.953323  3.678609   1.0 -3.330669e-15
> 1.5   5.953323  3.678609   1.0 -3.330669e-15

May be the possible reason is that it tries to reinitialize for the second window? Could be a good idea to move initialization part out as a separate function (similar to instantiate_fmu), and add a flag to simulate_fmu such that initialization function is called only if we set initialization flag = True in the simulate_fmu function. Could be other possible reason? This is just my guess

**Comment by t-sommer** [comment]
In your example using `instantiate_fmu()` has no benefit and makes the code unnecessarily complex. Also make sure to free the DLL and clean up the unzip directory before you return. The following code runs without problems:

```python
import numpy as np
import pandas as pd
from fmpy.simulation import simulate_fmu


def create_processor(fmu_file_path):

    def process(*args, step_size=None):
        df_in = args[0]
        start_time = df_in.index[0]
        stop_time = df_in.index[-1]

        df_in = pd.DataFrame.to_records(df_in)
        df_out = simulate_fmu(fmu_file_path, validate=False, input=df_in, step_size=step_size,
                              start_values={}, output_interval=0.5, start_time=start_time,
                              stop_time=stop_time, debug_logging=False)
        df_out = pd.DataFrame.from_records(df_out).set_index('time')
        print(df_out)
        return df_out

    return process


def main():
    df_window1 = pd.DataFrame(data=np.array(
        [[0.0, 0.0], [0.5, 0.0]], np.double), columns=['time', 'step2']).set_index('time')
    df_window2 = pd.DataFrame(data=np.array(
        [[1.0, 1.0], [1.5, 1.0]], np.double), columns=['time', 'step2']).set_index('time')

    processor = create_processor('CoupledClutches.fmu')
    processor(df_window1, 0.5)
    processor(df_window2, 0.5)


if __name__ == '__main__':
    main()
``` 

```
           J1_w      J2_w  J3_w          J4_w
time                                         
0.0   10.000000  0.000000   0.0  0.000000e+00
0.5    5.953323  3.678609   1.0 -3.330669e-15
[WARNING] fmi2DoStep: currentCommunicationPoint = 0.5000000000000000, expected 1.5000000000000000
[WARNING] fmi2DoStep: currentCommunicationPoint = 1.0000000000000000, expected 1.5000000000000000
           J1_w      J2_w      J3_w      J4_w
time                                         
1.0   10.000000  0.000000  0.000000  0.000000
1.5   10.227199  0.130463  0.130463  0.130463
```

The problem with `start_time != 0` has been resolved in the latest Dymola release.

**Comment by anki-ntnu** [comment]
@t-sommer : The issue with this is that when starting a new window it is restarting the simulation instead of continuing the simulation for the second window. I want to preserve the state so that the simulation for window 2 starts where the simulation from window 1 finishes. That's why I used instantiate_fmu() and passed the same fmu_instance so that the stimulation proceeds instead of starting a new simulation for each window

**Comment by t-sommer** [comment]
This cannot be achieved with `simulate_fmu()`. You could write your own simulation loop. See https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/custom_input.py for an example.

**Comment by anki-ntnu** [comment]
Great, thanks. Do you have such an example for Model exchange fmu as well by any chance @t-sommer ?

**Comment by apanys** [comment]
@t-sommer 
Thanks for the update. While this cannot be achieved at the moment with `simulate_fmu()` is this something you can add in a future version of FMPy?

This was exactly the scenario I tried to achieve in the sample from issue https://github.com/CATIA-Systems/FMPy/issues/182. I assume fmu_instance is exactly for that purpose.

**Comment by t-sommer** [comment]
You might be able to use the `step_finished` callback for this. Can you describe your use case?

**Comment by apanys** [comment]
I have a continuous stream scenario. An IOT device sends data 24*7h. My python application gets a window of data (some seconds) as parquet file. This window of data I want to process with FMPy. Then the next window of data (the next seconds) is reaching my python application and I want to process that.

**Comment by t-sommer** [comment]
Please move this discussion to StackOverflow and and link it here for reference. Feel free to open a new issue if you have a concrete change proposal.
