### ISSUE TITLE
Get inputs and values

### ISSUE THREAD

**Issue by PhillipEDRDK** [CATIA-Systems/FMPy#185]
Sorry if I cannot find it, but I am lacking a feature where a list of the inputs can be pulled. I only know that the start values can be pulled which also includes the outputs without a way to tell them apart. There is also the util.fmu_info(filename, causalities) function, but it returns a long string of non essential information. Is there a get function I have overlooked?

**Comment by t-sommer** [comment]
You can extract the input variables from the model description:

```python
from fmpy import read_model_description

filename = r'E:\Development\fmi-cross-check\fmus\2.0\cs\win64\Dymola\2019FD01\BooleanNetwork1\BooleanNetwork1.fmu'

model_description = read_model_description(filename)

input_variables = []

# get all input variables
for variable in model_description.modelVariables:
    if variable.causality == 'input':
        input_variables.append(variable)

# print the names and start values
for input_variable in input_variables:
    print('%s: %s' % (input_variable.name, input_variable.start))

```

**Comment by PhillipEDRDK** [comment]
Thank you!
