### ISSUE TITLE
The combination causality ="parameter" and variability = "constant" in variable is not allowed

### ISSUE THREAD

**Issue by manasdas17** [CATIA-Systems/FMPy#189]
I have been using FMPy ( version 0.2.25) to simulate Co-simulation FMUs, however given one FMU is throwing up error 
**The combination causality ="parameter" and variability = "constant" in variable is not allowed**

Regards,
Manas

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by manasdas17** [comment]
Thanks. Please find link for the fmu.
https://drive.google.com/file/d/1d16M8QQG9IBb9yHyZemE_GmSGdJjJu8R/view?usp=sharing

**Comment by t-sommer** [comment]
I can confirm that I get the following error:

```
Exception: Failed to validate model description. 2 problems were found:

- The combination causality="parameter" and variability="constant" in variable "autoDry_FMU_Param_sf_fmu.stepSizeScaleFactor" (line 627) is not allowed.
- The combination causality="parameter" and variability="constant" in variable "_Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu1.stepSizeScaleFactor" (line 3135) is not allowed.
```

@KarlWernersson, can you take a look at this?

If I simulate with validation disabled

```python
from fmpy import *

filename = 'Test.fmu'

result = simulate_fmu(filename, validate=False)
```

the FMU complains about a missing file `k-4Data.txt`:

```
[OK] Janus_AD_Dymola_Solver started

[OK] [fmi2OK]: 
[OK] _Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu: ... loading "tab1" from "C:\Users\XXX\AppData\Local\Temp\tmpd8mls52c\resources\k-4Data.txt"

[OK] [fmi2Error]: 
[OK] _Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu: Error: The following error was detected at time: 0

[OK] [fmi2Error]: 
[OK] _Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu: Not possible to open file "C:\Users\XXX\AppData\Local\Temp\tmpd8mls52c\resources\k-4Data.txt": No such file or directory

[OK] [fmi2Error]: 
[OK] _Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu: 

[OK] [fmi2Error]: 
[OK] _Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu: The stack of functions is:

[OK] [fmi2Error]: 
[OK] _Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu: Modelica.Blocks.Tables.CombiTable2D.readTableData

[OK] [fmi2Error]: 
[OK] _Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu: Modelica.Blocks.Tables.CombiTable2D.readTableData(
extraction_Model.extraction.extraction_Spin_Cycle.combiTable2D.tableID, 
false, 
extraction_Model.extraction.extraction_Spin_Cycle.combiTable2D.verboseRead)

[OK] [fmi2Error]: 
[OK] _Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu: 

[OK] [fmi2Error]: 
[OK] _Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu: Initialization Failed

[ERROR] Error: The following error was detected at time: 0
[ERROR] InitializeSlave failed
[ERROR] The stack of functions is:
[ERROR] Jnaus_AD_Final_MDL._Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu.fmi_Functions.fmiEnterSlaveInitializationMode
[ERROR] Jnaus_AD_Final_MDL._Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu.fmi_Functions.fmiEnterSlaveInitializationMode(
_Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu1.fmi, 
_Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu1.fmi_rTol, 
_Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu1.fmi_StartTime, 
_Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu1.fmi_forceShutDownAtStopTime, 
_Jan...
[OK] Error: Integrator failed to start model.

[ERROR] Initialization Failed
```

**Comment by KarlWernersson** [comment]
Hi the illegal combination is an issue that can occur in Dymola 2020x when exporting FMU's with cosimulation fmu's inside. 
This i fixed for Dymola 2021 which is available. 

For a quick fix of the modelDescription.xml in the fmu, change the causality of the problematic parameters to local in the xml.

**Comment by manasdas17** [comment]
@KarlWernersson, after changing the causality of the problematic parameters to local in the modelDescription.xml file, now it gets imported to FMPy but the error "Initialization Failed" still there. 
[OK] Error: Integrator failed to start model.
[ERROR] Initialization Failed.

**Comment by KarlWernersson** [comment]
@manasdas17 It is better you solve those issues by contacting Dymola support.
But do you also get the errro that torsten got ([OK] [fmi2OK]: 
[OK] _Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu: ... loading "tab1" from "C:\Users\XXX\AppData\Local\Temp\tmpd8mls52c\resources\k-4Data.txt"

[OK] [fmi2Error]: 
[OK] _Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu: Error: The following error was detected at time: 0

[OK] [fmi2Error]: 
[OK] _Janus128L_012KG_03_0EnergyInput_04_0Controller_fmu: Not possible to open file "C:\Users\XXX\AppData\Local\Temp\tmpd8mls52c\resources\k-4Data.txt": No such file or directory

That shows that the FMU cant find the k-4Data.txt

**Comment by manasdas17** [comment]
@KarlWernersson , yes, i got the exact errors as torsten got even after changing as you had suggested.

**Comment by t-sommer** [comment]
I can simulate the FMU if I move the files in `resources/r0/` one folder up to `resources/` where the FMU expects them.

**Comment by t-sommer** [comment]
> i got the exact errors as torsten got even after changing as you had suggested.

These problems are unrelated.

**Comment by manasdas17** [comment]
@t-sommer , ok. Could you please share the modified FMU that you are able to simulate? I will refer to that as i tried as per you suggested but still couldn't able to simulate.

**Comment by t-sommer** [comment]
[Test.zip](https://github.com/CATIA-Systems/FMPy/files/5510947/Test.zip)

**Comment by manasdas17** [comment]
@t-sommer , it doesn't work. Got the following error
[OK] Error: Integrator failed to start model.

[ERROR] Initialization Failed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\fmpy\simulation.py", line 658, in simulate_fmu
    result = simulateCS(model_description, fmu, start_time, stop_time, relative_tolerance, start_values, apply_default_start_values, input, output, output_int
erval, timeout, step_finished)
  File "C:\Python36\lib\site-packages\fmpy\simulation.py", line 1055, in simulateCS
    fmu.enterInitializationMode()
  File "C:\Python36\lib\site-packages\fmpy\fmi2.py", line 283, in enterInitializationMode
    return self.fmi2EnterInitializationMode(self.component)
  File "C:\Python36\lib\site-packages\fmpy\fmi2.py", line 215, in w
    raise Exception("%s failed with status %d." % (fname, res))
Exception: fmi2EnterInitializationMode failed with status 3.

**Comment by t-sommer** [comment]
Please contact Dymola support. Both issues are related to the FMU export and cannot be fixed in FMPy. Thank you.

**Comment by manasdas17** [comment]
ok, Thanks a lot for the support.
