### ISSUE TITLE
Misleading error message in case of wrong fmi_type argument

### ISSUE THREAD

**Issue by wulmer** [CATIA-Systems/FMPy#19]
If the user specifies an invalid `fmi_type`, e.g. `fmi_type='CoSimulation` for a ME-only FMU, this is not caught during the argument checks below:
https://github.com/CATIA-Systems/FMPy/blob/35245dd8bf2b8be2a8e750b04bd29df4557d3032/fmpy/simulation.py#L355-L360
You will get another error from some later code where `fmi_type` is used (even if it is wrong). 

Sorry, I can't provide a PR yet, but the fix is easy by checking if the FMU really supports the given mode, e.g.:

```python
if fmi_type is not None:
    if (fmi_type == 'CoSimulation' and not modelDescription.coSimulation) or \
            (fmi_type == 'ModelExchange' and not modelDescription.modelExchange):
        raise ValueError("Invalid choice. FMU doesn't support fmi_type=%r" % fmi_type)
```

**Comment by t-sommer** [comment]
Fixed with 78e9b790. Thanks for reporting!
