### ISSUE TITLE
Create "matryoshka" FMUs

### ISSUE THREAD

**Issue by t-sommer** [CATIA-Systems/FMPy#193]
on behalf of @fajansen and @jbernalr

**Comment by fajansen** [comment]
The branch works as requested! There is only an issue at termination of the simulation, it seems that this is not properly passed to the inner fmus.
As an additional feature it would be nice to be able to rename the exposed variables.

**Comment by t-sommer** [comment]
@fajansen, can you give 1f8a2f3c14a36be810a95e33c4474485d1eb72bf a try?

**Comment by fajansen** [comment]
Termination of simulation works now as expected!
Renaming the exposed variables also works.

**Comment by fajansen** [comment]
It might be confusing to always have support for all platforms in the container. For example the remoting mechanism would not properly detect that it should be enabled.

**Comment by chrbertsch** [comment]
Would it be possible to provide a short documentation and example for this feature? Or have I overseen it? Thanks!

**Comment by t-sommer** [comment]
> Would it be possible to provide a short documentation and example for this feature? Or have I overseen it? Thanks!

See https://github.com/CATIA-Systems/FMPy/blob/master/tests/test_fmu_container.py for a demo of the new (experimental) API.

**Comment by chrbertsch** [comment]
> See https://github.com/CATIA-Systems/FMPy/blob/master/tests/test_fmu_container.py for a demo of the new (experimental) API.

Thanks. So the connections are defined manually in by the "Configuration". Would it be possible to read in an SSP file instead and create the Congfiguration from it?

**Comment by t-sommer** [comment]
> Would it be possible to read in an SSP file instead and create the Congfiguration from it?

Theoretically, yes.
