### ISSUE TITLE
Needed some help regarding the model exchange FMU

### ISSUE THREAD

**Issue by Kinshuk94** [CATIA-Systems/FMPy#194]
I want to simulate a model exchange setup with multiple FMUs I had used ssp with cosimulation earlier and it at least runs but I am unable to do the same with the model exchange. Could someone please guide me on this I am quite new to fmpy. Also I wanted to check one more thing whether the ssp can be used with the model exchange too so far it gives me an exception that the .fmu file does not support co-simulation. 
Thanks in advance.

**Comment by t-sommer** [comment]
The SSP implementation currently supports only Co-Simulation FMUs.
