### ISSUE TITLE
Generate binary: Link static libraries found in the sources directory

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMPy#195]
This problem appears when using fmpy to compile a binary out of a source code fmu. 
If static libraries are found in the sources, these will not be linked to the final binary, causing unknow symbol exceptions at runtime. 
We have modified the command to add this libraries, but it would be nice to check or warn the user that these are present and were not linked.

**Comment by t-sommer** [comment]
Can you share an example of such an FMU?

**Comment by jbernalr** [comment]
I will try, but a number of targetlink fmus have this arrangement

**Comment by StrAma84** [comment]
@jbernalr I have the same problem.
Can you please explain which command you modified specifically to add the library?

**Comment by StrAma84** [comment]
I tried to solve this by adding the library .a file to the source folder manuall and modified the ggc command in util.py line 802:
`command += ' -shared -o%s *.o custom_model.a '`  
  
However when trying to compile I receive a multiple errors like this, although the .a file and all related source-files have already been created using the -fPIC option as advised:
`/usr/bin/ld: custom_model.a(OrDCzzapNnUMwFd.o): relocation R_X86_64_32 against symbol 'BJOLDIrYTRXnHdxgcUElLWwwGIpo' can not be used when making a shared object; recompile with -fPIC  `


Alternatively I tried to link the library as a shared-object:
`command += ' -shared -o%s *.o custom_model.so '`  
Now the binary is built without errors, however when trying to run it in the target-application, the following error occurs:
`custom_model.so: cannot open shared object file: No such file or directory`

**Comment by StrAma84** [comment]
Probably I used the wrong syntax to link the library.
I tried again using this command, which should link the custom_model.a (included in the source directory) properly:
`command += '  -shared -o%s -L%s -lcustom_model *.o' % (target, sources_dir) `  

The compilation executes without any errors, however now again results in undefined symbols at runtime.  
Any help or advice is appreciated.

**Comment by t-sommer** [comment]
@jbernalr and @StrAma84, is this still an issue?
