### ISSUE TITLE
Scheduled Execution not supported as fmp

### ISSUE THREAD

**Issue by iscopa** [CATIA-Systems/FMPy#199]
Hello,

I am testing the "**Clocks.fmu**" from the Reference FMUs using **FMPy 0.2.25**.

Clocks.fmu is a "Scheduled Execution" fmu.

When trying to "instantiate" the fmu, FMPy produces the error:

File "C:\Users\coi1le\.conda\envs\FMPy_testEnv\lib\site-packages\fmpy\simulation.py", line 747, in instantiate_fmu
    raise Exception('FMI type "%s" is not supported by the FMU' % fmi_type)

"**instantiate_fmu**" currently supports ME and CS fmus. Could you please extend the function to also support Scheduled Execution FMUs?

Thank you and regards

**Comment by t-sommer** [comment]
Solved with 5be4e0c14f558b4e01eb223b11616768a6b281b6.
