### ISSUE TITLE
Change parameter values and modify variables for output

### ISSUE THREAD

**Issue by Flancis** [CATIA-Systems/FMPy#20]
Within the Modelica model one can set some default values for parameters. Also, one can define variables for output. However, for a very complicated model, sometimes it is very difficult to output every desired variable, e.g., protected variables. Therefore, is it possible to modify parameter values and add output variables using Python code or the fmpy.gui?

**Comment by t-sommer** [comment]
Take a look at the [coupled_clutches.py](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/coupled_clutches.py) example. It sets a start value for the variable `CoupledClutches1_freqHz` and selects the variables `outputs[1]`, `outputs[2]`, `outputs[3]`, `outputs[4]`as outputs.
 
The same can be achieved in the GUI by writing the start value in the respective fields.

**Comment by Flancis** [comment]
Thanks for the explanation. It is a very nice feature to be able to modify the start value in the GUI. How about examining the value of protected intermediate variables then?

**Comment by t-sommer** [comment]
Just plot the variable or export the results. You'll get the value at every time step.

**Comment by Flancis** [comment]
Maybe I did not explain it clearly. I meant the protected variables inside FMU. Those variables were not defined as output. The reason I am asking this is that in the FMU Simulink interface one can redefine new output variables by just dragging the intermediate variables to the output port of FMU.

**Comment by t-sommer** [comment]
Any variable listed in the `modelDescription.xml` of an FMU can be added to the results of a simulation or be plotted in the GUI regardless of its causality.

**Comment by Flancis** [comment]
Now I see how to plot those variables in the GUI. But I am still not sure how to "add those variables to the results" in Python code. Could you be more specific about this? I am new to Python, and sorry about having so many questions.

**Comment by Flancis** [comment]
Thanks for the explanation. Finally figured out how to add more output variables. One can just add variables described in the `modelDescription` file to the output variable like the following.
 `output=['outputs[1]', 'outputs[2]', 'outputs[3]', 'outputs[4]', 'der(outputs[1])', 'der(outputs[2])', 'der(outputs[3])', 'der(outputs[4])']`.
