### ISSUE TITLE
Additional arguments to step_finished callback function

### ISSUE THREAD

**Issue by hyumo** [CATIA-Systems/FMPy#200]
Is it possible to improve the `step_finished` function a bit so that additional arguments could be passed into it? This could possibly make it more flexible to control when `step_finished` should return `true`.

**Comment by t-sommer** [comment]
Which parameters would you like to see added to `step_finished()`?

**Comment by hyumo** [comment]
Is it possible to make it '*args' or '**kwargs'? A use case would be passing a tolerance value to terminates the simulation when model reaches steady state.

**Comment by t-sommer** [comment]
Since these values don't change during the simulation you could capture them when you create the callback function:

```python
tolerance = 1e-4

def step_finished(...):
    # do something with tolerance
    ...

simulate_fmu(..., step_finished=step_finished)
```

**Comment by hyumo** [comment]
Yeah, I get it, but this would become tricky if people want to make the tolerance value a variable. 

Also, there might be other methods to terminate the sim as well which might require their arguments to be variables. 

This is just an enhancement suggestion, it's not an urgent requirement.

**Comment by t-sommer** [comment]
Please reopen if you have a concrete proposal or use case.
