### ISSUE TITLE
Bug in plot results?

### ISSUE THREAD

**Issue by AHaumer** [CATIA-Systems/FMPy#201]
I wonder whether I'm doing something wrong, or there's some bug - and where.
During online teaching, I'm using FMPy - and I'm switching between two screens. 
The result on the first screen looks good, on the second screen there's something wrong (have a look at both images).
I'm using Anaconda 3 on Windows 10, and installed the latest version of FMpy (conda ...).
![1](https://user-images.githubusercontent.com/6900273/100070143-dcf52900-2e39-11eb-8601-c441568ad0a3.PNG)
![2](https://user-images.githubusercontent.com/6900273/100070147-de265600-2e39-11eb-8662-4f3df23268f7.PNG)

**Comment by t-sommer** [comment]
This might be related to https://github.com/pyqtgraph/pyqtgraph/issues/756.
