### ISSUE TITLE
Needed some help regarding connecting multiple ME FMU

### ISSUE THREAD

**Issue by Kinshuk94** [CATIA-Systems/FMPy#203]
Hello I really appreciate the work you have done in building the fmpy. I have currently been working on simulating multiple ME FMU together to run the simulation but I am unable to make progress. The co-simulation works fine but I am unable to find an example for connecting multiple ME FMU's together. 
Thanks in advance.

**Comment by t-sommer** [comment]
FMPy cannot simulate connected Model Exchange FMUs. For simulating Co-Simulation FMUs see #15 and #193.
