### ISSUE TITLE
add a default experiment stepsize to container fmu

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMPy#209]
for instance the minium value of all included fmus
(not very high priority as it is easy to fix, but for the sake of consistency)

**Comment by fajansen** [comment]
Actually the second smallest timestep would be best. As an alternative, it would also be ok to just take the stepsize as an additional entry in the configuration dictionary.

**Comment by fajansen** [comment]
I take "second smallest timestep" back. Both have their usecases. So I guess my request would be an additional attribute of the Container class. Could you please implement this?

**Comment by fajansen** [comment]
@t-sommer Could you add a attribute for the container class that creates a default experiment?
