### ISSUE TITLE
Constant Inputs

### ISSUE THREAD

**Issue by Marvin-TMG** [CATIA-Systems/FMPy#211]
There are some nice utility functions to load a csv file and pass these (time varying) singals to the fmu in a convenient way. However, we have a lot of inputs which are practically constant. To save data, it would be nice if we can pass a seperate input structure with constant non varying inputs, instead of filling the csv with repeated values.

**Comment by Marvin-TMG** [comment]
Types of input signals we may want to use:
* Constant non varying signals
* Discrete time varying signals sampled at regular interval - supported
* Time dependent signals at non uniform intervals (i.e. a simulating a step in road surface friction at a given time) - nice to have, would require a {time, value} pair for each signal
* Closed loop inputs (input signal depends on output) - supported via callback function

**Comment by Marvin-TMG** [comment]
A custom implementation of Input class would be a good idea, I think.

**Comment by t-sommer** [comment]
Another option would be to use a [custom simulation loop](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/custom_input.py) that gives you full control of the inputs (and outputs).

**Comment by Marvin-TMG** [comment]
Yes, that would be an option indeed. I dont have a good idea yet for a simple and flexible way to implement something like this. 
The easiest way would be to have an independent time vector for each input and a callback function where you can overwrite the input for the next step, something like

callback(fmu):
   fmu.input['signal_name'] = new value

**Comment by t-sommer** [comment]
> * Time dependent signals at non uniform intervals (i.e. a simulating a step in road surface friction at a given time) - nice to have, would require a {time, value} pair for each signal

You can merge input signals with different sample times by interpolating them into a common grid:

```python
import numpy as np
from fmpy import plot_result

t1 = np.linspace(0, 10, 21)  # 0.5 s sample interval
t2 = np.linspace(0, 10, 51)  # 0.2 s sample interval

# the input signals
u1 = np.sin(t1)
u2 = np.cos(t2)

# merge the sample times
t_i = np.unique(np.concatenate((t1, t2)))

# interpolate the signals
u1_i = np.interp(t_i, t1, u1)
u2_i = np.interp(t_i, t2, u2)

# create an structured array that can be passed to simulate_fmu()
dtype = np.dtype([('time', np.float64), ('u1', np.float64), ('u2', np.float64)])

merged = np.array(list(zip(t_i, u1_i, u2_i)), dtype=dtype)

plot_result(merged)
```

**Comment by Marvin-TMG** [comment]
Yes, this is a possibility indeed. I think I will go for a custom simulation class, because I realized what I try to achieve is fairly complex.

From my reference data, some signals will are time dependent inputs, but others serve as a reference for a controller, like so
input = pid(reference - output)
and other inputs are not present in the data, but these need to be populated with constants. Given 100 or so inputs, most constant, it would be a bit of a waste of memory to resample these to fixed grid.

In a custom simulations function, I will implement a function to set all constant values at the beginning and another discrete function to map all time dependent signals (plus the controller action).

It would be possible to implement the controller in a callback function, but I would need to have access to the fmu object, the vrs table and the input data structure. I believe in the current implementation only the time and recorder structure are accessible.

**Comment by t-sommer** [comment]
> I believe in the current implementation only the time and recorder structure are accessible.

You can access the FMU instance via the `recorder` object:

```python
def step_finished(time, recorder)
    instance = recorder.fmu  # get the FMU instance
    # interact with the FMU instance...
    return True  # continue simulation

```

See also [`SimulationThread.stepFinished()`](https://github.com/CATIA-Systems/FMPy/blob/a2c62367ebf57c9bcabd6f036636588f563502d4/fmpy/gui/simulation.py#L52) for a more complex example.

**Comment by t-sommer** [comment]
For your use case, I would suggest the following setup:

- pass all constants (i.e. parameters and constant inputs) as `start_values` to `simulate_fmu()`
- merge all inputs into a structured NumPy array and pass it as `input` to `simulate_fmu()`
- calculate the remaining inputs (controller input) in `step_finished` and set them directly

**Comment by Marvin-TMG** [comment]
Thanks, I did something like this but in a custom simulation loop. Using the start values structure is a good idea, that should solve the constant values.

In order ot make the controller work, in the callback function I need to be able to access the following:
* Signal map from variable name to id, this can be obtained as recorder.modelDescription
* Access to the input data structure, you know where I can get this?

**Comment by t-sommer** [comment]
> Access to the input data structure, you know where I can get this?

You can [capture](https://planspace.org/20150425-working_with_captured_variables_in_python_closures/) the input signals when you create the callback function.
