### ISSUE TITLE
Option to Suppress Warnings When Inputs Signals Dont Exist

### ISSUE THREAD

**Issue by Marvin-TMG** [CATIA-Systems/FMPy#212]
When input signals are not available in the input structure warnings are printed. This is nice for diagnostics purposes, but we would like to generate Jupyter reports, it would be nice if we can suppress these warnings for production use.

**Comment by t-sommer** [comment]
If you explicitly want to ignore missing inputs you could simply add additional columns with zeros to the input array to avoid the warning.
