### ISSUE TITLE
Error simulating FMU with external data

### ISSUE THREAD

**Issue by pkangowski** [CATIA-Systems/FMPy#215]
I receive an error simulating a FMU that includes external data from a txt-file (2.0, ME+CS, resources copied). 
FMPy does not handle the path of the unzipped resource file located in my temp folder properly. I suppose this is due to the blank space in my user name in Windows. So within the path **_User Name_** is reduced to **_UserName_**.

The error message looks like this:
[ERROR] Not possible to open file "C:/Users/**_UserName_**/AppData/Local/Temp/tmpzixbigro/resources/Data.txt": No such file or directory

Running the same FMU as a windows user without any blank spaces works fine.

**Comment by t-sommer** [comment]
Can you share the output with FMI call logging enabled?

**Comment by t-sommer** [comment]
This is likely a bug in the FMU. See also https://github.com/modelica/Reference-FMUs/issues/74.

**Comment by pkangowski** [comment]
> Can you share the output with FMI call logging enabled?
```
[FMI] fmi2Instantiate(instanceName="ResourceFMU", fmuType=1, guid="{ee956a02-0b81-44ef-8064-fd3a5135cd72}", resourceLocation="file:///C:/Users/Paul%20Kangowski/AppData/Local/Temp/tmpvh6rnebg/resources", callbacks=<fmpy.fmi2.fmi2CallbackFunctions object at 0x000001F0E84044C8>, visible=0, loggingOn=0) -> 0x1f0e5dc7290
[FMI] fmi2SetupExperiment(component=0x1f0e5dc7290, toleranceDefined=1, tolerance=0.0001, startTime=0.0, stopTimeDefined=0, stopTime=0.0) -> OK
[ERROR] Error: The following error was detected at time: 0
[ERROR] Not possible to open file "C:/Users/PaulKangowski/AppData/Local/Temp/tmpvh6rnebg/resources/Data.txt": No such file or directory
```
The path of resourceLocation is correct though.
