### ISSUE TITLE
unzippdir issue when calling getlongpathname for long usernames

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMPy#217]
in windows, some usernames (longer than 8 characters) cause problems when the unzippdir is created. 
when the path is intended to be restored using getlongpathname, the real path name reamains using "~"
this leads to an error in the further code: "directory not found" etc. 

usernames less than 8 characters long cause no problems.

**Comment by t-sommer** [comment]
Can you provide an example of such a path before `GetLongPathName()` is called?

**Comment by t-sommer** [comment]
This is probably an issue with the `TMPDIR`, `TEMP`, or `TMP` environment variables that are used in `tempdir.mkdtemp()`. Make sure they point to a legal directory.
