### ISSUE TITLE
add modelName to the input information to create fmu container

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMPy#218]
It would be nice to have an additional input parameter when creating fmu containers that allows to define a "modelName". 
This string should be then used to rename the FMUContainer.c and the modelName in the xml. 
The outcome would be a binary with a custom name every time, avoiding collisions when using multiple containers in one tool.

**Comment by t-sommer** [comment]
The `modelName` can be controlled via `create_fmu_container(..., output_filename='MyModelName)`.

> [...], avoiding collisions when using multiple containers in one tool.

Why would two binaries with the same name be a problem?
