### ISSUE TITLE
FMI1 FMUs with ModelExchange and CoSimulation Implementation are not handled correctly

### ISSUE THREAD

**Issue by jnjaeschke** [CATIA-Systems/FMPy#219]
Looking at the implementation in read_model_description, an FMI1 FMU can either be CoSimulation or ModelExchange, but not both:
```python
    # model description
    if is_fmi1:

        modelIdentifier = root.get('modelIdentifier')

        if root.find('Implementation') is not None:
            modelDescription.coSimulation = CoSimulation()
            modelDescription.coSimulation.modelIdentifier = modelIdentifier
        else:
            modelDescription.modelExchange = ModelExchange()
            modelDescription.modelExchange.modelIdentifier = modelIdentifier
```
This implies that every fmu that has both implementation is considered "CS-only". However, Dymola FMUs usually contain both implementations.

**Comment by t-sommer** [comment]
An FMI 1.0 FMU that has the `<Implementation>` element in its modelDescription.xml is by definition a Co-Simulation FMU because the element is not allowed in FMI 1.0 for Model Exchange.

**Comment by jnjaeschke** [comment]
I would object to that. :) 

From my point of view, the specification is unclear about this (FMI1.0.1 CS Specification, Chapter 3.5.1):

"The FMI for Co-Simulation modifies the model description format of FMI for Model Exchange, by appending an Implementation element; the reader is referred to section 3.1 of FMI for Model Exchange specification to understand the details of the top level description. The Implementation element is optional; if present, the import tool should understand the model description as applying to co-simulation."

In the FMI3 spec, there is a definition of the words "should" and "must", which is missing for FMI1/2. However, I interpret this paragraph as "if <implementation> is present, CoSimulation **must** be available. But this does not say that ModelExchange **must not** be available."

Regardless, it is of course challenging to find out programmatically whether a FMI1 FMU that contains a CoSimulation implementation also contains a ModelExchange implementation.

I tested the Dymola (2019) FMI import. It allows to import an 1.0 FMU with both implementations as ModelExchange, but the user has to specify this at the importing stage.

Maybe @chrbertsch can bring some light into the darkness?

**Comment by chrbertsch** [comment]
> Maybe @chrbertsch can bring some light into the darkness?

I was not part of the FMI 1 development and am not aware of its details.
My personal experience with tools is, that only Dymola exports and imports such ME+CS FMI 1.0 FMUs and I would consider this as "going beyond the FMI 1.0 standard" .

I would discourage the use of FMI 1 anyway :-)
