### ISSUE TITLE
simulate_fmu causing dymola server crash

### ISSUE THREAD

**Issue by FWuellhorst** [CATIA-Systems/FMPy#220]
Hello,

when using the function `simualte_fmu`, running a simulation of ca. 1 s on 12 cpu's in parallel, our Dymola server crashes as each simulation a license checkout is performed. This results in at least 12 request to the server per second which is interpreted as a DDOS attack.
Currently i am passing the unzipped directory as a filename but not the instanciated fmu.
One question and one feature request:

# Question
Is passing a `fmu_instance` to `simulate_fmu` which i instanciate before i start simulating enough to avoid the license checkout and thus server crash? As others depend on the server as well, i need to be sure my solution will work.

# Feature request
`simulate_fmu` is currently a function, it would thus be difficult to store the fmu_instance.
However you could provide a simple class which uses the functions `simulate_fmu` and `instantiate_fmu` storing relevant data and files in the class object. Currently i am using this solution myself, having it (or something similar) available for all users would be nice.

**Comment by t-sommer** [comment]
You have two options:

1. Export the FMU without license check (requires a binary code export license)
2. Instantiate the FMUs beforehand (this will pull one license for each concurrent instance)

**Comment by FWuellhorst** [comment]
Thanks for the quick reply. 
So my solution should work!
