### ISSUE TITLE
simulate_fmu with validate=true should fail when xml issues found

### ISSUE THREAD

**Issue by Maplesoft-fmigroup** [CATIA-Systems/FMPy#221]
Running a ModelExchange MapleSim/2019/CoupledClutches.fmu in the 0.2.26 version of FMPy GUI or using simulate_fmu(..,validate=true) reports no issues.  However, running the same FMU using validation.validate_fmu()
identifies a problem in ModelStructure/InitialUnknowns (thus the FMU has been flagged as non-compliant).
Shouldn't the simulation (with validate=true) flag the same problem?  It would be helpful if it was possible to do a validation in the FMPy GUI as well.

**Comment by t-sommer** [comment]
Validating the variable names is a potentially very expensive operation and therefore not executed upon `simulate_fmu()`. Also the validity of the variable names is irrelevant for the simulation.

You can call `fmpy.validation.validate_fmu()` to retrieve a list of all validation issues.

**Comment by Maplesoft-fmigroup** [comment]
The unreported problem was not with variables names, rather incorrect data in the InitialUnknowns field of the ModelStructure.

**Comment by Maplesoft-fmigroup** [comment]
Also, would it be possible to add xml validation equivalent to validate_fmu to the FMPy GUI (perhaps as a separate button)?

**Comment by t-sommer** [comment]
The action `Tools > Validate FMU` added in be5d797 validates all aspects of the FMU (including the InitialUnknowns).
