### ISSUE TITLE
Check for order of sequences in modelDescription.xml in validaton

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMPy#223]
The Modelstructure in FMI 2.0.2 is defined as an xs:sequence (https://github.com/modelica/fmi-standard/blob/1324a73a09bffa488ed40402e69bf2480fb39c0f/schema/fmi2ModelDescription.xsd#L231), thus the order important.

I received an FMU with the following structure:

```
  <ModelStructure>
    <InitialUnknowns>
      <Unknown index="6" dependencies="1 2 3 4 5"/>
      <Unknown index="7" dependencies="1 2 3 4 5"/>
    </InitialUnknowns>
    <Outputs>
      <Unknown index="6" dependencies="1 2 3 4 5"/>
      <Unknown index="7" dependencies="1 2 3 4 5"/>
    </Outputs>
  </ModelStructure>
</fmiModelDescription>
```

i.e., the InitialUnknowns are listed before the outputs. 

This error is not detected by validate_fmu() or https://fmu-check.herokuapp.com/, but e.g. when loading the FMU in the GUI
![grafik](https://user-images.githubusercontent.com/16363372/105755924-3ec23400-5f4c-11eb-9f53-6f4e067153fd.png)

(The FMU Compliance Checker detects this error)

**Comment by t-sommer** [comment]
Can you share the XML?
