### ISSUE TITLE
Check for not allowed start values of variables with calculated initial values

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMPy#224]
According to p.57 of the 2.0.2 specification, 

`If initial= ′′calculated′′or causality = ′′independent′′, it is not allowed to provide a startvalue.`

But this is not checked by validate_fmu().

(But the FMU compliance Checker detects this error)

**Comment by t-sommer** [comment]
Can you share an XML to reproduce the problem?
