### ISSUE TITLE
Changed input behavior in 0.2.27

### ISSUE THREAD

**Issue by joerg-tt** [CATIA-Systems/FMPy#227]
We just tested the new release and observed a change in the input simulation behavior that have been introduced with #214.

Namely, when stimulating a step signal, we observe an overshoot when recording the same input signal:

![image](https://user-images.githubusercontent.com/69461468/106260371-a4e6d980-6220-11eb-8595-0f2f758d9849.png)

In 0.2.26 it looks like this:

![image](https://user-images.githubusercontent.com/69461468/106260471-bd56f400-6220-11eb-92bb-75dace37053b.png)

This can be reproduced in the demo model CoupledClutches_CS using the following input:

```csv
t,step2
0,0
0.001,0
0.002,0
0.003,0
0.004,0
0.005,1
0.006,1
0.007,1
0.008,1
0.009,1
0.01,1

```

Thanks!

**Comment by chrbertsch** [comment]
Are the derivative inputs created with difference quotients from the input data from the CSV file?
As shown above this is problematic.

One could provide also directly derivatives in the CSV file. (not difference quotients from the last timestep but suitable values for extrapolation for the coming timestep)
And it should be prossible to deactivate seeting input derivatives completely.

**Comment by t-sommer** [comment]
Can you try to insert an event at time = 0.005 s (two samples at the same time step), so you get a discrete step?

```
t,step2
0,0
0.001,0
0.002,0
0.003,0
0.004,0
0.005,0
0.005,1
0.006,1
0.007,1
0.008,1
0.009,1
0.01,1
```

**Comment by joerg-tt** [comment]
Yes, adding a duplicate sample at 0.005 gets rid of the overshoot. But only for this specific case.

Assume I want to model an exponential input, I am still getting small overshoot artifacts:

```
t,step2
0,0
0.001,0
0.002,0
0.003,0
0.004,0.6
0.005,0.9
0.006,1
0.007,1
0.008,1
0.009,1
0.01,1
```

![image](https://user-images.githubusercontent.com/69461468/106289980-3454b280-624a-11eb-810f-67f2a6dd4583.png)

**Comment by t-sommer** [comment]
@KarlWernersson, what's your opinion?

**Comment by chrbertsch** [comment]
> I am still getting small overshoot artifacts:

Seems like the problem occurs when the time instants in the CSV file and the communication points to not coincide.

**Comment by KarlWernersson** [comment]
Hmm, im wondering if there is something with how the plot is done. We see that for all time varying points the plot is done slightly past the point when the derivative should change. However if the computation would continue from that point instead of the intended communication point we would not see the small adjustment in the plot but rather a drift and the next points should start missing their target. Instead we see and adjustment back as if the next computation is done at the exact time point where it should change. 
So is it possible the plot not synchronized with the communication step size? And that this is just and artefact on the method used to interpolate the result points for plotting?

**Comment by joerg-tt** [comment]
Some further investigation has given me some clue what could be going wrong. In short: I think that the derivative calculation https://github.com/CATIA-Systems/FMPy/blob/216bd08c76c05a97d145e29f8ada7a156df0bceb/fmpy/simulation.py#L409 is off with respect to the current simulation time.

The whole problem becomes more obvious when I set the Output Interval to 0.0005, which is half the step size of what my input.csv is defining:

```
t,step2
0,0
0.001,0
0.002,0
0.003,0
0.004,0.6
0.005,0.9
0.006,1
0.007,1
0.008,1
0.009,1
0.01,1
```

The resulting plot of step2 then looks like this:

![image](https://user-images.githubusercontent.com/69461468/109812349-3e444980-7c2c-11eb-9e02-be0172872aac.png)

I have also output the interpolated values and the calculated derivative for each step:

```
time: v, der_v
0.0005: [0.], [0.]
0.0010: [0.], [0.]
0.0015: [0.], [0.]
0.0020: [0.], [0.]
0.0025: [0.], [0.]
0.0030: [0.], [0.]
0.0035: [0.3], [600.]
0.0040: [0.6], [600.]
0.0045: [0.75], [300.]
0.0050: [0.9], [300.]
0.0055: [0.95], [100.]
0.0060: [1.], [100.]
0.0065: [1.], [0.]
0.0070: [1.], [0.]
0.0075: [1.], [0.]
0.0080: [1.], [0.]
0.0085: [1.], [0.]
```

My assumption would be that the derivatives are shifted by one sample. I.e., at `t=0.003` we should already have `der_v=600`. And at `t=0.006` a value of `der_v=0` would be correct.

I've actually hacked the interpolate method a bit to give me the corrected values. This results in the following plot:

![image](https://user-images.githubusercontent.com/69461468/109813115-333de900-7c2d-11eb-9ad8-d703198b5bfd.png)

```
0.0005: [0.], [0]
0.0010: [0.], [0]
0.0015: [0.], [0]
0.0020: [0.], [0]
0.0025: [0.], [0]
0.0030: [0.], [600]
0.0035: [0.3], [600]
0.0040: [0.6], [300]
0.0045: [0.75], [300]
0.0050: [0.9], [100]
0.0055: [0.95], [100]
0.0060: [1.], [0]
0.0065: [1.], [0]
0.0070: [1.], [0]
0.0075: [1.], [0]
0.0080: [1.], [0]
0.0085: [1.], [0]
```

I'm happy to provide more info if needed.

BR, Jörg

**Comment by joerg-tt** [comment]
This is the change:

```python
Index: fmpy/simulation.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- fmpy/simulation.py	(revision 216bd08c76c05a97d145e29f8ada7a156df0bceb)
+++ fmpy/simulation.py	(date 1614929195560)
@@ -408,6 +408,13 @@
         v = w0 * v0 + w1 * v1
         der_v = (v1 - v0) / (t1 - t0)
 
+        i_next = np.where(t > time)[0][0]
+        i_prev = i_next - 1
+        v_next = table[:,i_next]
+        v_prev = table[:,i_prev]
+        der_v = (v_next - v_prev) / (t[i_next] - t[i_prev])
+
+        print(f'{time:.4f}: {v}, {der_v}')
         return v, der_v
 ```

But there is a restriction. This only works properly if the CSV sampling interval is an integer multiple of the output interval.

E.g., when setting `Output Interval = 0.0008`, the derivative calculation still seems off for some sample points:

![image](https://user-images.githubusercontent.com/69461468/110084240-0524ea00-7d90-11eb-82b7-fdbb45c8aa8f.png)

```
time    v     der_v
0.0008: [0.], [0.]
0.0016: [0.], [0.]
0.0024: [0.], [0.]
0.0032: [0.12], [600.]
0.0040: [0.6], [300.]
0.0048: [0.84], [300.]
0.0056: [0.96], [100.]
0.0064: [1.], [0.]
0.0072: [1.], [0.]
0.0080: [1.], [0.]
0.0088: [1.], [0.]
0.0096: [1.], [0.]
```

To be honest, I have no clue what would be the proper derivative values in this case.

**Comment by t-sommer** [comment]
Note that with 319230c9e659b9dd3869e45dc109602db0e23e60 input derivatives are now disabled by default.

**Comment by chrbertsch** [comment]
> Note that with 319230c input derivatives are now disabled by default.

this is good

> To be honest, I have no clue what would be the proper derivative values in this case.

I think one could to it (for a fixed timestep)  with a two-stage linear interpolation.
First interpolate linearly from the input timpoints of the csv to the time points of the simulation, then calculuate the "derivative" with a differenence quotient from these values
