### ISSUE TITLE
Setup start value for the custom input example

### ISSUE THREAD

**Issue by Flancis** [CATIA-Systems/FMPy#23]
Hi, in the `coupled_clutches.py` example one can set the start value using the `simulate_fmu` functionality. Is there a similar way to modify the start value (of a parameter) for an FMU instance? For example, how to modify the start value for the FMU in the `custom_input.py` example? To be specific, the parameter might have the following property, and I would like to modify the value 1.
`<ScalarVariable
      name="friction"
      valueReference="111"
      description="Friction coefficient"
      causality="parameter"
      variability="tunable">
      <Real start="1"/>`

**Comment by t-sommer** [comment]
You can use [apply_start_values()](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/simulation.py#L230) or set the values directly (see [parameter_variation.py](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/parameter_variation.py#L73)):

```python
# read model description & instantiate FMU ...

fmu.setupExperiment()

# OPTION 1: set the value directly
fmu.setReal(vr=[111], value=[1.5])

# OPTION 2: use apply_start_values()
apply_start_values(fmu, model_description, start_values={'friction': 1.5})

fmu.enterInitializationMode()
fmu.exitInitializationMode()

# start simulation loop...
```

**Comment by Flancis** [comment]
Hi, thanks for the explanation. I tested both options on the `custom_input.py` example, but it seems like OPTION 1 did not affect the result. I guess the two methods are essentially different? Maybe OPTION 1 did not work in the case `variability = "fixed"`? The following changes are made on the example.
`# OPTION 1`
`fmu.setReal(vr=[67], value=[0.4])`
`# OPTION 2`
`apply_start_values(fmu, model_description, start_values={'CoupledClutches1_freqHz': 0.4})`

**Comment by Flancis** [comment]
By the way, both methods work in the case `variability = "tunable"`.
