### ISSUE TITLE
Segfault on resource paths with spaces 

### ISSUE THREAD

**Issue by ranjanan** [CATIA-Systems/FMPy#230]
I generated an FMU with a json resource, and I found that while trying to instantiate this in `fmpy`, I get the following segfault: 
```
file:///C:/openmodelica/test/openmodelica/t%20mp/resources
assert            | debug   | Failed to open file C:/openmodelica/test/openmodelica/t%20mp/resources/Modelica_Electrical_Machines_Examples_DCMachines_DCPM_Temperature_info.json for reading: No such file or directory
getBestJumpBuffer got mmc_jumper=0000000000000000, globalJumpBuffer=0000000000000000
```
To reproduce, here's the zip file with the fmu and requisite code. Running `python test.py` in the openmodelica folder should reproduce it: 
[test.zip](https://github.com/CATIA-Systems/FMPy/files/5969875/test.zip)

I am on fmpy 0.2.27. If you change the name of folder from `t mp` to `tmp` (and change the path in `test.py`), it does not segfault, which leads me to believe that the space in the URI causes the segfault. 

Other potentially useful information. I believe this is the same issue as that which https://github.com/modelica/Reference-FMUs/pull/75 fixes. 

Thank you for your time!

**Comment by t-sommer** [comment]
This is a bug in the FMU. Please open an issue on https://github.com/OpenModelica/OpenModelica.

**Comment by ranjanan** [comment]
Sure, happy to post there. Would you mind expanding upon why it's an openmodelica bug? 

Is it because FMPy is calling the `fmi2instantiate` API from provided binary and it's that API which can't handle the URIs with spaces?

**Comment by t-sommer** [comment]
Most likely, yes.
