### ISSUE TITLE
UnicodeDecodeError in  printLogMessage

### ISSUE THREAD

**Issue by vruge** [CATIA-Systems/FMPy#231]
If our fmi is crashed `generationTool="Dymola Version 2020 (64-bit), 2019-04-10 (using dassl with tolerance 0.0001)"`
like

```bash
[ERROR]   Last value of the residual:
[ERROR] 

[OK]     { 1.56994E+06, 3.52382 }

[ERROR]  
[ERROR] 

[OK] Solver will attempt to handle this problem.
```
then
```python
printLogMessage(component, instanceName, status, category, message)
```
raise an `UnicodeDecodeError` 

where 
```python
component = None
instanceName = 'Test' 
status = 3
category = 3
message = '\n... Error message from \xa8\xb9&\\\x04\n'
```

Of course we override the `callbacks/printLogMessage` and catch the error in our workflow.

**Comment by t-sommer** [comment]
Can you share an FMU to reproduce the problem?

**Comment by vruge** [comment]
Currently  I am unable to reproduce the error. I hope the error with utf-8 is a duplication of #237
