### ISSUE TITLE
Optimizing compiler flags missing in 'fmpy compile'.

### ISSUE THREAD

**Issue by ckirches** [CATIA-Systems/FMPy#232]
'fmpy compile' must add -O2 or -O3 when compiling FMIs. Dymola, in particular, emits C source code so convolved that without optimization enabled, a significant amount of time is spent in millions of small functions calls.

**Comment by t-sommer** [comment]
Dymola uses the following flags when compiling the FMU's binary with MSVC:

```
/Oy /Ob1 /Oi /MT
```

Would this solve your problem?

**Comment by CSchulzeTLK** [comment]
Linker flags can be passed to msvc using the "CL" environment variable.

I addressed similar issues with gcc in my fork, but obviously you don't accept pull requests.
https://github.com/CSchulzeTLK/FMPy/commits/develop

**Comment by t-sommer** [comment]
With fd49a7c78094b0e54b06aef08ce94fde6329bf1a you can now use custom compiler options, e.g.

```
fmpy compile MyModel.fmu --compiler-options="/LDd /Zi"
```

to create a debug build on Windows.
