### ISSUE TITLE
fmi2Set* functions not executed by the fmpy simulator

### ISSUE THREAD

**Issue by vibhoraggarwal** [CATIA-Systems/FMPy#233]
### Description 
I am using simple fmpy command for simulating FMUs (eg. bouncingball.fmu). 
`fmpy simulate bouncingball.fmu`

What I understand is while simulating an FMU (let say for co-simulation) the step should be:
1.	Enter initialization mode
2.	apply inputs and set values (should use fmi2Set* functions here)
3.	Exit initialization
4.	Simulation continues

I want to use parameters for the fmu so need to use the fmi2Set* functions. However, the simulator does not access them. I gave a print call to the following functions for debugging (with: <function_name> function is executed)
1.	fmi2Enter/ExitInitialization(), 
2.	fmi2GetInteger(), and 
3.	fmi2SetInteger() functions 

and received the output as mentioned in the log below. It is evident from below that the fmi2Set* functions are not called. 

### Question:
1.	Has somebody already used the fmi2Set* functions and have an established workaround for this?

### Log
```
fmpy simulate bouncingBall.fmu
EnterInitializationMode() function is executed
ExitInitializationMode() function is executed
GetReal() function is executed

**Comment by t-sommer** [comment]
Did you specify any start values? E.g.

```
fmpy simulate BouncingBall.fmu --start-values h 2.5
```

**Comment by vibhoraggarwal** [comment]
@t-sommer I missed this, and it worked indeed. Thanks. 

----
For someone who might follow the issue: 
The code [here ](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/command_line.py#L46 ) gives a supportive command for setting the custom start value and [here](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/command_line.py#L47) gives a supportive command for setting directly from the xml file.
