### ISSUE TITLE
Trying to interact with the FMU in the middle of the process

### ISSUE THREAD

**Issue by aisak7** [CATIA-Systems/FMPy#235]
Hello,

I am carrying out an investigation on the integration of FMUs, I have launched an FMU model through the FMPy api.

Once this is achieved, my intention is to be able to modify some initial values ​​given to other values ​​given later in the middle of the execution, in this way to be able to achieve different results at same graph.

I explain it with an example, I am working on the "Bouncingball.fmu" model, which we pass some initial values ​​that are gravity and a coefficient, my intention is once I have launched the program with initial values ​​such as gravity (- 9.81) and coefficient of restitution (0.7) modify them and give it other values ​​such as g (-6) and cor (0.4), thus showing me a graph at the end with this fluctuation between the values, would this be possible? If so, would How could I do it? I've been going around it and trying various things, but without success.

thanks in advance.

**Comment by t-sommer** [comment]
For your example it seems better to iterate over the parameters (e.g. with a for-loop) and pass them as start values:

```python
result = simulate_fmu(..., start_values={'e': -6, 'cor', 0.4})
```

You can also interact with the FMU directly using the `step_finished` callback or a custom simulation loop (see #211). Note however that this will not reset or re-initialize the states of the FMU.

**Comment by aisak7** [comment]
Thanks for replying that fast, ill try it, keep in touch.

**Comment by aisak7** [comment]
Hello again @t-sommer ,

I am having some doubts about the step_finished callback, im using this print(dir(recorder.fmu)) to show the attributes available, have tested some of them without any result.

Could you guide me a bit on what attributes I could use and in what way to be able to modify the values?

thanks in advance.

**Comment by t-sommer** [comment]
You can use `recorder.fmu.setReal()` to set variables. See [custom_input.py](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/custom_input.py) for an example.

**Comment by aisak7** [comment]
Hello @t-sommer ,

im having the next error when trying to use "recorder.fmu.setReal" in ModelExchange

**[ERROR] Variable e can only be set after instantiation, in initialization mode or event mode.**

what could be the cause of this? i have tried lot of things but nothing work, the same example im trying worked perfectly at CoSimulation, but i want to do it on ModelExchange.
