### ISSUE TITLE
FMU - Problem reassigning a new value to a variable "ModelExchange"

### ISSUE THREAD

**Issue by aisak7** [CATIA-Systems/FMPy#238]
**Main Goal**

Start the FMU with defined start_values ​​and change it in the middle of the process at "ModelExachange".

**Approach**

 1. Take the FMU already created from the FMI standard web.
 2. Launch it with FMPY.
 3. Change value every step with step_finished parameter from simulate_fmu with my_callback function.

**First step**

FMU is loaded perfectly, and the same code is working perfectly at "CoSimulation" but the goal is "ModelExchange".

**The problem**

im trying to modify a value at my_callback function, but this give me the next error:

    [ERROR] Variable e can only be set after instantiation, in initialization mode, or in event mode.

i have tried run event mode before the assignment, or initialization mode, but nothing works.

In this line we modify the value, setting the reference from XML first parameter, and the value second parameter:

    recorder.fmu.setReal([2], [count])

at this point exactly is where im getting the exposed error.

Python Code:

 

    import fmpy
    from fmpy import *
    from ctypes import *
    
    fmpy.plot_library = 'plotly'  # experimental
    
    global count
    
    filename = 'BouncingBall.fmu'
    
    
    start_values = {
        # variable    start   unit       description
        'g':         (-9.81, 'm/s2'),  # Gravity acting on the ball
        'e':            0.7,           # Coefficient of restitution
    }
    
    output = [
        'h',  # Position of the ball
        'v',  # Velocity of the ball
    ]
    
    def my_callback(time, recorder):
        # use recorder.fmu to access the FMU instance
        count = 0
    
        if time < 1:
            count = 3
        else:
            count = 1
    
        recorder.fmu.setReal([2], [count])
    
        return True
    
    result = simulate_fmu(filename, start_values=start_values, output=output, stop_time=3.0,fmi_type = 'ModelExchange',solver = 'Euler', step_size = 0.001, output_interval = 0.001, step_finished = my_callback)
    
    plot_result(result)

**My questions:**

Any idea how could i solve this?, is possible to do what im trying for ModelExchange?

Thanks.

**Comment by t-sommer** [comment]
You have to enter Event Mode before setting the variable:

```python
def my_callback(time, recorder):
    count = 0
    # ...
    recorder.fmu.enterEventMode()
    recorder.fmu.setReal([2], [count])
    recorder.fmu.enterContinuousTimeMode()
    return True
```

**Comment by aisak7** [comment]
Hello @t-sommer,

Thanks you very much for ur answer, it works perfectly with my value reference 3, but it doesnt work with the value reference 2, here are the xml variable declarations:
```
</ScalarVariable>
    <ScalarVariable name="g" valueReference="2" causality="input" variability="continuous" initial="exact" description="Gravity `acting` on the ball">
      <Real start="-9.81" derivative="2" declaredType="Acceleration"/>
    </ScalarVariable>
    <ScalarVariable name="e" valueReference="3" causality="input" variability="continuous" initial="exact" description="Coefficient of restitution">
      <Real start="0.7" min="0.5" max="1"/>
    </ScalarVariable>  
```
Having again the same issue as exposed before:

**[ERROR] Variable g can only be set after instantiation or in initialization mode.**

thanks again, your helping me a lot.

**Comment by t-sommer** [comment]
Please move this discussion to StackOverflow and link it here. It's not related FMPy.

**Comment by aisak7** [comment]
Hello @t-sommer 

[StackOverFlow Discussion](https://stackoverflow.com/questions/66452092/fmu-problem-reassigning-a-new-value-to-a-variable)

here is the same question i have posted yesterday, please answer me there to my last question made here.

Thanks you very much.
