### ISSUE TITLE
Could not import CS FMU with clock definitions

### ISSUE THREAD

**Issue by iscopa** [CATIA-Systems/FMPy#239]
Hello,

I have created a Co-Sim FMU where I defined clocked model partitions. My variable definitions in the modelDescription.xml

![image](https://user-images.githubusercontent.com/64407895/109804840-008ef300-7c23-11eb-9cbe-0f1bdfcbd47e.png)

Currently it is not possible to import the FMU in fmpy (0.2.27), see import errors below, as the clock definitions in the tool are not harmonised with the FMI spec yet.

![image](https://user-images.githubusercontent.com/64407895/109804073-22d44100-7c22-11eb-9cea-0610130c3833.png)

A tool update correcting this issue would be helpful.

Thank you

**Comment by t-sommer** [comment]
The modelDescription.xml has correspond to the version of used by the respective version of FMPy. Note that FMI 3.0 support is experimental and subject to changes.
