### ISSUE TITLE
error: 'FMU3Slave' object has no attribute 'UpdateDiscreteStates' using FMPy 0.2.27

### ISSUE THREAD

**Issue by iscopa** [CATIA-Systems/FMPy#244]
Hello,

The function "newDiscreteStates" in the class "_FMU3(_FMU):" in fmi3.py should be updated to "**Update**DiscreteStates"

Thank you

**Comment by t-sommer** [comment]
Solved with f99c29f900d31b1f6b2c35e9a89c5f215d1240cf.
