### ISSUE TITLE
In python script use "apply default start values"

### ISSUE THREAD

**Issue by jharming** [CATIA-Systems/FMPy#245]
For a steady state FMU, i.e. no transient. I would just evaluate the FMU, I can do that with set and get variables.

But if I change the parameters values in the modelDescription.xml then when I set and get the variables then I cannot get FMPy to use the new model parameters. In the GUI there is a tick box where you can choose "Apply default start values". But I cannot figure out how to do that using a script.

I have created the FMU using modellica. It is simple polymials where I would like to be able to change the coefficients in python and then create new FMU's which can then be evaluated in python.

**Comment by vibhoraggarwal** [comment]
I also faced this issue a while back, documented in issue #233 

You can set the following property to be `True`:

`apply_default_start_values` in [simulate_fmu() function ](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/simulation.py#L565), eg. `simulate_fmu(<fmu file name>, apply_default_start_values= True)`

or

 if using `fmpy simulate <fmu name>`to simulate use it in the following way:
`fmpy simulate <fmu name> --apply-default-start-values`

**Comment by t-sommer** [comment]
Changing the start values in the XML is strongly discouraged (see FMI 2.0.2 Spec., p. 56).

**Comment by t-sommer** [comment]
Why not just use `simulate_fmu(..., output_interval=x, stop_time=x)` to do one step?

**Comment by jharming** [comment]
I used the method described in the "efficient loops", here I made the class as shown below. Sorry about the formatting I cannot get it to work properly. The class works in principle fine. It return a result file with a single value. The issue is that it is really slow compared to the other class above where I used FMU2slave and then set/get parameters. Is there a reason not to use set/get parameters when I am only evaluating a response surface.

class FMU():
    def __init__(self, FMU):
        self.unzipdir = extract(FMU)
        self.model_description = read_model_description(self.unzipdir)
        self.fmu_instance = instantiate_fmu(self.unzipdir, self.model_description, 'ModelExchange')
    
    def sim(self, start_values):
        self.fmu_instance.reset()
        # pass the unzipdir, model description and FMU instance to simulate_fmu()
        result = simulate_fmu(self.unzipdir,
                              start_values=start_values,
                              model_description=self.model_description,
                              fmu_instance=self.fmu_instance,
                              output_interval=1, stop_time=1)
        return(result[1])
        
    def close():
    
        # free the FMU instance and unload the shared library
        self.fmu_instance.freeInstance()
    
        # delete the temporary directory
        shutil.rmtree(self.unzipdir, ignore_errors=True)

**Comment by t-sommer** [comment]
> Is there a reason not to use set/get parameters when I am only evaluating a response surface.

Looks good to me.
