### ISSUE TITLE
serialize FMU state

### ISSUE THREAD

**Issue by DaJansenGit** [CATIA-Systems/FMPy#25]
Hey 
i realized that FMPy doesn't bring the option to serialize an FMU state. It would be really nice if you implement this feature FMI Feature (`fmi2SerializeFMUstate`) because the FMU states couldn't be stored by pickle. Or do you have any other idea how to store them?

**Comment by t-sommer** [comment]
`fmi2SerializeFMUstate` and `fmi2DeSerializeFMUstate` are the right way to retrieve / set the state of an FMU (given the FMU supports it). Pickle would probably not work because you also have to extract the FMU, load and initialize the shared library. Can you add some info or pseudo code on how you intend to use the functions?

**Comment by hyumo** [comment]
I think it would be interesting if some features like importing the dsfinal.txt file in Dymola could be implemented. Instead, fmupy could use serialized fmu states.

**Comment by DaJansenGit** [comment]
Thanks for the fast reply.
In my specific case i want to store the FMU state in a file because i want to continue the simulation a few days later but because it's very time consuming i don't want to start it from zero again. 

So it would be something like this
Day x:
`fmu.simulate`
`state_x = fmu.get_fmu_state()`
`state_x_byte_vector = serialize_fmu_state(state_x)`
`store state_x_byte_vector with pickle (should work with the vector)`

Day y:
`load stored_byte_vector`
`state_DeSerialized = deserialize_fmu_state( stored_byte_vector)`
`continue simulation from old state`

**Comment by t-sommer** [comment]
Just added the missing functions. See [test_serialize_fmu_state.py](https://github.com/CATIA-Systems/FMPy/blob/develop/tests/test_serialize_fmu_state.py) for an example.

**Comment by DaJansenGit** [comment]
Wow that was fast. Thank you really much for the fast integration.

**Comment by glmourad** [comment]
Hi @t-sommer, thanks for the example. Works fine using memory.
Is it possible to store the fmu state using files?

**Comment by t-sommer** [comment]
The serialized state is just a byte string. You can store it as a file or in a database.
