### ISSUE TITLE
Clarification on some part of FMPy code

### ISSUE THREAD

**Issue by manasdas17** [CATIA-Systems/FMPy#251]
Hi, Could you please clarify on this point:- 

What is the purpose of cswrapper code, sundials solver or functions? Is it only required for 
ModelExchange type FMU simulation and not for Co-simulation type FMU simulation?

Regards,
Manas

**Comment by t-sommer** [comment]
The `cswrapper` is an optional binary that adds a solver to a Model Exchange FMU and implements the Co-Simulation API.
`CVode` is a variable step solver that can be used to simulate Model Exchange FMUs.
