### ISSUE TITLE
Loading error with FMU

### ISSUE THREAD

**Issue by manasdas17** [CATIA-Systems/FMPy#252]
Hello,
Some unit related error is coming up while trying to load this FMU to FMPy and it's not getting loaded.
PFA for the error screenshot & the FMU.
[Test.zip](https://github.com/CATIA-Systems/FMPy/files/6283738/Test.zip)

**Comment by t-sommer** [comment]
The attached file is not a valid FMI 2.0 FMU. To work around the issue, you can disable the validation:

```Python
from fmpy import *

filename = 'Rosenbrock_64bits.fmu'

result = simulate_fmu(filename, validate=False)

plot_result(result)
```
