### ISSUE TITLE
getInterval...() function wrappers seem to be missing

### ISSUE THREAD

**Issue by oliverkotte** [CATIA-Systems/FMPy#255]
Hi Torsten,
using your latest dev build (commit e570058), we would like to simulate an FMU with an aperiodic changing input clock. This requires support of getIntervalDecimal(), getIntervalFraction() (and maybe others). We noted that class _FMU3(_FMU): contains in the  __init__ method the signatures of the required clock-related functions. And we also noted that if an FMU implements fmi3GetIntervalDecimal(), then the Python object fmu returned by fmpy.instantiate_fmu() will have a method fmu.fmi3GetIntervalDecimal(). Yet a wrapper function fmu.getIntervalDecimal() is missing in fmi3.py, but that would be needed to meaningfully call fmi3GetIntervalDecimal() from our Python code, right? Do you have plans to add the wrappers of the clock-related functions soon?

**Comment by t-sommer** [comment]
Fixed with 3993b05922b6d49a6935c6ddb5575b721eeb85ad.
