### ISSUE TITLE
getInterval() for all FMI types, not SE specific

### ISSUE THREAD

**Issue by oliverkotte** [CATIA-Systems/FMPy#257]
def getIntervalDecimal(self, valueReferences, intervals, qualifiers):
        self.fmi3GetIntervalDecimal(self.component, valueReferences, len(valueReferences), intervals, qualifiers, len(intervals))
is member of
class FMU3ScheduledExecution(_FMU3):
    """ An FMI 3.0 Scheduled Execution FMU """
but should not be specific to SE. 
It is definitely callable from CS, I believe also from ME, so should be general for all FMI types

See e.g. fmi spec 2.2.9.2 table 5
fmi3GetInterval in Initialization Mode, fmi3GetInterval in both Event Mode and Clock Activation Mode if and only if this Clock ticked using clocksTicked == fmi3True

**Comment by t-sommer** [comment]
Fixed with 3e90d02e98d9b2965b1223141407d35cdb47ff98.
