### ISSUE TITLE
read_model_description(fmu) fails if parameters in xml have no start value

### ISSUE THREAD

**Issue by EmmanuelChr** [CATIA-Systems/FMPy#258]
in some fmus parameters may not have start values in the xml file. Here an example for FMIKit:

 
```
<ScalarVariable name="Parameters.Gearbox.M_Rad[1]" valueReference="2" causality="parameter" variability="tunable">
     <Real/>
 </ScalarVariable>
```

Here the start value of the variable is missing (after the key word Real). A full description looks like this: 

```
   <ScalarVariable name="Parameters.P_loss_systemW_tableData[21,235]" valueReference="15779" causality="parameter" variability="tunable">
     <Real start="52829.502504769072"/>
    </ScalarVariable>
```

In such a case (where start values are missing) the call of read_model_description(fmu) fails thus leading to failure of fmu integration with FMPy. Yet the fmu is not corrupt and can be simulated in other platforms (e.g. SILVER from SYNOPSYS). Lookls like the start values are hard coded in the dll and could be resolved by the caller function.

**Comment by t-sommer** [comment]
Parameters must have a start value (see FMI 2.0 Spec, p. 54).

**Comment by EmmanuelChr** [comment]
OK, then we should forward this issue to FMIKit! Should I place it there?

**Comment by t-sommer** [comment]
Yes, please.
