### ISSUE TITLE
some arguments of getters for decimal/shift interval/fraction shall be return values

### ISSUE THREAD

**Issue by oliverkotte** [CATIA-Systems/FMPy#260]
for these getters, only fmpy-api-side input argument shall be array of value references, other stuff are **return values**
i.e `intervals, qualifiers = fmi3GetIntervalDecimal([valueReferences])`

typedef fmi3Status fmi3GetIntervalDecimalTYPE(fmi3Instance instance,
                                              const fmi3ValueReference valueReferences[],
                                              size_t nValueReferences,
                                              **fmi3Float64 intervals[],
                                              fmi3IntervalQualifier qualifiers[],
                                              size_t nIntervals);**

typedef fmi3Status fmi3GetIntervalFractionTYPE(fmi3Instance instance,
                                               const fmi3ValueReference valueReferences[],
                                               size_t nValueReferences,
                                               **fmi3UInt64 intervalCounters[],
                                               fmi3UInt64 resolutions[],
                                               fmi3IntervalQualifier qualifiers[],
                                               size_t nIntervals);**

typedef fmi3Status fmi3GetShiftDecimalTYPE(fmi3Instance instance,
                                           const fmi3ValueReference valueReferences[],
                                           size_t nValueReferences,
                                           **fmi3Float64 shifts[],
                                           size_t nShifts);**

typedef fmi3Status fmi3GetShiftFractionTYPE(fmi3Instance instance,
                                            const fmi3ValueReference valueReferences[],
                                            size_t nValueReferences,
                                            **fmi3UInt64 shiftCounters[],
                                            fmi3UInt64 resolutions[],
                                            size_t nShifts);**

**Comment by t-sommer** [comment]
You have to pass arrays that are "filled" by the function e.g.

```Python
vrs = (fmi3ValueReference * 1)(1001)
intervals = (fmi3Float64 * 1)()
qualifiers = (fmi3IntervalQualifier * 1)()

fmu.getIntervalDecimal(vrs, intervals, qualifiers)
```

**Comment by oliverkotte** [comment]
Thanks a lot for fixing/explaining this clock.related stuff in the past days so promptly!

Mit freundlichen Grüßen / Best regards

Oliver Kotte
CR/AEE3

Tel. +49 711 811-26282 | Mobil +49 172 5679055
​
