### ISSUE TITLE
Support alias variables in create_fmu_container

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMPy#264]
Currently, it is possible to rename the exposed variables when using the create_fmu_container feature by specifying a mapping in the "variables" dictionary of the configuration. This dictionary has the original name as the key, and as a value a dictionary with name and description as it should appear in the modelDescription.xml

Please extend this mechanism so a that the value supports a list of dictionaries.
Example:
` variables = {
'fmu1.out1': [{'name': 'out1', 'description': 'This is Output 1'}, {'name': 'fancyname', 'description': 'This is a fancy name for Output 1'}] } `

For FMI2 this should behave the following way:
If a list is passed and the variable has causality "output", for each element of the list an entry should be added in the modelDescription, all sharing the same valueReference.
If the variable has a different causality: Throw an error.

resulting modelDescription excerpt:
`
<ScalarVariable name="out1" valueReference="0" causality="output" description="This is Output 1">
      <Real/>
    </ScalarVariable>
<ScalarVariable name="fancyname" valueReference="0" causality="output" description="This is a fancy name for Output 1">
      <Real/>
    </ScalarVariable>
`

For FMI3 (once #256 is implemented) this should result in the creation of alias variables independent of causality.

**Comment by t-sommer** [comment]
> If a list is passed and the variable has causality "output", for each element of the list an entry should be added in the modelDescription, all sharing the same valueReference.

Why would that be important?

**Comment by fajansen** [comment]
The same motivation as for all alias variables (I request only outputs as inputs and parameters aliases are not allowed in FMU2.0):
It's a mapping functionality. In my case I need to have the outputs named after a customer request so they can be automatically connected to other FMUs, but also following a specific scheme for test automation.

**Comment by t-sommer** [comment]
But would it make a difference, if two outputs mapping to the same internal variable have different VRs?

**Comment by t-sommer** [comment]
This should be resolved with f58da66ec7b7b111f21dbc0d35e2e32f5600fd33.
