### ISSUE TITLE
Provide mechanism to map one input/parameter to multiple FMUs with create_fmu_container

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMPy#265]
Provide a way to map one variable with causality input or parameter to more than one inner fmu. It's currently already possible to map the output of one FMU to the inputs of several other FMUs with the connections mechanism, but not inputs to the container.

Example usecase:
Two models of physical systems that interact and are in the same room. Both have an input for the ambient pressure and temperature. When I wrap these in an container, currently I can only expose both inputs and then hope that the same value is written to both inputs. It would be much better if the container FMU just had one input and a call to fmiXSetXXX would result in the value being set for both inner FMUs.

**Comment by chrbertsch** [comment]
> I'm not aware of any way to create an SSP file from python, so while I generally agree that using an SSP file as input would make sense, it would not help me.

You can use the Python API of OMSimulator to programmatically create an SSP file from Pyhthon https://openmodelica.org/doc/OMSimulator/master/html/OMSimulatorPython.html#

**Comment by t-sommer** [comment]
@fajansen, can you give 930965e561017646aaceaeac2bcf62c55f0285ed a try?

**Comment by fajansen** [comment]
It works for me.
