### ISSUE TITLE
Option to delete source-code after binary (re)compilation

### ISSUE THREAD

**Issue by PhilippZofer** [CATIA-Systems/FMPy#269]
We get an increased demand for single FMUs which run on differnt platforms like Windows and Linux. This can be achived by exporting a source-code FMU and recompiling it on a different platform with FMPy. This option is very user-friendly, because the compiled binaries are directly stored in the original FMU. 

In some cases the users do not want to keep the source-code in the FMU due to privacy or storage issues. An optional "Delete source-code after binary compilation" function would be of great help.

**Comment by t-sommer** [comment]
With [7zip](https://www.7-zip.org/) you can conveniently open the FMU and delete the `sources` folder to remove the source code.
