### ISSUE TITLE
Permission Error with DYMOLA FMU

### ISSUE THREAD

**Issue by alexa-f** [CATIA-Systems/FMPy#27]
Hi,

I am facing an issue (dll not unlinked, see error message below) with FMUs generated with Dymola (tested with Versions 2017FD01, 2018FD01). The simple example below works fine, when using the FMU provided by the following link:

[](url)https://trac.fmi-standard.org/browser/branches/public/Test_FMUs/FMI_2.0/ModelExchange/win64/Dymola/2017/CoupledClutches/CoupledClutches.fmu

I am working with Python 3.6.2 (see installed packages below) and I am using the FMPy develop branch (the problem also occurs on the master branch release 0.2.1).

It seems that the dll is not unlinked properly. Inspecting threads I found the following line:

`Modelica_Mechanics_Rotational_Examples_CoupledClutches_DYMOLA2017FD01.dll!fmi2GetStringStatus+0x5bbec`

Thanks!
Alexander

### Export FMU (checked settings):
Type: Model Exchange
Version: 2.0
Binaries: 32-bit, 64-bit
Model description filters: Protected variables
Options: Copy resources to FMU, Show dialog when exporting

### Simple example:
```python
from fmpy import simulate_fmu

#filename = 'fmus/Modelica_Mechanics_Rotational_Examples_CoupledClutches_DYMOLA2018FD01.fmu'
filename = 'fmus/Modelica_Mechanics_Rotational_Examples_CoupledClutches_DYMOLA2017FD01.fmu'
# filename = 'fmus/Dymola2017/CoupledClutches.fmu'

simulate_fmu(
    filename=filename,
    start_time=0,
    stop_time=1.5,
    solver='CVode',
    step_size=1e-2,
    output_interval=2e-2,
    input=None,
    output=None,
    validate=False,
    fmi_logging=False)
```

### Error message:
```python
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-11-a27bbb9b9121> in <module>()
     17     output=None,
     18     validate=False,
---> 19     fmi_logging=False)

c:\users\opa2si1\documents\git_projects\fmpy\fmpy\simulation.py in simulate_fmu(filename, validate, start_time, stop_time, solver, step_size, relative_tolerance, output_interval, fmi_type, use_source_code, start_values, input, output, timeout, fmi_logging, logger, step_finished)
    435 
    436     # clean up
--> 437     shutil.rmtree(unzipdir)
    438 
    439     return result

~\AppData\Local\conda\conda\envs\FMPy_issue_PermissionError\lib\shutil.py in rmtree(path, ignore_errors, onerror)
    492             os.close(fd)
    493     else:
--> 494         return _rmtree_unsafe(path, onerror)
    495 
    496 # Allow introspection of whether or not the hardening against symlink

~\AppData\Local\conda\conda\envs\FMPy_issue_PermissionError\lib\shutil.py in _rmtree_unsafe(path, onerror)
    382             mode = 0
    383         if stat.S_ISDIR(mode):
--> 384             _rmtree_unsafe(fullname, onerror)
    385         else:
    386             try:

~\AppData\Local\conda\conda\envs\FMPy_issue_PermissionError\lib\shutil.py in _rmtree_unsafe(path, onerror)
    382             mode = 0
    383         if stat.S_ISDIR(mode):
--> 384             _rmtree_unsafe(fullname, onerror)
    385         else:
    386             try:

~\AppData\Local\conda\conda\envs\FMPy_issue_PermissionError\lib\shutil.py in _rmtree_unsafe(path, onerror)
    387                 os.unlink(fullname)
    388             except OSError:
--> 389                 onerror(os.unlink, fullname, sys.exc_info())
    390     try:
    391         os.rmdir(path)

~\AppData\Local\conda\conda\envs\FMPy_issue_PermissionError\lib\shutil.py in _rmtree_unsafe(path, onerror)
    385         else:
    386             try:
--> 387                 os.unlink(fullname)
    388             except OSError:
    389                 onerror(os.unlink, fullname, sys.exc_info())

PermissionError: [WinError 5] Access is denied: 'C:\\Users\\xxxxxxx\\AppData\\Local\\Temp\\tmp4v696d0o\\binaries\\win64\\Modelica_Mechanics_Rotational_Examples_CoupledClutches_DYMOLA2017FD01.dll'
```

### requirements (platform: win-64):
bleach=1.5.0=py36_0
ca-certificates=2018.1.18=0
certifi=2016.2.28=py36_0
colorama=0.3.9=py36_0
decorator=4.1.2=py36_0
entrypoints=0.2.3=py36_0
html5lib=0.9999999=py36_0
icu=58.2=vc14_0
ipykernel=4.6.1=py36_0
ipython=6.1.0=py36_0
ipython_genutils=0.2.0=py36_0
ipywidgets=6.0.0=py36_0
jedi=0.10.2=py36_2
jinja2=2.9.6=py36_0
jpeg=9b=vc14_2
jsonschema=2.6.0=py36_0
jupyter=1.0.0=py36_3
jupyter_client=5.1.0=py36_0
jupyter_console=5.2.0=py36_0
jupyter_core=4.3.0=py36_0
libpng=1.6.34=vc14_0
lxml=3.8.0=py36_0
markupsafe=1.0=py36_0
mistune=0.7.4=py36_0
mkl=2017.0.3=0
nbconvert=5.2.1=py36_0
nbformat=4.4.0=py36_0
notebook=5.0.0=py36_0
numpy=1.13.1=py36_0
openssl=1.0.2n=vc14_0
pandocfilters=1.4.2=py36_0
path.py=10.3.1=py36_0
pathlib=1.0.1=py36_0
pickleshare=0.7.4=py36_0
pip=9.0.1=py36_1
prompt_toolkit=1.0.15=py36_0
pygments=2.2.0=py36_0
pyqt=5.6.0=py36_2
python=3.6.2=0
python-dateutil=2.6.1=py36_0
pywin32=220=py36_2
pyzmq=16.0.2=py36_0
qt=5.6.2=vc14_1
qtconsole=4.3.1=py36_0
setuptools=36.4.0=py36_1
simplegeneric=0.8.1=py36_1
sip=4.18=py36_0
six=1.10.0=py36_0
testpath=0.3.1=py36_0
tornado=4.5.2=py36_0
traitlets=4.3.2=py36_0
vc=14=0
vs2015_runtime=14.0.25420=0
wcwidth=0.1.7=py36_0
wheel=0.29.0=py36_0
widgetsnbextension=3.0.2=py36_0
wincertstore=0.2=py36_0
zlib=1.2.11=vc14_0

**Comment by t-sommer** [comment]
I just exported the `Modelica.Mechanics.Rotational.Examples.CoupledClutches`model with the above settings from Dymola 2018FD01 and it runs without problems using the code you posted. Can you try with a different Python environment or on a different machine?

**Comment by alexa-f** [comment]
I could reproduce the error with a new Python (2.7.14) environment and also on a different machine. I am working with Windows 10 on both machines. Which operating system do you use?

**Comment by alexa-f** [comment]
The root cause for this problem seems to be in the Dymola FMU export. Something increases the reference count on the loaded DLL so that it has to be unloaded multiple times.
