### ISSUE TITLE
Different independent variable than time

### ISSUE THREAD

**Issue by BjorHart** [CATIA-Systems/FMPy#270]
I am reading about attributes of variables of the FMI standard on  https://fmi-standard.org/docs/3.0-dev/ section 2.4.7.4. "Variable Attributes" . It seems to me an independent variable can replace the time variable, and be the primary variable governing the solver. An independent variable "angle" is given as an example. Is there a way to do such a simulation with FMPy? It seems the time variable is automatically set in the simulateCS and simulateME functions of simulation.py.

Thank you in advance for answering!

**Comment by t-sommer** [comment]
> Is there a way to do such a simulation with FMPy?

Sure. What's holding you back?

**Comment by BjorHart** [comment]
hi, thanks for getting back to me. 
What is stopping me is i don't see how. If using the FMPy functions simulateME/simulateCS, the time is automatically the independent variable? Is there an explicit operation I need to do to change that?

**Comment by t-sommer** [comment]
First you need a model that has a different independent variable. In the result it would still be called time but you can treat it as whatever quantity you want.

I‘d be happy to try such an FMU if you can share it.
