### ISSUE TITLE
Problem simulating via FMPy

### ISSUE THREAD

**Issue by kosmylo** [CATIA-Systems/FMPy#271]
I have exported a PhotoVoltaics model as fmu from openmodelica and when I am trying to simulate it in python through FMPy I am getting the following error:

assert | debug | Model error: Argument of sqrt(converter.iAC.re ^ 2.0 + converter.iAC.im ^ 2.0) was nan should be >= 0

Any idea of what is going on?

**Comment by t-sommer** [comment]
Did you try to run this FMU in another application, e.g. the [FMU Compliance Checkerh](https://github.com/modelica-tools/FMUComplianceChecker)?

If it runs there, please re-open and provide the model and command line / script to reproduce the error.
