### ISSUE TITLE
Assert mandatory independent variable in FMI 3.0

### ISSUE THREAD

**Issue by t-sommer** [CATIA-Systems/FMPy#272]

**Comment by malinb73** [comment]
Hi all,
I see in validation.py
`        # assert independent variable
        if sum(v.causality == 'independent' for v in model_description.modelVariables) != 1:
            problems.append("Exactly one independent variable must be defined.")`
May I ask you why is this condition mandatory?
Could be avoided somehow?

**Comment by chrbertsch** [comment]
"Exactly one variable of an FMU must be defined as independent", see https://fmi-standard.org/docs/3.0.1/#independent

**Comment by malinb73** [comment]
Thank you for your fast answer.
