### ISSUE TITLE
Unable to open modelDescription.xml

### ISSUE THREAD

**Issue by saraths123** [CATIA-Systems/FMPy#274]
Hi,

I am trying to load an FMU via FMpy GUI, and am getting the error in console 
"Unable to open 'file:///C:/Users/Sam/AppData/Local/Temp/tmpvxx_aco0/modelDescription.xml'"
I have another FMU which is able to load in FMpy, So i tried to modify the xml as of the working one.. May be a stupid idea But it didnt worked out ;(

Anyone knows any workaround please suggest it.!

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by t-sommer** [comment]
Please reopen if you can provide steps to reproduce the problem.
