### ISSUE TITLE
separating simulate function in a class providing a high level interface 

### ISSUE THREAD

**Issue by philippGraf** [CATIA-Systems/FMPy#277]
Currently I have developed a gym (https://github.com/openai/gym) interface for fmu's based on fmpy. Our aim is to provide an as open as possible access to AI/Reinforcement Learning etc. on physical systems. 

I did so by separating the simulate-function of fmpy as an interface class for fmu's (https://github.com/ConsolinnoEnergy/FMPy). The problem with my approach is the following: The class strongly depends on the inner mechanic of the simulate function, which already lead to crashes, because of the upgrade of fmpy from 0.2 to 0.3.

In the sense of gym, the only thing I really need is
- the possibility to proceed and manipulate (via inputs) the simulation step-wise (where each step is a whole simulation say, 1 hour...) and to keep the inner state of fmu
- to reset the fmu to a initial state

I would really appreciate, if you could have a look at my implementation, and tell me your honest opinion.
- Did a overlook something with the simulate function? Could I have realized my interface without breaking into the code of simulate?
- Could it be a possibility that, you integrate the above described mechanics of an abstracted interface class directly into fmpy and maintain it as a high level API?

I really look forward to hear your opinion how we could provide a maintainable gym interface!

Best regards 

Philipp

**Comment by t-sommer** [comment]
Can you share a link to the file that implements your wrapper?

**Comment by philippGraf** [comment]
sorry...
https://github.com/ConsolinnoEnergy/FMPy/blob/master/fmpy/gym_interface.py
and 
https://github.com/ConsolinnoEnergy/FMPy/blob/master/fmpy/gym_examples

and nice to see your interest!

**Comment by t-sommer** [comment]
You should be able to adapt the [efficient_loops example](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/efficient_loops.py) to fit your needs. It demonstrates how to instantiate and simulate/reset an FMU multiple times.

**Comment by philippGraf** [comment]
Thank you very much for your quick help.


Dr. Philipp Graf

Abteilung Data Science und Optimierung



Consolinno Energy GmbH

An der Donau 5

93080 Pentling (Matting)


Sitz der Gesellschaft: 93080 Pentling

Handelsregister: Amtsgericht Regensburg HRB 15773

UST.-IdNr: DE310281278



***@***.***D7064B.49777B80]

________________________________
Von: Torsten Sommer ***@***.***>
Gesendet: Sonntag, 4. Juli 2021 23:38
An: CATIA-Systems/FMPy ***@***.***>
Cc: Philipp Graf ***@***.***>; Author ***@***.***>
Betreff: Re: [CATIA-Systems/FMPy] separating simulate function in a class providing a high level interface (#277)


Closed #277<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCATIA-Systems%2FFMPy%2Fissues%2F277&data=04%7C01%7Cp.graf%40consolinno.de%7Cf94f70acf5ac4056ab1f08d93f340d45%7Cbc9bf0109eca490ea88cc363033b1108%7C0%7C0%7C637610315072666878%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9rVHvf76HZzHozkBlY6GIzTqCI4boJsY4wmfcXuq330%3D&reserved=0>.
