### ISSUE TITLE
Error while creating fmu container

### ISSUE THREAD

**Issue by kosmylo** [CATIA-Systems/FMPy#281]
I am trying to create an FMU, which is consisted of multiple FMUs and I think that `fmu_container` is what I want to do this job. I followed as a template the file `test_fmu_container.py`, but I am getting the following error:

```
Traceback (most recent call last):

  File "C:\Users\kosmy\Test_Pandapower_FMU\fmu_container.py", line 63, in <module>
    create_fmu_container(configuration, filename)

  File "C:\Users\kosmy\anaconda3\envs\tf_gpu\lib\site-packages\fmpy\fmucontainer\__init__.py", line 74, in create_fmu_container
    model_description = read_model_description(component['filename'])

  File "C:\Users\kosmy\anaconda3\envs\tf_gpu\lib\site-packages\fmpy\model_description.py", line 488, in read_model_description
    raise ValidationError(problems)

ValidationError: Failed to validate modelDescription.xml:

- ERROR (line 4, column 0): Element 'SourceFiles': Missing child element(s). Expected is ( File ). 
```

Any idea of what is going on?

**Comment by t-sommer** [comment]
Seems like the FMU you're trying to import has an illegal modelDescription.xml. You can use FMPy or the [online FMU Check](https://fmu-check.herokuapp.com/) to validate your FMU.

**Comment by chrbertsch** [comment]
It seems that the inidividual FMUs can be validated, but the validation of the containerized FMU fails, see https://stackoverflow.com/questions/68337508/error-of-modelstructure-outputs-by-using-fmu-container .
@kosmylo : can you provide more information ?

**Comment by t-sommer** [comment]
@kosmylo, can you share the generated container FMU or at least the modelDescription.xml?

**Comment by kosmylo** [comment]
> @kosmylo, can you share the generated container FMU or at least the modelDescription.xml?

Here it is:
[FMU.zip](https://github.com/CATIA-Systems/FMPy/files/6807045/FMU.zip)

**Comment by t-sommer** [comment]
With the latest version on `develop` I get some errors regarding the Model Structure when validating your FMU. This problem has been addressed in 8287f3226f36dd0fe5bdc44f77c332969b2f814a. The fix will be in the next release.

**Comment by kosmylo** [comment]
The exported FMU is only for Linux platform?

**Comment by t-sommer** [comment]
The Container FMU supports all platforms that are supported by all inner FMUs.
