### ISSUE TITLE
How can we skip the initialize method in simulate_fmu for consecutive simulations?

### ISSUE THREAD

**Issue by philippGraf** [CATIA-Systems/FMPy#283]
This question refers to the following fork:
https://github.com/ConsolinnoEnergy/FMPy/tree/gym-branch
The aim is to provide an openai/gym interface to fmu's for training artificial inelligence. In other words simulations are performed consecutively, where actions are performed on the fmu via inputs within these discrete simulation steps.
Tests have showed that the current implementation of the simulate_fmu function leads to significant performance drawbacks in computation time. The fork therefore proposes the possibility of skipping the initialization of the fmu in consecutive simulations, when the fmu has once been initialized. The fmu continues then simply its trajectory doing do_steps. 
The following questions arise:
- Is it neccessary to initialize the fmu, when performing the next simulation step?
- more precisely: may the presence of new inputs make a initialization neccessary?
- when skipping initialization is possible, are there other methods one has to be aware of to guarantee a stable continuation of the trajectory?
- concerning https://github.com/CATIA-Systems/FMPy/issues/279: Why should the state have to be restored, when the fmu simply continues do step, when calling simulate_fmu with initialize=False?

**Comment by t-sommer** [comment]
> * Is it neccessary to initialize the fmu, when performing the next simulation step?

Please see the [FMI 2.0.2 Spec](https://github.com/modelica/fmi-standard/releases/download/v2.0.2/FMI-Specification-2.0.2.pdf) p. 107 for possible calling sequences.

> * more precisely: may the presence of new inputs make a initialization neccessary?

In Co-Simulation, inputs and tunable parameters may be set before calling `fmi2DoStep()`.

> * when skipping initialization is possible, are there other methods one has to be aware of to guarantee a stable continuation of the trajectory?

No.

> * concerning [using fmu as a state machine: initialize flag in simulate_fmu  #279](https://github.com/CATIA-Systems/FMPy/issues/279): Why should the state have to be restored, when the fmu simply continues do step, when calling simulate_fmu with initialize=False?

If you want full control of the simulation loop, you can simply write you own. See https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/custom_input.py#L54 for an example.
All you have to do is

```Python
fmu.setReal(...)  # set input and tunable parameters
fmu.doStep(...)  # make one simulation step h
fmu.getReal(...)  # get the outputs at t+h
```

**Comment by philippGraf** [comment]
Ok. So you do not want to include the initialize flag as a new feature in the simulate function, as the fmpy package provides enough mechanics for workarounds.

**Comment by t-sommer** [comment]
As I understand it, having this flag would allow you to simulate "sections" of the whole simulation. But what is the benefit compared to a custom simulation loop?

**Comment by philippGraf** [comment]
Simulate sections: "Yes". And each section is accompanied by a new event input values acting during this section (the "action"). 

Initialize-Flag: I see the benefit on the same level as the simulate_fmu function itself: 
Providing a high level interface for simulations. The user should not worry about writing loops, determining step widths and so on in the first place (thanks to your work concerning default values), but only what he wants to do and how he can tune this.

**Comment by t-sommer** [comment]
@greenwoodms06, @philippGraf, would it be sufficient if `simulate_fmu()` would accept the serialized state as a parameter?
