### ISSUE TITLE
FMPy not working in Azure Function

### ISSUE THREAD

**Issue by A1U2T3X5** [CATIA-Systems/FMPy#292]
I set up a python file outside of Azure and the FMPy library worked as expected.  The code was moved to Azure Function inside of Visual Studio Code and seems like FMU is not accessible any more, even though it is in the same directory as python file.  I tried just reading the model information with dump() and nothing was returned and no errors.  I also tried the coupled clutches example code and same issue

**Comment by t-sommer** [comment]
Can you provide steps to reproduce the problem?

**Comment by Bigrio001** [comment]
sorry for the delay have been checking things:

`import json
import logging
import fmpy
import numpy as np
from fmpy import *
from azure.identity import DefaultAzureCredential
from azure.digitaltwins.core import DigitalTwinsClient
from dotenv import load_dotenv
import azure.functions as func

load_dotenv("<location of connection strings>") ### just need one for AZURE_URL or you can add it in the function on the portal

# Create logger
logger = logging.getLogger('azure')
logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler(stream=sys.stdout)
logger.addHandler(handler)

def main(event: func.EventGridEvent):
    result = json.dumps({
        'id': event.id,
        'data': event.get_json(),
        'topic': event.topic,
        'subject': event.subject,
        'event_type': event.event_type,
    })

    z = event.get_json()
  
    trigger = z['data']['patch'][0]['path']

    if trigger == '/Max_Capacity':

    # fmpy.plot_library = 'plotly'  # experimental
    
        fmuFile = './EventGridTriggerRunFMU/<FMU file>'  ## I used an fmu that was compiled for linux and another one for windows.  The windows was used for local testing and the linux for uploading to the portal
    
        filename = fmuFile  

        logging.info(dump(filename))
        start_values = {
            # variable    start   unit      description
        }

        output = [
            'Out1',  # Out1
            'Out2',  # Out2
            'Out3',  # Out3
            'Out4',  # Out4
            'Out5',  # Out5
            'Out6',  # Out6
        ]

           result = simulate_fmu(filename, start_values=start_values, output=output, stop_time=3600000.0)


            print(result)

The program runs fine on local machine, but when used in Azure Function that is uploaded to portal the simulate_fmu() does not run.
 
        
        
`

**Comment by t-sommer** [comment]
Is there a way to run this on Azure with a free account?
