### ISSUE TITLE
separation of initialization, simulation and termination

### ISSUE THREAD

**Issue by FabiJa** [CATIA-Systems/FMPy#30]
Hi Torsten,

in the current implementation, during every call of 'simulate_fmu()', the fmu is unzipped, intialized and after the run terminated and the temporary folder is deleted. 
This is problematic for several (thousand) runs with the same fmu, e.g. Monte-Carlo. Would it be possible to re-structure and split the simulation in a init-, a run- and a terminate call, e.g. as a class:
```python
class simulate_with_fmu(object):

   def __init__(self):
     unzipdir = extract(filename)
     fmu.initialize()
     ...

   def run():
      return simulateME()

   def __exit__(self):
       fmu.terminate()
       fmu.freeInstance()
       shutil.rmtree(unzipdir)
```

**Comment by t-sommer** [comment]
You could adapt the [worker function in the parameter_variation.py example](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/parameter_variation.py#L37). It does exactly what you're looking for. If you know the parameters beforehand it might also make sense to distribute the work over multiple cores for better performance.

**Comment by FabiJa** [comment]
Yes, I have already done this. But I am wondering, if FMPy is sufficiently stable now, that my modifications will keep working over the next releases.

**Comment by t-sommer** [comment]
The low-level API (fmpy.fmi*) maps more or less directly to the FMI so it's very unlikely to change except maybe for bug-fixes. The conservative version numbering (0.x.x) was chosen to comply with [semantic versioning](https://semver.org/) and does not mean that we plan big changes to the API.

**Comment by FabiJa** [comment]
ok.

**Comment by chrbertsch** [comment]
As a future extension it would be still very useful for many applications (e.g. Parameter sweeps, Monte Carlo simulation, Uncertainty Quanticiation to follow the path depicted in the description above.

**Comment by t-sommer** [comment]
65076d90 addresses this issue by allowing simulation of extracted FMUs and pre-loaded model descriptions. I get up to 80% reduction in runtime for batch simulations of small models. See [tests/test_extracted_fmu.py](https://github.com/CATIA-Systems/FMPy/blob/65076d9038a6926488b66428328ea35491ccb556/tests/test_extracted_fmu.py) for an example.
