### ISSUE TITLE
simulate_fmu runs forever

### ISSUE THREAD

**Issue by kosmylo** [CATIA-Systems/FMPy#301]
I have exported the attached FMU, which consists of multiple FMUs connected together with fmu_container and it passes the validation. However, when I am trying to simulate it with simulate_fmu it seems like it runs forever.

I have to mention that the inputs are csv files, which I have converted to FMU. So what I want is to have an FMU that runs autonomously.

Any idea of what is going wrong?

[FMU.zip](https://github.com/CATIA-Systems/FMPy/files/6912855/FMU.zip)

**Comment by t-sommer** [comment]
The nested FMU `Pandapower_Reduced.fmu` depends on the Python runtime (`python3.dll`). Such an FMU cannot be simulated in Python.
