### ISSUE TITLE
Resume simulation using FMPy

### ISSUE THREAD

**Issue by Aatreyi** [CATIA-Systems/FMPy#303]
I am trying to start an FMU simulation from a given timestep, other than 0, using simulate_fmu. I am specifying the values of all the variables at that timestep  as the "start_values". But the result is different from what it is when the simulation is started from timestep 0. Can anybody help me with how to do it correctly? I am using the BouncingBall fmu created with OpenModelica.
[BouncingBall.zip](https://github.com/CATIA-Systems/FMPy/files/6915988/BouncingBall.zip)

**Comment by t-sommer** [comment]
This is the same problem as discussed in #279.

**Comment by Aatreyi** [comment]
Maybe I should rephrase. The solution mentioned in #279 works with {get/set}FMUstate. But in an FMU generated with openmodelica, those APIs cannot be used. That is because the flag canGetAndSetFMUstate is always set to False. Then what is the way forward? You can try with the FMU provided.

**Comment by t-sommer** [comment]
This is a limitation of the FMU. You can open an issue on https://github.com/OpenModelica/OpenModelica and suggest to implement the get/setFMUstate functions.

**Comment by bilderbuchi** [comment]
That issue seems to be https://github.com/OpenModelica/OpenModelica/issues/7939
