### ISSUE TITLE
Deserialized initialised FMU on not initialized FMU 

### ISSUE THREAD

**Issue by valentindrou** [CATIA-Systems/FMPy#304]
# Context

I am trying to save time at initialisation (60% of my total simulation time) by using serialization of FMI state after initialisation so that I can skip initialisation for my next simulations. So my workflow is as follow : 

1. Load the FMU, instanciate, initialize, serialize and save serialized state in file with joblib.

```
fmu_filename = "test_serialization.fmu"
path_file_serialized_state = "serialized.joblib"

# read the model description
model_description = read_model_description(fmu_filename)

print(model_description.coSimulation.__dict__)

fmpy.dump(fmu_filename)

# extract the FMU
unzipdir = extract(fmu_filename)

# instantiate the FMU
fmu = FMU2Slave(guid=model_description.guid,
                unzipDirectory=unzipdir,
                modelIdentifier=model_description.coSimulation.modelIdentifier)

# initialize
fmu.instantiate()
fmu.setupExperiment()
fmu.enterInitializationMode()
fmu.exitInitializationMode()

# get the FMU state
state = fmu.getFMUstate()

# serialize the FMU state
serialized_state = fmu.serializeFMUstate(state)

with open(path_file_serialized_state, "wb") as file:
        joblib.dump(serialized_state, file)
```

2. In a separate script, load the fmu, instanciate it, load serialized state from file, deserialize it and set the FMU state. 
```
fmu_filename = "test_serialization.fmu"
path_file_serialized_state = "serialized.joblib"

# read the model description
model_description = read_model_description(fmu_filename)

fmpy.dump(fmu_filename)

# extract the FMU
unzipdir = extract(fmu_filename)

# instantiate the FMU
fmu = FMU2Slave(guid=model_description.guid,
                unzipDirectory=unzipdir,
                modelIdentifier=model_description.coSimulation.modelIdentifier)

# initialize
fmu.instantiate()
fmu.setupExperiment()

# get the FMU state
state = fmu.getFMUstate()

with open(path_file_serialized_state, "rb") as file:
        serialized_state = joblib.load(file)

# de-serialize the FMU state (re-using memory)
deserialized_state = fmu.deSerializeFMUstate(serialized_state, state)

# set the FMU state
fmu.setFMUstate(deserialized_state)
```

Here are the two scripts I'm using for that : 
[serialize_and_deserialize.zip](https://github.com/CATIA-Systems/FMPy/files/6922984/serialize_and_deserialize.zip)

# Issue

This workflow works fine with some FMUs, for instance the ones provided by FMPy (CoupledClutches ). However this doesn't work with a very simple model exported from Dymola (FMI2, cosimulation using Cvode, generated on Dymola 2022). 

Here is the content of the model : 
```
model test_serialization

  input Real x(start=1);
  input Real y(start=2);

  output Real xy;

equation 

  xy = x*y*time;

end test_serialization;
```

Fmu and model are here : 
[test_serialization_model.zip](https://github.com/CATIA-Systems/FMPy/files/6922926/test_serialization_model.zip)

When running deSerializeFMUstate, I get the message : 
```
not a valid tpl file
[WARNING] %s
```
If I follow with my workflow and try to set the deserialized state to my FMU, I get a segmentation fault. 

If I try my FMU with the test_serialize_fmu_state.py available in FMPy, it works fine with my Dymola FMU. (Inspired from [this issue](https://github.com/CATIA-Systems/FMPy/issues/57))
The difficulty really seems to come from deserializing the fmu state before initialisation. 

All of these tests were made on Linux Ubuntu 20.04 with Python 3.8. I am using Dymola 2022.

**Comment by t-sommer** [comment]
This is a bug in the FMU. Calling `setFMUstate()` causes a NPE in `integration.c` line 976

```C
	N_VScale(1.0, source->iData->abstol, iData->abstol);
```

because `iData->abstol` is `NULL`.

Here is a minimal example to reproduce the problem:

```Python
import shutil
from fmpy import *

fmu_filename = "test_serialization.fmu"

# read the model description
model_description = read_model_description(fmu_filename)

# extract the FMU
unzipdir = extract(fmu_filename)

fmu = instantiate_fmu(unzipdir=unzipdir, model_description=model_description)

# initialize
fmu.instantiate()
fmu.setupExperiment()
fmu.enterInitializationMode()
fmu.exitInitializationMode()

# get the FMU state
state = fmu.getFMUstate()

# serialize the FMU state
serialized_state = fmu.serializeFMUstate(state)

fmu.terminate()
fmu.freeInstance()
fmu = instantiate_fmu(unzipdir=unzipdir, model_description=model_description)

# de-serialize the FMU state (re-using memory)
deserialized_state = fmu.deSerializeFMUstate(serialized_state, state)

# set the FMU state
fmu.setFMUstate(deserialized_state)

fmu.terminate()
fmu.freeInstance()

# clean up
shutil.rmtree(unzipdir)
```

**Comment by t-sommer** [comment]
Please open an issue on https://www.3ds.com/support/.
