### ISSUE TITLE
Error: the attribute 'needsexecutiontool' is not allowed

### ISSUE THREAD

**Issue by kosmylo** [CATIA-Systems/FMPy#305]
I need to use FMPy for co-simulation using a model exported from a software. Unfortunately, when I try to load the FMU file, it raises this error: 

```
error (line 1, column 0): element 'fmimodeldescription', attribute 'needsexecutiontool': the attribute 'needsexecutiontool' is not allowed.
```

I have to note that I can load and simulate the same FMU fine with another tool.

What can I do to make it work? Why such limitation?

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by kosmylo** [comment]
Here it is:

[FMICS2.zip](https://github.com/CATIA-Systems/FMPy/files/6939927/FMICS2.zip)

**Comment by t-sommer** [comment]
> What can I do to make it work?

You can remove the attribute `needsExecutionTool="true"` from the `<fmiModelDescription>` element in `modelDedescription.xml`.

This is a bug in the FMU export. Please open an issue on https://github.com/JModelica/JModelica.
