### ISSUE TITLE
simulate FMU with multiple inputs coming from csv files

### ISSUE THREAD

**Issue by kosmylo** [CATIA-Systems/FMPy#307]
I have an FMU with 4 inputs and I have 4 csv files that I want to use as input. I know that the `simulate_fmu` command has the parameter `input`  for this reason. However, it is not clear to me how I can use multiple inputs in this parameter. Is there any example maybe that I could take a look at?

**Comment by t-sommer** [comment]
Can you share the FMU and CSVs?

**Comment by kosmylo** [comment]
The FMU has 4 inputs, namely _P_load1, P_load2, P_pv1, P_pv2_ and I want the csv _load_prof_ to be used as input for the first 2 and the csv _pv_prof_ as input for the last 2.

[Files.zip](https://github.com/CATIA-Systems/FMPy/files/6950473/Files.zip)

**Comment by t-sommer** [comment]
If the time columns of the CSVs match, you can concatenate them into a new input array:

```Python
from fmpy import *
import numpy as np

# load the CSVs
l = read_csv('load_prof.csv')
p = read_csv('pv_prof.csv')

# make sure the time columns match
assert np.all(l['time'] == p['time'])

data = list(zip(l['time'], l['power'], l['power'], p['power'], p['power']))
dtype = [('time', np.float64), ('P_load1', np.float64), ('P_load2', np.float64), ('P_pv1', np.float64), ('P_pv2', np.float64)]

# create the structured input array
input = np.array(data, dtype=dtype)
```
