### ISSUE TITLE
fmi2EnterInitializationMode failed with status 3 while simulate_fmu

### ISSUE THREAD

**Issue by kosmylo** [CATIA-Systems/FMPy#308]
I am trying for some time to understand why an FMU cannot be simulated with FMPy, while I can simulate it with PyFMI. 
I created a very simple case (with the help of another issue that I opened here), where I have isolated the FMU, and I tried to simulate it with some CSV files as inputs as follows: 

```
from fmpy import simulate_fmu
import numpy as np
import pandas as pd

electricity_network = r"C:\Users\kosmy\Test_Pandapower_FMU\Pandapower.fmu"
load_prof = r"C:\Users\kosmy\Test_Pandapower_FMU\load_prof.csv"
pv_prof = r"C:\Users\kosmy\Test_Pandapower_FMU\pv_prof.csv"

l = pd.read_csv(load_prof)
p = pd.read_csv(pv_prof)

data = list(zip(l['time'], l['power'], l['power'], p['power'], p['power']))
dtype = [('time', np.float64), ('P_load1', np.float64), ('P_load2', np.float64), ('P_pv1', np.float64), ('P_pv2', np.float64)]

input_object = np.array(data, dtype=dtype)

res = simulate_fmu(electricity_network, start_time = 0, stop_time = 95, step_size= 1, input = input_object)
```

The error that I am getting is the following:

```
Traceback (most recent call last):

  File "C:\Users\kosmy\Test_Pandapower_FMU\run_fmpy_csv.py", line 24, in <module>
    res = simulate_fmu(electricity_network, start_time = 0, stop_time = 95, step_size= 1, input = input_object)

  File "C:\Users\kosmy\anaconda3\envs\sim_fmu_py36\lib\site-packages\fmpy\simulation.py", line 789, in simulate_fmu
    result = simulateCS(model_description, fmu, start_time, stop_time, relative_tolerance, start_values, apply_default_start_values, input, output, output_interval, timeout, step_finished, set_input_derivatives)

  File "C:\Users\kosmy\anaconda3\envs\sim_fmu_py36\lib\site-packages\fmpy\simulation.py", line 1198, in simulateCS
    fmu.enterInitializationMode()

  File "C:\Users\kosmy\anaconda3\envs\sim_fmu_py36\lib\site-packages\fmpy\fmi2.py", line 283, in enterInitializationMode
    return self.fmi2EnterInitializationMode(self.component)

  File "C:\Users\kosmy\anaconda3\envs\sim_fmu_py36\lib\site-packages\fmpy\fmi2.py", line 215, in w
    raise Exception("%s failed with status %d." % (fname, res))

Exception: fmi2EnterInitializationMode failed with status 3.
```
As long as I know, the FMU is dependent on python37.dll, so I simulate it with python 3.6.

I am attaching the FMU:

[FMU.zip](https://github.com/CATIA-Systems/FMPy/files/6960819/FMU.zip)

Does my FMU include a limitation that I am not aware of?

**Comment by t-sommer** [comment]
Does the environment variable `PATH` for the process that's loading the FMU include all paths to the dependent DLLs?

**Comment by kosmylo** [comment]
Do you mean the global environment variable `PATH` that can be accessed through system properties? What other paths should include apart from python37?

**Comment by t-sommer** [comment]
> Do you mean the global environment variable PATH that can be accessed through system properties?

Yes. Every external DLL your FMU depends on must be on the PATH.

**Comment by t-sommer** [comment]
Note that this may lead to clashes if a different DLL with the same name has already been loaded by the importing process (see https://en.wikipedia.org/wiki/DLL_Hell).

**Comment by kosmylo** [comment]
> Yes. Every external DLL your FMU depends on must be on the PATH.

I am pretty sure that all the external DLLs are in the PATH. Is there a way to check for external DLLs in an FMU to be sure?

> Note that this may lead to clashes if a different DLL with the same name has already been loaded by the importing process (see https://en.wikipedia.org/wiki/DLL_Hell).

If I understood right this might be caused when I am trying to run the simulation from python 3.7. I did this initially and I got the following error:

```
Traceback (most recent call last):

  File "C:\Users\kosmy\Test_Pandapower_FMU\run_fmpy_csv.py", line 24, in <module>
    res = simulate_fmu(electricity_network, start_time = 0, stop_time = 95, step_size= 1, input = input_object)

  File "C:\Users\kosmy\anaconda3\envs\FMU_container\lib\site-packages\fmpy\simulation.py", line 789, in simulate_fmu
    result = simulateCS(model_description, fmu, start_time, stop_time, relative_tolerance, start_values, apply_default_start_values, input, output, output_interval, timeout, step_finished, set_input_derivatives)

  File "C:\Users\kosmy\anaconda3\envs\FMU_container\lib\site-packages\fmpy\simulation.py", line 1198, in simulateCS
    fmu.enterInitializationMode()

  File "C:\Users\kosmy\anaconda3\envs\FMU_container\lib\site-packages\fmpy\fmi2.py", line 283, in enterInitializationMode
    return self.fmi2EnterInitializationMode(self.component)

  File "C:\Users\kosmy\anaconda3\envs\FMU_container\lib\site-packages\fmpy\fmi2.py", line 206, in w
    res = f(*args)

OSError: exception: access violation reading 0x0000000000000010
```
But I noticed in an old issue that someone mentioned the same problem and you proposed to run it with a different version of python. So, I did that and I got the error that I mentioned initially

**Comment by t-sommer** [comment]
> I am pretty sure that all the external DLLs are in the PATH. Is there a way to check for all external DLLs apart from binaries in an FMU to be sure?

You can try to analyze the DLL with [Dependency Walker](https://www.dependencywalker.com/).

> If I understood right this might be caused when I am trying to run the simulation from python 3.7. I did this initially and I got the following error: ...

You cannot load the Python runtime from within Python.

> But I noticed in an old issue that someone mentioned the same problem and you proposed to run it with a different version of python. So, I did that and I got the error that I mentioned initially

This might work in certain situations but it's not generally supported. After all, why would you want to package your Python code as an FMU to run it in Python?
