### ISSUE TITLE
Changing parameter values in the modeldescription.xml-file is dangerous

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMPy#31]
In FMPy 0.2.3., writing new parameter values to the xml file has been introduced.
However, this is dangerous, as it is not specified, whether an importing tool should consider these values or the hard coded values, see this discussion: [https://trac.fmi-standard.org/ticket/387].
Strictly speaking, changing the modeldescription.xml could even invalidate the FMU (consistency of xml and binary could be checked by creating a GUID with by a checksum.
The clean way to support changed parameter and even different parameter sets is the coming SSP standard.

**Comment by t-sommer** [comment]
I'm aware of the concerns shared in this discussion but used with care this feature allows workflows previously impossible. Also note that you can now explicitly set the start values from the model description using the `--apply-default-start-values` switch on the command line or the check box `Apply default start values` in the GUI. 

Is there anything you want changed about the current implementation?

**Comment by chrbertsch** [comment]
Wouldn't it be possible easily to create automatically from a single FMU and SSP file that contains only this FMU, has the some in/outputs and parameters? 
Changing these parameters would be absolutely fine.

**Comment by t-sommer** [comment]
We'll look into this again when the SSP standard is released.
