### ISSUE TITLE
avoiding 'printLogMessage'

### ISSUE THREAD

**Issue by xavfa** [CATIA-Systems/FMPy#311]
Hi to all,
I recently switch from FMI++ (being used only on Windows) to FMPy because the latter offer very ease installation on both Linux and windows. Thanks for this packages !
I am making co-simulation with quite some FMUs (30 for the time being and it should increase in the future). I would like the messages from the printLogMessage in fmi1.py program to be written in a log file instead of popping out in the command window. at least if the status is labeled [OK]

is there an already made option to avoid printing OK messages ? Instead of writing a straightforward (but maybe not quite relevant) filter before printing the message by `if status not OK: print()`.

Thanks in advances
Xavier

**Comment by t-sommer** [comment]
You can pass a custom logger callback to `simulate_fmu()` to catch the messages with "OK" status:

```Python
from fmpy import *
from fmpy.fmi2 import fmi2OK

filename = 'MyModel.fmu'


def log_message(componentEnvironment, instanceName, status, category, message):

    if status == fmi2OK:
        pass  # do nothing
    else:
        print(message.decode('utf-8'))


simulate_fmu(filename, logger=log_message)
```

**Comment by xavfa** [comment]
Thanks for your answer and proposal, but I am not using simulate_fmu(). I am modifying input parameters at each time step and thus uses setReal(), doStep() and getReal(). My concern is more on the instantiate() and initialization stage (for either 1.0 and 2.0).
but following the thread, I saw it was in the printLogMessage() of fmi1.py scripts. As I understood from the scripts, there is no such Callable function in these. Am I right ?
Thanks

**Comment by t-sommer** [comment]
You can also pass the logger callback to [`instantiate_fmu()`](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/simulation.py#L805) or to the constructor of the respective FMU class.

**Comment by xavfa** [comment]
Hi,
It seems that I am not mastering python enough I guess, but I am still facing the issue.
Here is more or less what I'm doing for example for FMU1.0 (should be similar for 2.0 no? ), inspired from one of the example in the git). The log_message is added thanks to what I understood from your answer (in the FMU1Slave definition only in the lines below).
Even though the creation of the FMU1Slave object does not return any error, the instantiate function yes (the logger callback needs to be define as well (from what I caught from the messages...)).
The reason of my question is because I am modelling more than 30FMUs in the same environment and keeping this messages [OK]... leads to a bunch of lines that makes the overall simulation a bit confusing during the initialization step. (Some students should use it in a couple of weeks).

thanks in advance for any help in order to avoid these messages being printed and keeping the FMPy as it is (avoiding making my own changes in possibly different scripts of the package and thus making impossible to get updates afterward...)

```
from fmpy import *
from fmpy.fmi1 import FMU1Slave
from fmpy.fmi1 import fmi1OK

def log_message(componentEnvironment, instanceName, status, category, message):
    if status == fmi1OK:
        pass  # do nothing
    else:
        print(message.decode('utf-8'))

def InstanciateAndInit(file,start_time,stopTime):
    model_description = read_model_description(file)
    FMUElement['unzipdir'] = extract(file)
    vrs = {}
    for variable in model_description.modelVariables:
        vrs[variable.name] = variable.valueReference
    FMUElement['fmu'] = FMU1Slave(guid=model_description.guid,
                            unzipDirectory=FMUElement['unzipdir'],
                            modelIdentifier=model_description.coSimulation.modelIdentifier,
                            instanceName=model_name, fmiCallLogger = log_message)
    FMUElement[FMUKeyName]['fmu'].instantiate()
    FMUElement['fmu'].setReal([vrs['inputs']],[0])
    FMUElement['fmu'].initialize(tStart=start_time, stopTime=stop_time)
    return  FMUElement

def SimFMU(FMUElement,start_time,stopTime,step_size):
    time = start_time
    newInput += 0
   Ouputs = []
    while time < stop_time:
        FMUElement['fmu'].setReal([vrs['inputs']], [newInput])
        FMUElement['fmu'].doStep(currentCommunicationPoint=time, communicationStepSize=step_size)
        Ouputs.append(FMUElement['fmu'].getReal([vrs['outputs']]))
        time += step_size
    FMUElement['fmu'].terminate()
    FMUElement['fmu'].freeInstance()
    return Outputs

if __name__ == '__main__':
    file = 'My_FMU.fmu'
    start_time = 0
    stop_time =  10000
    step_size = 1
    FMUElement = InstanciateAndInit(file,start_time,stopTime)
    Outputs = SimFMU(FMUElement,start_time,stopTime,step_size)
```

**Comment by t-sommer** [comment]
You can either [create your own callback functions](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/simulation.py#L828) or simply use [`instantiate_fmu(..., logger=log_message)`](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/simulation.py#L828) instead of calling the constructor directly.

**Comment by xavfa** [comment]
Great !!! Thanks a lot. I'm using instantiate_fmu() with the log_message() above. works great !
