### ISSUE TITLE
Failed to load shared library 

### ISSUE THREAD

**Issue by mehrdad-moradi** [CATIA-Systems/FMPy#312]
Hi,

I try to instantiate a FMU but I get this error:

Exception: Failed to load shared library C:\Users\Mehrdad\AppData\Local\Temp\tmpte7_w6bw\binaries\win64\ACCTestBenchExampleFMU2_20a.dll. Could not find module 'C:\Users\Mehrdad\AppData\Local\Temp\tmpte7_w6bw\binaries\win64\ACCTestBenchExampleFMU2_20a.dll' (or one of its dependencies). Try using the full path with constructor syntax.

How can I solve it?

Thanks,

**Comment by t-sommer** [comment]
Can you share the FMU?
