### ISSUE TITLE
"Max. sample" will impact the input and results

### ISSUE THREAD

**Issue by sunjw132** [CATIA-Systems/FMPy#313]
during simulating the FMU using fmpy.gui, found that the Simulation options “Max. Sample” will impact the input values and results.
The FMU complied from dymola, and checked the options "Store result in mat file", and set Intervel is blank.

there are 3 inputs in this FMU. Set "FanSPD" is a time-series, as below table, other tow inputs is fixed.
time  | FanSPD | Var2 | Var3
0       |  0          | 153  | 131
500   |  1300    | 153  | 131 
1000 |   0         | 153  | 131

if i set "Max. Sample" is 2, and run simulation, get the values of FanSPD from .mat file is a step line, and the values is changed to 1300 from 0 within the time from 500s to 501s, and the values is 0 defore 500s, and 1300 after 501s.

and if set "Max. Sample" is 500, got different values of FanSPD, the value is continus lines from 0 to 1294.8 within the time from 0s to 500s, and then it goes down to 5.2 at 1000s.

Those values are different with that in dymola, and inputs created by Modelica.Blocks.Sources.

**Comment by sunjw132** [comment]
fmpy version is 0.3.1
![图片1](https://user-images.githubusercontent.com/89722260/131242140-195b5ee4-0942-4c2f-a01e-265d9f7558cb.png)

**Comment by t-sommer** [comment]
Can you share the FMU and input CSV?

**Comment by sunjw132** [comment]
> Can you share the FMU and input CSV?

here cannot upload FMU, can i share them by email?

**Comment by t-sommer** [comment]
Just put everything in a Zip file and drag it onto the comment box.

**Comment by sunjw132** [comment]
attached
[fmpy_issue.zip](https://github.com/CATIA-Systems/FMPy/files/7089122/fmpy_issue.zip)

**Comment by t-sommer** [comment]
With

```Python
from fmpy import *

input = read_csv('MCycle_SimpleCooling_0111_in.csv')

result = simulate_fmu('MCycle_SimpleCooling_0111.fmu',
                      input=input,
                      output=['dTSource', 'dTtoPipe', 'dTCoolant', 'u', 'u1', 'u2'],
                      stop_time=1000,
                      output_interval=500)  # two samples

plot_result(result)
```
I get

![313](https://user-images.githubusercontent.com/2453858/131640506-2dc010fe-9fda-4e25-9fee-14c582f63b2b.png)

@sunjw132, can you please describe your expected result?

**Comment by sunjw132** [comment]
i the input csv, i defined the signal will be changed at 20s, but in your results there were changed at 500s

**Comment by t-sommer** [comment]
Input signals can only be set at communication points. This behavior is expected.
