### ISSUE TITLE
issue with getting interval as a variable from modelvariables

### ISSUE THREAD

**Issue by srivathsanRavi** [CATIA-Systems/FMPy#314]
There is a possibility to get "interval" as a variable from model variables in 
https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/model_description.py

from line 643..
# model variables
    for variable in root.find('ModelVariables'):

        if variable.get("name") is None:
            continue

        sv = ScalarVariable(name=variable.get('name'), valueReference=int(variable.get('valueReference')))
        sv.description = variable.get('description')
        sv.causality = variable.get('causality', default='local')
        sv.variability = variable.get('variability')
        sv.initial = variable.get('initial')
        sv.clocks = variable.get('clocks')
        sv.sourceline = variable.sourceline

At present getting "interval" as a variable is not implemented. Having it helps to search and identify different types of clocks. A line could be added as suggested below.
       sv.interval = variable.get('interval')

**Comment by oliverkotte** [comment]
I believe the line
`sv.interval = variable.get('interval')`
is indeed missing to retrieve the interval attribute.
If you agree, could you add it? (with this fix, we should be able to run FMPy unmodified for our use case)
