### ISSUE TITLE
File not found error using FMU exported from OpenModelica

### ISSUE THREAD

**Issue by BjorHart** [CATIA-Systems/FMPy#319]
Hi!
I am trying to run a openmodelica exported linux FMU. It throws error 

```python
'Failed to load shared library /tmp/tmpgm0f5nd7/binaries/linux64/Runner_test.so. liblapack.so.3: cannot open shared object file: No such file or directory'
```
I am able to remove the error by running:
```
sudo apt-get install libatlas-base-dev
```
why is it so that i need this libatlas? I am hoping to find a workaround, as I am going to run the FMU in a cloud environment.

Zipped FMU is attached below.
[Runner_test.zip](https://github.com/CATIA-Systems/FMPy/files/7162251/Runner_test.zip)

**Comment by t-sommer** [comment]
This FMU has a dependency on an external library. Please open an issue on https://github.com/OpenModelica/OpenModelica.
