### ISSUE TITLE
Simulation failed. The FMU cannot be simulated on the current platform (linux32).

### ISSUE THREAD

**Issue by englucasbt** [CATIA-Systems/FMPy#322]
Hi! I'm trying to use FMPy to do some simulations, but I can't and the following error appears:
Simulation failed. The FMU cannot be simulated on the current platform (linux32).

System Settings:
Operating system: GNU Linux Debian 32 bits
Python 3.7.3

What can I do to resolve this issue?

![FMU](https://user-images.githubusercontent.com/63653719/134963721-158cf644-d1f0-45f9-b684-fbabe1e36c3c.png)
![FMU2](https://user-images.githubusercontent.com/63653719/134963723-b9179d9b-94f3-41d5-b98d-69e550a52f18.PNG)

**Comment by t-sommer** [comment]
You need the matching platform binaries for your platform (32-bit Linux in your case).

**Comment by iscopa** [comment]
You can generate the Linux32 binary using FMPy for Python v2.7 and then run the FMU with FMPy for Python v3.X:

1. Install FMPy v0.2.27 for python v2 and compile the source-code FMU for Linux32 following the tutorial : https://github.com/CATIA-Systems/FMPy/wiki/RaspberryPi :

```

 root@A11QRA:/home/jarvis/FMUs# python -m pip list
 Package                       Version
 ----------------------------- -------
 asn1crypto                    0.24.0
 backports.functools-lru-cache 1.5
 beautifulsoup4                4.7.1
 chardet                       3.0.4
 configparser                  3.5.0b2
 cryptography                  2.6.1
 entrypoints                   0.3
 enum34                        1.1.6
 FMPy                          0.2.27
 html5lib                      1.0.1
 ipaddress                     1.0.17
 keyring                       17.1.1
 keyrings.alt                  3.1.1
 lxml                          4.3.2
 numpy                         1.16.2
 pathlib                       1.0.1
 pip                           18.1
 pycrypto                      2.6.1
 PyGObject                     3.30.4
 pyxdg                         0.25
 SecretStorage                 2.3.1
 setuptools                    40.8.0
 six                           1.12.0
 soupsieve                     1.8
 webencodings                  0.5.1
 wheel                         0.32.3
 
```

2. Install current version of FMPy for Python v3.X 

```
 sudo apt install python3-numpy python3-lxml python-pathlib python3-pip
 sudo pip3 install --no-deps fmpy
```
Check that the current version of FMPy is installed:
```
root@A11QRA:/home/jarvis/FMUs# python3 -m pip list
Package            Version
------------------ ---------
attr               0.3.2
attrs              22.1.0
beautifulsoup4     4.7.1
certifi            2021.5.30
chardet            3.0.4
charset-normalizer 2.0.6
FMPy               0.3.12
html5lib           1.0.1
idna               3.2
lxml               4.3.2
numpy              1.16.2
paho-mqtt          1.5.1
pip                18.1
requests           2.26.0
six                1.12.0
soupsieve          1.8
urllib3            1.26.6
webencodings       0.5.1

```

3. Run the FMU with current version of FMPy for Python v3.X

![grafik](https://user-images.githubusercontent.com/64407895/184353045-1ea0fe7c-5f94-4379-bf26-512459f9da68.png)
