### ISSUE TITLE
Number of Samples

### ISSUE THREAD

**Issue by xogeny** [CATIA-Systems/FMPy#33]
Looking at the source code for `command_line.py`, (specifically [this line](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/command_line.py#L38)), I don't see how this command line parameter has any effect.  It doesn't appear as though the value extracted from the command line is used anywhere.

Am I missing something?

**Comment by t-sommer** [comment]
You're right: `--num-samples` wasn't used. As of 40261d2e436bb5827cc9aabe3cc0036e2399f207 you can control the number of samples through `--output-interval`. Thanks for reporting this problem!

**Comment by xogeny** [comment]
The problem with output intervals is that unless you know the default start time and end time, you cannot calculate the output interval to achieve a specific number of outputs.

But you (presumably) have the necessary information to do that calculation.  So it seems too burdensome (to me) to expect the user to open up the FMU and parse the model description file to get the default start and end times in order to compute an output interval to achieve a specified number of output points.

Or is there some easier way for the user to do this?

**Comment by t-sommer** [comment]
Getting the start and stop time for the default experiment is actually quite easy:

```
$ fmpy info Rectifier.fmu

Model Info
...

Default Experiment

  Stop Time         0.1
  Step Size         1e-07
...
```

The reason for using output interval instead of number of samples is that it gives a "nicer" grid (see also #28). If you don't specify it FMPy will calculate an output interval so you get a "nice" grid with 500-1000 samples.
