### ISSUE TITLE
Bug in custom_input.py result storing

### ISSUE THREAD

**Issue by make-ing** [CATIA-Systems/FMPy#334]
Hello,

i think the `custom_input.py` example has a small bug. The stored results in the `rows` variable should be shifted by one timestep. The reason in IMHO is that the results are retrieved after the `doStep` methond is called, but stored with the prevoius time value. I created a PR #333 which explains the bug in more detail.

**Comment by t-sommer** [comment]
Superseded by 7bf96f3b53bdffb5b1a2542b682a564f30e9d01f.

**Comment by t-sommer** [comment]
Fixed with 7bf96f3b53bdffb5b1a2542b682a564f30e9d01f.
