### ISSUE TITLE
How do I access all variables with simulate_fmu?

### ISSUE THREAD

**Issue by sharanry** [CATIA-Systems/FMPy#337]
The following code only plots and gives access to and plots 5 variables from 1000+ variables. How do I access the rest of the variables? 

```python
import fmpy
fmu = "FMU_FILE.fmu"
fmpy.dump(fmu)
result = fmpy.simulate_fmu(fmu)
fmpy.util.plot_result(result)
```

```python
result.dtype.descr
-----
[('time', '<f8'),
 ('r_1', '<f8'),
 ('r_2', '<f8'),
 ('r_3', '<f8'),
 ('r_4', '<f8'),
 ('r_5', '<f8')]
```

**Comment by t-sommer** [comment]
By default `simulate_fmu()` records only outputs (or a small set of internal variables if there are no outputs). The variables to record can be specified with `simulate_fmu(..., outputs=['r_1', 'r_3', 'r_5'])`.
