### ISSUE TITLE
Error while try to run co-simulation on ubuntu 

### ISSUE THREAD

**Issue by Arvin-Hosseinnejad** [CATIA-Systems/FMPy#338]
When I tried to co-simulate the KGN86_16C_verified_v11.fmu file in ubuntu, I have got an error message as follow:
the same file is working on the windows platform. I wonder why the fmu file does not work on ubuntu? is there any opinion? 

Exception: Failed to load shared library /tmp/tmp7882aqr0/binaries/linux64/KGN86_16C_verified_v11.so. /tmp/tmp7882aqr0/binaries/linux64/KGN86_16C_verified_v11.so: undefined symbol: dgelsy_

**Comment by t-sommer** [comment]
The FMU seems to depend on a library that is not installed on your system.
