### ISSUE TITLE
Typos in util.py documentation

### ISSUE THREAD

**Issue by traversaro** [CATIA-Systems/FMPy#34]
* https://github.com/CATIA-Systems/FMPy/blob/08a2e3c8fcac6cfaa66cca1a5b903f0bc8ce17a5/fmpy/util.py#L18  trajectoies --> trajectories 
* https://github.com/CATIA-Systems/FMPy/blob/08a2e3c8fcac6cfaa66cca1a5b903f0bc8ce17a5/fmpy/util.py#L147  agains --> against 
* https://github.com/CATIA-Systems/FMPy/blob/08a2e3c8fcac6cfaa66cca1a5b903f0bc8ce17a5/fmpy/util.py#L496 conatains --> contains 

I have the changes in the branch https://github.com/traversaro/FMPy/tree/patch-1 , but I did not open a PR given that, citing the contributing guide:
> For legal reasons we're currently not accepting pull requests. Please create an issue if you have suggestions for improvements.

**Comment by t-sommer** [comment]
Thanks for your help! We're working on a way to accept external contributions.
