### ISSUE TITLE
"structured" naming convention validation issue

### ISSUE THREAD

**Issue by simongeisseler** [CATIA-Systems/FMPy#347]
The validation of the "structured" naming convention has a small typo in the grammar.

This line is missing a `*` for the second "token pair":
https://github.com/CATIA-Systems/FMPy/blob/47760e9e4c4f435c43e8c14cdd8e12fccf6f7028/fmpy/validation.py#L242
It should be:
```
            qname           : "'" ( qchar | escape ) ( qchar | escape )* "'" 
```

**Comment by t-sommer** [comment]
From the FMI 2.0.3 Spec, p. 67:

![syntax](https://user-images.githubusercontent.com/2453858/145369279-a876d1c0-53f7-42bf-aded-6c13f39d2867.PNG)
