### ISSUE TITLE
PythonSlave.so. libpython3.9.so.1.0

### ISSUE THREAD

**Issue by zhangbin006** [CATIA-Systems/FMPy#348]
Under Linux. Failed to load Shared library/TMP/tmpssa9_q04 / binaries/on/PythonSlave. So. Libpython3.9. So. 1.0: unable to open the Shared object file: There is no file or directory, you have not encountered

**Comment by zhangbin006** [comment]
Loading pythonslave. fmu with fmpy. GUI under Linux causes the problem mentioned above, but the file exists under load force

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by zhangbin006** [comment]
[PythonSlave.zip](https://github.com/CATIA-Systems/FMPy/files/7683786/PythonSlave.zip)
Hi, this is fMU I packaged in Linux, but using Fmpy. GUI will cause the above problem. Please take a look at it for me

**Comment by t-sommer** [comment]
The FMU's binary depends on `libpython3.9.so.1.0`:

```
$ ldd PythonSlave.so
        linux-vdso.so.1 (0x00007fffea0d0000)
        libpython3.9.so.1.0 => not found
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1a1af30000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1a1ad10000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1a1a910000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1a1a570000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1a1b600000)
```

Such an FMU cannot be simulated in Python.

**Comment by zhangbin006** [comment]
How can I solve this problem, is I install GCC problem?

**Comment by zhangbin006** [comment]
I compiled FMU using the pythonFUm package, which worked fine under Windows, but not in Linux

**Comment by t-sommer** [comment]
> How can I solve this problem

FMUs that require the Python runtime cannot run in Python. Any other simulator should work (e.g. the [FMU Compliance Checker](https://github.com/modelica-tools/FMUComplianceChecker)).

After all, what's the point of exporting Python code as an FMU to run that FMU in Python?

**Comment by markaren** [comment]
> FMUs that require the Python runtime cannot run in Python

That is not true. The issue here is that the FMU requires Python 3.9 and the user has some other version installed. This is only an issue under Linux.

> After all, what's the point of exporting Python code as an FMU to run that FMU in Python?

That is a weird statement. What is the reason for creating FMUs at all?

**Comment by SchmJo** [comment]
I posted a solution that worked in my case on #435
