### ISSUE TITLE
An example of co-simulation?

### ISSUE THREAD

**Issue by jbkoh** [CATIA-Systems/FMPy#36]
Hi,

I just started learning this FMI world and FMPy seems to be the best opensource option that I could use right now. Do you have any example code of cosimulation? I plan to do it for building physics and control operations from different frameworks and would like to use FMI and FMPy to execute them.

Thanks!

**Comment by t-sommer** [comment]
A similar question has been asked in #15

**Comment by jbkoh** [comment]
I will try it out with the getset example. Thanks!
