### ISSUE TITLE
simulate_fmu of contained FMU fails

### ISSUE THREAD

**Issue by Matthias776** [CATIA-Systems/FMPy#360]
Hello together,

when trying to simulate a contained FMU, that was created by _create_fmu_container_, with the _simulate_fmu_ function I have the issue that the program doesn't run reliable.
When executing the attached code it ended up with the following statement:

Process finished with exit code -1073740940 (0xC0000374)

In different threads I red that some people assume that a memory issue is causing this.
The size of the FMUs (Reference.fmu 1903KB , Controller.fmu 1906KB, Drivetrain.fmu 2027KB) I'm using is much greater than the one shown in the examples (Rectifier.fmu 68KB). Since I exported them from Dymola I don't have an impact on their size from my point of view.

I'm interested in if anyone else ran into a similar problem or can tell me what have to be considered when dealing with large FMUs using the fmpy package.

Kind regards,
Matthias

PS: It's very likely that this issue causes the timeout problem #358  I reported yesterday
_________________________________________________________________________________________________________________________________________

```
import os
from fmpy import simulate_fmu, plot_result
from fmpy.fmucontainer import create_fmu_container, Variable, Connection, Configuration, Component, Unit, BaseUnit, DisplayUnit, SimpleType
from fmpy.validation import validate_fmu

curr_dir = os.path.dirname(os.path.abspath(__file__))
path_to_fmus = os.path.join(curr_dir)
path_to_fmus_model1 = os.path.join(path_to_fmus,"Reference","CS","2")
path_to_fmus_model2 = os.path.join(path_to_fmus,"Controller","CS","2")
path_to_fmus_model3 = os.path.join(path_to_fmus,"Drivetrain","CS","2")

def simulate_ControlledDrivetrain(show_plot=True):
    configuration = Configuration(
        description="A controlled drivetrain",
        variableNamingConvention='structured',
        unitDefinitions=[
            Unit(name='N*m', baseUnit=BaseUnit(kg=1, m=1**2, s=-1**2))
        ],
        typeDefinitions=[
            SimpleType(name='Torque', type='Real', unit='N*m')
        ],
        variables=[
            Variable(
                type='Real',
                variability='continuous',
                causality='input',
                name='u1',
                start="0",
                description='Reference Signal',
                mapping=[('controller', 'u1')]
            ),
            Variable(
                type='Real',
                variability='continuous',
                causality='input',
                name='u2',
                start="0",
                description='Feedback Signal',
                mapping=[('controller', 'u2')]
            ),
            Variable(
                type='Real',
                variability='continuous',
                causality='input',
                name='u',
                start="0",
                description='Drivetrain input',
                mapping=[('drivetrain', 'u')]
            ),
            Variable(
                type='Real',
                variability='continuous',
                causality='output',
                name='y1',
                description='Reference output',
                mapping=[('reference', 'y')]
            ),
            Variable(
                type='Real',
                variability='continuous',
                causality='output',
                name='y2',
                description='Controller output',
                mapping=[('controller', 'y')],
                declaredType="Torque"
            ),
            Variable(
                type='Real',
                variability='continuous',
                causality='output',
                name='y',
                description='Drivetrain output',
                mapping=[('drivetrain', 'y')]
            ),
        ],
        components=[
                Component(
                    filename=os.path.join(path_to_fmus_model1, 'Reference.fmu'),
                    name='reference'
                ),
                Component(
                    filename=os.path.join(path_to_fmus_model2, 'Controller.fmu'),
                    name='controller',
                ),
                Component(
                    filename=os.path.join(path_to_fmus_model3, 'Drivetrain.fmu'),
                    name='drivetrain',
                )
            ],
        connections=[
            Connection('reference', 'y', 'controller', 'u2'),
            Connection('controller', 'y', 'drivetrain', 'u'),
            Connection('drivetrain', 'y', 'controller', 'u1'),
        ]
    )

    filename = 'ControlledDrivetrain.fmu'

    create_fmu_container(configuration, filename)

    problems = validate_fmu(filename)

    # check if list "problems" is empty
    if not problems:
        # simulate the container fmu
        print("Simulate...")
        result = simulate_fmu(filename, output=["y", "y1", "y2"], stop_time=0.1)
        print("Simulation was successful!")
        # plot the results
        if show_plot:
            print("Plot...")
            plot_result(result)
    else:
        print("Simulation not possible due to following problems:\n"+problems)


def main():
    simulate_ControlledDrivetrain()
    return

if __name__ == '__main__':
    main()
```

**Comment by t-sommer** [comment]
Can you share the FMUs that you've used?

**Comment by Matthias776** [comment]
Thank you for the quick reply!
Since I don't have source code generation license for exporting FMUs and using a shared license, Dymola needs to be opened when simulating the FMUs. Otherwise it would raise an error regarding "DYMOLA_RUNTIME_LICENSE".

[FMUs.zip](https://github.com/CATIA-Systems/FMPy/files/7854439/FMUs.zip)

**Comment by Matthias776** [comment]
> Thank you for the quick reply! Since I don't have source code generation license for exporting FMUs and using a shared license, Dymola needs to be opened when simulating the FMUs. Otherwise it would raise an error regarding "DYMOLA_RUNTIME_LICENSE".
> 
> [FMUs.zip](https://github.com/CATIA-Systems/FMPy/files/7854559/FMUs.zip)

I zipped the wrong files by mistake. The have been updated now!

**Comment by t-sommer** [comment]
This seems to be a bug in `Reference.fmu` that causes a heap corruption when `fmi2FreeInstance()` is called. Can you try to export it with the latest Dymola version?

**Comment by Matthias776** [comment]
I'm using Dymola Version 2021x and will look if I can get an update now.
Just for having those FMUs as an example I set the export settings as used in this example:
[](https://www.claytex.com/tech-blog/build-fmus-from-dymola-model-run-fmus-in-dymola-and-simulink/)

Since you assume there is bug when exporting the model I did a FMU check at:
[](https://fmu-check.herokuapp.com/)
with the following result.
![image](https://user-images.githubusercontent.com/75908701/149321871-c6904977-2f22-47d2-967d-dda294aae9f4.png)

Here is the Dymola File of the model so that you also can try as long as I haven't the latest Dymola version:
[DymolaModel.zip](https://github.com/CATIA-Systems/FMPy/files/7862384/DymolaModel.zip)

**Comment by t-sommer** [comment]
Please reopen if the problem persists when exporting the FMUs the latest Dymola version.

**Comment by Matthias776** [comment]
Even FMU exports of Dymola Version 2022 failed. My assumption is that it has to deal with the export of components of the multibody library. I build the same model in OpenModelica Connection Editor with the same result, so that I raised the issue in Open Modelica Forum (#11262)
https://www.openmodelica.org/forum/default-topic/3399-fmu-export-of-multibody-models-fails

**Comment by Matthias776** [comment]
Using Dymola Version 2022x (64-bit) I created a three different FMUs (JointModel_CS.fmu, Reference_CS.fmu, RigidBodyModel_CS.fmu) of the Controlled Drivetrain of which I created one "Container" FMU (ControlledDrivetrainDymolaFMU.fmu) again.
I can simulate this Container FMU successfully whereas the one I created by using create_fmu_container crashes when simulating.

I hope you can reproduce it by using the following files:
[FMUs.zip](https://github.com/CATIA-Systems/FMPy/files/8033912/FMUs.zip)
