### ISSUE TITLE
can not get license from license server

### ISSUE THREAD

**Issue by ArvidMartensRenson** [CATIA-Systems/FMPy#361]
Our Dymola installation is linked to a Dassault systemes license server, running some of our FMUs requires the usage of a license. However, whenever we want to run our FMUs with FMPy we get an error that no license could be checked out. In the python scripts we set the environment variable to point at the license file. I also tested opening dymola (to acquire a license) before running the script, but that does not work either.

**Comment by t-sommer** [comment]
Can you try to set the environment variable in cmd.exe and then simulate the FMU?

```
C:\temp>set DYMOLA_RUNTIME_LICENSE=c:/users/xxx/appdata/roaming/dassaultsystemes/dymola/dymola.lic

C:\temp>fmpy simulate Model.fmu
```

**Comment by ArvidMartensRenson** [comment]
That does not seem to work either. I suppose it has something to do with using the Dassault Systemes license server (DSLS). When booting Dymola we also have to run the exe with the additional /DSLS option, otherwise dymola does not recognize the DSLS server and it falls back on the trail version. Do you think there is a way to add this option when fmpy tries to acquire the dymola license?

**Comment by KarlWernersson** [comment]
Hi Arvid
Fmpy should not and cannot retrieve the license, this should be done by the FMU itself.
You should contact Dymola Support and they can help you. This can be done through your reseller.

**Comment by KarlWernersson** [comment]
Hi Arvid, do you have an export licesne with the DSLS?

Dymola User Manual Volume 1, 4.3.2 Dassault Systèmes License Server (DSLS)
Limitations:
• Borrowing of licenses (the Dymola command Tools > License Setup > Borrow) is not supported.
• Running FMUs that were exported without export license is not supported "
