### ISSUE TITLE
Shared memory remoting hangs at end of simulation

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMPy#362]
When using the shared memory remoting, the simulation runs fine, but hangs at the end.

When I enable Debug Logging, "fmi2FreeInstance" is reached, and the server process is terminated, but the slave dll seems to never return.

**Comment by t-sommer** [comment]
Can you provide steps to reproduce the problem?

**Comment by fajansen** [comment]
Sorry, it was a problem of the FMU I remoted.
