### ISSUE TITLE
simulate_fmu appears to not be thread safe

### ISSUE THREAD

**Issue by greenwoodms06** [CATIA-Systems/FMPy#363]
I am attempting to leverage FMPYy in some optimization workflows using [RAVEN](https://github.com/idaholab/raven]). This code handles parallelization and what not internally. However, when sending an FMU to simulate_fmu() there can arise issues where two threads appear to be trying to use the FMU at the same time.

I am currently looking at other work arounds but I wanted to know if simulate_fmu() was supposed to be thread safe?

**Comment by t-sommer** [comment]
Can you provide steps to reproduce the problem?

**Comment by greenwoodms06** [comment]
Sure. The test `ModelicaPy/tree/master/modelicapy/raven/plugin/tests/calibrateFMU_test.xml`  is the example I am seeing this in. After some random (?) number of iterations (311 the last time I tried on my machine) an error is thrown that indicates the fmu cannot be found which is believed to actually be a thread issue. Setting `batchsize = 1` (line 20) runs to completion as expected.

I am running this on Windows 10 via a gitbash. RAVEN installation for Windows if you are able/interested in testing is here: https://github.com/idaholab/raven/wiki/installationWindowsNew.

Once installed go to the `ModelicaPy/tree/master/modelicapy/raven/plugin/tests/calibrateFMU_test.xml` folder and then from gitbash run:

```./PATHTORAVENFOLDER/raven_framework calibrateFMU_test.xml```

Happy to have a meeting with you and get a RAVEN dev on the line too if that would be better for you.

**Comment by t-sommer** [comment]
Is the FMU itself thread safe?

**Comment by greenwoodms06** [comment]
The FMU being tested is generated from Dymola. Any ideas on if their implementation is supposed to create thread safe FMUs?

**Comment by TorstenBlochwitz** [comment]
FMUs don't have to be thread safe (see section 2.1 of the FMI 2.0 specification. The importer has to ensure a thread safe calling sequence of the API-functions.

**Comment by greenwoodms06** [comment]
Thanks for that information @TorstenBlochwitz . Hmm. So... @t-sommer do you think FMPy `simulate_fmu()` should be thread safe if the FMU is thread safe?... I can reach out to Dymola folks but any fix they may have wouldn't be until their next release cycle in June-ish at best. Want to make sure we narrow down who is causing the problem but it seems the tool that uses the FMU may be the more likely culprit... but maybe I just don't understand... :(

**Comment by greenwoodms06** [comment]
I don't know if things are thread safe but in the RAVEN system specifying the absolute path fixed my issues on my computer. I'll go ahead and close this as I'm not sure how to create a specific test for thread safe verification more generally.
