### ISSUE TITLE
can't start the Web App

### ISSUE THREAD

**Issue by mycrocs** [CATIA-Systems/FMPy#364]
I can't start the Web App. Here is the error.
![image](https://user-images.githubusercontent.com/31428244/150733673-2655258b-4ff1-42dd-a5cb-46f3616c3787.png)
I install the package from conda. Here is the version. 
![image](https://user-images.githubusercontent.com/31428244/150734009-6945379c-9417-4b6c-83f0-1bc0dee702d7.png)

**Comment by t-sommer** [comment]
Have you activated the Python environment where you installed FMPy?

**Comment by mycrocs** [comment]
Yes, the packages listed above is in my Python env. 
I tried using the pip to install the same package and it starts successfully.

**Comment by t-sommer** [comment]
I can install and run the web app with

```
conda create -n webapp -c conda-forge python=3.10 fmpy
conda activate webapp
python -m fmpy.webapp MyModel.fmu
```

Please reopen and provide steps to reproduce if the problem persists.
