### ISSUE TITLE
fmi3LogMessageCallback to many arguments

### ISSUE THREAD

**Issue by KarlWernersson** [CATIA-Systems/FMPy#368]
fmi3LogMessageCallback has one string argument to much
fmi3LogMessageCallback         = CFUNCTYPE(None, fmi3InstanceEnvironment, **fmi3String**, fmi3Status, fmi3String, fmi3String)
shoud be
fmi3LogMessageCallback         = CFUNCTYPE(None, fmi3InstanceEnvironment, fmi3Status, fmi3String, fmi3String)
 
instance name was removed in beta 3

**Comment by t-sommer** [comment]
This is a duplicate of #365.
