### ISSUE TITLE
Add co-simulation wrapper  can't use

### ISSUE THREAD

**Issue by mycrocs** [CATIA-Systems/FMPy#369]
Add co-simulation wrapper  can't use. 
![image](https://user-images.githubusercontent.com/31428244/151101300-4840b96f-8d23-4664-a0c0-77b974d84833.png)

**Comment by t-sommer** [comment]
Can you provide steps to reproduce the problem?

**Comment by mycrocs** [comment]
First, i loaded my fmu in FMpy. It's a fmi2.0 model_exchange model from SCADE.
Then i used the Co-Simulation Wrapper function to wrap the model, but it didn't work.
The error says "fail to add co-simulation wrapper. System cant find the path <mypath>\\documentation\\licenses".

Does the add co-simulation wrapper need license or the SCADE fmu model itself need?

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by mycrocs** [comment]
Hi! Here is the FMU.
[SCADEModel.zip](https://github.com/CATIA-Systems/FMPy/files/8012122/SCADEModel.zip)
