### ISSUE TITLE
API Documentation?

### ISSUE THREAD

**Issue by jbkoh** [CATIA-Systems/FMPy#37]
Hi,

Though I am looking through the examples and source codes, it'd be great to read through actual API documentation, but I can't find one.

Thanks!

**Comment by t-sommer** [comment]
The FMI specifications are available on http://fmi-standard.org/downloads/. There you find the documentation for the FMI functions, calling sequences, modelDescription.xml etc.

**Comment by jbkoh** [comment]
Thanks for the quick response. I guess my question is more about FMPy's APIs (though I still need to learn more about FMI). Otherwise, are dump() and simulate_fmu() the only function that I need from FMPy?

**Comment by t-sommer** [comment]
If you want to get information about a model and simulate it that should be all you need

**Comment by jbkoh** [comment]
As I mentioned in another thread, I would like to set/get values also and use any other functions for writing a co-simulation if there are. I guess that's it for now but it'd be great to have a documentation for reference during the development. Just my two cents.

Thanks!

**Comment by t-sommer** [comment]
You might want to have a look at the [custom_input.py](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/custom_input.py) example.
