### ISSUE TITLE
Function logMessage crashes

### ISSUE THREAD

**Issue by TorstenBlochwitz** [CATIA-Systems/FMPy#370]
I have installed version 0.3.5. When I call the logMessage callback function within the GUI version of FMPy, it crashes with an access violation.

**Comment by TorstenBlochwitz** [comment]
A test FMU can be found in the fmi-design repo: fmi-design\FMI_3.0\sandbox\fmus\3.0-beta.3\cs\x86_64-windows\SimulationX

**Comment by t-sommer** [comment]
With af832ee87746fdb59ef7f22c25423d901d073e6f I can simulate the FMU:

```
> fmpy simulate BouncingBall3CSEvent.fmu
[OK] Event Mode not used
[OK] Early return not allowed
```

Note that the fix is only available on `develop`.

**Comment by TorstenBlochwitz** [comment]
@t-sommer : Just to make sure sure: I followed the instructions on https://github.com/CATIA-Systems/FMPy/blob/master/docs/faq.md to install a development build. The last Run I see on https://dev.azure.com/CATIA-Systems/FMPy/_build?view=runs is from Monday. Is the fix included?

**Comment by t-sommer** [comment]
This should include the fix. I've updated the FAQ to point to the `merged` Wheel.

**Comment by TorstenBlochwitz** [comment]
Yes, it worked. Thanks!
