### ISSUE TITLE
Enable FMU state save/restart in simulate_FMU

### ISSUE THREAD

**Issue by greenwoodms06** [CATIA-Systems/FMPy#372]
I have been fiddling with scenarios where restart capabilities at some point in a simulation would be required to dramatically decrease computational time. Saving all states and properly reinitializing seems to not be the best approach for aa variety of reasons. However, I was thinking that could likely be readily included in the `simulate_fmu` would be something that saves the current state of the FMU at whatever step. I was thinking that that fmu state could then be an optional input and if found it could be used as a robust restart.

An example of possible implementation could be a binary form of the fmu state (e.g., pickle) at could be saved at some simulation interval
- perhaps only in cosimulation mode (not sure if this makes sense or not in modelexchange)
- interval could be based on:
    -  number of steps (output interval)
    -  at the nearest specified times (i.e., list of time intervals)
    -  after certain events (not sure about this one)
- A flag option to override or create new copies of the pickled fmu state per the user needs
- the pickled state would be updated (when other conditions are met) after the doStep is completed correctly

The question I have is if this seems feasible with the underworking of FMPy? For example, is pickling the fmu after a doStep and then loading that pickle for a restart simply not possible (e.g., some sort of memory issue, etc.)?

Do you believe there are any show stoppers to this?... or it already exists and I missed it...

**Comment by t-sommer** [comment]
This is already possible with the `step_finished` callback:

```Python
from fmpy import *
import shutil


serialization_time = None
serialized_state = None  # a simple byte string that can be saved to a file


def save_state(time, recorder):
    """ callback to serialize the FMU state and stop the simulation """
    
    if time >= 0.6:  # condition to serialize the FMU state
        fmu = recorder.fmu
        state = fmu.getFMUstate()
        global serialization_time, serialized_state
        serialization_time = time
        serialized_state = fmu.serializeFMUstate(state)
        return False  # stop the simulation

    return True  # continue the simulation


filename = 'BouncingBall.fmu'

# simulate the FMU...
result = simulate_fmu(filename, stop_time=3.0, step_finished=save_state)

# ... and resume the simulation with the serialized state
unzipdir = extract(filename)
model_description = read_model_description(unzipdir)

fmu_instance = instantiate_fmu(unzipdir=unzipdir, model_description=model_description)

state = fmu_instance.deSerializeFMUstate(serialized_state)
fmu_instance.setFMUstate(state)

result = simulate_fmu(filename=unzipdir, model_description=model_description,
                      fmu_instance=fmu_instance, start_time=serialization_time)

plot_result(result)

# clean up
shutil.rmtree(unzipdir, ignore_errors=True)
```

**Comment by greenwoodms06** [comment]
Oh great!... That looks very much like what I was thinking. I'll try that out and report back.

**Comment by t-sommer** [comment]
This seems to be a bug in the FMU. @KarlWernersson, can you help @greenwoodms06?

**Comment by t-sommer** [comment]
@greenwoodms06, can you try to export the FMU with CVode?

**Comment by KarlWernersson** [comment]
@greenwoodms06 could you make a support request at Dymola support.
I will look at it there.

**Comment by greenwoodms06** [comment]
@t-sommer I attempted with CVode. The same error occurred.

@KarlWernersson , can you please advise on where I make a formal Dymola support (e.g., link)?

**Comment by KarlWernersson** [comment]
@greenwoodms06 You need to contact the seller of your Dymola license they will set it up for you.

**Comment by KarlWernersson** [comment]
This is now corrected for Dymola 2023, this bug affects dassl, lsodar rkfix and euler solver. 
It should work better on other solvers i would recommend cvode or RaduaII if you want to avoid a bdf solver

Note that simulate_fmu function cannot be used after the deserialized state has been set as this function initializes the FMU and in the state the FMU has been set to it is already initialized
