### ISSUE TITLE
Editing public FMU parameters like fmi_NumberOfSteps

### ISSUE THREAD

**Issue by Matthias776** [CATIA-Systems/FMPy#374]
Is it possible to change the public parameters of a FMU like fmi_NumberOfSteps?

The screenshot below shows how they are accessible in Dymola:
![image](https://user-images.githubusercontent.com/75908701/153205748-adbcf35a-2c46-4b5a-818c-53878d9f361e.png)

Using https://fmu-check.herokuapp.com/ shows which parameters of FMU are accessible. Since it's not listed I fear it cannot be changed from FMPy. Is this right?

**Comment by t-sommer** [comment]
Can you describe a use case for this feature?

**Comment by Matthias776** [comment]
I am thinking of a simulation with a model that has a significant sluggishness with respect to the dynamics of the other models. For example, a thermal model of an enclosure that experiences a heat flux due to the friction of a gearbox or the winding losses of a motor.
My guess is that this can save computation time in the case of co-simulations.
