### ISSUE TITLE
Changing parameters in fmu using fmpy

### ISSUE THREAD

**Issue by PrasannaVaradarajan** [CATIA-Systems/FMPy#377]
The question that I have, Is there any limitation with fmpy to only change the input variables during the execution of the fmu and not any other parameters ?
Is there a special way that I should define the parameters if I am going to use the fmu using fmpy so that the parameters can be changed outside while executing the fmu?

**Comment by t-sommer** [comment]
In order to change parameters during the simulation they have to be defined with `variability="tunable"`.

**Comment by PrasannaVaradarajan** [comment]
Hi thanks for the update. I am not clear on how to do it in Modelica to define certain parameters to the variability as tunable. Any suggestions on that side

**Comment by t-sommer** [comment]
Exporting FMUs is outside the scope of FMPy. Please consult the documentation of your tool.
