### ISSUE TITLE
Build Tools 2019 no longer supported

### ISSUE THREAD

**Issue by CSchulzeTLK** [CATIA-Systems/FMPy#381]
Since Visual Studio 2022 is supported, 2019 Build Tools no longer are (c5adf10f65825a26f2b10f3ea7c14a0a72486986).

The argument `-product *` has been removed:
https://github.com/CATIA-Systems/FMPy/blob/c4d71f51caf48ea648c9bcb7002442291eb2f287/fmpy/util.py#L694

vswhere help points out:
-products arg  One or more product IDs to find. **Defaults to Community, Professional, and Enterprise.**

So the argument product is required to find the BuildTools. The ProductID of the BuildTools is "productId: Microsoft.VisualStudio.Product.BuildTools".

Additionally, custom Installpaths are not supported. The version number is read from the directory name, instead of retrieving it from vswhere (--property InstallationPath).
https://github.com/CATIA-Systems/FMPy/blob/c4d71f51caf48ea648c9bcb7002442291eb2f287/fmpy/util.py#L726

**Comment by t-sommer** [comment]
@CSchulzeTLK, can you give 5a390ae74e97aa5c261182ca11fed5101177f44c a try?
