### ISSUE TITLE
How to set and get the array ?

### ISSUE THREAD

**Issue by indhupriyadharshini** [CATIA-Systems/FMPy#382]
@t-sommer 
@m-kessler 

I am new to FMI and FMPy.i have a problem in setting and getting the array

Here in the below example variable G is float array 

Status setFloat64(ModelInstance* comp, ValueReference vr, const double *value, size_t *index) {
    switch (vr) {
        case vr_G:
            M(G) = value[(*index)++];
            return OK;
	 default:
            return Error;
    }
}

i have tried something like this and it didn't work fmu.setFloat64([vr['G[]']], [10,20])

and simout is an array i want to get that array
fmu.getFloat64([vr['simout[i]']])

Could you please help me with this?

**Comment by t-sommer** [comment]
Can you provide an full example with an FMU?

**Comment by indhupriyadharshini** [comment]
I cannot share the full example in public because it is master thesis stuff.
is there any way of sending it in private?
