### ISSUE TITLE
Is it possible to hook up 2 FMU's to each other using FMPY ?Any inputs will help.

### ISSUE THREAD

**Issue by pchidamb** [CATIA-Systems/FMPy#385]

**Comment by t-sommer** [comment]
[create_fmu_container()](https://github.com/CATIA-Systems/FMPy/blob/42f22b01e0e441cc917f8fbb9a188ada973ce241/fmpy/fmucontainer/__init__.py#L58) (experimental) might be what you're looking for. See [tests/test_fmu_container.py](https://github.com/CATIA-Systems/FMPy/blob/master/tests/test_fmu_container.py) for an example how to use it.
