### ISSUE TITLE
Installing Problems

### ISSUE THREAD

**Issue by WaetzoldP** [CATIA-Systems/FMPy#386]
When I try to install FMPy via "pip install fmpy[complete]" I get the Error-Message: 
"Could not find a version that satisfies the requirement pywin32; platform_system == "Windows" (from fmpy[complete]) (from versions: )
No matching distribution found for pywin32; platform_system == "Windows" (from fmpy[complete])"

**Comment by t-sommer** [comment]
Can you provide steps to reproduce the problem? What Python distribution / version are you using?
