### ISSUE TITLE
Fmpy tests fMU problems

### ISSUE THREAD

**Issue by 2018-Summer** [CATIA-Systems/FMPy#387]
hi，I ues  result = simulate_fmu(fmu_filename, start_values=create_input_dict(data_flow), timeout=0.01)，When new data is transmitted to fMU block, its calculation time will increase by 0.4s every time it is calculated, which will lead to slower and slower running later. I don't know why this problem occurs. Do you know? If you know, please answer. Thank you！

**Comment by t-sommer** [comment]
Can you share an example to reproduce the problem?
