### ISSUE TITLE
apply_default_start_values does nothing

### ISSUE THREAD

**Issue by joerg-tt** [CATIA-Systems/FMPy#389]
It looks like that since https://github.com/CATIA-Systems/FMPy/commit/386fe67de36dd6ee9fb1cd5e263f71dc07c14381 the parameter `apply_default_start_values` in `simulate_fmu()` has no functionality anymore.

**Comment by joerg-tt** [comment]
Thanks for the clarification! Could you maybe elaborate why this would be a bad idea? I know of a couple of users who would love to have this feature and think it's a great idea ;-)

**Comment by t-sommer** [comment]
See [FMI 2.0.3 Specification](https://github.com/modelica/fmi-standard/releases/download/v2.0.3/FMI-Specification-2.0.3.pdf), p. 56.
