### ISSUE TITLE
FMPy for exporting to FMU?

### ISSUE THREAD

**Issue by LasseLedet** [CATIA-Systems/FMPy#390]
Can FMPy be used for exporting a Python script to a FMU?

**Comment by t-sommer** [comment]
No, FMPy cannot export such FMUs. You might want to take a look at [Modelica-ExternalLibrary](https://github.com/CATIA-Systems/Modelica-ExternalLibrary). It allows you to call Python code from Modelica. With a tool like [Dymola](https://www.3ds.com/products-services/catia/products/dymola/) you can then export an FMU from your model.
