### ISSUE TITLE
FMU simulation problems

### ISSUE THREAD

**Issue by piotre13** [CATIA-Systems/FMPy#392]
Good evening, I'm trying to simulate with doStep an FMU for which i want to feed the inputs at each time-step. For now I'm trying to simply simulate it with the command line interface which continues to return "fmi2DoStep failed with status 3.". Instead when using FMU2slave and doStep the traceback add some more details as shown in  the figure

![trouble_FMU](https://user-images.githubusercontent.com/48677314/163185069-8fc36d30-7dc9-4958-9972-2096c5e89387.png)
s
I'm sure there is some error either on how i export the FMU or on how i simulate it, but I'm not understanding what could be the cause, do you have any suggestion?

the FMU I'm trying to simulate is the following one
[RC_building_HeatCool.zip](https://github.com/CATIA-Systems/FMPy/files/8481622/RC_building_HeatCool.zip)
Thanks a lot

**Comment by t-sommer** [comment]
For personal support requests please follow the [contribution guidelines](https://github.com/CATIA-Systems/FMPy/blob/master/docs/contributing.md#using-the-issue-tracker) and ask this question on StackOverflow. If you think this is a bug in FMPy please provide steps to reproduce the problem and re-open.
