### ISSUE TITLE
fmpy.gui run issue 

### ISSUE THREAD

**Issue by frankldm** [CATIA-Systems/FMPy#393]

**Comment by frankldm** [comment]
When I try to run 
# python -m fmpy.gui
I get the error message:
Failed to add logger proxy function. Could not find module 'C:\Python38\lib\site-packages\fmpy\logging\win64\logging.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Failed to add logger proxy function. Could not find module 'C:\Python38\lib\site-packages\fmpy\logging\win64\logging.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Traceback (most recent call last):
  File "C:\Python38\Lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\lib\site-packages\fmpy\gui\__main__.py", line 11, in <module>
    from fmpy.gui.MainWindow import MainWindow
  File "C:\Python38\lib\site-packages\fmpy\gui\MainWindow.py", line 17, in <module>
    from fmpy.gui.generated.MainWindow import Ui_MainWindow
ModuleNotFoundError: No module named 'fmpy.gui.generated.MainWindow'

It seems that the path is C:\Python38\Lib instead of C:\Python38\lib

**Comment by t-sommer** [comment]
Have you installed FMPy directy from the source code?

**Comment by frankldm** [comment]
Yes, i directly install from source code.

**Comment by t-sommer** [comment]
If you install from source you have to build the binaries yourself using the `build_*.py` scripts.

**Comment by frankldm** [comment]
When i try to build_binary.py, the error message is the same. 
Failed to add logger proxy function. Could not find module 'C:\Python38\lib\site-packages\fmpy\logging\win64\logging.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by t-sommer** [comment]
You can use the binaries form the [Python Wheel](https://files.pythonhosted.org/packages/c8/8d/fd0764b8fdc2cd3e142d8849d01228ff0a1f2ef9366139b33df00909d93e/FMPy-0.3.9-py3-none-any.whl) if you have trouble building them yourself. The easiest solution would be to [simply follow the readme](https://github.com/CATIA-Systems/FMPy#installation) and install FMPy from PyPI or Conda.
