### ISSUE TITLE
Set log level

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMPy#397]
At the instanciation of an FMU in fmpy one can select whether to have logging or not.
https://github.com/CATIA-Systems/FMPy/blob/c01eb7b45a8c0542986d6692458f8c81df425587/fmpy/fmi2.py#L97

It would be great to be able to set the log level. Is this already possible today or would this be a new feature?

**Comment by t-sommer** [comment]
You can pass a logger function to `simulate_fmu()` to filter the messages:

```Python
from fmpy import simulate_fmu
from fmpy.fmi2 import fmi2OK


def log_message(environment, instanceName, status, category, message):
    if status == fmi2OK:  # log only status == OK
        print(message.decode('utf-8'))


simulate_fmu(filename='BouncingBall.fmu', logger=log_message, debug_logging=True)
```
