### ISSUE TITLE
install without internet connection?

### ISSUE THREAD

**Issue by EmmanuelChr** [CATIA-Systems/FMPy#40]
Is there a possibility to install the package without needing an interent connection? I have tried all the possible ways to install (apart from PIP) and all have failed due to connect timeouts. I suppose the problem in my case lies in the firewall of the company or in a proxy setting.
What is an aternative to this? Can one download the package and just install it? 
Thanks in advance for any hint.

Emmanuel

**Comment by t-sommer** [comment]
You can install FMPy without an internet connection with PIP by downloading the [latest wheel](https://pypi.org/project/fmpy/#files). Copy it to the target machine and enter

```
pip install --no-deps FMPy-0.2.5-py2.py3-none-any.whl
```
or using Conda by downloading the respective [Conda package](https://anaconda.org/conda-forge/fmpy/files)

```
conda install --no-deps fmpy-0.2.5-py36_0.tar.bz2
```

Depending on your use case you might need [additional packages](https://github.com/CATIA-Systems/FMPy/blob/master/docs/install.md#required-packages). The [Anaconda distribution](https://www.anaconda.com/download/) contains most of these packages out-of-the-box.

**Comment by EmmanuelChr** [comment]
Hello, 

thanks a lot for the quick respond. I've tried both. They seemde to work. Now I cannot check if everything is OK. What I do is to try to start the GUI (python -m fmpy.gui). This doesn't work, I get the following messages on the console: 

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fmpy\gui\__main__.py", line 16, in <module>
    from fmpy.gui.generated.MainWindow import Ui_MainWindow
  File "C:\ProgramData\Anaconda3\lib\site-packages\fmpy\gui\generated\MainWindow.py", line 869, in <module>
    from pyqtgraph import GraphicsLayoutWidget
	ModuleNotFoundError: No module named 'pyqtgraph'

Do you have a clue what the Problem can be? 
If I try to install with dependencies the installation fails due to pathlib. That's where I get the connect timeouts. Is that lib so essential for the gui and all?

**Comment by t-sommer** [comment]
The GUI depends on PyQtGraph available as a [Wheel on PyPI](https://pypi.org/project/pyqtgraph/) and as a [Conda package](https://anaconda.org/anaconda/pyqtgraph)

**Comment by EmmanuelChr** [comment]
Now it works! Thanks a lot again!
