### ISSUE TITLE
Why there is a time delay?

### ISSUE THREAD

**Issue by AlesVojacek** [CATIA-Systems/FMPy#401]
During a co-simulation of an FMU in fmpy (see attached dynPipeFMU_cvode.fmu, fmu_dynPipe_01_csvInput.py, input_massFlow.csv), the input signal is delayed by one time step. So do the resulted variables.

When running the model-exchange with CVode solver in fmpy (dynPipeFMU_ME.fmu, fmu_dynPipe_01_csvInput_ME.py, input_massFlow.csv), the input signal is not delayed, however the resulted variables are delayed by 2 time step.

I do not see any delays when I simulate both FMUs (co-simulation and model exchange) in Dymola.

Is this an issue of fmpy? Or can be the time delays in fmpy of co-simulation and model exchange be explained?
 
[dynPipeFMU.zip](https://github.com/CATIA-Systems/FMPy/files/8796406/dynPipeFMU.zip)

**Comment by t-sommer** [comment]
This is an inherent property of FMI for Co-Simulation. From the [FMI Specification](https://fmi-standard.org/docs/3.0-dev/#fmi-for-co-simulation):

> In the time between two communication points (or between entering [Intermediate Update Mode](https://fmi-standard.org/docs/3.0-dev/#IntermediateUpdateMode)), the subsystem inside an FMU is solved independently by internal means. This leads to a delay for information "traveling through" the FMU, so there cannot be an immediate reaction (direct feedthrough) as in [Initialization Mode](https://fmi-standard.org/docs/3.0-dev/#InitializationMode), [Event Mode](https://fmi-standard.org/docs/3.0-dev/#EventMode) or [Continuous-Time Mode](https://fmi-standard.org/docs/3.0-dev/#ContinuousTimeMode) of Model Exchange. The co-simulation algorithm of the importer controls the data exchange and the synchronization between FMUs.

**Comment by t-sommer** [comment]
see also #89
