### ISSUE TITLE
parameter_variation.py - Key Error: 'VAC'

### ISSUE THREAD

**Issue by stpilks99** [CATIA-Systems/FMPy#406]
Hi, when running parameter_variation.py (latest develop branch) with Rectifier.fmu in a Linux environment (Python notebook):

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [7], in <cell line: 197>()
    194     return LOSSES
    197 if __name__ == '__main__':
--> 199     run_experiment()

Input In [7], in run_experiment(show_plot)
    136 fmu_args = {'guid': model_description.guid,
    137             'modelIdentifier': model_description.coSimulation.modelIdentifier,
    138             'unzipDirectory': unzipdir}
    140 # get the value references for the start and output values
--> 141 start_vrs = [vrs['VAC'], vrs['IDC']]
    142 result_vrs = [vrs['uDC'], vrs['Losses']]
    144 indices = list(np.ndindex(I_DC.shape))

KeyError: 'VAC'
```

If you print the `vrs` dictionary before running the `start_vrs` line it shows the following:

`{'internalTime': 0, 'outputs': 1, 'Rectifier1.Capacitor2.v': 2, 'Rectifier1.iAC[2]': 3, 'Rectifier1.iAC[3]': 4, 'Rectifier1.IdealDiode1.s': 5, 'Rectifier1.IdealDiode2.s': 6, 'Rectifier1.IdealDiode3.s': 7, 'Rectifier1.IdealDiode4.s': 8, 'Rectifier1.IdealDiode5.s': 9, 'Rectifier1.IdealDiode6.s': 10, 'Rectifier1.IdealDiode4.p.i': 11, 'Rectifier1.IdealDiode5.p.i': 12, 'Rectifier1.IdealDiode6.p.i': 13, 'Rectifier1.Inductor2.v': 14, 'Rectifier1.Inductor3.v': 15, 'Rectifier1.SineVoltage1.p.v': 16, 'Rectifier1.SineVoltage2.p.v': 17, 'Rectifier1.SineVoltage3.n.v': 18, 'Rectifier1.SineVoltage3.p.v': 19, 'Rectifier1.IdealDiode1.off': 20, 'Rectifier1.IdealDiode2.off': 21, 'Rectifier1.IdealDiode3.off': 22, 'Rectifier1.IdealDiode4.off': 23, 'Rectifier1.IdealDiode5.off': 24, 'Rectifier1.IdealDiode6.off': 25, 'der(outputs)': 26, 'Rectifier1.Capacitor2.v.der': 27, 'Rectifier1.iAC[2].der': 28, 'Rectifier1.iAC[3].der': 29, 'Rectifier_r_30': 30, 'Rectifier_r_31': 31, 'Rectifier_r_32': 32, 'Rectifier_r_33': 33, 'Rectifier_r_34': 34, 'Rectifier_r_35': 35, 'Rectifier_r_36': 36, 'Rectifier_r_37': 37, 'Rectifier_r_38': 38, 'Rectifier_r_39': 39, 'Rectifier_r_40': 40, 'Rectifier_r_41': 41, 'Rectifier_r_42': 42, 'Rectifier_r_43': 43, 'Rectifier_r_44': 44, 'Rectifier_r_45': 45, 'Rectifier_r_46': 46, 'Rectifier_r_47': 47, 'Rectifier_r_48': 48, 'Rectifier_r_49': 49, 'Rectifier_r_50': 50, 'Rectifier_r_51': 51, 'Rectifier_r_52': 52, 'Rectifier_r_53': 53, 'Rectifier_r_54': 54, 'Rectifier_r_55': 55, 'Rectifier_r_56': 56, 'Rectifier_r_57': 57, 'Rectifier_r_58': 58, 'Rectifier_r_59': 59, 'Rectifier_r_60': 60, 'minsamplestep': 61, 'binfilename': 62}`

It seems like there is no parameter called `VAC` in the model so it's causing an error.

**Comment by t-sommer** [comment]
The variable names listed above are not matching the FMU that's meant to be used in this example. If you use your own FMU you have to adapt the variable names.
