### ISSUE TITLE
Limit number of compilation of fmu

### ISSUE THREAD

**Issue by cosmital** [CATIA-Systems/FMPy#408]
It appears that the number of times a fmu can be compiled is limited (around 1050 times) when it was exported from modelica but unlimited when it is exported from dymola. Is there a way to be able to compile fmu produced from modelica a high number of times  (for optimization tasks for instance).
I can give you specific fmu and input files but we have tried on very simple ones and the issue always raises after 1052 iteration of the function:
fmpy.simulate_fmu(
            filename=fmu_filename,
            relative_tolerance = 1e-4,
            start_time=0,
            stop_time= 3600,
            solver='CVode',
            output_interval= 3600,
            input = ,
            output= 
            )

Thank you for your help,
Cosme

**Comment by cosmital** [comment]
you can find the error [https://github.com/cosmital/fmu_bug.git](here)

**Comment by cosmital** [comment]
you can find the error [here](https://github.com/cosmital/fmu_bug.git)

**Comment by t-sommer** [comment]
This seems to be a limitation of the FMU. Please open an issue on https://github.com/OpenModelica/OpenModelica/issues.
