### ISSUE TITLE
Setting start_values doesn't work

### ISSUE THREAD

**Issue by mroehrl** [CATIA-Systems/FMPy#414]
Hi everyone,

I'm simulating this FMU and want to change some parameter with the keyword "start_values" .  Unfortunately it doesn't work and the output is always the same, although it seems that the parameter is set accordingly.

`filename='Therm.fmu'
simulate_fmu(filename, start_values = {'sens.port.T': T_amb[0], 'TYR.mass.C': 1000}, output=['TYR.mass.C'], output_interval=0.1, stop_time=600, fmi_call_logger=print)`

Here's the FMU: [Therm.zip](https://github.com/CATIA-Systems/FMPy/files/9160335/Therm.zip)

Anybody knows what's the reason for this?
Many thanks in advance!

**Comment by t-sommer** [comment]
`sens.port.T` is an internal variable. Setting it causes undefined behavior.

**Comment by mroehrl** [comment]
> `sens.port.T` is an internal variable. Setting it causes undefined behavior.

Thanks for the quick reply! I have a follow up question:

`sens.port.T` is the initial temperature of my simulation and the only parameter which I'm able so set and see the change in the output. Actually all the other parameters can't be set, also if I don't change `sens.port.T`. Do you why is that?

**Comment by t-sommer** [comment]
This seems to be a limitation of the model. Please contact your tool vendor for support.
