### ISSUE TITLE
FMU 1.0 on Raspberry pi

### ISSUE THREAD

**Issue by RasPiTool** [CATIA-Systems/FMPy#42]
Hello,
Thanks for FMPy.
Is it possible to simulate a FMU 1.0 on Raspi. I have tried it and i get an error.

**Comment by t-sommer** [comment]
It's possible to simulate an FMI 1.0 FMU on a Raspberry PI. However you'll have to make sure that the binary (in binaries/linux32) is compiled for the correct platform (in this case [ARM](https://en.wikipedia.org/wiki/Raspberry_Pi#Processor)).

For FMI 2.0 source FMUs you can conveniently [compile the binary directly on your Raspberry PI](https://github.com/CATIA-Systems/FMPy/wiki/RaspberryPi).
