### ISSUE TITLE
model_description.py typeDefinitions Fail to Support Enumerations

### ISSUE THREAD

**Issue by jpkauffman** [CATIA-Systems/FMPy#43]
There is a comment in the model_description.py file that notes:
#TODO: add enumeration items

While at first glance this appears to be a relatively insignificant feature, it would absolutely be a benefit to users if it could be added. 

As an example, I am working on a tool to run FMUs within Python using FMPy, and then present the results to a user who may not be familiar with the code/architecture of the FMU. To provide clear results to the user, it is important to be able to display enumeration values not only as their integer values but also as their 'name' or 'description' strings so that the user gains insight.

I am still just learning Python or I would try to tackle this problem myself, but I would appreciate if you have the time to work at this feature.

Thank you,
Justin

**Comment by t-sommer** [comment]
I've added the enumeration items to the model description and a [unit test](https://github.com/CATIA-Systems/FMPy/blob/feature/type_defintions/tests/test_type_definitions.py) that shows how to use it.
Let me know if it works for you.
