### ISSUE TITLE
export ME fmu's + sundials CVODE solver as new CS fmu's from FMPy?

### ISSUE THREAD

**Issue by githubfrond** [CATIA-Systems/FMPy#436]
PROBLEM:
In our particular toolchain, we have not be able to produce reliable co-simulation (CS) fmu's from our modelling tool. We can, however, produce good model-exchange (ME) fmu's. 

A CS fmu is needed so that we can either:
1. use it in our real-time toolset (using fmi-adapter for ROS), or
2. be able to write our own custom Python script around the doStep method and include it in a node for ROS.

QUESTION:
Since we can produce very reliable simulations by coupling our ME fmu's to your CVODE solver in FMPy, we would like to know if there is any **existing** way we can export these ME fmu's + CVODE solver as CS fmu's from FMPy? Or are there examples of coupling something like the Python doStep to use an ME fmu?

Thanks again for your wonderful toolset!

**Comment by t-sommer** [comment]
You can add a Co-Simulation wrapper to an FMI 2.0 Model Exchange FMU with [add_cswrapper()](https://github.com/CATIA-Systems/FMPy/blob/main/fmpy/cswrapper/__init__.py#L3) or by selecting `Tools > Add Co-Simulation Wrapper` in the GUI.

**Comment by rubix18** [comment]
Noting that the add_cswrapper() function results in a hybrid CoSimulation and Model Exchange FMU, are you able to advise on subsequent steps to produce a pure CoSimulation FMU (removing the Model Exchange references all together?)

**Comment by githubfrond** [comment]
@t-sommer will have a more authoritative response than I do :-), but I think I looked at the resulting zip folder .fmu and just removed everything but the .so and the .xml files. I may have had to edit the .xml too, I can't remember.  If you can produce a pure CS fmu from openmodelica, you can see what files are needed, and what the .xml says, and edit appropriately whatever you produce from the cswrapper.  But, as I said, @t-sommer will have a better answer I'm sure!

**Comment by t-sommer** [comment]
What would be the benefit of removing the Model Exchange interface?
