### ISSUE TITLE
Output time TOUT is equal to starting time T

### ISSUE THREAD

**Issue by FWuellhorst** [CATIA-Systems/FMPy#437]
Hello,

I am getting an error in an FMU from Dymola (binary export):
```
Output time TOUT is equal to starting time T (=3.000000e+01).
This is not allowed for the used integrator. Other integrators
may support T=TOUT on the first call.
```
I call doStep in the fmi2 instance with 1 s steps and a tolerance of 0.001. 
The stop time is inf.

I can't upload the FMU due to industry secrets, but wanted to better understand how and why this error occurs, and how to fix it.

Do you have any idea?

**Comment by FWuellhorst** [comment]
Yes. Also, it works under windows. Simulate_fmu() works for both linux and windows. 
One difference to simulate_fmu() is that with the doStep, inputs are send over an IoT plattform, leading to slightly time-shifted inputs.

**Comment by t-sommer** [comment]
This seems to be an issue with your code. Please follow [our issue guidelines](https://github.com/CATIA-Systems/FMPy/blob/main/docs/contributing.md#using-the-issue-tracker) and ask this question on StackOverflow.

**Comment by FWuellhorst** [comment]
For your information: The error was introduced due to another thread writing on the FMU while doing the step. In my opinion this could be avoided in fmpy / fmu by using some sort of lock and then raise a more meaningful error message.
