### ISSUE TITLE
simulate_fmu status error 3 using Matlab FMU

### ISSUE THREAD

**Issue by Ferus-TUB** [CATIA-Systems/FMPy#443]
Hey everyone,

I am simulating a matlab fmu using `simulate_fmu` in co-simulation by calling it with:

`resulst2 = simulate_fmu(filepath+filename , start_values = setdic , input = signals, stop_time=signals['time'][-1], output_interval=20)`

It works when `stop_time` is fairly small but when I increase it to lets say 50 sec or higher I get an exception `FMICallException('fmi2DoStep failed with status 3 (error).')` at the end of the simulation. It triggers it only in the last simulation step.

First I thought it had something to do with the `output_interval` so I changed it in a way that the else-Statement of 
`if time + output_interval <= stop_time:` wouldn't be triggered but that didn't change anything.
I'm frustrated because I cannot find the issue here. Is this a FMPy issue or an Matlab FMU issue and if so how can I fix it.

I'm running fmpy version 0.3.7 and Matlab 2020b.

Thanks a lot in advance. 

PS: I can't share the FMU-file for security reasons
Edit: Some more detailed information.

**Comment by t-sommer** [comment]
Can you reproduce the problem with a simple model you can share?

**Comment by Ferus-TUB** [comment]
Yes I can reproduce the error using the following code and alternative model by running it in co-simulation with matlab.
[Ventilschiebermodell.zip](https://github.com/CATIA-Systems/FMPy/files/9443320/Ventilschiebermodell.zip)

For co-simulation in Matlab you need to use this tool included in a lot matlab version (e.g. 2020b):
https://de.mathworks.com/help/simulink/ug/export-model-as-tool-coupling-fmu.html#mw_636622ca-e837-448f-b40f-303d2c29af1f

**Comment by t-sommer** [comment]
Can you simulate with `simulate_fmu(..., fmi_call_logger=print)` and share the output?

**Comment by Ferus-TUB** [comment]
The print was:

`fmi2GetReal(component=0x17569bce280, vr=[1, 2, 3], nvr=3, value=[0.0, 0.0, 0.0]) -> OK`
`fmi2SetReal(component=0x17569bce280, vr=[0], nvr=1, value=[0.0]) -> OK`
`[OK] Simulation terminated by Simulink slave.`

`fmi2DoStep(component=0x17569bce280, currentCommunicationPoint=80.0, communicationStepSize=20, `
`noSetFMUStatePriorToCurrentPoint=1) -> ERROR `

**Comment by t-sommer** [comment]
The FMU returns `fmi2Error` without providing a reason. Please contact the MATLAB support if you think this is a bug in the FMU.
