### ISSUE TITLE
Clarification on behaviour of output_interval

### ISSUE THREAD

**Issue by peppermintcoding** [CATIA-Systems/FMPy#456]
Hi all,

while testing some models I have encountered a weird behaviour and would love some clarification about the variable output_interval.

I tested letting my model run for 9000s with an Output Interval of 1 and get the correct result, but if I change the interval to 10 or just randomly higher it produces extremely implausible results.

The correct output with: Output Interval = 1, StopTime = 9000 (using the FMPY GUI)
![image](https://user-images.githubusercontent.com/58445479/191956220-2197bb5f-f8f4-4adb-94e2-eb483291fcff.png)

The wrong output with: Output Interval = 10, StopTime = 9000 (using the FMPY GUI)
![image](https://user-images.githubusercontent.com/58445479/191956433-60fb4f67-5c9e-4bb2-b093-7079c3aa60e8.png)

My question now is, what does Output Interval actually do and how do you know what value it should have for any FMU Model?

Data for Testing:
[Test.csv](https://github.com/CATIA-Systems/FMPy/files/9633442/Test.csv)

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by peppermintcoding** [comment]
Of course, thought it was already included.

[simple.zip](https://github.com/CATIA-Systems/FMPy/files/9643845/simple.zip)

**Comment by t-sommer** [comment]
> what does Output Interval actually do

With the `output_interval` option you can control the time steps where the FMU is sampled:

```python
import fmpy
from fmpy import *

filename = 'simple.fmu'

input = read_csv('Test.csv')

result = simulate_fmu(filename, output=['y'], stop_time=9000, output_interval=10, input=input)
result['time'][0:10]
```

```
SimulationResult([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])
```

```python
result = simulate_fmu(filename, output=['y'], stop_time=9000, output_interval=1, input=input)
result['time'][0:10]
```

```
SimulationResult([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
```
> I have encountered a weird behaviour

For issues with OpenModelica models, please open an issue on https://github.com/OpenModelica/OpenModelica.
