### ISSUE TITLE
After standard installation in Windows - can not start jupyter notebook

### ISSUE THREAD

**Issue by janpeter19** [CATIA-Systems/FMPy#457]
Following your instruction for installation of FMPy using conda and I choose Python 3.9.13.
Started the GUI an loaded a FMU and run it successfully.
Created a Jupyter notebook test.ipynb successfully.
Closed the gui.
Terminal command jupyter notebook test.ipynb
Get the error text: "Jupyter command 'jupyter-notebook' not found.
(And of course I did not use any "-" sign between jupyter and notebook but still I get this error text)

I also not by the command conda list that jupyter is not instllaed but jupyter_core is.
What to do? Install jupyter (again)?

**Comment by t-sommer** [comment]
Did you try the solutions proposed in https://stackoverflow.com/questions/35313876/after-installing-with-pip-jupyter-command-not-found?

**Comment by janpeter19** [comment]
I just installed jupyter, using conda as for everything else, and works.

**Comment by t-sommer** [comment]
When installing via pip you have different options. To install the dependencies for Jupyter notebooks use `pip install fmpy[notebook]` or `pip install fmpy[complete]`.
