### ISSUE TITLE
How to get the value of a parameter in an FMU?

### ISSUE THREAD

**Issue by janpeter19** [CATIA-Systems/FMPy#458]
I begin to use FMPy and have studied to some extent the examples given in the documentation for FMPy.

How do I get a value of parameter of the model?

   from fmpy import read_model_description
   fmu_filename = 'my_model.fmu'
   model_description = read_model_description('my_mode..fmu')
   parameters = [v for v in model_description.model.modelVariables if v.causality == 'parameter']

However parameters is just a list of names and other properties but no values.
What should I do?

**Comment by t-sommer** [comment]
The start value of the `ScalarVariable` is stored in the field `start`.
