### ISSUE TITLE
Changing tolerance of a CS FMU?

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMPy#46]
When simulating a 2.0 CS FMU, the `relative_tolerance` argutment of `simulate_fmu` is not used (this parameter is only currently intended for the CVODE Solver of ME FMUs):
in https://github.com/CATIA-Systems/FMPy/blob/d266f17694a62e624218814025aa2223b5e119d8/fmpy/simulation.py#L510, no tolerance is passed to a CS FMU. 

Do I understand https://github.com/CATIA-Systems/FMPy/blob/d266f17694a62e624218814025aa2223b5e119d8/fmpy/simulation.py#L726 right, that even a tolerance present in the default experiment of an FMU is ignored and overwritten by `none`?

It would be good, if it were possible to set the tolerance for simulating a 2.0 CS FMU explicitly, perhaps be using the `relative_tolerance` parameter currently only used for ME FMUS with CVODE.

**Comment by t-sommer** [comment]
The `--relative-tolerance` parameter will now be forwarded to FMI 2.0 co-simulation FMUs as well. Thanks for your help @chrbertsch!
