### ISSUE TITLE
How to get simulation results  for variables that are not state variables?

### ISSUE THREAD

**Issue by janpeter19** [CATIA-Systems/FMPy#460]
I see that results from results = simulate_fmu(...) brings time series of the continuous time state variables. How do I get out times series of other variables?

I see that model_description.modelVariables bring information about variables, constants and parameters. Also the variables I want, but I do not see how to get out the time series. How do I address these?

If there is some text that describes FMPy it would be good.

**Comment by t-sommer** [comment]
You can record any set of variables using the [output parameter](https://github.com/CATIA-Systems/FMPy/blob/main/fmpy/simulation.py#L631):

```Python
result = simulate_fmu(..., output=['variable_a', 'variable_b'])
```
