### ISSUE TITLE
How to determine if a "modelVariable" in model_description is a constant and not a variable?

### ISSUE THREAD

**Issue by janpeter19** [CATIA-Systems/FMPy#462]
I get more and more used to FMPy and handling the interaction through model_description.

Here is a difference between parameters and all other "variables" in model_description reported in the field causality which I find in my FMUs have only two values "parameter" and "local". I wish "constants" had a separate value here, but that is not  the case. Is there some other way to figure out that a "variable" is declared as a constant in the Modelica code?

The difficulty may also be related to what compiler is used and I use mainly JModelica so far.

**Comment by t-sommer** [comment]
`constant` is a [variability](https://fmi-standard.org/docs/3.0/#variability) not a causality.

In the future, please follow [our community guidelines](https://github.com/CATIA-Systems/FMPy/blob/main/docs/contributing.md#using-the-issue-tracker) and ask these kinds of questions on StackOverflow.
