### ISSUE TITLE
fmpy GUI save changes button is not working

### ISSUE THREAD

**Issue by achenbachsven** [CATIA-Systems/FMPy#464]
I tried multiple times to save parameter value changes on the .fmu file by using the button "Save Changes", but the changes never happends.

Would it be possible to solve this in a next version.

Best wishes
Sven

**Comment by t-sommer** [comment]
The only legal way to change the start values of an existing FMU is to wrap it, e.g. with [create_fmu_container()](https://github.com/CATIA-Systems/FMPy/blob/main/fmpy/fmucontainer/__init__.py#L66).

Closing in favor of #467.
