### ISSUE TITLE
Re-add sources to Container FMUs

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMPy#471]
in previous versions of fmpy, when a FMUContainer was created, the FMUContainer.c and mpack.c were stored in the resources files. 
This was very useful to recompile FMUContainers whenever the sources of the subordinate FMUs were available. 
As far as I can see now. These resources are not included anymore in the resources folder. 
Only the resources of the subordinate FMUs are there.
We would very much would like / need  to have the old functionality back. 
Or maybe there is a new way to do it?

**Comment by t-sommer** [comment]
The binaries of the Container FMU are generic. Can you share your reason for re-compiling them?

**Comment by jbernalr** [comment]
@t-sommer I have a target that supports only a specific glibc version. Therefore I need a specific compiler version and environment. This was working great in the past and I have several applications for it.

**Comment by jbernalr** [comment]
@t-sommer thanks I will give this a try today

**Comment by jbernalr** [comment]
hi @t-sommer I can confirm that the sources are now there. However, if you try to recompilate the FMUContainer in Windows errors pointing to mpack come out (see below). I think its related to the 'inline' flags when compiling with visual studio but I may be wrong. I attach such an fmu that cannot be compiled under the current develop wheel-fmpy and also not the released version. 

```
FMI.c
FMI2.c
FMUContainer.c
mpack-common.c
mpack-expect.c
mpack-node.c
mpack-platform.c
mpack-reader.c
mpack-writer.c
mpack-writer.c(67) : error C2054: expected '(' to follow 'inline'
mpack-writer.c(67) : error C2085: 'mpack_writer_track_element' : not in formal parameter list
mpack-writer.c(67) : error C2143: syntax error : missing ';' before '{'
mpack-writer.c(1366) : error C2054: expected '(' to follow 'inline'
mpack-writer.c(1366) : error C2085: 'mpack_builder_check_sizes' : not in formal parameter list
mpack-writer.c(1366) : error C2143: syntax error : missing ';' before '{'
mpack-writer.c(1402) : error C2054: expected '(' to follow 'inline'
mpack-writer.c(1402) : error C2085: 'mpack_builder_page_size' : not in formal parameter list
mpack-writer.c(1402) : error C2143: syntax error : missing ';' before '{'
mpack-writer.c(1413) : error C2054: expected '(' to follow 'inline'
mpack-writer.c(1413) : error C2085: 'mpack_builder_align_build' : not in formal parameter list
mpack-writer.c(1413) : error C2143: syntax error : missing ';' before '{'
mpack-writer.c(1421) : error C2054: expected '(' to follow 'inline'
mpack-writer.c(1421) : error C2085: 'mpack_builder_free_page' : not in formal parameter list
mpack-writer.c(1421) : error C2143: syntax error : missing ';' before '{'
mpack-writer.c(1432) : error C2054: expected '(' to follow 'inline'
mpack-writer.c(1432) : error C2085: 'mpack_builder_page_remaining' : not in formal parameter list
mpack-writer.c(1432) : error C2143: syntax error : missing ';' before '{'
```
