### ISSUE TITLE
QUESTION: is it possible to open a FMPy created jupyter notebook from any operating-system?

### ISSUE THREAD

**Issue by ubaldot** [CATIA-Systems/FMPy#476]
This is not an issue but a question - sorry I could not find anywhere to ask. 

Say that I have an FMU created under Win10 and that I create a jupyter notebook out it, as described in the readme file.
I am wondering if such a notebook (which I assume it includes the FMU that can be simulate with different inputs and configurations) can be used from any OS or if it will work only with Win10.

**Comment by t-sommer** [comment]
The notebook should work on any platform that is supported by the FMU. If the FMU contains source code you can compile it on the target platform.
