### ISSUE TITLE
Simply simulate with custom input?

### ISSUE THREAD

**Issue by ubaldot** [CATIA-Systems/FMPy#477]
Hello!

I am wondering if there is a way to simply simulate (with no gui) the response of an `fmu` in front of a certain input. 
I have seen that there is an example, but there is a while loop to scan all the time steps, that I wish to avoid that and having something like

`y = some_simulation_function(fmu_filename, t_start, t_stop, t_step, initial_condition, u)`

where **u** is a `numpy `array of dumension _pxN_ where _p_ is the number of input and _N_ is the number of realizations and **y** is a _qxN_  `numpy `array, where _q_ is the output dimension?

**Comment by t-sommer** [comment]
Take a look at https://github.com/CATIA-Systems/FMPy/blob/main/fmpy/examples/coupled_clutches.py. The argument `input` can also be created programmatically (see https://github.com/CATIA-Systems/FMPy/blob/main/fmpy/simulation.py#L205).
