### ISSUE TITLE
How to acccess the ssp-standard-dev repository referenced by test_ssp.py?

### ISSUE THREAD

**Issue by ForrestTrepte** [CATIA-Systems/FMPy#478]
[tests\test_ssp.py](https://github.com/CATIA-Systems/FMPy/blob/450000dffaf22918334d1d47abd0edf29916dfdb/tests/test_ssp.py#L11), says `"Environment variable SSP_STANDARD_DEV must point to the clone of https://github.com/modelica/ssp-standard-dev"`.

I wasn't able to access https://github.com/modelica/ssp-standard-dev. GitHub says `Page not found`. Has it been moved or removed? Or is special "dev" access required in order to use it?

**Comment by chrbertsch** [comment]
> [tests\test_ssp.py](https://github.com/CATIA-Systems/FMPy/blob/450000dffaf22918334d1d47abd0edf29916dfdb/tests/test_ssp.py#L11), says `"Environment variable SSP_STANDARD_DEV must point to the clone of https://github.com/modelica/ssp-standard-dev"`.
> 
> I wasn't able to access https://github.com/modelica/ssp-standard-dev. GitHub says `Page not found`. Has it been moved or removed? Or is special "dev" access required in order to use it?

This is currently a private repository of the SSP Project

**Comment by ForrestTrepte** [comment]
Thanks for explaining, @chrbertsch. By the way, I am having difficulty finding public examples and test cases for SSPs. As the standard matures, hopefully more material like this will be become public.

**Comment by chrbertsch** [comment]
> Thanks for explaining, @chrbertsch. By the way, I am having difficulty finding public examples and test cases for SSPs. As the standard matures, hopefully more material like this will be become public.

@ForrestTrepte: I agree that missing publicly available examples for SSP are hindering the adoption of this standard.

You can ask map-ssp_projectlead@googlegroups.com for access to the ssp-dev repository; signing the Modelica Asscoiation CLA might be necessary.

In the meantime, you can create SSP examples with the freely available easySSP and OMSimulator tools, see https://ssp-standard.org/tools/
In the context of a traceability extension of SSP  you can find an example here: https://github.com/PMSFIT/SSPTraceability/blob/master/examples/TraceabilityDemo.ssp
