### ISSUE TITLE
Global sensitivity analysis in Python after exporting from Dymola

### ISSUE THREAD

**Issue by Amuntaseer** [CATIA-Systems/FMPy#48]
Is it possible to perform Global Sensitivity Analysis in Python after exporting the model from Dymola to Python using FMPy? I want to see the effect of different Parameters and the correlation between them.

**Comment by t-sommer** [comment]
You could start with the [parameter_variation.py](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/parameter_variation.py) example and adapt it to your use case.
