### ISSUE TITLE
No structured naming convention possible in FMUContainer

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMPy#483]
when two fmus inside a fmu container have a variable with the same name. Lets say: 

instance1
- temperature1
- other variables

instance2
- temperature1
- more variables

The Container's xml will have two entries with the same variable name (different VRs). 
Even if I set `variableNamingConvention="structured"` in `Configuration` the variables wont be prefixed with the instance name. 
In previous version this was the case. The variable names in in the xml would be

```
instance1.temperature1
instance2.temperature1
```

I tested this with the current develop version (wheel file)

**Comment by fajansen** [comment]
That depends on how you configure the container. You can control the names completely yourself. To follow your example:
variables=[Variable(
        type='Real',
        variability='continuous',
        causality='output',
        initial='calculated',
        name='instance1.temperature1',
        mapping=[('instance1', 'temperature1')]
     ),
     Variable(
        type='Real',
        variability='continuous',
        causality='output',
        initial='calculated',
        name='instance2.temperature1',
        mapping=[('instance2', 'temperature1')]
     )]

**Comment by jbernalr** [comment]
@fajansen I think the default behaviour should produce a valid fmu in the first place. 
I don't see the renaming of the variables as a means to fix or get a valid fmu.
This was already the case in the first version of the fmu container. 0.2.26
Besides, I guess this is also the expected behaviour according to the implementation. see the 'variableNamingConvention' property.

**Comment by fajansen** [comment]
@jbernalr  What do you mean with default behaviour? There is no default naming for the variables, you always have to specify a name and a mapping in your own code.

**Comment by jbernalr** [comment]
> @jbernalr What do you mean with default behaviour? There is no default naming for the variables, you always have to specify a name and a mapping in your own code.

@fajansen yes, its clear (before in 0.2.26 and now) you need to specify the names of the variables. But you did not have to state the obvious before in the "name", i.e. that a variable belongs to a certain instance.

This is redundant since In mapping, this information was already defined like: 

```mapping=[('instance2', 'temperature1')]```

In example above, to have a valid fmu, one needs to set names prefixed by the instance name or whatever else that produces unique variable names:

Container-declaration: 
- name='instance1.temperature1
- name='instance2.temperature1

The ideal behaviour would be that if you let ```name``` empty, your variables in the xml will be named: 
- instance2.temperature1 
automatically, since as I mentioned above, you have this information in the mapping. 

If you have FMUs with thousands of variables, this makes a great difference.

See also #481 which is related to this.

**Comment by t-sommer** [comment]
As @fajansen mentioned above this behavior is intended to provide maximum flexibility. This allows e.g. to map an input or parameter of the container to multiple nested FMUs. The naming convention of the container is always `structured`.
