### ISSUE TITLE
cannot run 32bit fmi on my windows 64bits

### ISSUE THREAD

**Issue by flochocinco** [CATIA-Systems/FMPy#49]
Everything in the title. It seems important for me to be able to run 32 bits fmu on windows 64bits (most common OS)

**Comment by t-sommer** [comment]
You need a 32-bit Python to run 32-bit FMUs. On Windows you can install a 32-bit [Anaconda](https://www.anaconda.com/download/#windows) or create a 32-bit Conda environment using `set CONDA_FORCE_32BIT=1` as described in [hacking FMPy](https://fmpy.readthedocs.io/en/latest/hacking/#setup-your-python-environment).
