### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AHaumer** [CATIA-Systems/FMPy#496]
Maybe I just don't find it: I'm missing a documentation which routines with which parameters are available to load and simulate FMUs if I'm developing some own Python routines.

**Comment by t-sommer** [comment]
FMPy exposes the full FMI API for all versions and interface types. Take a look at https://github.com/CATIA-Systems/FMPy/blob/main/fmpy/examples/custom_input.py for an example of a custom simulation loop that uses FMI 2.0 for Co-Simulation.
