### ISSUE TITLE
Visible results in fmpy.gui

### ISSUE THREAD

**Issue by AHaumer** [CATIA-Systems/FMPy#497]
I'd like to provide FMUs as BlackBox for students.
I tried two approches to hide parameters and results in fmpy.gui:

- I did declare these parameters and results I'd like to hide as protected before exporting the FMU: No effect, they're shwon.
- Use Dymola's dialog to choose which variables should be exported: Yes there's some effect but not really the expected. 
The "not exported" variables are shown as "concealedxx" and if you tick such one for plotting, something is plotted and you might guess which variable is plotted. Why not hide them completeley?

**Comment by t-sommer** [comment]
> * I did declare these parameters and results I'd like to hide as protected before exporting the FMU: No effect, they're shwon.

This is the expected behavior.

> * Use Dymola's dialog to choose which variables should be exported: Yes there's some effect but not really the expected.
>   The "not exported" variables are shown as "concealedxx" and if you tick such one for plotting, something is plotted and you might guess which variable is plotted. Why not hide them completeley?

This is a limitation of the FMU. Please contact the Dymola support if you have suggestions for improvements.

A possible solution would be to remove the variables manually or with a script from the `modelDescription.xml`.
