### ISSUE TITLE
Incomplete path to fmuResourceLocation

### ISSUE THREAD

**Issue by kevin-kaspar** [CATIA-Systems/FMPy#5]
fmi2Instantiate is called with the wrong path for the fmuRessourceLocation,
since self.fmuLocation points to the unzipped FMU, but the fmuRessourceLocation should point to the resources directory of the unzipped FMU.

# fmi2.py
`self.component = self.fmi2Instantiate(self.instanceName.encode('utf-8'),
									  kind,
									  self.guid.encode('utf-8'),
									  self.fmuLocation.encode('utf-8'), # fix e.g.: + b'/resources'
									  byref(callbacks),
									  visible,
									  loggingOn)
`

**Comment by t-sommer** [comment]
Fixed in 93151d0ed8425268f9f41404b3d998b4f590f1e2
