### ISSUE TITLE
Issues with GUI on Mac "dark mode"

### ISSUE THREAD

**Issue by Maplesoft-fmigroup** [CATIA-Systems/FMPy#510]
@t-sommer  Version 0.3.14 looks fine in regular mode but buttons are not visible in "dark mode" (see attached screen shot).
<img width="1087" alt="FMPy_3_14" src="https://user-images.githubusercontent.com/33963250/211639953-5ba37a73-bd11-478c-b7ad-e5d2005ef4b9.png">

**Comment by bekcpear** [comment]
As a workaround, edit the generated `path/to/site-packages/fmpy/gui/generated/MainWindow.py` file, replace the  all color code `255, 255, 255` in the first few lines with a dark color, such as `13, 17, 23`.

Although it still looks tired, the content can be recognized now.

**Comment by t-sommer** [comment]
Fixed with f2762a7686f04deec18704dab7c905c0e3c51e06.
