### ISSUE TITLE
FMU file import error using FMPy

### ISSUE THREAD

**Issue by luckyluke023** [CATIA-Systems/FMPy#511]
Hi, everyone.
an error happens when I am using FMPy to import a FMU file which is generated by ANSYS ROM. My steps are as follows:
1, Using 3D ROM function in Ansys Workbench to export a FMU file and name this FMU file as "TEST.fmu" for example;
2, Start FMPy GUI using "python -m fmpy.gui" and open this fmu file, but an error happens, showed as following.
![image](https://user-images.githubusercontent.com/33722491/212235060-f4f408a6-f34b-49e7-a08a-165421cd0fa9.png)
Can any one tell me how to fix this problem.

**Comment by t-sommer** [comment]
The FMU is not FMI compliant because it is using units that are not defined. Please contact your tool vendor for support.
