### ISSUE TITLE
gui license ?

### ISSUE THREAD

**Issue by jschueller** [CATIA-Systems/FMPy#512]
the gui part uses PyQt, and the license text does not reflect the GPL
our users were tricked into believing they can redistribute derived works of fmpy into BSD
seems you need a dual license BSD/GPL for this

**Comment by t-sommer** [comment]
According to https://www.pythonguis.com/faq/pyqt-vs-pyside/ you need a commercial PyQt license if you bundle it with your software and you don't want to ship the source code.

**Comment by jschueller** [comment]
using PySide now
