### ISSUE TITLE
FMI spec violated: setting of constant locals

### ISSUE THREAD

**Issue by s1mahoeg** [CATIA-Systems/FMPy#514]
Hi,

for the last two days I have been struggling with the following problem:
* I change the value of a parameter `p` in my FMU.
* Parameters that depend on parameter `p` are not updated
In the end, I figured out that I made a mistake in the model and the parameter `p` had actually a variability of `constant` and causality of `local`.

Now, however, I'm wondering why it's actually possible to change the value of a `constant local`. According to the FMI specification (in my case 2.0.2, page 51) this is not allowed:
> Variable where the value never changes. Cannot be used in another model.

I have written a small example model to demonstrate this behaviour (`const_local` corresponds to the parameter `p` of my real model):
```modelica
model LocalConstants
  constant Real const = 1;
  parameter Real const_local = const;
  Modelica.Blocks.Sources.RealExpression real_expr(y=const_local);
equation
end LocalConstants;
```

I am able to change the value of each of these variables independently of each other. Attached is my FMU and a test-script to demonstrate it [TestFmpy.zip](https://github.com/CATIA-Systems/FMPy/files/10472193/TestFmpy.zip). What I'm basically doing:
* load the fmu
* initialize the fmu
* change the value of `const` to 10
* simulate (is it actually necessary for the demonstration!?)
* get variable values: `const=10`, `const_local=1`, `real_expr.y=1`
* change the value of `const_local` to 20
* simulate
* get variable values: `const=10`, `const_local=20`, `real_expr.y=1`
* change the value of `real_expr.y` to 30
* simulate
* get variable values: `const=10`, `const_local=20`, `real_expr.y=30`

I think this behaviour is quite dangerous for the user. So far I have only checked if the values I want to change have actually been updated. I only found out by accident that two of my hundred to thousand dependent parameters were not updated, because of my modelling error.

Feature request  / questions:
* Raise an exception if the user tries to change the value of a variable for which this is not allowed according to the FMI specification. If performance is a concern, maybe additional safe-set methods that include this check is an option!?
* I was wondering if the behaviour of my fmu is also questionable. Here, I'm not quite sure how to interpret the FMI spec: Does the FMI spec describe the expected behaviour of fmus (for example, `constant locals` can't be changed) or is it up to the tools implementing the FMI spec that `constant locals` cannot be updated?

**Comment by t-sommer** [comment]
`simulate_fmu()` does not allow you to set constants:

```
>>> from fmpy import *
>>> simulate_fmu('LocalConstants.fmu', start_values={'const': 10})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "x:\y\fmpy\simulation.py", line 758, in simulate_fmu
    result = simulateCS(model_description, fmu, start_time, stop_time, relative_tolerance, start_values, apply_default_start_values, input, output, output_interval, timeout, step_finished, set_input_derivatives, use_event_mode, early_return_allowed, validate, initial
ize, terminate)
  File "x:\y\fmpy\simulation.py", line 1220, in simulateCS
    raise Exception("The start values for the following variables could not be set: " +
Exception: The start values for the following variables could not be set: const
>>>
```

If you write your own simulation loop using the low-level API, you have to perform any checks yourself.

Regarding the behavior of the FMU, please contact the Dymola support.
