### ISSUE TITLE
Webapp does not support FMU's with external tables

### ISSUE THREAD

**Issue by benlandg** [CATIA-Systems/FMPy#515]
I have made a fmu of a map based model which uses an external table. The table is located in the same folder as the fmu. 

The FMPy GUI simulates the model correctly and without issues. 

However the webapp outputs the following code when loaded: 

"Simulation failed. exception: access violation reading 0x0000022AB7F122A8"

**Comment by t-sommer** [comment]
Can you share an FMU to reproduce the problem?

**Comment by benlandg** [comment]
@t-sommer I tried to create a minimal example but the web app seems to work every time as expected except for with this one model.

**Comment by t-sommer** [comment]
The problem is that the FMU is trying to load `ktDrivingCycle_inverse.txt` with a relative path and is expecting it to be in the current working directory. A possible workaround is to use an absolute path or to load the file from the `resources` directory of the FMU.
