### ISSUE TITLE
How to add fmi2SetString to Modelica FMI Package

### ISSUE THREAD

**Issue by vsskanth** [CATIA-Systems/FMPy#519]
I have a Model Exchange FMU 2.0 that works in FMPy but does not initialize in Dymola 2023. So, I am trying to simulate it in Dymola using the FMI Modelica package in fmpy along with the "Import to Modelica" option. However, the FMU i'm using requires a string parameter to be set, but the FMI package does not have any functions to set string parameters (fmi2SetString)

Since the C source code for ModelicaFMI is available, I tried to add this function myself but i've been having issues building it in Visual Studio 2022 using CMake. I am able to generate the project and ModelicaFMI.dll library builds successfully, but when I replace the existing library with the one I built and run the test experiment FMI.Examples.FMI2.ModelExchange.VanDerPol, I get this error

```
Symbol fmi3GetVersion is missing in shared library.
```

I tried to re-build it without any modifications to the source and I still get the same error, so it appears I am missing some configuration in CMake. It would be helpful if we could either have instructions on how to build ModelicaFMI.dll correctly or add the set string functions to the library, it might help me simulate the target FMU

**Comment by t-sommer** [comment]
Can you share the FMU and steps to reproduce the problem?

**Comment by vsskanth** [comment]
The non-working fmu needs a license file so i'm unable to share it, but I've attached a model exchange FMU with a string parameter input, this is what I intend to ultimately achieve. I can actually import this in Dymola directly and it runs fine, so this would be just be to test and see if `fmi2SetString` is working in the FMI package.

[MEFMUTest.zip](https://github.com/CATIA-Systems/FMPy/files/10744158/MEFMUTest.zip)

```modelica
model MEFMUTest "Model with String Parameter"
  extends Modelica.Icons.Example;

  parameter String sInput = "" "String frequency input" annotation(Evaluate=false);
  parameter Modelica.Units.SI.Frequency fCutoff = Modelica.Utilities.Strings.scanReal(sInput);

  Modelica.Blocks.Continuous.LowpassButterworth lowpassFilter(f=fCutoff, initType=Modelica.Blocks.Types.Init.InitialState) annotation (Placement(transformation(extent={{-18,-16},{14,16}})));
  Modelica.Blocks.Interfaces.RealInput u(start=0) annotation (Placement(transformation(extent={{-120,-20},{-80,20}})));
  Modelica.Blocks.Interfaces.RealOutput y annotation (Placement(transformation(extent={{90,-10},{110,10}})));

equation 
  connect(u, lowpassFilter.u) annotation (Line(points={{-100,0},{-21.2,0}}, color={0,0,127}));
  connect(lowpassFilter.y, y) annotation (Line(points={{15.6,0},{100,0}}, color={0,0,127}));
  annotation (
    experiment(
      StopTime=1.5,
      Interval=0.001,
      __Dymola_fixedstepsize=0.001,
      __Dymola_Algorithm="Euler"));
end MEFMUTest;
```

**Comment by t-sommer** [comment]
Thanks for sharing the example. I'm closing this issue in favor of #522.
