### ISSUE TITLE
Getting status back from doStep

### ISSUE THREAD

**Issue by GarronFish** [CATIA-Systems/FMPy#534]
I was working with an old version of FMPy (from about 2 years ago) and found that after updating (on 25/02/2023) that the status returned by doStep are not working in the same way.

previously I had:
```
fmu = fmpy.fmi2.FMU2Slave(guid=model_description.guid,
                unzipDirectory=unzipdir,
                modelIdentifier=model_description.coSimulation.modelIdentifier,
                instanceName='instance1')
status = 0
. . .
status = fmu.doStep(...)
```

This would simulate and status would be set accordingly:

```
# status
# 0 - OK
# 1 - warning
# 2 - discard (status information could not be returned)
# 3 - error (can restart using fmi2SetFMUstate)
# 4 - fatal (re-run program)
# 5 - pending (still busy)
```

However after the last update status is not updated a all it is like the return value has been removed as when I put my cursor on status it shows:
![image](https://user-images.githubusercontent.com/20284436/222708110-5c869519-cba0-4914-8c26-3c553a43183d.png)

How do I get access to the status value?

**Comment by t-sommer** [comment]
You can get the status by calling the low level function directly:

```Python
status = fmu.fmi2DoStep(fmu.component, time, stepSize, fmi2True)
```

**Comment by GarronFish** [comment]
Thanks that works as it did before.
