### ISSUE TITLE
Simulation of Model Exchange FMUs on Raspberry Pi

### ISSUE THREAD

**Issue by RasPiTool** [CATIA-Systems/FMPy#54]
Hello,

I simulated ModelCosimulation on Raspberry Pi and it work's very well. Now I tried to simulate a ModelExchange on Raspberry and it doesn't work.

I used following file /FMI_2.0/ModelExchange/c-code/Dymola/2017/CoupledClutches.fmu

Compilation worked with

`fmpy compile CoupledClutches.fmu
`
By simulation I get some error

```
$ fmpy simulate CoupledClutches.fmu --show-plot
Traceback (most recent call last):
  File "/usr/local/bin/fmpy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/fmpy/command_line.py", line 114, in main
    fmi_call_logger=fmi_call_logger)
  File "/usr/local/lib/python3.5/dist-packages/fmpy/simulation.py", line 507, in simulate_fmu
    result = simulateME(model_description, fmu_args, start_time, stop_time, solver, step_size, relative_tolerance, start_values, apply_default_start_values, input, output, output_interval, record_events, timeout, callbacks, debug_logging, step_finished)
  File "/usr/local/lib/python3.5/dist-packages/fmpy/simulation.py", line 595, in simulateME
    from .sundials import CVodeSolver
  File "/usr/local/lib/python3.5/dist-packages/fmpy/sundials/__init__.py", line 16, in <module>
    sundials_nvecserial = cdll.LoadLibrary(os.path.join(library_dir, 'sundials_nvecserial' + sharedLibraryExtension))
  File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.5/dist-packages/fmpy/sundials/linux32/sundials_nvecserial.so: cannot open shared object file: No such file or directory

```

This is my directory:

```
pi@server:/usr/local/lib/python3.5/dist-packages/fmpy/sundials $ tree
.
├── darwin64
│   ├── sundials_cvode.dylib
│   └── sundials_nvecserial.dylib
├── __init__.py
├── linux64
│   ├── sundials_cvode.so
│   └── sundials_nvecserial.so
├── __pycache__
│   └── __init__.cpython-35.pyc
├── win32
│   ├── sundials_cvode.dll
│   └── sundials_nvecserial.dll
└── win64
    ├── sundials_cvode.dll
    └── sundials_nvecserial.dll
```

I googled to sundials_cvode.so and sundials_nvecserial.so for Linux 32Bit but didn't find it.
How could I solve this problem?

Best regards

**Comment by t-sommer** [comment]
If you want to simulate model exchange FMUs on a Raspberry Pi you have two options:

- use the `Euler` solver (which is implemented in Python)
- compile the necessary shared libraries of the [SUDIALS CVode](https://computation.llnl.gov/projects/sundials) solver for your platform and put them in `fmpy/sundials/linux32` or `linux64` (depending on the bitness of the operating system)

**Comment by t-sommer** [comment]
FMPy expects an older version of the SUNDIALS library. The function `CVDense` has been removed in the newer releases.

**Comment by RasPiTool** [comment]
Thank you very much!
It works great!
I installed sundials version 2.7.0 then `CVDence `funciton is removed after this version.
`https://computation.llnl.gov/projects/sundials/download/sundials-2.7.0.tar.gz`

**Comment by t-sommer** [comment]
@RasPiTool Just out of curiosity: what's you're use-case of model exchange on a Raspberry PI?

**Comment by RasPiTool** [comment]
I am currently writing my master thesis. And my main topic is simulation of FMUs on Raspberry server. So I have to create a server via OPC UA on one Rasperry and Raspberry Pi workers (clients). The server get FMUs and the server sends the FMUs to other Clients (Raspberry Pi workers) to solve it.
