### ISSUE TITLE
Change values for various parameters, start values

### ISSUE THREAD

**Issue by ravitejareddyz** [CATIA-Systems/FMPy#558]
Hi, i have csv from a hex file. I want to import the values from my csv (or hex) as start values for my fmu and save the fmu . how do i do that?

**Comment by t-sommer** [comment]
The start values of an FMU cannot be changed. However you can use a wrapper that has it's own modelDescription.xml (e.g. [FMPy's Container FMU](https://github.com/CATIA-Systems/FMPy/blob/main/tests/test_fmu_container.py)) and sets the start values during initialization.
