### ISSUE TITLE
Output_interval control

### ISSUE THREAD

**Issue by ravikiranbadathala** [CATIA-Systems/FMPy#559]
result = simulate_fmu(plant_path,start_time=0,
            stop_time=stoptime,
            #solver='Cvode',
            step_size=1e-2,
            input=input,
            output_interval = 10,
            debug_logging = True
            ) 

my input contains 9200 instances , where my output contains  9700 instances with output interval 10, how can in make the Simulate_FMU to take exact input with time stamp to give output same time stamp

i.e, if i have 9200 instances with different time steps, simulate_fmu output also will have to be 9200 instances with same time steps

**Comment by t-sommer** [comment]
You can pause and continue your simulation (see https://github.com/CATIA-Systems/FMPy/blob/main/fmpy/examples/continue_simulation.py). 

If you only simulate one step at a time and use the step size of your input signals as the `step_size` and `output_interval` you should get exactly what you're looking for.

**Comment by ravikiranbadathala** [comment]
Thanks for the quick reply,
if my input file has time in yyyy/mm/dd format, is there any way to give same time format as input to simulate fmu, or shall i give time start from zero and later convert the time stamp
