### ISSUE TITLE
How to stop simulation when it reaches steady state (question)

### ISSUE THREAD

**Issue by ravikiranbadathala** [CATIA-Systems/FMPy#566]
Hi, I am trying to run a dynamic simulation, for example, engine speed is 1500 for first 5 minutes, 1500 for next 5 minutes, then how to stop the simulation based on steady state output, since there is no new operating condition, hence i can use the previous ones which are already simulated. 

can you please give me an example for this or some kind of direction how to stop

**Comment by t-sommer** [comment]
You can continue a simulation until you decide to terminate it based on the result (see [examples/continue_simulation.py](https://github.com/CATIA-Systems/FMPy/blob/main/fmpy/examples/continue_simulation.py) for an example).
