### ISSUE TITLE
FMU state serialization test crashes on Linux

### ISSUE THREAD

**Issue by t-sommer** [CATIA-Systems/FMPy#57]
The [FMU state serialization test](https://github.com/CATIA-Systems/FMPy/blob/develop/tests/test_serialize_fmu_state.py) with the MapleSim 2016.2 Rectifier.fmu crashes with a memory error on Linux for both Python 2.7 and 3.6 (see e.g. https://circleci.com/gh/CATIA-Systems/FMPy/4).

@Maplesoft-fmigroup, do you have an idea what could cause the problem?

**Comment by Maplesoft-fmigroup** [comment]
Can you please provide more information about your test?  In the linked code there's a sequence of calls:
# get the FMU state
state = fmu.getFMUstate()
# serialize the FMU state
serialized_state = fmu.serializeFMUstate(state)
# de-serialize the FMU state
fmu.deSerializeFMUstate(serialized_state, state)

but  fmi2SerializeFMUstate() requires an array ‘serializedState’ and its size as inputs. 
The latter is obtained by calling fmi2SerializedFMUstateSize but we don’t see that call in the test code.  Is it hidden in the fmu.serializeFMUstate() call?
Is this test failing only on linux?  Is the 2018 version of the Rectifier working for you?

Thanks

**Comment by t-sommer** [comment]
The memory is allocated in [serializeFMUState()](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/fmi2.py#L346)

```python
    def serializeFMUstate(self, state):
        """ Serialize an FMU state
        Parameters:
            state   the FMU state
        Returns:
            the serialized state as a byte string
        """

        size = c_size_t()
        self.fmi2SerializedFMUstateSize(self.component, state, byref(size))
        serializedState = create_string_buffer(size.value)
        self.fmi2SerializeFMUstate(self.component, state, serializedState, size)
        return serializedState.raw
```

Maybe it's a problem with Python's garbage collector that's freeing the memory too early. You can run the test with a different version of the FMU by changing [this line](https://github.com/CATIA-Systems/FMPy/blob/master/tests/test_serialize_fmu_state.py#L17):

```python
download_test_file('2.0', 'cs', 'MapleSim', '2016.2', 'Rectifier', fmu_filename)
```

**Comment by t-sommer** [comment]
I will try to keep a reference to `serializedState` to save it from the garbage collector.

**Comment by t-sommer** [comment]
@Maplesoft-fmigroup cdf83f70d1357805f65e2c8de9684aff4b83412c fixes the problem for MapleSim 2016.2. For 2018 however it still doesn't work. Did you change something for the 2018 release?

**Comment by Maplesoft-fmigroup** [comment]
@t-sommer  We only added some error checks for the inputs.  Is it possible to turn on logging to see exactly what the problem is?

**Comment by Maplesoft-fmigroup** [comment]
@t-sommer  Can you make sure that 'state' is NULL when you first call fmi2GetFMUstate?

**Comment by t-sommer** [comment]
`state` is initialized to `None` (= `NULL` in C)

**Comment by Maplesoft-fmigroup** [comment]
@t-sommer  We have reproduced your test code in our FMU Import and ran it with our 2016.2 and 2018 Rectifier FMU on Linux64.  We ran the serialization code at every simulation step to stress test the code.  Both of the FMUs ran fine, there were no issues at any simulation step.  Here is the C-code we used for testing:
```        fmi2Byte *serializedState;
        fmi2FMUstate state=NULL;
        size_t size;
        sts = S->fmi2GetFMUstate(S->comp,&state);
        if( sts!=fmi2OK ) {
            sprintf(buf,"FMU[%s]: Call to fmi2GetFMUstate failed",S->instancename);
            FMI20throwerror(kv,buf);
            return;
        }    
        sts = S->fmi2SerializedFMUstateSize(S->comp,state,&size);
        if( sts!=fmi2OK ) {
            sprintf(buf,"FMU[%s]: Call to fmi2SerializedFMUstateSize failed",S->instancename);
            FMI20throwerror(kv,buf);
            return;
        }    
        serializedState=(fmi2Byte *)malloc(size*sizeof(fmi2Byte));
        sts = S->fmi2SerializeFMUstate(S->comp,state,serializedState,size);
        if( sts!=fmi2OK ) {
            sprintf(buf,"FMU[%s]: Call to fmi2SerializeFMUstate failed",S->instancename);
            FMI20throwerror(kv,buf);
            return;
        }    
        sts = S->fmi2FreeFMUstate(S->comp,&state);
        if( sts!=fmi2OK ) {
            sprintf(buf,"FMU[%s]: Call to fmi2FreeFMUstate failed",S->instancename);
            FMI20throwerror(kv,buf);
            return;
        }    
        state=NULL;
        sts = S->fmi2DeSerializeFMUstate(S->comp,serializedState,size,&state);
        if( sts!=fmi2OK ) {
            sprintf(buf,"FMU[%s]: Call to fmi2DeSerializeFMUstate failed",S->instancename);
            FMI20throwerror(kv,buf);
            return;
        }    
        free(serializedState);
        sts = S->fmi2SetFMUstate(S->comp,state);
        if( sts!=fmi2OK ) {
            sprintf(buf,"FMU[%s]: Call to fmi2SetFMUstate failed",S->instancename);
            FMI20throwerror(kv,buf);
            return;        }
        sts = S->fmi2FreeFMUstate(S->comp,&state);
        if( sts!=fmi2OK ) {
            sprintf(buf,"FMU[%s]: Call to fmi2FreeFMUstate failed",S->instancename);
            FMI20throwerror(kv,buf);
            return;
        }
```

**Comment by t-sommer** [comment]
Can you provide a source code FMU of the 2018 release to debug the serialization function?

**Comment by Maplesoft-fmigroup** [comment]
@t-sommer  Our 2018 source code FMUs are available on GitHub:
https://github.com/modelica/fmi-cross-check/tree/master/fmus/2.0/cs/c-code/MapleSim/2018

**Comment by hyumo** [comment]
Hi @t-sommer :

I encountered a similar issue with Dymola 2019 exported FMU on windows tho. Could you take a look at this when you got some time? 

I am using the `test_serialize_fmu_state.py` file, with `filename` modified to point to my own FMU. Here's the error message generated:

```
(fmpy) D:\Sandbox\fmpy\test>python test_state_serialization.py
not a valid tpl file
[WARNING] b'fmi2DeSerializeFMUstate: tpl_load failed'
Traceback (most recent call last):
  File "test_state_serialization.py", line 58, in <module>
    test_serialize_fmu_state()
  File "test_state_serialization.py", line 43, in test_serialize_fmu_state
    fmu.setFMUstate(state)
  File "D:\ProgramData\anaconda3\envs\fmpy\lib\site-packages\fmpy\fmi2.py", line 341, in setFMUstate
    self.fmi2SetFMUstate(self.component, state)
  File "D:\ProgramData\anaconda3\envs\fmpy\lib\site-packages\fmpy\fmi2.py", line 201, in w
    res = f(*args)
OSError: exception: access violation reading 0x00000008
```

Here's the FMU I am using, which is exported from Dymola 2019 with command:

```
translateModelFMU("Modelica.Mechanics.Rotational.Examples.CoupledClutches", false, "Modelica_Mechanics_Rotational_Examples_CoupledClutches", "2", "all", true, 0);
```

The fmu is attached (please change the format back to `*.fmu`):
[CoupledClutches_buggy.zip](https://github.com/CATIA-Systems/FMPy/files/2634689/CoupledClutches_buggy.zip)


Thanks. 
HYu

**Comment by t-sommer** [comment]
@hyumo, I can reproduce the problem. The FMU crashes in fmiCommonFunctions_int.c (line 716):

```
assert(source->allocDone);
```

where allocDone == 0.

@KarlWernersson, can you take a look at this?

**Comment by hyumo** [comment]
Thanks @KarlWernersson , I will contact customer support. And thanks @t-sommer !

**Comment by t-sommer** [comment]
Here's what I get for the Dymola FMU before the crash:

```
[FMI] fmi2Instantiate(instanceName=b'Modelica_Mechanics_Rotational_Examples_CoupledClutches', fmuType=1, guid=b'{2da10f79-06f0-4a7d-aeee-1a50a502a2d5}', resourceLocation=b'file:///C:/Users/XXX/AppData/Local/Temp/tmp4jiad_xl/resources', callbacks=<fmpy.fmi2.fmi2CallbackFunctions object at 0x000001A6D7C68DC8>, visible=0, loggingOn=0) -> 0x1a6d4cb6010
[FMI] fmi2SetupExperiment(component=0x1a6d4cb6010, toleranceDefined=0, tolerance=0.0, startTime=0.0, stopTimeDefined=0, stopTime=0.0) -> OK
[FMI] fmi2EnterInitializationMode(component=0x1a6d4cb6010) -> OK
[FMI] fmi2ExitInitializationMode(component=0x1a6d4cb6010) -> OK
[FMI] fmi2GetFMUstate(component=0x1a6d4cb6010, FMUstate=1816097556896) -> OK
[FMI] fmi2SerializedFMUstateSize(component=0x1a6d4cb6010, FMUstate=0x1a6d7d989a0, size=889046) -> OK
[FMI] fmi2SerializeFMUstate(component=0x1a6d4cb6010, FMUstate=0x1a6d7d989a0, serializedState=<ctypes.c_char_Array_889046 object at 0x000001A6D7C68F48>, size=c_ulonglong(889046)) -> OK
[FMI] fmi2DeSerializeFMUstate(component=0x1a6d4cb6010, FMUstate=<ctypes.c_char_Array_889046 object at 0x000001A6D7C68F48>, serializedState=889046, size=1816097559296) -> OK
```

@KarlWernersson, is it possible that the problem is in the FMU? I would also suggest to change the error handling to

```
if (source->allocDone == 0) {
    // log error
   return fmi2Error;
}
```

in order to allow the importer to shut down properly.

**Comment by t-sommer** [comment]
@Maplesoft-fmigroup, the problem seems to be in line 1822 of Rectifier.c (fmi-cross-check\fmus\2.0\cs\c-code\MapleSim\2018\Rectifier, compiled from source on Windows 64-bit with Visual Studio 2015 & FMPy generated CMake project):

```
for(i=0;i<NUMBER_OF_STRINGS;i++)
    sto+=strlen(comp->s[i])+1;
```

where `comp->s == 0x0`.

**Comment by Maplesoft-fmigroup** [comment]
@t-sommer  That looks like an oversight on our part, we'll fix.  Thanks for investigating!
