### ISSUE TITLE
The FMU cannot be simulated on the current platform (linux64)

### ISSUE THREAD

**Issue by elderwann** [CATIA-Systems/FMPy#576]
Hello,

I try to use fmpy (last release) on windows platform and when I start with the command : 

fmpy simulate FMU_file.fmu --show-plot 

it returned : "The FMU cannot be simulated on the current platform (win)"

So I installed fmpy on linux platform and when I start with the same command, it returned : 

"The FMU cannot be simulated on the current platform (linux64)"

What could be the error ??

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by elderwann** [comment]
Thank you for replying, I'm sorry but I can't share that FMU. However I test to open it with 7 zip, unzip it, and the resultat was inside a linux32 folder... maybe that is the cause of error messages... So I'm going install fmpy under a linux32 and test again. I'll be back to share the result.
