### ISSUE TITLE
Failed to validate modelDescription.xml (version=3.0) for causality "input" with intial "exact" defined

### ISSUE THREAD

**Issue by atavarek** [CATIA-Systems/FMPy#579]
**modelDescription.xml snippet**
```
<fmiModelDescription fmiVersion="3.0" ../>
<ModelVariables>
    <Float64 causality="input" description="Input" initial="exact" name="Input" start="0" valueReference="0" variability="continuous"/>
</ModelVariables>
```
**Error message thrown by fmpy when importing the fmu**
Failed to load /tmp/Basic.fmu. Failed to validate modelDescription.xml:- Variable "Input" (line 6) " has causality "input" but defines a intial "exact".

**From my understanding of FMI 3.0 specification this combination is allowed**
https://fmi-standard.org/docs/3.0/#table-definition-initial 
Table 21. Type Specific Attributes

The interpretation of [start](https://fmi-standard.org/docs/3.0/#start) is defined by variable attribute [initial](https://fmi-standard.org/docs/3.0/#initial).
If [initial](https://fmi-standard.org/docs/3.0/#initial) = [exact](https://fmi-standard.org/docs/3.0/#exact) or [approx](https://fmi-standard.org/docs/3.0/#approx), a [start](https://fmi-standard.org/docs/3.0/#start) attribute must be provided.

validation.py Line 76  - if is_fmi2 or is_fmi3:  (check is valid for 2.0, I am not sure about 3.0)

**Comment by t-sommer** [comment]
Can you share an FMU to reproduce the problem?

**Comment by atavarek** [comment]
[FeedThrough_Modified.zip](https://github.com/CATIA-Systems/FMPy/files/12035350/FeedThrough_Modified.zip)

**Comment by atavarek** [comment]
Line 666 in model_description.py
```
# default values for 'initial' derived from variability and causality
    initial_defaults = {
        'constant':   {'output': 'exact', 'local': 'exact', 'parameter': 'exact'},
        'fixed':      {'parameter': 'exact', 'calculatedParameter': 'calculated', 'structuralParameter': 'exact', 'local': 'calculated'},
        'tunable':    {'parameter': 'exact', 'calculatedParameter': 'calculated', 'structuralParameter': 'exact', 'local': 'calculated'},
        'discrete':   {'input': None, 'output': 'calculated', 'local': 'calculated'},
        'continuous': {'input': None, 'output': 'calculated', 'local': 'calculated', 'independent': None},
        'clock':      {'input': 'exact', 'output': 'calculated', 'local': 'calculated'},
    }
```
Comparing with https://fmi-standard.org/docs/3.0/#table-definition-initial is not compliant for some cases

1. 'constant' - 'parameter' is not applicable
2. 'discrete'  - 'input' is 'exact'
3. 'continuous' - 'input' is 'exact'
