### ISSUE TITLE
Input interpolation breaks when last sample is an event

### ISSUE THREAD

**Issue by RasPiTool** [CATIA-Systems/FMPy#58]
hello,

I have to connect several FMUs. It could be connection between CO-Simulations or a mixed connection between CO and Exchange-Simulations. There is some examples to CO-Simulation that I understand. I can get or set variables with `fmu.setReal([ValueReference], [Value])` or `fmu.getReal([ValueReference])`. Now I try to understand how ModelExchange simulation works and how can I get or set variables.
I tried to simulate the ModelExchange CoupledClutches from Dymola with input.
Like this:
`>fmpy simulate CoupledClutches.fmu --step-size 0.005 --stop-time 2 --solver "Euler" --input-file "CoupledClutches_in.csv" --show-plot`
So I get a error
```
Traceback (most recent call last):
  File "C:\Users\mesau\Anaconda3\Scripts\fmpy-script.py", line 5, in <module>
    sys.exit(fmpy.command_line.main())
  File "C:\Users\mesau\Anaconda3\lib\site-packages\fmpy\command_line.py", line 114, in main
    fmi_call_logger=fmi_call_logger)
  File "C:\Users\mesau\Anaconda3\lib\site-packages\fmpy\simulation.py", line 508, in simulate_fmu
    result = simulateME(model_description, fmu_args, start_time, stop_time, solver, step_size, relative_tolerance, start_values, apply_default_start_values, input, output, output_interval, record_events, timeout, callbacks, debug_logging, step_finished)
  File "C:\Users\mesau\Anaconda3\lib\site-packages\fmpy\simulation.py", line 639, in simulateME
    t_input_event = input.apply(time)
  File "C:\Users\mesau\Anaconda3\lib\site-packages\fmpy\simulation.py", line 199, in apply
    self.real_values[:] = self.interpolate(time=time, t=self.t, table=self.real_table, after_event=after_event)
  File "C:\Users\mesau\Anaconda3\lib\site-packages\fmpy\simulation.py", line 274, in interpolate
    t1 = t[i1]
IndexError: index 523 is out of bounds for axis 0 with size 523
```
If I change the --stop-time to 1.5 than it works fine. The input-time goes from 0 to 1.5.
It would be good, if simulation applies last inputs (at input-time 1.5) for the remaining simulation-time.
How could I solve this problem?

**Comment by t-sommer** [comment]
Seems to be a bug in the input interpolation. Can you share the files?

**Comment by RasPiTool** [comment]
Here are the files
[CoupledClutches.zip](https://github.com/CATIA-Systems/FMPy/files/2584480/CoupledClutches.zip)
[CoupledClutches_in.txt](https://github.com/CATIA-Systems/FMPy/files/2584483/CoupledClutches_in.txt)
I changed the endings from .fmu, .csv to .zip, .txt because the upload doesn't work.

**Comment by t-sommer** [comment]
The problem is the event at the last value (t=1.5). As a work around you can delete the last line in the CSV.

**Comment by t-sommer** [comment]
The problem still needs to be fixed. Input with an event at the end is unusual but valid.

**Comment by t-sommer** [comment]
With 4e0137381bc111e6fa0399fe152c0f629ed43dc2 the input is now extrapolated as you suggested. Thanks for your help!
