### ISSUE TITLE
Remoting: fmi2SetString failes with status 3

### ISSUE THREAD

**Issue by fajansen** [CATIA-Systems/FMPy#582]
I have a 32 bit windows FMU with a string as an input. Executing it with fmpy in a 32bit python installation and setting the string inputs works fine. However, when I add remoting and then use fmpy in a 64 bit python installation to set the input, fmi2SetString fails with status 3 (error).

**Comment by nl78** [comment]
I made a complete rewrite of remoting code (SHM). I would be glad to contribute to fmpy. Is there a way ?
nl@haplo.info
