### ISSUE TITLE
Need an example input file(.csv) for Array variable 

### ISSUE THREAD

**Issue by PRAVEENFrmBOSCH** [CATIA-Systems/FMPy#594]
I am using attached xml file for Testing.
[FMI3.zip](https://github.com/CATIA-Systems/FMPy/files/12428890/FMI3.zip)

**Comment by nl78** [comment]
what do you think of adding a button to generate skeleton of CSV input file?

**Comment by t-sommer** [comment]
> what do you think of adding a button to generate the skeleton (= header line) of the CSV input file?

This feature already exists:

![Capture](https://github.com/CATIA-Systems/FMPy/assets/2453858/cd111b2c-817a-4fa7-b7bc-bdd1e7e6830a)

**Comment by t-sommer** [comment]
Closing in favor of #495.

**Comment by PRAVEENFrmBOSCH** [comment]
I have used below csv file

![image](https://github.com/CATIA-Systems/FMPy/assets/138491531/8abd5be1-b9e9-4474-b934-7fabd82091d5)

[LinearTransform_in.csv](https://github.com/CATIA-Systems/FMPy/files/12452812/LinearTransform_in.csv)

**Comment by PRAVEENFrmBOSCH** [comment]
[LinearTransform_in.csv](https://github.com/CATIA-Systems/FMPy/files/12452827/LinearTransform_in.csv)


![image](https://github.com/CATIA-Systems/FMPy/assets/138491531/2152fd0b-6489-4f11-8965-3f56d5e7d881)
[LinearTransform_in.csv](https://github.com/CATIA-Systems/FMPy/files/12452833/LinearTransform_in.csv)
