### ISSUE TITLE
Creating template input file for Array datatype as a csv format is not working

### ISSUE THREAD

**Issue by PRAVEENFrmBOSCH** [CATIA-Systems/FMPy#595]
file generated just has time and u column but u variable is an array in my model , how to pass array values to the same? 
Sample file is generated from the gui  as mentioned in https://github.com/CATIA-Systems/FMPy/issues/594
[LinearTransform_in_1.csv](https://github.com/CATIA-Systems/FMPy/files/12452867/LinearTransform_in_1.csv)

FMU : 
[LinearTransform.zip](https://github.com/CATIA-Systems/FMPy/files/12452957/LinearTransform.zip)

**Comment by PRAVEENFrmBOSCH** [comment]
https://github.com/CATIA-Systems/FMPy/blob/main/fmpy/util.py#L8 
I have checked above code which is expecting csv file to be u[1] and u[2]  seems but when i am passing the same i am getting below error 
![image](https://github.com/CATIA-Systems/FMPy/assets/138491531/fea62e30-0fbd-40b6-946e-f564d920e746)

**Comment by t-sommer** [comment]
Array variables are currently not supported via CSV (see #495).
