### ISSUE TITLE
how to do steady steady state simulations with fmpy

### ISSUE THREAD

**Issue by ravikiranbadathala** [CATIA-Systems/FMPy#597]
I want use FMU or .sif to run steady state simulations without giving time as input. 
is there any way to run steady state simulations with fmpy

**Comment by KarlWernersson** [comment]
Are you talking about initializing the FMU in steady state?
if its a model exported correctly to an FMU then its only an issue about setting the required start values for the output/Derivative you want to fix.
If you want to do something more complex I would recommend Dymola =)

**Comment by ravikiranbadathala** [comment]
can you please tell me how to initialize FMU in steady state.
as we are using FMU for both steady state and dynamic simulations, i am able to run the FMU in transient conditions, but i need to run the same FMU with steady state

**Comment by KarlWernersson** [comment]
The fmu's don't have a specific way to initialize into steady state.
FMU's are initialized. If you export your model as an FMU to be initialized in steady state then it should be initialized into steady state when you finish the initialization phase of the FMU. This would be by far the easiest option for you.

If this is not possible. You have to setup your equation related to the FMU so it is initialized into steady state by aplyinhg external constraints on the variables you want to fix and then modify other inputs(start values) to get the desired result. This is not trivial.  If you are using fpmy you would have to setup all those equations yourself in python.
I would recommend to use a specialized software like Dymola to solve this issue, that requires you to know or learn Modelica (if you choose Dymola).

**Comment by KarlWernersson** [comment]
Another option would be to simulate into steady state then save the fmuState with serizalizeFMUState functionality (not all tool vendors fmu's support this). Then this state can be loaded in to a new instance to start it at that time. If you want to do computations at that point without modifying the time you need to use modelExchange as co-simulation according to the FMI standard requires you to use doStep (which updates time) to compute new outputs. (Or use Dymola as we are not enforcing that requirement strictly on our co-simulation FMU's)
