### ISSUE TITLE
GUI to compose multiple systems

### ISSUE THREAD

**Issue by jankap** [CATIA-Systems/FMPy#601]
This project looks incredible and might be the best place to start with my project. 

I'm searching for or trying to develop a python tool that composes multiple FMUs and functions written in other languages to a new system. I was thinking of a (web-) GUI that can achieve that. Reason is that I'd like to combine tools like Simukink, python and Ansys Twin builder and it seems like the easiest way to do so is to use FMUs and some glue code to combine them. 

Do you think that's feasible? Could the GUI be enhanced to connect multiple FMUs?

**Comment by t-sommer** [comment]
For the actual implementation of your combined system you might want to take a look at FMPy's [FMU Container](https://github.com/CATIA-Systems/FMPy/tree/main/fmpy/fmucontainer). However there are no plans to build a GUI for it.
