### ISSUE TITLE
simulate_fmu() has arguments that does not exits longer

### ISSUE THREAD

**Issue by overkligheten** [CATIA-Systems/FMPy#602]
Hi,
I get an error when i set the argument "set_stop_time=False" in  simulate_fmu(). I am told that this argument does not exist any longer. I use this when I want to continue a simulation in a similar fashion like in your example continue_simulation.py. How can I continue a simulation without any errors?

Thanks!

continue_simulation.py:
________________________________________________
def continue_simulation(fmu_filename):

    # extract the FMU to a temporary directory
    unzipdir = extract(fmu_filename)

    # read the model description
    model_description = read_model_description(unzipdir)

    # instantiate the FMU beforehand, so we can keep it alive
    fmu_instance = instantiate_fmu(unzipdir=unzipdir, model_description=model_description)

    # simulate to 1 s
    result1 = simulate_fmu(
        filename=unzipdir,
        model_description=model_description,
        fmu_instance=fmu_instance,
        start_values={'e': 0.95},
        stop_time=1,
        **set_stop_time=False,  # don't communicate the stop time, so we can continue**
        terminate=False  # keep the FMU instance alive
    )

    # change a tunable parameter
    apply_start_values(fmu=fmu_instance, model_description=model_description, start_values={'e': 0.55})

    # continue to 2 s
    result2 = simulate_fmu(
        filename=unzipdir,
        model_description=model_description,
        fmu_instance=fmu_instance,
        initialize=False,  # the FMU instance is already instantiated
        start_time=1,  # start where we left off
        stop_time=2,
        terminate=False
    )
 _____________________________________________________

**Comment by t-sommer** [comment]
The argument exists (see https://github.com/CATIA-Systems/FMPy/blob/main/fmpy/simulation.py#L616). Make sure you are using the correct FMPy version.
