### ISSUE TITLE
Loop on simulate_fmu crashes after 1060 iterations

### ISSUE THREAD

**Issue by Claire-Eleutheriane** [CATIA-Systems/FMPy#608]
[test_basic_fmu - scripts Eleu.zip](https://github.com/CATIA-Systems/FMPy/files/12854183/test_basic_fmu.-.scripts.Eleu.zip)

I created a very simple FMU (one parameter, one equation), kind ME & CS, using OpenModelica 1.21.

With a for loop, I try to simulate the FMU 2000 times in a row. But the code ends after 1060 simulations, without any error code nor segmentation fault.

The same FMU can be simulated 2000 times problemlessly using PyFMI.
The same FMU, if generated using Dymola, can apparently be simulated 2000 times problemlessly using FMPy (I couldn’t test myself, as I don’t have a licence).

**Comment by Claire-Eleutheriane** [comment]
(I use FMPy 0.3.15, installed using Anaconda)

**Comment by t-sommer** [comment]
This seems to be a limitation of the FMU. However, if you do the same with FMPy you do with pyFMI, it simulates just fine:

```python
# instantiate the FMU
fmu_instance = instantiate_fmu(unzipdir, model_description, 'CoSimulation')

# perform the iteration
for i in range(2000):

    # reset the FMU instance instead of creating a new one
    fmu_instance.reset()

    # pass the unzipdir, model description and FMU instance to simulate_fmu()
    result = simulate_fmu(
        unzipdir,
        model_description=model_description,
        fmu_instance=fmu_instance
    )

    print(i)

# free the FMU instance and unload the shared library
fmu_instance.freeInstance()

# delete the temporary directory
shutil.rmtree(unzipdir, ignore_errors=True)
```

**Comment by Claire-Eleutheriane** [comment]
Simple and efficient to solve the problem. Thanks a lot!
