### ISSUE TITLE
Suppress Logging of CVODE Solver

### ISSUE THREAD

**Issue by wredsen** [CATIA-Systems/FMPy#613]
When trying to call the `reset()` or `instantiate()` function like in [this example](https://github.com/CATIA-Systems/FMPy/blob/8945636e85f09e6267b2b4ee101b99c81982530a/fmpy/examples/custom_input.py#L44), the CVODE solver of a cosim FMU will cause a log looking like:
```
LOG_SOLVER        | info    | CVODE linear multistep method CV_BDF
LOG_SOLVER        | info    | CVODE maximum integration order CV_ITER_NEWTON
LOG_SOLVER        | info    | CVODE use equidistant time grid YES
LOG_SOLVER        | info    | CVODE Using relative error tolerance 1.000000e-06
LOG_SOLVER        | info    | CVODE Using dense internal linear solver SUNLinSol_Dense.
LOG_SOLVER        | info    | CVODE Use internal dense numeric jacobian method.
LOG_SOLVER        | info    | CVODE uses internal root finding method NO
LOG_SOLVER        | info    | CVODE maximum absolut step size 0
LOG_SOLVER        | info    | CVODE initial step size is set automatically
LOG_SOLVER        | info    | CVODE maximum integration order 5
LOG_SOLVER        | info    | CVODE maximum number of nonlinear convergence failures permitted during one step 10
LOG_SOLVER        | info    | CVODE BDF stability limit detection algorithm OFF
```
Is it possible to suppress this log?

Best regards,
Konstantin

**Comment by t-sommer** [comment]
Can you share an FMU to reproduce the problem?

**Comment by wredsen** [comment]
Sure, for example the one attached (It is zipped for upload).

[dummy_for_FMU_cosim.zip](https://github.com/CATIA-Systems/FMPy/files/13235767/dummy_for_FMU_cosim.zip)

Best, 
Konstantin

**Comment by t-sommer** [comment]
This is a limitation of the FMU (see https://github.com/OpenModelica/OpenModelica/issues/11500).

**Comment by wredsen** [comment]
Sorry if the following is misplaced here and I also posted it at [OpenModelica's](https://github.com/OpenModelica/OpenModelica/issues/11506), but I found another interesting thing about the `reset()` behaviour of Co-Sim FMUs (the problem is bigger with cvode, but also occurs using euler solver). 

If I initialize a Co-Simulation FMU using FMPy:
```
import os
from fmpy import read_model_description, extract
from fmpy.fmi2 import FMU2Slave

fmu_path = os.path.abspath('path/to/FMU')

unzipdir = extract(fmu_path)
fmu_description = read_model_description(fmu_path)
fmu = FMU2Slave(guid=fmu_description.guid,
                unzipDirectory=unzipdir,
                modelIdentifier=fmu_description.coSimulation.modelIdentifier,
                instanceName='instance1')

fmu.instantiate()
fmu.setupExperiment(startTime=0.0)
fmu.enterInitializationMode()
fmu.exitInitializationMode()
```

and afterwards I run a loop of `reset()`:
```
for _ in range(int(1e6)):
    fmu.reset()
```
I can observe my memory usage growing continuously. This hints a problem with the clean up of prior FMU instances after reset.
