### ISSUE TITLE
Use PySide6 in GUI

### ISSUE THREAD

**Issue by t-sommer** [CATIA-Systems/FMPy#615]
instead of PyQt5

**Comment by jschueller** [comment]
one solution is to use [QtPy](https://pypi.org/project/QtPy/) abstraction layer
with minimal changes this would allow using pyqt5/6, pyside5/6
pyqtgraph dependency also supports pyside

**Comment by t-sommer** [comment]
Solved with f2762a7686f04deec18704dab7c905c0e3c51e06.
