### ISSUE TITLE
OpenModelica FMU crashes on Linux

### ISSUE THREAD

**Issue by triccyx** [CATIA-Systems/FMPy#62]
When I try to execute an FMU from OpenModelica a crash occurs.
OpenModelica version: OMEdit v1.13.0-dev.214+gb23d97a
OS: Ubuntu 16.04
Mmpy:0.2.7

I include the simplest FMU that reproduce the problem, just remove zip extension.
[problem.fmu.zip](https://github.com/CATIA-Systems/FMPy/files/2611026/problem.fmu.zip)

error log:
 python3 -m fmpy.gui
JSON object expected ',' or '}', got: "lineEnd":4,"colStar
Aborted (core dumped)

**Comment by t-sommer** [comment]
Can you execute the FMU on the command line with FMI and debug logging enabled?

```
$ fmpy simulate --debug-loggin --fmi-logging problem.fmu
```

**Comment by triccyx** [comment]
With the new OpenModelica (& tools) build it does not crash anymore.
