### ISSUE TITLE
FMUs with aarch64-darwin binaries not supported

### ISSUE THREAD

**Issue by Maplesoft-fmigroup** [CATIA-Systems/FMPy#623]
In version 0.3.19 of fmpy, we get the following error when trying to simulate FMI3.0 FMU with binaries/aarch64-darwin:
```
Python/3.11.6/APPLE_ARM64_MACOS/lib/python3.11/site-packages/fmpy/simulation.py", line 667, in simulate_fmu\n    raise
Exception(f"The FMU cannot be simulated on the current platform ({platform}).")\n', 'Exception: The FMU cannot be simulated on the current platform (darwin64).\n']
```
the issue is probably on line 100 of \_\_init\_\_.py:
`100         if head in {'binaries/darwin64', 'binaries/x86_64-darwin'} and tail.endswith('.dylib'):
`

**Comment by t-sommer** [comment]
Unfortunately I don't have access to an Apple Silicon Mac. Can you suggest a change that works for you?

**Comment by Maplesoft-fmigroup** [comment]
These are the changes I made to get around the problem:
in \_\_init\_\_.py:
```
import platform
if platform.machine() == 'arm64':
    architecture = 'aarch64'
```
and on line 100:
`if head in {'binaries/darwin64', 'binaries/x86_64-darwin', 'binaries/aarch64-darwin'} and tail.endswith('.dylib'):
`
These allowed me to simulate FMI3.0 FMU with ARM binaries.
Additionally, I made some changes in util.py line 867:
` if target_platform in ['darwin64', 'x86_64-darwin', 'aarch64-darwin']:
`
