### ISSUE TITLE
Please add a -v|--version to get the version from FMPy.

### ISSUE THREAD

**Issue by adrpo** [CATIA-Systems/FMPy#625]
There is a PR here: https://github.com/CATIA-Systems/FMPy/pull/624 which you can use for inspiration.
You should really set up a CLA so that contributors can sign the rights of the PR code to you.

**Comment by casella** [comment]
@t-sommer this would be a nice feature for our testing system, so we can easily report which version of FMPy was used to run the FMUs

**Comment by t-sommer** [comment]
For now you can use this workaround that should work with all versions of FMPy.

```
python -c "import fmpy; print(fmpy.__version__)"
```

**Comment by adrpo** [comment]
Thanks, I did -h and grep on the version, but this seems better.
