### ISSUE TITLE
Exception: Failed to load shared library ... .dll. Could not find module '... .dll' (or one of its dependencies). Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by gearskill** [CATIA-Systems/FMPy#626]
Hello everyone,
I exported a Simulink model as a FMU. The FMUchecker says that there is no problem with the FMU. But when I want to run `simulate_fmu(fmuName)`, I get the error below. I think that Fmpy might not know where to find the matlab/matlab runtime, even though I tried to specify them in the Path variable:
C:\Program Files\MATLAB\R2023b\runtime\win64;
C:\Program Files\MATLAB\R2023b\bin;
C:\Program Files\MATLAB\MATLAB Runtime\R2023b\runtime\win64;
C:\Program Files\MATLAB\MATLAB Runtime\R2023b\extern\bin\win64;
C:\Program Files\MATLAB\MATLAB Runtime\R2023b\bin\win64

I am running Python 3.9 on Pycharm. My FMU is called 'FINAL_varstep.fmu'.

FileNotFoundError                         Traceback (most recent call last)
File C:\Program Files\MATLAB\R2023b\bin\StableRLS\venv\lib\site-packages\fmpy\fmi1.py:163, in _FMU.__init__(self, guid, modelIdentifier, unzipDirectory, instanceName, libraryPath, fmiCallLogger, requireFunctions)
    162 try:
--> 163     self.dll = cdll.LoadLibrary(libraryPath)
    164 except Exception as e:

File C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py:452, in LibraryLoader.LoadLibrary(self, name)
    451 def LoadLibrary(self, name):
--> 452     return self._dlltype(name)

File C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py:374, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    373 if handle is None:
--> 374     self._handle = _dlopen(self._name, mode)
    375 else:

FileNotFoundError: Could not find module 'C:\Users\jakob\AppData\Local\Temp\tmps_spd0t5\binaries\win64\FINAL_varstep.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
Cell In[7], line 1
----> 1 result = simulate_fmu(fmu)

File C:\Program Files\MATLAB\R2023b\bin\StableRLS\venv\lib\site-packages\fmpy\simulation.py:741, in simulate_fmu(filename, validate, start_time, stop_time, solver, step_size, relative_tolerance, output_interval, record_events, fmi_type, start_values, apply_default_start_values, input, output, timeout, debug_logging, visible, logger, fmi_call_logger, step_finished, model_description, fmu_instance, set_input_derivatives, remote_platform, early_return_allowed, use_event_mode, initialize, terminate, fmu_state, set_stop_time)
    738     add_remoting(unzipdir, host_platform=platform, remote_platform=remote_platform)
    740 if fmu_instance is None:
--> 741     fmu = instantiate_fmu(unzipdir, model_description, fmi_type, visible, debug_logging, logger, fmi_call_logger, None, early_return_allowed, use_event_mode, None, validate)
    742 else:
    743     fmu = fmu_instance

File C:\Program Files\MATLAB\R2023b\bin\StableRLS\venv\lib\site-packages\fmpy\simulation.py:823, in instantiate_fmu(unzipdir, model_description, fmi_type, visible, debug_logging, logger, fmi_call_logger, library_path, early_return_allowed, event_mode_used, intermediate_update, require_functions)
    821     fmu.instantiate(functions=callbacks, loggingOn=debug_logging)
    822 elif is_fmi2:
--> 823     fmu = FMU2Slave(**fmu_args)
    824     fmu.instantiate(visible=visible, callbacks=callbacks, loggingOn=debug_logging)
    825 else:

File C:\Program Files\MATLAB\R2023b\bin\StableRLS\venv\lib\site-packages\fmpy\fmi2.py:524, in FMU2Slave.__init__(self, instanceName, **kwargs)
    520 def __init__(self, instanceName=None, **kwargs):
    522     kwargs['instanceName'] = instanceName
--> 524     super(FMU2Slave, self).__init__(**kwargs)
    526     # Simulating the slave
    528     self._fmi2Function('fmi2SetRealInputDerivatives',
    529                        ['c', 'vr', 'nvr', 'order', 'value'],
    530                        [fmi2Component, POINTER(fmi2ValueReference), c_size_t, POINTER(fmi2Integer), POINTER(fmi2Real)])

File C:\Program Files\MATLAB\R2023b\bin\StableRLS\venv\lib\site-packages\fmpy\fmi2.py:85, in _FMU2.__init__(self, **kwargs)
     83 def __init__(self, **kwargs):
---> 85     super(_FMU2, self).__init__(**kwargs)
     87     # Inquire version numbers of header files and setting logging status
     88     self._fmi2Function('fmi2GetTypesPlatform', [], [], fmi2String)

File C:\Program Files\MATLAB\R2023b\bin\StableRLS\venv\lib\site-packages\fmpy\fmi1.py:165, in _FMU.__init__(self, guid, modelIdentifier, unzipDirectory, instanceName, libraryPath, fmiCallLogger, requireFunctions)
    163     self.dll = cdll.LoadLibrary(libraryPath)
    164 except Exception as e:
--> 165     raise Exception("Failed to load shared library %s. %s" % (libraryPath, e))
    167 # change back to the working directory
    168 os.chdir(work_dir)

Exception: Failed to load shared library C:\Users\jakob\AppData\Local\Temp\tmps_spd0t5\binaries\win64\FINAL_varstep.dll. Could not find module 'C:\Users\jakob\AppData\Local\Temp\tmps_spd0t5\binaries\win64\FINAL_varstep.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by gearskill** [comment]
No I am sorry.
Is there another way I can provide you with the information you need?

**Comment by t-sommer** [comment]
Can you reproduce the problem with an example model you can share?

**Comment by gearskill** [comment]
> Can you share the FMU?

I invited you to the repository, where I uploaded the FMU. Is this okay?
Thank you in advance for your help!

**Comment by t-sommer** [comment]
The `FINAL_varstep.dll` depends on DLLs that are not contained in the FMU. You might be able to add the corresponding directory to the `PATH`, so importers can find them.

![image](https://github.com/CATIA-Systems/FMPy/assets/2453858/b78c4d11-e6ac-4ecf-8c40-a84d11144aaa)

**Comment by gearskill** [comment]
I found the solution:

Add the DLL paths in python by: 
```
import os
os.add_dll_directory(r"...")
```

https://stackoverflow.com/questions/59330863/cant-import-dll-module-in-python

I didn't know that specifying them in the PATH environment variable isn't enough for python.
Thank you for your support!
