### ISSUE TITLE
Windows Error while simulating a FMU

### ISSUE THREAD

**Issue by GabaSys** [CATIA-Systems/FMPy#63]
I have created a Co-Simulation FMU from MATLAB 2018b. I am using Windows 64bit, Python 2.7.15 and FMPY latest version.

I am trying to run the created FMU with FMPY. While running "dump" and "simulate_fmu" commands i have experienced the below errors respectively:

dump(fmu)
             File "<stdin>", line 1, in <module>
             File "C:\Python27\lib\site-packages\fmpy\__init__.py", line 191, in dump
                         print(fmu_info(filename))
             File "C:\Python27\lib\site-packages\fmpy\util.py", line 451, in fmu_info
                        l.append("  Event Indicators  %d" % md.numberOfEventIndicators)
             TypeError: %d format: a number is required, not NoneType

result = simulate_fmu(fmu)
            File "<stdin>", line 1, in <module>
            File "C:\Python27\lib\site-packages\fmpy\simulation.py", line 505, in simulate_fmu
                    result = simulateCS(model_description, fmu_args, start_time, stop_time, relative_tolerance, 
                                       start_values, apply_default_start_values, input, output, output_interval, timeout, 
                                     callbacks, debug_logging, step_finished)
            File "C:\Python27\lib\site-packages\fmpy\simulation.py", line 725, in simulateCS
                                fmu.setupExperiment(tolerance=relative_tolerance, startTime=start_time)
            File "C:\Python27\lib\site-packages\fmpy\fmi2.py", line 272, in setupExperiment
                            return self.fmi2SetupExperiment(self.component, toleranceDefined, tolerance, 
                                                                                  startTime, stopTimeDefined, stopTime)
            File "C:\Python27\lib\site-packages\fmpy\fmi2.py", line 201, in w
                         res = f(*args)
WindowsError: exception: access violation writing 0x0000000000000088

 Kindly go through this and suggest me a solution.

**Comment by GabaSys** [comment]
I have attached the FMU which i have used in FMPY. Kindly go through it. 

[bouncingBallFMU.zip](https://github.com/CATIA-Systems/FMPy/files/2670935/bouncingBallFMU.zip)

**Comment by chrbertsch** [comment]
With which tooling has this FMU been generated form ML/SL 2018b?

**Comment by t-sommer** [comment]
@GabaSys, have you tried running the FMU in another tool, e.g. the [FMU Compliance Checker](https://github.com/modelica-tools/FMUComplianceChecker/releases)?

**Comment by GabaSys** [comment]
> With which tooling has this FMU been generated form ML/SL 2018b?

The FMU is created with "Tool Coupling for Co-Simulation Toolbox" from Simulink 2018b Project.

**Comment by GabaSys** [comment]
> @GabaSys, have you tried running the FMU in another tool, e.g. the [FMU Compliance Checker](https://github.com/modelica-tools/FMUComplianceChecker/releases)?

No, I am trying it now.

**Comment by chrbertsch** [comment]
> 
> 
> > With which tooling has this FMU been generated form ML/SL 2018b?
> 
> The FMU is created with "Tool Coupling for Co-Simulation Toolbox" from Simulink 2018b Project.

Have you followed the steps desfribed in https://de.mathworks.com/help/simulink/ug/_mw_54e936ec-2fa7-4418-be70-d99c8f91d2bd.html  to start the server?

**Comment by GabaSys** [comment]
> > > With which tooling has this FMU been generated form ML/SL 2018b?
> > 
> > 
> > The FMU is created with "Tool Coupling for Co-Simulation Toolbox" from Simulink 2018b Project.
> 
> Have you followed the steps described in https://de.mathworks.com/help/simulink/ug/_mw_54e936ec-2fa7-4418-be70-d99c8f91d2bd.html to start the server?

Yes, i done it. I am trying to run the FMU with PyFMI software it's sucessfully running it. But i would like the same in FMPY.

**Comment by GabaSys** [comment]
> @GabaSys, have you tried running the FMU in another tool, e.g. the [FMU Compliance Checker](https://github.com/modelica-tools/FMUComplianceChecker/releases)?

I have tried it with PYFMI and it's successfully running.

By using the "FMU Compliance Checker"  I got the below errors

1. [FMU][logStatusError][FMU status:Error] fmi2Instantiate: Error using fmuhelper

2. java.io.FileNotFoundException:

FMU check summary:
FMU reported:
        1 warning(s) and error(s)
Checker reported:
        0 Warning(s)
        1 Error(s)
        1 Fatal error(s) occurred during processing

**Comment by t-sommer** [comment]
This seems to be a problem with the FMU. You should file a bug report with the MathWorks.

**Comment by GabaSys** [comment]
No, now the same FMU is working with "FMU compliance checker" and "PyFMI". Only FMPY gives me the trouble while simulating and dumping. Run the FMU which i have attached above and check it.

**Comment by t-sommer** [comment]
The comments in the ScalarVariable tag caused a hiccup in the XML parser. It's resolved with 6bb111ce58f66495ce96f61a4a4cd6bcd77370bb.
