### ISSUE TITLE
Simulating fail for FMI3.0 win32 fmu in Windows X64 Machine

### ISSUE THREAD

**Issue by cuzperf** [CATIA-Systems/FMPy#630]
Runing `python -m fmpy.gui` in terminal, load BouncingBall.fmu, get following info
![image](https://github.com/CATIA-Systems/FMPy/assets/112376327/03bd24b7-f2f3-4787-b558-01fca8d9d546)

BouncingBall.fmu layout as follows
![image](https://github.com/CATIA-Systems/FMPy/assets/112376327/1b5e0fec-a266-44bb-b5c2-46cbea53ee2b)

simulating fail with log
![image](https://github.com/CATIA-Systems/FMPy/assets/112376327/8b4b37f6-5345-44bf-aa5a-b2dce11300b8)

It seems to **find x64 version of fmu by mistake** since my windows is x64. And the layout changed
![image](https://github.com/CATIA-Systems/FMPy/assets/112376327/51670922-5687-4608-ad47-dc8108d5f0a8)

## environment
> python 3.11
> fmpy v0.3.19
> fmu type: 3.0 Co-Simulation win32
> OS: windows AMD64
> [BouncingBall.zip](https://github.com/CATIA-Systems/FMPy/files/13667614/BouncingBall.zip)

**Comment by cuzperf** [comment]
I rename `x86_windows` to `win32` in origin BouncingBall.fmu and rezip it otherwise i will get an error log:

`[Errno 2] No such file or directory: 'C:\\User\\xxx\\AppData\\Local\\Temp\\xxxxxxxx\\binaries\\win32\server_sm.exe`

**Comment by t-sommer** [comment]
Can you share the original FMU?

**Comment by cuzperf** [comment]
@t-sommer the origin FMU and mo file: 
[BouncingBall.zip](https://github.com/CATIA-Systems/FMPy/files/13690903/BouncingBall.zip)

> github don't allow upload fmu or mo file in comment
