### ISSUE TITLE
Drop support for Windows 32-bit

### ISSUE THREAD

**Issue by t-sommer** [CATIA-Systems/FMPy#64]
Conda Forge has [dropped support for Windows 32-bit](https://github.com/conda-forge/staged-recipes/issues/5640), so v0.2.7 is the last release with Windows 32-bit support on [Conda Forge](https://anaconda.org/conda-forge/fmpy). Maybe we should drop Windows 32-bit support altogether.

Opinions welcome!

**Comment by lmblanes** [comment]
Hi @t-sommer 

What is the latest stable python 32 bits compatible with FMpy?
```
  Could not find a version that satisfies the requirement pywin32; platform_system == "Windows" (from fmpy[complete]) (from versions: )
No matching distribution found for pywin32; platform_system == "Windows" (from fmpy[complete])
```
thanks!

**Comment by t-sommer** [comment]
All versions of FMPy still work on Windows 32-bit. Have you tried to install [pywin32 from PyPI](https://pypi.org/project/pywin32/) with `pip install pywin32`?

Anaconda also provides a 32-bit Windows installer in their [archive](https://repo.continuum.io/archive/) that contains all dependencies except PyQtGraph.

**Comment by lmblanes** [comment]
Thanks @t-sommer 
It's working ok. What really happens I think it is related to the fmu I am trying to simulate. As I see in the file infor:

> FMI Version       1.0
  FMI Type          Model Exchange
  Model Name        MyFMU
  Description       None
  Platforms         win32
  Continuous States 8
  Event Indicators  35
  Variables         3522
  Generation Tool   JModelica.org
  Generation Date 
  2018-08-03T11:02:09

**Comment by t-sommer** [comment]
We've had [multiple reports of broken OpenModelica FMUs in the past](https://github.com/CATIA-Systems/FMPy/issues?utf8=%E2%9C%93&q=is%3Aissue+openmodelica). Please try to simulate the model in another tool and open a new issue if the problem is reproducible.

**Comment by dmitrygrigoryev** [comment]
We are use the 32-bit FMPy to simulate some legacy models.
