### ISSUE TITLE
Write to csv file option doen't work, as expected: expected Integer, get an exponential 

### ISSUE THREAD

**Issue by syl2si** [CATIA-Systems/FMPy#647]
I use the FMPy (V0.3.19) with python (V3.8.8) to run my FMU during a pytest execution. 
I use the option (--otput-file output.csv) to write all the outputs to a output.csv file. 
I expect an Integer on one of the existing FMU outports, e.g. "-2147483648". 
I observe the value -2.14748e+09. 

The exponential representation would be also ok, but the last four characters "3648" get lost. This is completely wrong, and I need your help to resolve the issue.

**Additional Information:**

I use the output to validate the exact FMU output value against an expected in a test of our VECU-BUILDER product using pytest. The exact value is mandatory for the success of my defined pytest.

**Comment by t-sommer** [comment]
Can you share an FMU to reproduce the problem?

**Comment by syl2si** [comment]
[SimpleExample.zip](https://github.com/CATIA-Systems/FMPy/files/14190073/SimpleExample.zip)
Sure. Rename the zip back to fmu. It was not possible to upload the file type.

**Comment by syl2si** [comment]
Here is the input.csv file for fmu stimulation:
[input.csv](https://github.com/CATIA-Systems/FMPy/files/14190096/input.csv)

**Comment by syl2si** [comment]
Morning Torsten,


Thank you very much for the very quick fix.

When can I expect the fix? In which FMPy version?



Slawa Slabospizki


T +49 711 3423-2628
***@***.******@***.***>

ETAS GmbH, ETAS-DEV/XPC-Fe3
Borsigstraße 24, 70469 Stuttgart, Germany
www.etas.com<http://www.etas.com/>

ETAS – Empowering Tomorrow’s Automotive Software

Managing Directors: Dr. Thomas Irawan, Nicolet Eglseder, Mariella Minutolo
Chairman of the Supervisory Board: Dr. Walter Schirm
Registered Office: Stuttgart, Registration Court: Amtsgericht Stuttgart, HRB: 19033
​

**Comment by t-sommer** [comment]
It will go into the next release. We‘re working on getting it out.
