### ISSUE TITLE
Support for additional ODE solvers

### ISSUE THREAD

**Issue by magraeber** [CATIA-Systems/FMPy#65]
I would like to use **implicit** Euler method to simulate Model Exchange FMUs. Are there any plans to support additional ODE solvers besides CVODE and explicit Euler?

Would you accept a pull request with implicit Euler included? If yes, I would try to implement it.

**Comment by t-sommer** [comment]
I'd rather try to interface the [ODE solvers that come with SciPy](https://docs.scipy.org/doc/scipy/reference/integrate.html).

Can you describe your use case?

**Comment by magraeber** [comment]
I have two use cases in mind:
1. educational: demonstrate effects of stiffness with explicit vs. implicit Euler
2. find steady state working points by forward simulation with large step sizes.

The second uses case is described in the German Wikipedia article:
[https://de.wikipedia.org/wiki/Implizites_Euler-Verfahren]()

Using Scipy ODE solver sounds good. As far as I understand they don't have a simple implicit Euler method, but there is a general Base Class:
`scipy.integrate.OdeSolver`
If this Base Class is used in FMPy as interface, it should be possible to include other solvers.

**Comment by t-sommer** [comment]
If all you want is to pass your own solver implementation to `simulate_fmu()` we could extent it to accept an arbitrary class that implements the same methods as the [ForwardEuler](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/simulation.py#L331) and [CVodeSolver](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/sundials/__init__.py#L143) classes:

```
class ForwardEuler(object):

    def __init__(self, nx, nz, get_x, set_x, get_dx, get_z):
      ...

    def step(self, t, tNext):
       ...

    def reset(self, time):
        ...
```

**Comment by t-sommer** [comment]
If you want to try it out you can replace lines 629-651 in simulation.py with this

```python
    # select the solver
    if solver_name == 'Euler':
        solver = ForwardEuler(**solver_args)
        fixed_step = True
    elif solver_name is None or solver_name == 'CVode':
        from .sundials import CVodeSolver
        solver = CVodeSolver(set_time=fmu.setTime,
                             startTime=start_time,
                             maxStep=(stop_time - start_time) / 50.,
                             relativeTolerance=relative_tolerance,
                             **solver_args)
        step_size = output_interval
        fixed_step = False
    else:
        try:
            solver = solver_name(**solver_args)
            fixed_step = True
        except:
            raise Exception("Unknown solver: %s. Must be one of 'Euler' or 'CVode'." % solver_name)
```

and then pass your own solver

```python
from ctypes import *
import numpy as np
from fmpy import simulate_fmu

class ExplicitEuler(object):

    def __init__(self, nx, nz, get_x, set_x, get_dx, get_z):

        self.get_x = get_x
        self.set_x = set_x
        self.get_dx = get_dx
        self.get_z = get_z

        self.x = np.zeros(nx)
        self.dx = np.zeros(nx)
        self.z = np.zeros(nz)
        self.prez = np.zeros(nz)

        self._px = self.x.ctypes.data_as(POINTER(c_double))
        self._pdx = self.dx.ctypes.data_as(POINTER(c_double))
        self._pz = self.z.ctypes.data_as(POINTER(c_double))
        self._pprez = self.z.ctypes.data_as(POINTER(c_double))

        # initialize the event indicators
        self.get_z(self._pz, self.z.size)

    def step(self, t, tNext):

        # get the current states and derivatives
        self.get_x(self._px, self.x.size)
        self.get_dx(self._pdx, self.dx.size)

        # perform one step
        dt = tNext - t
        self.x += dt * self.dx

        # set the continuous states
        self.set_x(self._px, self.x.size)

        # check for state event
        self.prez[:] = self.z
        self.get_z(self._pz, self.z.size)
        stateEvent = np.any((self.prez * self.z) < 0)

        return stateEvent, tNext

    def reset(self, time):
        pass  # nothing to do


result = simulate_fmu('CoupledClutches.fmu', fmi_type='ModelExchange', solver=ExplicitEuler)
```

**Comment by magraeber** [comment]
Thanks, this would perfectly work for me. I will try it and report the results.

**Comment by t-sommer** [comment]
@magraeber, can we close this issue?

**Comment by magraeber** [comment]
Yes, it works perfectly.
