### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by AHaumer** [CATIA-Systems/FMPy#650]
Linux Mint 21.3 on VirtualBox 7.0.14 on Windows 11
Anaconda3-2023.09-0-Linux-x86_64 (Python 3.11)
FMPy 0.3.19
fmpy compile MyModel.fmu
fatal error: inttypes.h: No such file or directory
![grafik](https://github.com/CATIA-Systems/FMPy/assets/6900273/7ec3da87-26bf-47f2-aa70-5d12b395dd4a)
Simulating a fmu cross-compiled with Dymola and WSL on Windows works fine.

**Comment by t-sommer** [comment]
Can you share the FMU?

**Comment by AHaumer** [comment]
No problem. I tried it with different FMUs, this one is an example from MSL. 
I had to pack the fmu additionally into a zip.
[IMC_DOL.zip](https://github.com/CATIA-Systems/FMPy/files/14226564/IMC_DOL.zip)

**Comment by t-sommer** [comment]
`inttypes.h` was added with `C99`. Does your compiler support it?

**Comment by AHaumer** [comment]
Windows 11 64 bit:      Visual Studio 2022
Linux Mint 21.3 64 bit: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by AHaumer** [comment]
@t-sommer no idea? I'd have to prepare the FMUs for the new semester.

**Comment by AHaumer** [comment]
Sorry for bothering: The gcc-installation on my Linux (on a VM) was faulty. After a reinstallation the compilation works fine!
