### ISSUE TITLE
Issues with non-integer --output-interval in ModelExchange simulation of a Buildings FMU

### ISSUE THREAD

**Issue by casella** [CATIA-Systems/FMPy#655]
Hi,

we encountered a weird problem while testing OMC-generated FMUs of the Buildings library with FMPy. Steps to reproduce:
- get the development version of Buildings library from https://github.com/lbl-srg/modelica-buildings/
- get the latest OMC nightly build
- export `Buildings.Airflow.Multizone.Validation.ThreeRoomsContamDiscretizedDoor` as FMU-ME
- run 	
```python
python3 -m fmpy simulate  --output-file ThreeRoomsContamDiscretizedDoor_res.csv --start-time 0 --stop-time 3600 --timeout 50 --relative-tolerance 1e-06 --solver CVode  --interface-type ModelExchange --output-interval 5 ThreeRoomsContamDiscretizedDoor.fmu
```
the simulation runs successfully until time = 3600 and produces a simulation result file. This also works fine if you set `--output-interval 10`. 

However, if you set `--output-interval 7.2` or `--output.interval 5.7`, the simulation hangs somewhere before stopTime and eventually a partial result file is issued.

This is quite weird, maybe it's a problem with our installation, but if you can reproduce it, it would be nice to have it fixed. Keeping @deepak19015 and @AndreaBartolini in the loop.

Thanks!

**Comment by casella** [comment]
@t-sommer could you please give us some feedback about this issue? Thanks!

**Comment by casella** [comment]
Thanks t-sommer! This is not urgent, but I guess it needs to be fixed, eventually.

BTW, I hope you are getting much less headaches and complaints caused by OMC-generated FMUs these days, compared to when we met in Aachen last year. If you still do, please let me know, we are eager to improve and we now have the resources to do that.

**Comment by t-sommer** [comment]
We should use `isclose()` instead of a fixed epsilon when comparing floats to account for numerical tolerances (see also https://stackoverflow.com/questions/5595425/what-is-the-best-way-to-compare-floats-for-almost-equality-in-python).

**Comment by casella** [comment]
Thanks @t-sommer! Do you have plans for the next release of FMPy?

**Comment by t-sommer** [comment]
v0.3.21 is out.
