### ISSUE TITLE
spaces in dependencies

### ISSUE THREAD

**Issue by masoud-najafi** [CATIA-Systems/FMPy#66]
This XML crashes FMPY.

<?xml version="1.0" encoding="UTF-8"?>
	<fmiModelDescription fmiVersion="2.0" modelName="sb_amplif" description=" " generationTool="Activate" version="2019.1" guid="SCP_FMU_generator(2) ID= 3248.39-219274900-542745130" variableNamingConvention="flat" numberOfEventIndicators="0">
	  <ModelExchange modelIdentifier="sb_amplif" canBeInstantiatedOnlyOncePerProcess="false" canGetAndSetFMUstate="false" providesDirectionalDerivative="false"/>
	  <CoSimulation modelIdentifier="sb_amplif" canBeInstantiatedOnlyOncePerProcess="false" canGetAndSetFMUstate="false" providesDirectionalDerivative="false" canHandleVariableCommunicationStepSize="true" canInterpolateInputs="true" maxOutputDerivativeOrder="0"/>
	  <LogCategories>
	    <Category name="all" description="show all messages"/>
	    <Category name="fmicall" description="show only calls to the FMI block"/>
	    <Category name="event" description="show only events"/>
	    <Category name="error" description="show only error messages"/>
	    <Category name="warning" description="show only warning messages"/>
	    <Category name="info" description="show only information messages"/>
	  </LogCategories>
	  <DefaultExperiment startTime="0." stopTime="10." tolerance="1e-006"/>
	  <ModelVariables>
	    <ScalarVariable name="Ipar(3,1)" valueReference="4" description="index:1 ,parameter variable:SCSINT32_COP" causality="parameter" variability="fixed" initial="exact">
	      <Integer start="1"/>
	    </ScalarVariable>
	    <ScalarVariable name="Ipar(2,1)" valueReference="3" description="index:2 ,parameter variable:SCSINT32_COP" causality="parameter" variability="fixed" initial="exact">
	      <Integer start="1"/>
	    </ScalarVariable>
	    <ScalarVariable name="Ipar(1,1)" valueReference="2" description="index:3 ,parameter variable:SCSINT32_COP" causality="parameter" variability="fixed" initial="exact">
	      <Integer start="1"/>
	    </ScalarVariable>
	    <ScalarVariable name="Opar(3)" valueReference="1" description="index:4 ,parameter variable:SCSINT32_COP" causality="parameter" variability="fixed" initial="exact">
	      <Integer start="0"/>
	    </ScalarVariable>
	    <ScalarVariable name="Opar(2)" valueReference="0" description="index:5 ,parameter variable:SCSINT32_COP" causality="parameter" variability="fixed" initial="exact">
	      <Integer start="0"/>
	    </ScalarVariable>
	    <ScalarVariable name="Opar(1)" valueReference="4" description="index:6 ,parameter variable:SCSREAL_COP" causality="parameter" variability="fixed" initial="exact">
	      <Real start="12."/>
	    </ScalarVariable>
	    <ScalarVariable name="state[0]" valueReference="2" description="index:7 ,local variable:SCSREAL_COP" causality="local" variability="continuous" initial="exact">
	      <Real start="5.6"/>
	    </ScalarVariable>
	    <ScalarVariable name="der(state[0])" valueReference="3" description="index:8 ,local variable:SCSREAL_COP" causality="local" variability="continuous" initial="calculated">
	      <Real derivative="7"/>
	    </ScalarVariable>
	    <ScalarVariable name="Output" valueReference="1" description="index:9 ,output variable:SCSREAL_COP" causality="output" variability="continuous" initial="calculated">
	      <Real/>
	    </ScalarVariable>
	    <ScalarVariable name="Input" valueReference="0" description="index:10 ,input variable:SCSREAL_COP" causality="input" variability="continuous">
	      <Real start="0.0"/>
	    </ScalarVariable>
	  </ModelVariables>
	  <ModelStructure>
	    <Outputs>
	      <Unknown index="9" dependencies=" 10"/>
	    </Outputs>
	    <Derivatives>
	      <Unknown index="8"/>
	    </Derivatives>
	    <InitialUnknowns>
	      <Unknown index="9" dependencies=" 10"/>
	    </InitialUnknowns>
	  </ModelStructure>
	</fmiModelDescription>

**Comment by t-sommer** [comment]
Fixed with b414a171603e0b223fab2f3395c6002656edcc95

**Comment by t-sommer** [comment]
Thank you, @masoud-najafi !
