### ISSUE TITLE
Help!! Could anyone give me example to connect and run multi FMUs :((

### ISSUE THREAD

**Issue by clawdis** [CATIA-Systems/FMPy#662]
Help!! Could anyone give me example to connect and run multi FMUs :((

**Comment by t-sommer** [comment]
With FMPy you can only simulate individual FMUs. However you can create a Container FMU from multiple FMUs that you can simulate. See https://github.com/CATIA-Systems/FMPy/blob/main/tests/test_fmu_container.py for an example.
