### ISSUE TITLE
cant load the fmu with fmi3.0 that is exported by dymola

### ISSUE THREAD

**Issue by chrisemtan** [CATIA-Systems/FMPy#666]
dymola export the fmi2.0 fmu is easy to be read by fmpy. but the fmi3.0 version no matter 32-bit or64-bit or co-simulation or for model-exchange cant load by fmpy. error mention that Failed to validate modelDescription.xml: 
- ERROR (line 2941, column 0): Element 'Annotation', attribute 'order': The attribute 'order' is not allowed.
- ERROR (line 2953, column 0): Element 'Annotation', attribute 'order': The attribute 'order' is not allowed.
...
- ERROR (line 37420, column 0): Element 'Annotations': This element is not expected. Expected is ( Alias ).
- ERROR (line 37468, column 0): Element 'Annotations': This element is not expected. Expected is ( Alias ).
...
![屏幕截图 2024-04-22 203307](https://github.com/CATIA-Systems/FMPy/assets/100499027/bc8e4c45-9f53-472e-b043-04ea1186a730)
[fmu.zip](https://github.com/CATIA-Systems/FMPy/files/15063017/fmu.zip)

**Comment by chrisemtan** [comment]
> Can you share the FMU?

The ZIP I uploaded is the FMUs.
[fmu.zip](https://github.com/CATIA-Systems/FMPy/files/15070268/fmu.zip)

**Comment by t-sommer** [comment]
This problem should be resolved with Dymola 2024x Refresh 1. Please contact the Dymola support if the problem persists.
