### ISSUE TITLE
Example to create a simple FMU in MAC

### ISSUE THREAD

**Issue by sergiochavezlazo96** [CATIA-Systems/FMPy#673]
Hello, first of all thank you for having this project.
I am starting to learn and use FMU and I just can't find a simple example to create an FMU from scratch using FMPy. Does someone know where can I find one?
Thank you!

**Comment by t-sommer** [comment]
FMPy is a library to simulate (import) FMUs. If you need FMUs to experiment with you might want to take a look at the [Reference FMUs](https://github.com/modelica/reference-fmus). They come with source code and can be adapted to your needs.
