### ISSUE TITLE
How to get access to stored variable values with causality 'calculatedParameter' and variability 'fixed'?

### ISSUE THREAD

**Issue by janpeter19** [CATIA-Systems/FMPy#679]
I develop simulation scripts in Python using FMPy (and also PyFMI). For some Modelica models you have parameters that are defined as a function of other parameters. If you include these parameters in the list "output" of the simulate_fmu() function you get information about that "variable" stored.

Information stored is: name, variability, causality etc. The variability and causality are here correctly: 'fixed' and 'calculatedParameter'. But where is the actual value stored?

Since this is a calculated parameter it is not natural to also include it in the start_values list to the simulate_fmu() function. This means here is not any start value stored.

I currently use FMPy ver 0.3.20 in a Python 3.12.3 environment on Windows. Using PyFMI for the same FMU I have no problem to extract the values of these derived parameters.

I suspect here is a recent change and for 0.3.19 the derived parameter might have been stored in the field 'start', but I have not been able to check. But my scripts for FMPy have worked fine before, but here is a change of FMUs as well.

(see Stackoverflow post: https://stackoverflow.com/questions/78773149/how-with-fmpy-to-get-access-to-stored-variable-values-with-causality-calculate)

**Comment by t-sommer** [comment]
Can you share an example to reproduce the problem?

**Comment by janpeter19** [comment]
I have an example of running the FMU with FMPy 0.3.20 at Github and with a click you can start up a Colab notebook (simulation Ion Exchange Chromatography).  See the hyperlink at the later part of the page. 

https://github.com/janpeter19/BPL_IEC_validation

After the first simulation and shown diagrams. I have a few notebook cells just for checking some (derived) parameter values that now is commented-out, since you cannot access them. If you take away "#" you can run the command and see the problem. Focus on "commands" model_get(). 

The python code that do model_get() you find in the setup file 

BPL_IEC_fmpy_explore.py

In the setup-file you also see under the heading "Extra only for describe()" those few parameters that are derived form other parameters that you can change as a user (with the python function par(height=25) while default is 20 [cm].

The Modelica application I cannot share, but I can later this week put together a very small example that illustrates the problem. But you may solve the problem before that, hopefully.

**Comment by janpeter19** [comment]
Perhaps a Modelica code extract that shows the column parameters and the derived ones is clarifying.  See attached file. 

[column-properties.txt](https://github.com/user-attachments/files/16337991/column-properties.txt)

**Comment by t-sommer** [comment]
So you you want to retrieve the value of variable `b` of the following Modelica model, exported as an FMU?

```Modelica
model CalculatedParameters
  parameter Real a = 2;
  parameter Real b = 3 * a;
  output Real c;
equation 
  c = b;
end CalculatedParameters;
```

**Comment by janpeter19** [comment]
Yes!Skickat från min iPhone23 juli 2024 kl. 14:14 skrev Torsten Sommer ***@***.***>:﻿
So you you want to retrieve the value of variable b of the following Modelica model, exported as an FMU?
model CalculatedParameters
  parameter Real a = 2;
  parameter Real b = 3 * a;
  output Real c;
equation 
  c = b;
end CalculatedParameters;

**Comment by jbernalr** [comment]
one way to do what you want is to associate the value of the desired variable to a global model variable

**Comment by janpeter19** [comment]
Well, I am aware of the possibility to let the “derived” parameter to be a variable and then stored as a time series (that remains constant). But it is a solution I do not really like. I think there is a general need to address initial calculations like my example and most likely there is a solution in the current FMPy version, but I do not see it. On the other hand, if here is a gap, perhaps here is a motivation to fix it from Torsten et al. Skickat från min iPhone24 juli 2024 kl. 11:08 skrev i. Bernal ***@***.***>:﻿
one way to do what you want is to associate the value of the desired variable to a global model variable

**Comment by janpeter19** [comment]
I have extended and played with Torstens simplified example. The extension I do with inclusion of a model within a model is more similar to the actual problem, but perhaps do not add anything to the core problem after all.

The instantiation of the internal model using calculate parameters brings questions of the sequence of calculations. But if keep our "functional language" mindset we do not get confused.

Example 4 shows just thet extension of Torstens example with the internal model calcParFun that is instansiated with calculated parameter b

Example 5 shows moving calculation of parameter b to an initial equation section. 

Example 6 shows introduction of a calculation also in the argument of the instantiated function calc_par_fun.

All three models works well in OpenModelica (as well as in JModelica). The FMU generated works with both FMPy and PyFMI. However, in all thee examples you cannot get out the value of the calculated parameter b using FMPy. 

I am tempted to actually use an initial equations to do the calculation of parameter in this way to perhaps improve readability of the code. However, the reader must then have then "functional mindset" and understand that initial equations is calculated before the execution of the arguments for the instantiation of calc_par_fun. 

But I really would like to see that FMPy could retrieve the calculated b parameter, somehow. And today I do not understand how. Perhaps something very simple. But I can also imagine that the FMI-standard may not cover calculation before time=0, sort of, or what do you think?

[Examples 456.zip](https://github.com/user-attachments/files/16407992/Examples.456.zip)

**Comment by t-sommer** [comment]
Exporting model `calcPar4.mo`

```Modelica
model calcPar

  parameter Real a=2;
  parameter Real b=3*a;
  output Real c;
	
  model calcParFun
    parameter Real b;
    output Real out;
    equation
      out = b;
  end calcParFun;
	
  calcParFun calc_par_fun(b=b);
	
equation
  c = calc_par_fun.b;
end calcPar;
```

with Dymola 2024x Refresh 1 results in an FMU with the following `modelDescription.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<fmiModelDescription
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  fmiVersion="2.0"
  modelName="calcPar"
  guid="{7ff2283c-da3f-47e3-b5c4-2bd58bad4f4f}"
  generationTool="Dymola Version 2024x Refresh 1, 2024-05-07"
  generationDateAndTime="2024-07-29T07:44:45Z"
  variableNamingConvention="structured"
  numberOfEventIndicators="0">
  <!-- ... -->
  <ModelVariables>
    <!-- Index for next variable = 1 -->
    <ScalarVariable
      name="a"
      valueReference="16777216"
      causality="parameter"
      variability="fixed">
      <Real start="2"/>
    </ScalarVariable>
    <!-- Index for next variable = 2 -->
    <ScalarVariable
      name="b"
      valueReference="100663296"
      variability="fixed">
      <Real/>
    </ScalarVariable>
    <!-- Index for next variable = 3 -->
    <ScalarVariable
      name="c"
      valueReference="67108864"
      causality="output">
      <Real/>
    </ScalarVariable>
    <!-- Index for next variable = 4 -->
    <ScalarVariable
      name="calc_par_fun.b"
      valueReference="100663297"
      variability="fixed">
      <Real/>
    </ScalarVariable>
    <!-- Index for next variable = 5 -->
    <ScalarVariable
      name="calc_par_fun.out"
      valueReference="100663297"
      variability="fixed">
      <Real/>
    </ScalarVariable>
  </ModelVariables>
  <!-- ... -->
</fmiModelDescription>
```

With the following code you can set `a` and retrieve `b` (or any other variable for that matter)

```Python
from fmpy import *

result = simulate_fmu(
    'calcPar.fmu',
    start_values={'a': 3},  # set a different start value for variable "a"
    output=['b'],           # record variable "b"
    output_interval=1,      # simulate one step
    stop_time=1,
    fmi_call_logger=print   # log the FMI calls
)

b = result['b'][0]  # get the value of variable "b"

print(f'Value of variable "b" is {b}.')
```

```
fmi2Instantiate(instanceName="calcPar", fmuType=1, guid="{7ff2283c-da3f-47e3-b5c4-2bd58bad4f4f}", resourceLocation="file:///C:/Users/xxx/AppData/Local/Temp/tmp8aluws5m/resources", callbacks=fmi2CallbackFunctions(logger=0x000002BB8E275A40, allocateMemory=0x000002BB8E275A40, freeMemory=0x000002BB8E275A40, stepFinished=0x000002BB8E275A40, componentEnvironment=0x0), visible=0, loggingOn=0) -> 0x2bb8dd69150
fmi2SetupExperiment(component=0x2bb8dd69150, toleranceDefined=1, tolerance=0.0001, startTime=0.0, stopTimeDefined=1, stopTime=1.0) -> OK
fmi2SetReal(component=0x2bb8dd69150, vr=[16777216], nvr=1, value=[3.0]) -> OK
fmi2EnterInitializationMode(component=0x2bb8dd69150) -> OK
fmi2ExitInitializationMode(component=0x2bb8dd69150) -> OK
fmi2GetReal(component=0x2bb8dd69150, vr=[100663296], nvr=1, value=[9.0]) -> OK
fmi2DoStep(component=0x2bb8dd69150, currentCommunicationPoint=0.0, communicationStepSize=1, noSetFMUStatePriorToCurrentPoint=1) -> OK
fmi2GetReal(component=0x2bb8dd69150, vr=[100663296], nvr=1, value=[9.0]) -> OK
fmi2Terminate(component=0x2bb8dd69150) -> OK
fmi2FreeInstance(component=0x2bb8dd69150)
Value of variable "b" is 9.0.
```

**Comment by janpeter19** [comment]
So you mean that here is a field "value", in parallell with "variability", "causality", "start", etc, where I can perhaps get both value of calculated parameter, as well as parameter, right?

Could the tool of translation differ here between current Dymola you refer to and current OpenModelica? I doubt that since my question is very basic, but I ask anyway.

**Comment by janpeter19** [comment]
I will try and make some tests later, but no access to my computer for some time.

**Comment by janpeter19** [comment]
Now I understand "the issue" and it is entirely due my misunderstanding of how FMPy works.

The calculated parameters are results from simulation, although done "before" time=0, sort of, and stored in the result-file from a simulation. Here the calculated parameters are stored as time series, although here is only a calculation "before" time = 0. Thus FMPy also store fixed calculated parameters as time series, in the same way as PyFMI, although I would prefer just a single value. 

Thank you Torsten Sommer for working through the example!
