### ISSUE TITLE
Check for start values

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMPy#68]
It would be good to include in `validate_test_fmu`  a check  if start values are set accoding to  “If  initial= exact or approx, or causality = ′′input′′ a start value must be provided”. on p. 47 of the FMI 2.0 standard.

**Comment by t-sommer** [comment]
@chrbertsch, can you provide an FMU that violates this rule?

**Comment by t-sommer** [comment]
@chrbertsch, with [the additional check](https://github.com/CATIA-Systems/FMPy/commit/7e7d664f27745b424eee5e00ab8262c416bcef0f) I couldn't find any FMUs that violate the above rule.

**Comment by chrbertsch** [comment]
Actually it was just a suspicion, but I think I was wrong (I cannot share the FMU);
Here is  a simple test FMU :-) (just remove the ending zip)
[Feedthrough.fmu.zip](https://github.com/CATIA-Systems/FMPy/files/2963596/Feedthrough.fmu.zip)
