### ISSUE TITLE
CoSim FMU causes fmpy.gui to crash

### ISSUE THREAD

**Issue by AHaumer** [CATIA-Systems/FMPy#689]
I exported an FMU from OpenModelica btoh ME and CoSim v.2.0: It is the bouncing ball (see enclosed source and FMU).
The ME version runs but shows incorrect result at the end, it seems that some when-clauses are not handled correctly.
So I tried CoSim but the simulation gets stuck just before the first reflection of the ball and subsequently the gui crashes.
Interesting: In Simulink ME shows of course the same shows incorrect result, but CoSIm runs smoothly and shows correct results.
[BouncingBall.zip](https://github.com/user-attachments/files/16740274/BouncingBall.zip)

**Comment by t-sommer** [comment]
Can you try to run the FMU in the FUMSim GUI https://github.com/modelica/Reference-FMUs/releases/tag/v0.0.33 ?

**Comment by AHaumer** [comment]
Works in FMUSim both as ME and CS without crash. 
Yes a nice example where CS works well if one takes care about the communication interval but ME delivers nonsens.
Sorry I didn't know FMUSim. Why didn't you try this yourself? The FMU is enclosed as zip.

**Comment by t-sommer** [comment]
When I re-export the FMU with OpenModelica v1.23.1 (64-bit), I can successfully simulate it as both CS and ME with a710177756745ca1010a14d4e79999bba4dcbb93. I assume it is a bug in the OpenModelica export.
