### ISSUE TITLE
Running FMUs in GUI in Anaconda using FMus from Dymola that require license

### ISSUE THREAD

**Issue by lvanfretti** [CATIA-Systems/FMPy#69]
Hi @t-sommer 

Here's an issue I'm having.

I'm running the GUI from the Anaconda Prompt. 
When loading the FMU attached, I am not able to run again the simulation. At first I thought that this could be fixed by adding the environment variable within the Conda prompt, however, this doesn't seem to fix the problem.

![Screenshot 2019-03-15 14 48 49](https://user-images.githubusercontent.com/7248948/54455225-a47aed80-4731-11e9-9fe7-b0c6bc660c5a.png)
Any suggestions?

Luigi

[Tutorial_Example_01_Example_01.zip](https://github.com/CATIA-Systems/FMPy/files/2972473/Tutorial_Example_01_Example_01.zip)

**Comment by t-sommer** [comment]
The attached FMU contains no implementation. "Platforms" should contain at leas one entry (see also your screenshot).

**Comment by lvanfretti** [comment]
I made the mistake of not select binaries option in the dialog.

Now that platforms are included, but still the same problem.
Any ideas?
![Screenshot 2019-03-17 08 33 13](https://user-images.githubusercontent.com/7248948/54490817-a9ee4a00-488f-11e9-93c0-4a04d55c0e77.png)
![Screenshot 2019-03-17 08 33 22](https://user-images.githubusercontent.com/7248948/54490818-aa86e080-488f-11e9-8e06-bf9e33c17d1a.png)
[Tutorial_Example_01_Example_01_0fmu.zip](https://github.com/CATIA-Systems/FMPy/files/2975132/Tutorial_Example_01_Example_01_0fmu.zip)

**Comment by lvanfretti** [comment]
@t-sommer 

I exported the FMU using a different tool who's name shall not be mentioned ;-) and everything is working.

[OpenIPSL_Tutorial_Example_1_Example_1_fmu.zip](https://github.com/CATIA-Systems/FMPy/files/2975655/OpenIPSL_Tutorial_Example_1_Example_1_fmu.zip)


![Screenshot 2019-03-17 16 06 00](https://user-images.githubusercontent.com/7248948/54497252-c8276a80-48ce-11e9-8f91-58e6a407c9ca.png)

![Screenshot 2019-03-17 16 06 44](https://user-images.githubusercontent.com/7248948/54497253-c8276a80-48ce-11e9-90f2-eda81325a7c9.png)

This is definitely an issue of how I am exporting the model from Dymola or however the check for the local license is being done by fmpy or a problem from using Anaconda as the Python environment and how the environment variables get pass on, or most likely, something else I don't understand.

If you want me to keep testing on the FMU export from Dymola in my set-up, I'd be happy to help, this can be a likely issue with other beginners that use Dymola mainly...

**Comment by t-sommer** [comment]
@lvanfretti, have you tried to set the license path as a system wide environment variable?

**Comment by lvanfretti** [comment]
Like this? If so, yes.

Luigi

**Comment by MaxPanzer** [comment]
> 
Hi ivanfretti, 
with which tool did you export the .fmu file?
I have exactly the same problem when opening a file under Anaconda.
I hope you can help me with this! Thank you very much!

**Comment by lvanfretti** [comment]
@MaxPanzer I got a Dymola license that allows to generate FMUs that can be used in other machines without a license, so this was my work around.
