### ISSUE TITLE
co-simulation with dymola solver can not deseriealize fmu state

### ISSUE THREAD

**Issue by leleyouyou57** [CATIA-Systems/FMPy#691]
in my project ， i uses a clara plus library， export fmu （version2.0 type co-silulation with dymola solver）， serialize fmu state is ok， but can not deserialize fmu state .
code as below:

```Python
import shutil
from fmpy import read_model_description, extract
from fmpy.fmi2 import FMU2Slave

# set FMU path
fmu_filename = 'system0d_test.fmu'

# read_model_description
model_description = read_model_description(fmu_filename)
# extract fmu
unzipdir = extract(fmu_filename)
print(unzipdir)
serialization_file = 'fmu_state.dat'  # 定义一个明确的文件名
simulation_time = 10

# #  creat FMU instance
fmu = FMU2Slave(guid=model_description.guid,
                unzipDirectory=unzipdir,
                modelIdentifier=model_description.coSimulation.modelIdentifier,
                instanceName='instance1')

#  load FMU
fmu.instantiate()

# initialize FMU
fmu.setupExperiment(startTime=0)
fmu.enterInitializationMode()
fmu.exitInitializationMode()

# 
fmu.doStep(currentCommunicationPoint=0, communicationStepSize=simulation_time)

# get FMU state
state = fmu.getFMUstate()

#serialize FMU state
serialized_state = fmu.serializeFMUstate(state)

# save state to file
with open(serialization_file, 'wb') as f:
    f.write(serialized_state)

print("FMU state has been saved to", serialization_file)

# stop and clear FMU instance
fmu.terminate()
fmu.freeInstance()
shutil.rmtree(unzipdir, ignore_errors=True)

# ------ deserialize fmu state process ------

# reload and creat fmu instance
unzipdir = extract(fmu_filename)
fmu = FMU2Slave(guid=model_description.guid,
                unzipDirectory=unzipdir,
                modelIdentifier=model_description.coSimulation.modelIdentifier,
                instanceName='instance2')

# load FMU
fmu.instantiate()

# initialize FMU
fmu.setupExperiment(startTime=simulation_time)
fmu.enterInitializationMode()
fmu.exitInitializationMode()

# 
with open(serialization_file, 'rb') as f:
     serialized_state = f.read()


# deserialize FMU state
try:
    state = fmu.deSerializeFMUstate(serialized_state)


# set FMU state 
fmu.setFMUState(state)

# running simulation
fmu.doStep(currentCommunicationPoint=simulation_time, communicationStepSize=10
```

**Comment by leleyouyou57** [comment]
PS："It cannot be deserialized independently."

**Comment by ZiweiGuogg** [comment]
Have you solved it yet? I also encountered this problem

**Comment by t-sommer** [comment]
This seems to be a limitation of the FMU. @KarlWernersson, do you have an idea why this fails?

**Comment by KarlWernersson** [comment]
No not with the info here simplest is if you can make a support with Dymola through your Dymola reseller, where you provide the original Modellica model and we can debug it. If you can't provide the original mo try making a similar model with the same behavior that you can share.

**Comment by leleyouyou57** [comment]
Fmu：
Dymola Version：2023
Library：ClaraPlus v1.6.0
fmu type：2.0 co-simulation with dymola solver
sourece：ClaRaPlus.Examples.SteamCycle_02

Source Code：
`import shutil
from fmpy import read_model_description, extract
from fmpy.fmi2 import FMU2Slave

# set FMU path
fmu_filename = 'SteamCycle_002.fmu'

# read_model_description
model_description = read_model_description(fmu_filename)
# extract fmu
unzipdir = extract(fmu_filename)
serialization_file = 'fmu_state.dat'
simulation_time = 10

# #  creat FMU instance
fmu = FMU2Slave(guid=model_description.guid,
                unzipDirectory=unzipdir,
                modelIdentifier=model_description.coSimulation.modelIdentifier,
                instanceName='instance1')

#  load FMU
fmu.instantiate()

# initialize FMU
fmu.setupExperiment(startTime=0)
fmu.enterInitializationMode()
fmu.exitInitializationMode()

fmu.doStep(currentCommunicationPoint=0, communicationStepSize=simulation_time)
print('Simulation completed')

# get FMU state
state = fmu.getFMUstate()

# serialize FMU state
serialized_state = fmu.serializeFMUstate(state)
print('Serialization completed')

# save state to file
with open(serialization_file, 'wb') as f:
    f.write(serialized_state)

# stop and clear FMU instance
fmu.terminate()
fmu.freeInstance()
shutil.rmtree(unzipdir, ignore_errors=True)

# ------ deserialize fmu state process ------

# reload and creat fmu instance
fmu = FMU2Slave(guid=model_description.guid,
                unzipDirectory=unzipdir,
                modelIdentifier=model_description.coSimulation.modelIdentifier,
                instanceName='instance2')

# load FMU
fmu.instantiate()

# initialize FMU
fmu.setupExperiment(startTime=simulation_time)
fmu.enterInitializationMode()
fmu.exitInitializationMode()


with open(serialization_file, 'rb') as f:
    serialized_state = f.read()

# deserialize FMU state
try:
    state = fmu.deSerializeFMUstate(serialized_state)
    print("deSerialization completed")
except Exception as e:
    print("Error occurred during deserialization:", e)

# set FMU state
fmu.setFMUState(state)

# running simulation
fmu.doStep(currentCommunicationPoint=simulation_time, communicationStepSize=10)
print('Simulation completed again')`


Results：
1..Run the complete program
`Simulation completed
Serialization completed
deSerialization compelted
Simulation completed again

Precess finished with exit code 0`

2.After running the program in its entirety, generate the fmu_state.dat file locally and annotate the content of the serialized save state (in deserialze fmu state section). Only run the code section for deserializing the loaded state, and deserialization will result in an error.
`Traceback(most recent call last):
File "test\state test fmi2.0.py", line 76, in <module>
fmu.setFMUState(state)NameError: name 'state'is not definedError occurred during deserialization: exception: access violation writing 0x0000020634031040
Process finished with exit code 1`

This is the source code and FMU related to this issue. Thank you for your support

**Comment by leleyouyou57** [comment]
Unfortunately, the FMU exceeds 25mb and I am unable to upload it. Can you export it yourself or send it to you through other contact information?

**Comment by t-sommer** [comment]
This is not a problem with FMPy. Please contact the Dymola support.
