### ISSUE TITLE
Error importing FMU 3.0 with string parameter exported from Dymola 2024x Refresh 1 in FMPy

### ISSUE THREAD

**Issue by adwait-gm** [CATIA-Systems/FMPy#696]
I am getting an error trying to simulate FMU 3.0 with string parameters in FMPy. There seems to be an issue with the modelDescription.xml file. If I try to import an FMU 3.0 exported with a string parameter with `annotation(Evaluate=false)` using Dymola 2024X R1 then it gives the following error. 

![error](https://github.com/user-attachments/assets/81d466d2-2413-4b0e-ad95-6dce734a6406)

The following flag was used to export the FMU using Dymola 2024X R1

`Advanced.FMI.AllowStringParametersForFMU=true` 

The FMU imports in Dymola itself, but not in FMPy. Please find the example model to replicate this error. The FMU imports without errors in FMPy if I set `Evaluate=true` for the string parameter.

Model Code:
```
model StringParameterModel
  parameter String stringParameter = "str" annotation(Evaluate=false);
  output Real y = sin(time);
end StringParameterModel;
```
Steps to recreate:
1. Export StringParameterModel as Model-Exchange FMU3 in Dymola with Evaluate=false, FMU will fail to import on FMPy because of XML issue.
2. Export StringParameterModel as Model-Exchange FMU3 in Dymola with Evaluate=true, FMU will import and run on FMPy.

**Comment by t-sommer** [comment]
I cannot reproduce the problem with Dymola 2024x Refresh 1, 2024-05-07. Can you share the faulty FMU?

**Comment by t-sommer** [comment]
This is a bug in Dymola. I forwarded the issue to the Dymola team.

**Comment by KarlWernersson** [comment]
Will be included in Dymola 2025x
Fix pack will be available for Dymola 2024x Refresh 1 by contacting Dymola support through your retailer.
