### ISSUE TITLE
First input is repeated when using simulate_fmu

### ISSUE THREAD

**Issue by MarkusSchumacherVG** [CATIA-Systems/FMPy#697]
When using the convinience function simulate_fmu with an external input to the FMU the first input value is used for the first two time-steps. Is that behaviour intended or a bug?

This issue seems to be induced by the order of input.apply, fmiDoStep and recorder.apply in the sub-function simulateCS.

Thanks for your help!

**Comment by t-sommer** [comment]
Can you share an example to reproduce the problem?

**Comment by MarkusSchumacherVG** [comment]
The content of the FMU is not relevant. You just need to set a Real continous input and route it though as an output. Then you can compare desired vs. actual intput. The result should be the same as with the FMU that I used.

**Comment by MarkusSchumacherVG** [comment]
[HeatPumpLib_FMU_Sandbox_ResidentialBuilding.zip](https://github.com/user-attachments/files/17339206/HeatPumpLib_FMU_Sandbox_ResidentialBuilding.zip)

**Comment by t-sommer** [comment]
Can you simulate with

```Python
simulate_fmu(..., fmi_call_logger=print)
```
and share the relevant output?

**Comment by MarkusSchumacherVG** [comment]
fmi2SetupExperiment(component=0x28b725da550, toleranceDefined=1, tolerance=0.0001, startTime=0.0, stopTimeDefined=1, stopTime=14400.0) -> OK
fmi2EnterInitializationMode(component=0x28b725da550) -> OK
fmi2SetReal(component=0x28b725da550, vr=[352321536], nvr=1, value=[293.15]) -> OK
fmi2ExitInitializationMode(component=0x28b725da550) -> OK
fmi2GetReal(component=0x28b725da550, vr=[335544320, 335544321, 335544322, 335544323, 335544324, 335544325, 335544326, 335544327, 335544328, 335544329, 335544330, 335544331, 335544332, 335544333, 335544334, 335544335, 67108880, 67108881, 67108882, 67108883, 335544340, 335544341, 335544342, 335544343, 335544344, 335544345, 335544346, 335544347, 335544348, 335544349, 335544350, 335544351, 335544352, 335544353, 335544354, 335544355, 335544356, 335544357, 335544358, 335544359, 67108904, 67108905, 67108906, 67108907, 335544364, 335544365, 335544366, 335544367, 335544368, 335544369, 335544370], nvr=51, value=[293.15, 0.0, 0.0, 273.25, 269.65, 262.80818274099244, 0.8200000000000001, 0.0, 0.0, 0.0, 270.5, 2.6179938779914944, 5.8, 20000.0, 0.5, 0.75, 0.8932572527146457, 0.12556517183534113, 0.0, 101325.0, -1.073097835457442, -0.40288613372050763, -3.0317654355195782, 2.6438941622523386, 1510.232657060692, 0.0, 273.25, 273.25, 269.65, 262.80818274099244, 0.8200000000000001, 0.0, 0.0, 0.0, 270.5, 2.6179938779914944, 5.8, 20000.0, 0.5, 0.75, 0.8932572527146457, 0.12556517183534113, 0.0, 101325.0, -1.073097835457442, -0.40288613372050763, -3.0317654355195782, 2.6438941622523386, 1510.232657060692, 0.0, 293.15]) -> OK
fmi2SetReal(component=0x28b725da550, vr=[352321536], nvr=1, value=[293.15]) -> OK
fmi2DoStep(component=0x28b725da550, currentCommunicationPoint=0.0, communicationStepSize=3600, noSetFMUStatePriorToCurrentPoint=1) -> OK
fmi2GetReal(component=0x28b725da550, vr=[335544320, 335544321, 335544322, 335544323, 335544324, 335544325, 335544326, 335544327, 335544328, 335544329, 335544330, 335544331, 335544332, 335544333, 335544334, 335544335, 67108880, 67108881, 67108882, 67108883, 335544340, 335544341, 335544342, 335544343, 335544344, 335544345, 335544346, 335544347, 335544348, 335544349, 335544350, 335544351, 335544352, 335544353, 335544354, 335544355, 335544356, 335544357, 335544358, 335544359, 67108904, 67108905, 67108906, 67108907, 335544364, 335544365, 335544366, 335544367, 335544368, 335544369, 335544370], nvr=51, value=[293.14992721058803, 1917.457832990739, 6472.60673203248, 272.75, 268.34999999999997, 262.80818274099244, 0.78, 0.0, 0.0, 0.0, 270.5, 2.548180707911721, 6.9, 20000.0, 0.5, 0.875, 0.8932572527146457, 0.12556517183534113, 0.0, 101325.0, -1.0024338897415341, -0.40283294927680513, -2.770047661037579, 2.5732302165364307, 5109.11039339075, 3600.0, 272.75, 272.75, 268.34999999999997, 262.80818274099244, 0.78, 0.0, 0.0, 0.0, 270.5, 2.548180707911721, 6.9, 20000.0, 0.5, 0.875, 0.8932572527146457, 0.12556517183534113, 0.0, 101325.0, -1.0024338897415341, -0.40283294927680513, -2.770047661037579, 2.5732302165364307, 5109.11039339075, 3600.0, 293.15]) -> OK
fmi2SetReal(component=0x28b725da550, vr=[352321536], nvr=1, value=[293.4088190451025]) -> OK
fmi2DoStep(component=0x28b725da550, currentCommunicationPoint=3600.0, communicationStepSize=3600, noSetFMUStatePriorToCurrentPoint=1) -> OK
fmi2GetReal(component=0x28b725da550, vr=[335544320, 335544321, 335544322, 335544323, 335544324, 335544325, 335544326, 335544327, 335544328, 335544329, 335544330, 335544331, 335544332, 335544333, 335544334, 335544335, 67108880, 67108881, 67108882, 67108883, 335544340, 335544341, 335544342, 335544343, 335544344, 335544345, 335544346, 335544347, 335544348, 335544349, 335544350, 335544351, 335544352, 335544353, 335544354, 335544355, 335544356, 335544357, 335544358, 335544359, 67108904, 67108905, 67108906, 67108907, 335544364, 335544365, 335544366, 335544367, 335544368, 335544369, 335544370], nvr=51, value=[293.4088330106029, 2104.891688554875, 7085.16936894428, 272.65, 267.45, 264.13401706682015, 0.74, 0.0, 0.0, 0.0, 276.0, 2.522000769131806, 7.6, 20000.0, 0.5, 0.875, 0.8932572527146457, 0.12556517183534113, 0.0, 101325.0, -0.879286512239716, -0.4027795471132453, -2.5083298535086573, 2.4500828390346125, 8707.988584148608, 7200.0, 272.65, 272.65, 267.45, 264.13401706682015, 0.74, 0.0, 0.0, 0.0, 276.0, 2.522000769131806, 7.6, 20000.0, 0.5, 0.875, 0.8932572527146457, 0.12556517183534113, 0.0, 101325.0, -0.879286512239716, -0.4027795471132453, -2.5083298535086573, 2.4500828390346125, 8707.988584148608, 7200.0, 293.4088190451025]) -> OK
fmi2SetReal(component=0x28b725da550, vr=[352321536], nvr=1, value=[293.65]) -> OK
fmi2DoStep(component=0x28b725da550, currentCommunicationPoint=7200.0, communicationStepSize=3600, noSetFMUStatePriorToCurrentPoint=1) -> OK
fmi2GetReal(component=0x28b725da550, vr=[335544320, 335544321, 335544322, 335544323, 335544324, 335544325, 335544326, 335544327, 335544328, 335544329, 335544330, 335544331, 335544332, 335544333, 335544334, 335544335, 67108880, 67108881, 67108882, 67108883, 335544340, 335544341, 335544342, 335544343, 335544344, 335544345, 335544346, 335544347, 335544348, 335544349, 335544350, 335544351, 335544352, 335544353, 335544354, 335544355, 335544356, 335544357, 335544358, 335544359, 67108904, 67108905, 67108906, 67108907, 335544364, 335544365, 335544366, 335544367, 335544368, 335544369, 335544370], nvr=51, value=[293.6500237511927, 2240.7091607741713, 7606.984644692913, 272.95, 267.34999999999997, 264.89631652750205, 0.72, 0.0, 0.0, 0.0, 279.2, 2.5394540616517496, 7.9, 20000.0, 0.5, 0.875, 0.8932572527146457, 0.12556517183534113, 0.0, 101325.0, -0.7289928175829461, -0.4027259272719727, -2.246612012801403, 2.2997891443778427, 12306.867231141297, 10800.0, 272.95, 272.95, 267.34999999999997, 264.89631652750205, 0.72, 0.0, 0.0, 0.0, 279.2, 2.5394540616517496, 7.9, 20000.0, 0.5, 0.875, 0.8932572527146457, 0.12556517183534113, 0.0, 101325.0, -0.7289928175829461, -0.4027259272719727, -2.246612012801403, 2.2997891443778427, 12306.867231141297, 10800.0, 293.65]) -> OK
fmi2SetReal(component=0x28b725da550, vr=[352321536], nvr=1, value=[293.85710678118653]) -> OK
fmi2DoStep(component=0x28b725da550, currentCommunicationPoint=10800.0, communicationStepSize=3600, noSetFMUStatePriorToCurrentPoint=1) -> OK
fmi2GetReal(component=0x28b725da550, vr=[335544320, 335544321, 335544322, 335544323, 335544324, 335544325, 335544326, 335544327, 335544328, 335544329, 335544330, 335544331, 335544332, 335544333, 335544334, 335544335, 67108880, 67108881, 67108882, 67108883, 335544340, 335544341, 335544342, 335544343, 335544344, 335544345, 335544346, 335544347, 335544348, 335544349, 335544350, 335544351, 335544352, 335544353, 335544354, 335544355, 335544356, 335544357, 335544358, 335544359, 67108904, 67108905, 67108906, 67108907, 335544364, 335544365, 335544366, 335544367, 335544368, 335544369, 335544370], nvr=51, value=[293.84443746848854, 2336.3220494053053, 8000.0, 273.25, 267.04999999999995, 265.0385173391268, 0.6900000000000001, 0.0, 0.0, 0.0, 279.8, 2.5569073541716927, 8.2, 20000.0, 0.5, 1.0, 0.8932572527146457, 0.12556517183534113, 0.0, 101325.0, -0.5673248938837063, -0.4026720897952974, -1.9848941387844727, 2.138121220678603, 15905.7463361749, 14400.0, 273.25, 273.25, 267.04999999999995, 265.0385173391268, 0.6900000000000001, 0.0, 0.0, 0.0, 279.8, 2.5569073541716927, 8.2, 20000.0, 0.5, 1.0, 0.8932572527146457, 0.12556517183534113, 0.0, 101325.0, -0.5673248938837063, -0.4026720897952974, -1.9848941387844727, 2.138121220678603, 15905.7463361749, 14400.0, 293.85710678118653]) -> OK
fmi2Terminate(component=0x28b725da550) -> OK
fmi2FreeInstance(component=0x28b725da550)

**Comment by MarkusSchumacherVG** [comment]
![image](https://github.com/user-attachments/assets/ecd62b50-fd66-4951-bb13-fdbfde368afb)

The input at 3600s should be 293.40882 instead of 293.15 doesn't it? Or am I missing out on something here?

**Comment by t-sommer** [comment]
> The input at 3600s should be 293.40882 instead of 293.15 doesn't it?

The input value for variable `TSetRoom` (value reference `352321536`) is `293.4088190451025` at `currentCommunicationPoint=3600.0`:

```
fmi2SetupExperiment(component=0x28b725da550, toleranceDefined=1, tolerance=0.0001, startTime=0.0, stopTimeDefined=1, stopTime=14400.0) -> OK
fmi2EnterInitializationMode(component=0x28b725da550) -> OK
fmi2SetReal(component=0x28b725da550, vr=[352321536], nvr=1, value=[293.15]) -> OK
fmi2ExitInitializationMode(component=0x28b725da550) -> OK

fmi2GetReal(component=0x28b725da550, vr=[..., 335544370], nvr=51, value=[..., 293.15]) -> OK

fmi2SetReal(component=0x28b725da550, vr=[352321536], nvr=1, value=[293.15]) -> OK
fmi2DoStep(component=0x28b725da550, currentCommunicationPoint=0.0, communicationStepSize=3600, noSetFMUStatePriorToCurrentPoint=1) -> OK
fmi2GetReal(component=0x28b725da550, vr=[..., 335544370], nvr=51, value=[..., 293.15]) -> OK

fmi2SetReal(component=0x28b725da550, vr=[352321536], nvr=1, value=[293.4088190451025]) -> OK
fmi2DoStep(component=0x28b725da550, currentCommunicationPoint=3600.0, communicationStepSize=3600, noSetFMUStatePriorToCurrentPoint=1) -> OK
fmi2GetReal(component=0x28b725da550, vr=[..., 335544370], nvr=51, value=[..., 293.4088190451025]) -> OK

fmi2SetReal(component=0x28b725da550, vr=[352321536], nvr=1, value=[293.65]) -> OK
fmi2DoStep(component=0x28b725da550, currentCommunicationPoint=7200.0, communicationStepSize=3600, noSetFMUStatePriorToCurrentPoint=1) -> OK
fmi2GetReal(component=0x28b725da550, vr=[..., 335544370], nvr=51, value=[..., 293.65]) -> OK

fmi2SetReal(component=0x28b725da550, vr=[352321536], nvr=1, value=[293.85710678118653]) -> OK
fmi2DoStep(component=0x28b725da550, currentCommunicationPoint=10800.0, communicationStepSize=3600, noSetFMUStatePriorToCurrentPoint=1) -> OK
fmi2GetReal(component=0x28b725da550, vr=[..., 335544370], nvr=51, value=[..., 293.85710678118653]) -> OK

fmi2Terminate(component=0x28b725da550) -> OK
fmi2FreeInstance(component=0x28b725da550)
```

**Comment by MarkusSchumacherVG** [comment]
Looks like it from the log. But in the FMU I route the input TRoomSet through to TRoomSet_Out. Why is it not the same then at t=3600s? Maybe I totally lack understanding here, but I would expect it to be equal.

**Comment by t-sommer** [comment]
`fmi2DoStep()` introduces a delay of `communicationStepSize`, so the value of the input variables is still the same as before the step.

**Comment by MarkusSchumacherVG** [comment]
So when I would route an input through the FMU and return it as an output (e.g. TSetRoom -> TSetRoom_Out), don't touch it in the FMU, then I will always add a delay of communicationStepSize? Is that right?

**Comment by t-sommer** [comment]
Note that the variables are recorded _after_ `fmi2DoStep()` has been called. Hence the input variables have the value that has been set _before_ `fmi2DoStep()`.
