### ISSUE TITLE
Cannot simulate example parameter_variation.py on Linux

### ISSUE THREAD

**Issue by krzysztofarendt** [CATIA-Systems/FMPy#7]
https://trac.fmi-standard.org does not contain Rectifier.fmu for linux64/Dymola. 
When I try to simulate parameter_variation.py on Linux I get the following error:
```
Exception: Failed to download https://trac.fmi-standard.org/export/HEAD/branches/public/Test_FMUs/FMI_2.0/CoSimulation/linux64/Dymola/2017/Rectifier/Rectifier.fmu (status code: 404)
```
Other examples run fine. It would be helpful to mark OS-dependent tests and maybe disable them on unsupported platforms.

(Thanks for your work on this package :+1: )

**Comment by krzysztofarendt** [comment]
I noticed on README.rst that this FMU is available here:
https://trac.fmi-standard.org/export/HEAD/branches/public/Test_FMUs/FMI_2.0/CoSimulation/linux64/MapleSim/2016.2/Rectifier/Rectifier.fmu

So maybe a system dependent link would be a good idea.

**Comment by t-sommer** [comment]
The MapleSim FMU does not expose the required parameters for the variation. I've added a platform check in 931916e that raises an exception when run on platforms other than windows.
