### ISSUE TITLE
Beginners Tutorial

### ISSUE THREAD

**Issue by lvanfretti** [CATIA-Systems/FMPy#70]
@t-sommer 

This is a "feature" request for a beginners tutorial using Jupyter notebooks to explain step by step the different functionalities of fmpy using simple workflows.

Based on the feedback I got from you and hands-on examples, I put together the one attached. It is meant for people (like me) that are not very familiar with Python.

Hope it is good feedback, you can probably make it nicer!

Luigi

[FMPY_Jupyter_Begginers_Tutorial.ipynb.zip](https://github.com/CATIA-Systems/FMPy/files/2975589/FMPY_Jupyter_Begginers_Tutorial.ipynb.zip)

**Comment by t-sommer** [comment]
I've already made some experiments with https://notebooks.azure.com/. They host an entire Anaconda installation on a VM you can share with others including data, FMUs etc. for free.

The CoupledClutches example is fairly synthetic. Maybe we can find something more accessible for beginners? A simple test equation?

**Comment by lvanfretti** [comment]
Oh! That's great! I remember now you mentioned this, you are fast!

Do you want to share the environment it with me so I can test my script?

About the example, I usually like to use the bouncing ball, because it is not easy to do it with traditional tools (e.g. Matlab), and is really simple with Modelica. 

`model BouncingBall "The 'classic' bouncing ball model"
  type Height=Real(unit="m");
  type Velocity=Real(unit="m/s");
  parameter Real e=0.8 "Coefficient of restitution";
  parameter Height h0=1.0 "Initial height";
  Height h "Height";
  Velocity v(start=0.0, fixed=true) "Velocity";
initial equation
  h = h0;
equation
  v = der(h);
  der(v) = -9.81;
  when h<0 then
    reinit(v, -e*pre(v));
  end when;
end BouncingBall;`

One can start without the event detection conditions, and then add them in another model. This would allow to compare the information in the two different FMUs.
`equation
  v = der(h);
  der(v) = -9.81;
end BouncingBall;`

You could use the bouncing ball through all of your examples related to the FMI projects. For example, in the case of the Unity example, without the "when" equations, the ball should go below the floor.

**Comment by t-sommer** [comment]
> Do you want to share the environment it with me so I can test my script?

Here you go: https://notebooks.azure.com/t-sommer/projects/fmpy-demo-2

It's still a work in progress...

**Comment by lvanfretti** [comment]
Thanks Torsten, that saves a lot of time!
I’ll test out my script in your environment in the next days.

You can close the thread if you wish.

Luigi

**Comment by t-sommer** [comment]
I've renamed the project to https://notebooks.azure.com/t-sommer/projects/CoupledClutches and added a link to the README.md
