### ISSUE TITLE
Compatibility Matlab FMU3 with FMPy 3

### ISSUE THREAD

**Issue by bavodenys** [CATIA-Systems/FMPy#700]
I exported a Simulink model to FMU using the settings 
FMU Type: Co-Simulation 
FMI version: 3.0 

I'm using Matlab 2024b (and Simulink Compiler toolbox)

When creating a FMU3Slave an exception is thrown: "Function fmi3InstantiateModelExchange is missing in shared library". Why does it need the function "fmi3InstantiateModelExchange" when it is a Co-Simulation FMU? 

As 'quick' fix I would propose:

class FMU3Slave(_FMU3):
    """ An FMI 3.0 Co-Simulation FMU """

    def __init__(self, requireFunctions = False, instanceName=None, **kwargs):

        kwargs['instanceName'] = instanceName
        kwargs['requireFunctions'] = requireFunctions

        super(FMU3Slave, self).__init__(**kwargs)

I never contributed to a project like FMPy. How does the proces works of getting this change approved?

**Comment by t-sommer** [comment]
Can you share an FMU to reproduce the problem?

**Comment by bavodenys** [comment]
The FMU I experience the problem with I cannot share due to confidentiality. I created a simple FMU in Matlab that arises the same problem when creating a FMU3 slave. 

I exported a Simulink model to FMU using the settings:
- Matlab version: 2024b
- FMU Type: Co-Simulation
- FMI version: 3.0 

Maybe it could only require the function that is linked to the FMI type?  

[testModel.zip](https://github.com/user-attachments/files/17408146/testModel.zip)

**Comment by t-sommer** [comment]
This FMU is not a valid FMI 3.0. FMU.

From the FMI Spec 3.0.1, [2.5. FMU Distribution](https://fmi-standard.org/docs/3.0.1/#fmu-distribution)

> The FMU must implement all API functions declared in fmi3Functions.h, even if they are only needed for interface types or optional capabilities that the FMU does not support.

**Comment by bavodenys** [comment]
Ok, so I should submit this as an issue at MathWorks. Thanks!
