### ISSUE TITLE
Issue when using simulate_ssp() from a ssp file.

### ISSUE THREAD

**Issue by Carloslb17** [CATIA-Systems/FMPy#704]
I used the function _simulate_ssp()_ to connect two Python-based FMU´s and did an SSD file to try the parametrization standard from FMI. It is quite nice by the way, however, there might be something wrong with the connections.

I managed to validate the ssp file, however, when I simulated the system I got a null result in the variables or an error in the function: _connectors = get_connectors(ssp_file)_ in  _simulate_ssp()_. 

```
inputs = {
    "Sinosuidal.Amplitude": np.ones_like(time),  # Constant amplitude of 1
    "Sinosuidal.ang_vel": np.linspace(0.1, 1.0, len(time))  # Angular velocity ramp
}

    results = simulate_ssp(ssp_file, stop_time=10.0, inputs=inputs)

`UnboundLocalError: start_p`
```

I had a good result when I was declaring the external connectors to the internal connectors from the FMU but the final output of the simulation was 0. 

Do you have any ssp examples that I could look?  Or any tip to use ssp files to connect one or several FMU's?

Let me know if you need the full ssp file.

[SystemStructure.txt](https://github.com/user-attachments/files/17802563/SystemStructure.txt)

**Comment by t-sommer** [comment]
> One question, any performance tip when doing simulations with ssp orchestration?

Connecting multiple FMUs in Python is not optimal for larger configurations. I'm planning to re-work the SSP implementation and use the Container FMU infrastructure which should give much better performance.
