### ISSUE TITLE
Issue with EnergyPlus cosimulation

### ISSUE THREAD

**Issue by anoushp** [CATIA-Systems/FMPy#71]
Hello,

I am trying to create a simple co-simulation example with .fmu file generated from EnergyPlus. I looked at your co simulation examples and they used FMU3Slave. However EnergyPlus to FMU  supports FMI 1.0 so I am using FMU1Slave. I get the following error on fmu instance initialisation fmu.initialize(tStart=86400+60, stopTime=259200):
" **The delta between the FMU stop time %f and the FMU start time %f must be a multiple of 86400. This is required by EnergyPlus. The current delta is %f. Instantiation of %s failed.\nfmiInitializeSlave: The delta between the FMU stop time %f and the FMU start time %f must be a multiple of 86400. This is required by EnergyPlus. The current delta is %f. Instantiation of %s failed.\nfmiInitializeSlave: The delta between the FMU stop time %f and the FMU start time %f must be a multiple of 86400. This is required by EnergyPlus. The current delta is %f. Instantiation of %s failed.\n**"

Please help to understand,

Kind regards,
Anush

**Comment by chrbertsch** [comment]
@anoushp :  It looks like this is an EnergyPLus specific error, exactly as the error message says: 
Your differenceof stop-time and start time is not devidable by 86400s (one day). Perhaps use tStart=86400? or tStart=0?

**Comment by t-sommer** [comment]
Unless you need a custom simulation loop I'd recommend to use `simulate_fmu()` instead of instantiating `FMU1Slave` directly. It allows you to set the start and stop time via parameters.

The reason why you see the  `%f` in the message is that it's not possible to access the variadic arguments in the callback that's implemented in Python.

**Comment by t-sommer** [comment]
@anoushp, can you share the FMU and / or some demo code, so we can reproduce the issue?

**Comment by anoushp** [comment]
> @anoushp : It looks like this is an EnergyPLus specific error, exactly as the error message says:
> Your differenceof stop-time and start time is not devidable by 86400s (one day). Perhaps use tStart=86400? or tStart=0?

Thanks I tried everything (tStart=0 and Tstart = 86400) and couldn't make it work before.

**Comment by anoushp** [comment]
> @anoushp, can you share the FMU and / or some demo code, so we can reproduce the issue?
Thanks t-sommer I am trying to attach the files but it doesn't let me to attach fmu/py files.

**Comment by t-sommer** [comment]
You can pass the `print` function as a log function to the constructor of `FMU1Slave` to get a full log of the FMI calls:

```
fmu = FMU1Slave(..., fmiCallLogger=print)
```

There you can see if the start and stop time are passed correctly to the FMU.

**Comment by t-sommer** [comment]
@anoushp, can you post the FMI call log (as suggested above)?

**Comment by anoushp** [comment]
> @anoushp, can you post the FMI call log (as suggested above)?

Hi, sorry I was away. Is there any chance I can send you the code and fmu and you could reproduce it.
I tried fmiCallLogger and on fmu.dostep I get 
(base) C:\testfmu>python cosimtest1.py
<fmpy.model_description.ModelDescription object at 0x0000024015993908>
_fmu_export_actuator
C:\Users\ap647\AppData\Local\Temp\tmpv175imxo
[OK] b'The current working directory is %s\n'
[WARNING] b'fmiInstantiate: The fmuOutput directory %s exists. It will now be deleted.\n'
[OK] b'This is the output folder %s\n'
[OK] b'This is the command to be executed to delete existing directory %s\n'
[OK] b'fmiInstantiateSlave: Path to fmuUnzipLocation is not %s.\n'
[OK] b'fmiInstantiateSlave: Path to fmuUnzipLocation is not %s.\n'
[OK] b'fmiInstantiateSlave: Path to fmuUnzipLocation is not %s.\n'
[OK] b'Command executes to copy content of resources folder: %s\n'
C:\Users\ap647\AppData\Local\Temp\tmpv175imxo\resources\variables.cfg
1 File(s) copied
[OK] b'fmiInstantiateSlave: Path to model description file is %s.\n'
[OK] b'fmiInstantiateSlave: The FMU modelIdentifier is %s.\n'
[OK] b'fmiInstantiateSlave: The FMU modelGUID is %s.\n'
[OK] b'fmiInstantiateSlave: Slave %s is instantiated.\n'
[OK] b'fmiInstantiateSlave: Instantiation of %s succeded.\n'
fmiInstantiateSlave(instanceName=b'_fmu-export-actuator.idf', guid=b'79f5b5e25d1c5cea96c17d41d22f522f', fmuLocation=b'file:///C:/Users/ap647/AppData/Local/Temp/tmpv175imxo', mimeType=b'application/x-fmu-sharedlibrary', timeout=0, visible=b'\x00', interactive=b'\x00', functions=fmi1CallbackFunctions(logger=<CFunctionType object at 0x0000024015A26388>, allocateMemory=<CFunctionType object at 0x0000024015A26458>, freeMemory=<CFunctionType object at 0x0000024015A26528>, stepFinished=None), loggingOn=b'\x00') -> 0x24012c21660
Traceback (most recent call last):
  File "cosimtest1.py", line 81, in <module>
    simulate_custom_input()
  File "cosimtest1.py", line 56, in simulate_custom_input
    fmu.doStep(currentCommunicationPoint=time, communicationStepSize=6)
  File "C:\Users\ap647\AppData\Local\Continuum\anaconda3\lib\site-packages\fmpy\fmi1.py", line 485, in doStep
    return self.fmi1DoStep(self.component, currentCommunicationPoint, communicationStepSize, newStep)
  File "C:\Users\ap647\AppData\Local\Continuum\anaconda3\lib\site-packages\fmpy\fmi1.py", line 281, in w
    res = f(*args)
OSError: exception: integer divide by zero

**Comment by t-sommer** [comment]
Can you try to put everything in a ZIP file and attach it to you comment?

**Comment by anoushp** [comment]
Hi,

Thanks for quick response. I am not an expert in Energy Plus so I am using a simple example model fmu provided by EnergyPlusToFMU  software package.  Please see the zip attached. I am using EnergyPlusv9-0-1.
[testfmu.zip](https://github.com/CATIA-Systems/FMPy/files/3106731/testfmu.zip)

**Comment by t-sommer** [comment]
The attached FMU is trying to execute the command `energyplus` (tool coupling)

```
energyplus -w runweafile.epw -p _fmu_export_actuator -s C -x -m -r _fmu_export_actuator.idf
```

which I don't have installed.

Can you try to run the following Python script:

```python
from fmpy import simulate_fmu

result = simulate_fmu('fmu_export_actuator.fmu')
```

**Comment by anoushp** [comment]
> The attached FMU is trying to execute the command `energyplus` (tool coupling)
> 
> ```
> energyplus -w runweafile.epw -p _fmu_export_actuator -s C -x -m -r _fmu_export_actuator.idf
> ```
> which I don't have installed.
> 
> Can you try to run the following Python script:
> 
> ```python
> from fmpy import simulate_fmu
> 
> result = simulate_fmu('fmu_export_actuator.fmu')
> ```
I get the following error written in .err file
Program Version,EnergyPlus, Version 9.0.1-bb7ca4f0da, YMD=2019.04.23 11:07,
   ** Warning ** Weather file location will be used rather than entered (IDF) Location object.
   **   ~~~   ** ..Location object=CHICAGO_IL_USA TMY2-94846
   **   ~~~   ** ..Weather File Location=Denver Centennial  Golden   Nr CO USA TMY3 WMO#=724666
   **   ~~~   ** ..due to location differences, Latitude difference=[2.04] degrees, Longitude difference=[17.43] degrees.
   **   ~~~   ** ..Time Zone difference=[1.0] hour(s), Elevation difference=[862.63] percent, [1639.00] meters.
   ** Warning ** SetUpDesignDay: Entered DesignDay Barometric Pressure=99063 differs by more than 10% from Standard Barometric Pressure=81198.
   **   ~~~   ** ...occurs in DesignDay=CHICAGO_IL_USA ANNUAL HEATING 99% DESIGN CONDITIONS DB, Standard Pressure (based on elevation) will be used.
   ** Warning ** SetUpDesignDay: Entered DesignDay Barometric Pressure=99063 differs by more than 10% from Standard Barometric Pressure=81198.
   **   ~~~   ** ...occurs in DesignDay=CHICAGO_IL_USA ANNUAL COOLING 1% DESIGN CONDITIONS DB/MCWB, Standard Pressure (based on elevation) will be used.
   ************* Testing Individual Branch Integrity
   ************* All Branches passed integrity testing
   ************* Testing Individual Supply Air Path Integrity
   ************* All Supply Air Paths passed integrity testing
   ************* Testing Individual Return Air Path Integrity
   ************* All Return Air Paths passed integrity testing
   ************* No node connection errors were found.
   ************* Beginning Simulation
   ** Severe  ** ExternalInterface: Socket communication received error value "-1" at time = 0.00 hours.
   **   ~~~   ** ExternalInterface: Flag from server " 0".
   **  Fatal  ** Error in ExternalInterface: Check EnergyPlus *.err file.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=ExternalInterface: Socket communication received error value "-1" at time = 0.00 hours.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 3 Warning; 1 Severe Errors; Elapsed Time=00hr 00min  0.56sec

**Comment by anoushp** [comment]
(base) C:\testfmu\Output_EPExport__fmu_export_actuator>energyplus -w runweafile.epw -p _fmu_export_actuator -s C -x -m -r _fmu_export_actuator.idf
Running EPMacro...
ExpandObjects Started.
No expanded file generated.
ExpandObjects Finished. Time:     0.016
EnergyPlus Starting
EnergyPlus, Version 9.0.1-bb7ca4f0da, YMD=2019.04.23 11:07
Adjusting Air System Sizing
Adjusting Standard 62.1 Ventilation Sizing
Initializing Simulation
Reporting Surfaces
Beginning Primary Simulation
Initializing New Environment Parameters
Warming up {1}
Instantiating FunctionalMockupUnitExport interface
ExternalInterface initializes.
[OK] b'fmiInitializeSlave: The connection has been accepted.\n'
[OK] b'fmiInitializeSlave: Slave %s is initialized.\n'
Number of outputs in ExternalInterface = 2
Number of inputs  in ExternalInterface = 1
Warming up {2}
Warming up {3}
Warming up {4}
Warming up {5}
Warming up {6}
Starting Simulation at 01/21 for CHICAGO_IL_USA ANNUAL HEATING 99% DESIGN CONDITIONS DB
Initializing New Environment Parameters
Warming up {1}
Warming up {2}
Warming up {3}
Warming up {4}
Warming up {5}
Warming up {6}
Starting Simulation at 07/21 for CHICAGO_IL_USA ANNUAL COOLING 1% DESIGN CONDITIONS DB/MCWB
Initializing New Environment Parameters
Warming up {1}
Warming up {2}
Warming up {3}
Warming up {4}
Warming up {5}
Warming up {6}
Starting Simulation at 01/01/2011 for RUNPERIOD 1
ExternalInterface starts first data exchange.
[ERROR] b'fmiDoStep: An error occured in a previous call. CommunicationStepSize: %f is different from time step: %d in input file.\n'
Traceback (most recent call last):
  File "testpy.py", line 3, in <module>
    result = simulate_fmu('fmu_export_actuator.fmu')
  File "C:\Users\ap647\AppData\Local\Continuum\anaconda3\lib\site-packages\fmpy\simulation.py", line 505, in simulate_fmu
    result = simulateCS(model_description, fmu_args, start_time, stop_time, relative_tolerance, start_values, apply_default_start_values, input, output, output_interval, timeout, callbacks, debug_logging, step_finished)
  File "C:\Users\ap647\AppData\Local\Continuum\anaconda3\lib\site-packages\fmpy\simulation.py", line 754, in simulateCS
    fmu.doStep(currentCommunicationPoint=time, communicationStepSize=output_interval)
  File "C:\Users\ap647\AppData\Local\Continuum\anaconda3\lib\site-packages\fmpy\fmi1.py", line 485, in doStep
    return self.fmi1DoStep(self.component, currentCommunicationPoint, communicationStepSize, newStep)
  File "C:\Users\ap647\AppData\Local\Continuum\anaconda3\lib\site-packages\fmpy\fmi1.py", line 290, in w
    raise Exception("FMI call failed with status %d." % res)
Exception: FMI call failed with status 3.
Failed to peek at socket.: No error
**FATAL:Error in ExternalInterface: Check EnergyPlus *.err file.

(base) C:\testfmu>EnergyPlus Run Time=00hr 00min  0.56sec
Program terminated: EnergyPlus Terminated--Error(s) Detected.

**Comment by t-sommer** [comment]
You can set the sample interval manually:

```
from fmpy import simulate_fmu

result = simulate_fmu(
    filename='fmu_export_actuator.fmu',
    output_interval=6
)
```

**Comment by anoushp** [comment]
Many thanks I tried it and it doesn't give error.  But I need to print variables on every step or change the input variable. I understood fmu.doStep method. but with simulate_fmu is it possible to control every step?

**Comment by t-sommer** [comment]
You can pass a callback function to `simulate_fmu()` that gets called after every step:

```python
def my_callback(time, recorder):
    # use recorder.fmu to access the FMU instance
    pass

result = simulate_fmu('my_model.fmu', step_finished=my_callback)
```

In the callback you can use `fmu.setReal()` to set the input.

**Comment by anoushp** [comment]
> You can pass a callback function to `simulate_fmu()` that gets called after every step:
> 
> ```python
> def my_callback(time, recorder):
>     # use recorder.fmu to access the FMU instance
>     pass
> 
> result = simulate_fmu('my_model.fmu', step_finished=my_callback)
> ```
> 
> In the callback you can use `fmu.setReal()` to set the input.

t-sommer thanks, I tried your suggestion and executed the following code
from fmpy import simulate_fmu
def my_callback(time, recorder):
    print(recorder.fmu)
    # use recorder.fmu to access the FMU instance
    pass

result = simulate_fmu('fmu_export_actuator.fmu', output_interval=6, step_finished=my_callback)
but again it does not work:
Starting Simulation at 01/01/2011 for RUNPERIOD 1
ExternalInterface starts first data exchange.
[ERROR] b'fmiDoStep: An error occured in a previous call. CommunicationStepSize: %f is different from time step: %d in input file.\n'
Traceback (most recent call last):
  File "testpy.py", line 7, in <module>
    result = simulate_fmu('fmu_export_actuator.fmu', output_interval=6, step_finished=my_callback)
  File "C:\Users\ap647\AppData\Local\Continuum\anaconda3\lib\site-packages\fmpy\simulation.py", line 505, in simulate_fmu
    result = simulateCS(model_description, fmu_args, start_time, stop_time, relative_tolerance, start_values, apply_default_start_values, input, output, output_interval, timeout, callbacks, debug_logging, step_finished)
  File "C:\Users\ap647\AppData\Local\Continuum\anaconda3\lib\site-packages\fmpy\simulation.py", line 754, in simulateCS
    fmu.doStep(currentCommunicationPoint=time, communicationStepSize=output_interval)
  File "C:\Users\ap647\AppData\Local\Continuum\anaconda3\lib\site-packages\fmpy\fmi1.py", line 485, in doStep
    return self.fmi1DoStep(self.component, currentCommunicationPoint, communicationStepSize, newStep)
  File "C:\Users\ap647\AppData\Local\Continuum\anaconda3\lib\site-packages\fmpy\fmi1.py", line 290, in w
    raise Exception("FMI call failed with status %d." % res)
Exception: FMI call failed with status 3.
Failed to peek at socket.: No error
**FATAL:Error in ExternalInterface: Check EnergyPlus *.err file.
EnergyPlus Run Time=00hr 00min  0.57sec
Program terminated:
En(base) C:\testfmu>ergyPlus Terminated--Error(s) Detected.

**Comment by t-sommer** [comment]
Did you check the "EnergyPlus *.err file"?

**Comment by anoushp** [comment]
Perhaps the problem is with CommunicationStepSize I am not sure. Here is the .err file from E+
```
Program Version,EnergyPlus, Version 9.0.1-bb7ca4f0da, YMD=2019.04.23 14:58,
   ** Warning ** Weather file location will be used rather than entered (IDF) Location object.
   **   ~~~   ** ..Location object=CHICAGO_IL_USA TMY2-94846
   **   ~~~   ** ..Weather File Location=Denver Centennial  Golden   Nr CO USA TMY3 WMO#=724666
   **   ~~~   ** ..due to location differences, Latitude difference=[2.04] degrees, Longitude difference=[17.43] degrees.
   **   ~~~   ** ..Time Zone difference=[1.0] hour(s), Elevation difference=[862.63] percent, [1639.00] meters.
   ** Warning ** SetUpDesignDay: Entered DesignDay Barometric Pressure=99063 differs by more than 10% from Standard Barometric Pressure=81198.
   **   ~~~   ** ...occurs in DesignDay=CHICAGO_IL_USA ANNUAL HEATING 99% DESIGN CONDITIONS DB, Standard Pressure (based on elevation) will be used.
   ** Warning ** SetUpDesignDay: Entered DesignDay Barometric Pressure=99063 differs by more than 10% from Standard Barometric Pressure=81198.
   **   ~~~   ** ...occurs in DesignDay=CHICAGO_IL_USA ANNUAL COOLING 1% DESIGN CONDITIONS DB/MCWB, Standard Pressure (based on elevation) will be used.
   ************* Testing Individual Branch Integrity
   ************* All Branches passed integrity testing
   ************* Testing Individual Supply Air Path Integrity
   ************* All Supply Air Paths passed integrity testing
   ************* Testing Individual Return Air Path Integrity
   ************* All Return Air Paths passed integrity testing
   ************* No node connection errors were found.
   ************* Beginning Simulation
   ** Severe  ** ExternalInterface: Socket communication received error value "-1" at time = 0.00 hours.
   **   ~~~   ** ExternalInterface: Flag from server " 0".
   **  Fatal  ** Error in ExternalInterface: Check EnergyPlus *.err file.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=ExternalInterface: Socket communication received error value "-1" at time = 0.00 hours.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 3 Warning; 1 Severe Errors; Elapsed Time=00hr 00min  0.57sec
```
Do you have any working example of co simulation with energyplus fmu ? I could have a look at it too.

**Comment by t-sommer** [comment]
I don't have an example of a Python script with a tool coupling FMU (I assume this is what you mean by "co simulation"), but any legal FMU should work. Please contact the tool vendor for an example. It does not seem like there is an issue with FMPy.

**Comment by anoushp** [comment]
> I don't have an example of a Python script with a tool coupling FMU (I assume this is what you mean by "co simulation"), but any legal FMU should work. Please contact the tool vendor for an example. It does not seem like there is an issue with FMPy.

No problems, thanks for help. One more thing the vendor website [](http://simulationresearch.lbl.gov/fmu/EnergyPlus/export/userGuide/usage.html#f2)

says that " **a tool that imports the FMU must synchronize it every 10 minutes. Otherwise, the simulation will stop with an error**". This is for the case TimeStep=6. Perhaphs there is an argument that I missed in **simulate_fmu** that could do that?

**Comment by Denzo77** [comment]
I don't know if you're still having this problem (or even care), but hopefully this will help anyone else having this issue:
``` python
import fmpy
fmu = 'fmu_export_actuator.fmu'

# This is the number of simulation steps per hour.
# It must be the same as the TimeStep variable in fmu_export_actuator.idf
time_step = 6 

# Convert time_step into seconds
step_interval = (60*60) / time_step

# The critical bit here is passing step_interval to both step_size and output_interval
result = fmpy.simulate_fmu(
    filename=fmu,
    step_size=step_interval,
    output_interval=step_interval
)
```
One thing that would really help is if the documentation for simulate_fmu explained the units for its inputs. I couldn't find anything that explains how the units of the inputs relate (I'm assuming that they don't necessarily have to be seconds).

**Comment by xavfa** [comment]
Hi, I am digging out this subject as I am encountering an issues with FMPy and EnergyPlus. The FMU simulation works great and gives me expected results from the specified outputs in the FMU, but I didn't manage to make the input change at each time step... The fmu.setReal() doesn't gives me error, but the fmu.getReal() of same variable is constantly 0..., 
Is there something to do with the read_model_description ?
By the way, I using FMU 2.0 for Energyplus as I didn't manage to make it work with FMU 1.0...
my reason of using FMPy is that PyFMI is just impossible to install...and FMI++ works perfectly on windows (i've used it for a while) but as I need to make my work compatible with different os, I found FMPy on Ubuntu (and when it will work, I'll check on Windows afterward).
Thanks for any help on the setReal() function !
Xavier

**Comment by Denzo77** [comment]
I gave up and started using PyFMI. You need to install it with Anaconda using the package in [conda-forge](https://anaconda.org/conda-forge/pyfmi). It's a shame because FMPy is generally much nicer to work with.

It sounds like it's working better than it was the last time I tried which is good though.

**Comment by xavfa** [comment]
I am not fond of conda (as I don't master the jumps between pip and conda depending on packages and I am used to virtualenv). But I resolved the issue and it seems to work perfectly well on FMPy (with FMU version 2.0). I'll see now with all the changes i have to do on windows (all implemented with FMI++) as I want my work to uses the same packages being either on windows or Linux.
