### ISSUE TITLE
separator in the input CSV file

### ISSUE THREAD

**Issue by masoud-najafi** [CATIA-Systems/FMPy#73]
If the separator character in the input-file is not a comma (',')  fmpy crashes.
here is an example of the input file.

"time";"Voltage"
0.0;0.0
0.01;1.0

  File "e:\anaconda3\Scripts\fmpy-script.py", line 10, in <module>
    sys.exit(main())
  File "e:\anaconda3\lib\site-packages\fmpy\command_line.py", line 91, in main
    input = read_csv(args.input_file) if args.input_file else None
  File "e:\anaconda3\lib\site-packages\fmpy\util.py", line 23, in read_csv
    traj = np.genfromtxt(filename, delimiter=',', names=True, deletechars='')
  File "e:\anaconda3\lib\site-packages\numpy\lib\npyio.py", line 2161, in genfromtxt
    output = np.array(data, dtype)
ValueError: could not convert string to float: b'0.0;0.0'

**Comment by t-sommer** [comment]
CSV stands for "Comma Separated Values" and it's the format we use e.g. in the FMI Cross-Check. The above example is not a valid CSV.

However you can read the file using [numpy.genfromtxt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html) with the `delimiter` argument and pass it to `simulate_fmu`.

**Comment by masoud-najafi** [comment]
OK. That's clear now. A crash is a little bit misleading, an error message would help more.

**Comment by t-sommer** [comment]
IMHO the error message provided is quite clear:

```
ValueError: could not convert string to float: b'0.0;0.0'
```

The string `0.0;0.0` is not a valid float literal.

**Comment by ergimaqellari** [comment]
> However you can read the file using numpy.genfromtxt with the `delimiter` argument and pass it to `simulate_fmu`.
Hello Ive stumbled across this thread and im having issues using numpy.genfromtext with the [CSV Rules](https://github.com/modelica/fmi-standard.org/blob/main/CONTRIBUTING.md#csv-rules-for-inout-and-result-files-for-compatibility-information) specified for arrays. The output of gentext just puts the cells with array data.
Is there a method that allows for array data and what will be the correct value for these array outputs? Thanks

<img width="624" height="18" alt="Image" src="https://github.com/user-attachments/assets/73572b50-9fe1-477f-b881-4120322a7d3d" />

<img width="950" height="19" alt="Image" src="https://github.com/user-attachments/assets/f81b62de-0c07-41d4-b214-0039cb6f60ac" />
