### ISSUE TITLE
String input / output support

### ISSUE THREAD

**Issue by diasdm** [CATIA-Systems/FMPy#74]
Hello,
Sorry to bring this question here, but I asked a question in [stackoverflow](https://stackoverflow.com/questions/55497090/how-to-get-string-output-variables-with-fmpy) and I still haven't found a definite answer for it.
 My question is:
* does FMPy support input / output String variables? If so, can you provide some pointers or example usage?

Thank you

**Comment by t-sommer** [comment]
@diasdm, can you describe a use case where you need Strings as input and/or output?

**Comment by diasdm** [comment]
For now I'm just exploring the FMI standard for use in a project and don't have a specific use case to give you. But as an example, it might be useful while FMI does not have support for arrays.

Thank you for the reply in stackoverflow. If you see fit, you can close this issue.

**Comment by diasdm** [comment]
Hi, I found an easy solution and for what I was trying to accomplish. I will describe it in case someone finds it useful.

In [simulation.py](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/simulation.py#L58) I added the String type as a Python object (probably not ideal... but it works):

    types = [('Real', np.float64), ('Integer', np.int32), ('Boolean', np.bool_), ('String', object)]

In the same file I added a condition in the sample function:

    def sample(self, time, force=False):
        """ Record the variables """

        if not force and self.interval is not None and len(self.rows) > 0:
            last = self.rows[-1][0]
            if time - last + eps < self.interval:
                return

        row = [time]

        for t in self.types:
            names, vrs, shapes, nValues, getter = self.info[t]
            if self.modelDescription.fmiVersion in ['1.0', '2.0']:
                values = getter(vr=vrs)
            else:
                values = getter(vr=vrs, nValues=nValues)
>            if t == 'String':
>                values = [item.decode('ascii') for item in values]; values
            self._append_reshaped(row, values, shapes)

        self.rows.append(tuple(row))

I haven't runned FMPy tests, so I'm not sure if this does not break something else. It's working for me when simulating `values.fmu` present in [fmusdk](https://github.com/qtronic/fmusdk/tree/master/fmu20/src/models/values).

    from FMPy import fmpy
    from FMPy.fmpy import util

    t_final = 2.
    step_num = 100
    fmu_name = os.path.join('values.fmu')
    res = fmpy.simulate_fmu(fmu_name, stop_time=t_final, debug_logging=False)
    print('Simulation results contain:' + str(res.dtype.names))
    print(res['string_out'])
    fmpy.util.plot_result(res)

Even the plot looks nice!

**Comment by t-sommer** [comment]
Thanks for sharing your findings, @diasdm! I've already implemented experimental support for String I/O on [feature/string-output](https://github.com/CATIA-Systems/FMPy/tree/feature/string-output).

However I'm hesitant to merge it into develop because it adds more complexity and I still don't see the need beyond supporting the synthetic values.fmu.

**Comment by diasdm** [comment]
I didn't know, thank you.
I understand. If I find a use case for which String I/O is required I'll make my case.
