### ISSUE TITLE
Logging shows placeholders

### ISSUE THREAD

**Issue by diasdm** [CATIA-Systems/FMPy#75]
Hello,
While simulating FMUs with `loggingOn=True` the logs are printed to the console but the place holders are not replaced by its values.

Example: using this [example](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/custom_input.py) with `fmu.instantiate(loggingOn=True)` I get the following console output:

```
[OK] fmi2DoStep: currentCommunicationPoint = %g, communicationStepSize = %g, newStep = fmi2%s
[OK] fmi2GetReal: #r%u# = %.16g
[OK] fmi2GetReal: #r%u# = %.16g
[OK] fmi2SetReal: nvr = %d
[OK] fmi2SetReal: #r%d# = %.16g
```
I have rulled out a problem with the FMU (CoupledClutches) since PyFMI shows the logging with values:
```
FMIL: module = Model, log level = 4: [log][FMU status:OK] fmi2DoStep: currentCommunicationPoint = 1.996, communicationStepSize = 0.004, newStep = fmi2True
FMIL: module = Model, log level = 4: [log][FMU status:OK] fmi2GetReal: internalTime = 2
FMIL: module = Model, log level = 4: [log][FMU status:OK] fmi2GetReal: J1.phi = 9.429530790072679
FMIL: module = Model, log level = 4: [log][FMU status:OK] fmi2GetReal: outputs[1] = 3.102266663296025
FMIL: module = Model, log level = 4: [log][FMU status:OK] fmi2GetReal: J2.phi = 6.281255916795093
````
Is this a known issue or am I doing something wrong?
Thank you

**Comment by t-sommer** [comment]
It's a limitation of the ctypes interface that the variadic arguments passed to the logger callback are not accessible.

FWIW, the variadic arguments will be removed in FMI 3.0, so this won't be an issue any more.

**Comment by diasdm** [comment]
Just now realised that #71 references this, sorry about that. Thank you for your answer.
