### ISSUE TITLE
control verbosity of simulate_fmu

### ISSUE THREAD

**Issue by jbernalr** [CATIA-Systems/FMPy#76]
Is there a way to control the verbosity level when calling simulate_fmu? 
from no output to lets say show me only the events occurred an no other information?

**Comment by t-sommer** [comment]
> Is there a way to control the verbosity level when calling simulate_fmu?

If you want to filter the log messages you can pass your own logger function to `simulate_fmu()` e.g.

```python
def log_only_set_real(message):
    if 'SetReal' in message:
        print(message)

simulate_fmu('model.fmu', logger=log_only_set_real)
```

> from no output to lets say show me only the events occurred an no other information?

Events generate duplicate samples in the result (same time for successive samples). You can even plot the events with 

```python
plot_result(result, events=True)
```

For something more advanced just put a (conditional) breakpoint in the code - it's open source.

**Comment by jbernalr** [comment]
This works. There are messages however that come out from the solver (which of course comes precompiled) I'm want to figure now how to control the call to the solver and if there are any parameters regarding logging I can control. Thanks!

**Comment by t-sommer** [comment]
The interface to CVode is the [CVodeSolver](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/sundials/__init__.py#L143) class. CVode has a lot of options but only some of them are exposed in the Python interface (e.g. `maxStep`, `relativeTolerance` and `maxNumSteps`). To change other parameters you would have to add the respective constants and functions from the SUNDIALS header files using ctypes.

**Comment by t-sommer** [comment]
@jbernalr, please open a new issue if you need additional functions from the CVode API.
