### ISSUE TITLE
simulate_fmu: callback function problem

### ISSUE THREAD

**Issue by anoushp** [CATIA-Systems/FMPy#77]
Hi,

I am trying to track the variables of fmu on each step. Currently I have the following code:
```
from fmpy import simulate_fmu
def my_callback(time, recorder):
    print(time)	
    pass
result = simulate_fmu('fmu_export_actuator.fmu', output_interval=600, start_time=0,step_size=600,stop_time=345600,step_finished=my_callback)
print(result)
```
my callback prints time only once in the end and it is 0. However simulation runs successfully. I am not sure what can cause this problem.

Thanks,

**Comment by t-sommer** [comment]
You have to return `True` to continue the simuliation:

```python
def my_callback(time, recorder):
    print(time)	
    return True  # continue simulation
```

Note that this callback interface is marked experimental and might change in a future release.

**Comment by anoushp** [comment]
@t-sommer thanks!
