### ISSUE TITLE
single line CSV input file

### ISSUE THREAD

**Issue by masoud-najafi** [CATIA-Systems/FMPy#78]
If the CSV input file is composed of only a single line, FMPY cannot read it. 
Here is an example where "inputx" input variable is constant all over the simulation.

"time","inputx" 
0.0,1 

This may have already been fixed or it is not an issue, but since FmuChecker supports the single line csv file, it would be good to support it in FMPY too.

**Comment by t-sommer** [comment]
Fixed with d606671858d5acc403cbfc51afa9f1196d42faa8
