### ISSUE TITLE
Error on simulate_fmu clean up

### ISSUE THREAD

**Issue by ebw44** [CATIA-Systems/FMPy#79]
At the end of simulate_fmu() when cleaning the tempdir I get a:
> OSError: [WinError 145] The directory is not empty: 'C:\\Users\\.....\\AppData\\Local\\Temp\\tmp0qc8rb9d\\binaries\\win64'

Replacing l554 of fmpy\simulation.py
`shutil.rmtree(tempdir)`
by
`shutil.rmtree(tempdir, ignore_errors=True)`
fix the problem for me.

**Comment by t-sommer** [comment]
Seems like a DLL is still loaded. Can you share the FMU that causes the problem?

**Comment by ebw44** [comment]
Here is a simple example (output is the product of the input with a sin signal). It was generated by Hopsan and the extension changed to zip in order to post it here.
[fmuTest.zip](https://github.com/CATIA-Systems/FMPy/files/3186236/fmuTest.zip)

Please note that Hopsan has [issue ](https://github.com/Hopsan/hopsan/issues/1846) with generationDateAndTime date field (fixed manually for that example) and the ModelStructure/Output so you need to use: 
`fmpy.simulate_fmu(filename, validate=False)`
