### ISSUE TITLE
Open non valid fmu in gui.

### ISSUE THREAD

**Issue by ebw44** [CATIA-Systems/FMPy#81]
If opening of fmu fail, then ask the user if he/she wants to try without model validation.
[Here ](https://github.com/ebw44/FMPy/commit/053e055d261a7ca8d9100a2b27fd5ae1bcf8b905)is a commit on a fork that does it.
And here is the patch
[patch.diff.txt](https://github.com/CATIA-Systems/FMPy/files/3217450/patch.diff.txt)

**Comment by t-sommer** [comment]
The GUI relies on a valid model description. Disabling the validation would likely break the GUI and lead to a poor user experience.
