### ISSUE TITLE
Possibility to get progress during simulation

### ISSUE THREAD

**Issue by magraeber** [CATIA-Systems/FMPy#82]
When using the function simulate_fmu for long simulations I would like to have the possibility to send progress information somewhere, to have some kind of progress indicator for users.

One idea would be to allow customization of Recorder class.

**Comment by t-sommer** [comment]
You can pass a callback function (`step_finished`) to `simulate_fmu()` that gets called after every step (see also #77).

**Comment by t-sommer** [comment]
Does this work for you, @magraeber?

**Comment by magraeber** [comment]
Yes, that's perfect. Thanks!
