### ISSUE TITLE
Interactive Simulation

### ISSUE THREAD

**Issue by magraeber** [CATIA-Systems/FMPy#84]
I would like to use FMPy in some kind of real-time simulation with interactive user-input.

Synchronization with real-time can be done outside FMPy, but I need the possibility to:
* do some simulation steps
* wait for new inputs
* continue simulation

I have scanned the Input class. Maybe I could customize it, to support this interactivity.

@t-sommer, what is your recommended way to implement something like this?

Co-simulation FMU with fixed macro step size is fine.

**Comment by t-sommer** [comment]
How about using the `step_finished` callback? (see also #82)

**Comment by magraeber** [comment]
Ok, I could use this callback to synchronize with real time, by inserting something like sleep() in my function.

But how can I change the FMU inputs to new values (that are not known in advance)?

**Comment by t-sommer** [comment]
You can call `fmu.setReal()` (see [custom_input.py](https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/examples/custom_input.py) for an example).

**Comment by t-sommer** [comment]
Depending on what you're trying to do it might be easier to write your own simulation loop based on the above example. That way it's easy to synchronize with your real-time I/O.

**Comment by magraeber** [comment]
Thanks for the hints. This example looks like a perfect starting point.
