### ISSUE TITLE
FMU is not a zipped file

### ISSUE THREAD

**Issue by aakashsehgal** [CATIA-Systems/FMPy#86]
I am not accessing the raspi through a SSH client.
I could download the fmu mentioned in the turorial but while performing any other operation, it gives an error stating that the File is not a zip file.

**Comment by t-sommer** [comment]
Can you provide the output and steps to reproduce the problem?

**Comment by aakashsehgal** [comment]
Yes Sure !

I followed the [this](https://github.com/CATIA-Systems/FMPy/wiki/RaspberryPi) tutorial :

Firstly installed the dependencies :

```
pi@raspberrypi:~ $ sudo apt-get update
[...]
pi@raspberrypi:~ $ sudo apt-get install python-numpy python-lxml python-pathlib python-pip
[...]
pi@raspberrypi:~ $ sudo pip install --no-deps fmpy
[...]
```
and then getting the fmu: 

```
pi@raspberrypi:~ $ wget https://trac.fmi-standard.org/export/HEAD/branches/public/Test_FMUs/FMI_2.0/CoSimulation/c-code/MapleSim/2017/CoupledClutches/CoupledClutches.fmu
[...]
```
Untill this point it works fine. Now as soon as i try to do any operation on this fmu, i get the following error: 

`pi@raspberrypi:~ $ fmpy info CoupledClutches.fmu`

Error: 

> Traceback (most recent call last):
>   File "/usr/local/bin/fmpy", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/fmpy/command_line.py", line 56, in main
>     dump(args.fmu_filename)
>   File "/usr/local/lib/python2.7/dist-packages/fmpy/__init__.py", line 201, in dump
>     print(fmu_info(filename))
>   File "/usr/local/lib/python2.7/dist-packages/fmpy/util.py", line 489, in fmu_info
>     md = read_model_description(filename, validate=False)
>   File "/usr/local/lib/python2.7/dist-packages/fmpy/model_description.py", line 264, in read_model_description
>     with zipfile.ZipFile(filename, 'r') as zf:
>   File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
>     self._RealGetContents()
>   File "/usr/lib/python2.7/zipfile.py", line 813, in _RealGetContents
>     raise BadZipfile, "File is not a zip file"
> zipfile.BadZipfile: File is not a zip file

**Comment by t-sommer** [comment]
The SVN repo has been moved to GitHub. Please use this URL instead: https://github.com/modelica/fmi-cross-check/raw/master/fmus/2.0/cs/c-code/MapleSim/2016.2/CoupledClutches/CoupledClutches.fmu

I've updated the example. Please re-open the issue if it does not work.

**Comment by aakashsehgal** [comment]
It works. Thanks !

I just had one question. Does the fmu needs to be generated for a specific platform to be run with fmpy ?
I generated one using Matlab for linux 32 but i cannot simulate this:

> Model Info
> 
>   FMI Version       2.0
>   FMI Type          Co-Simulation
>   Model Name        SimTime
>   Description       Simulink model - SimTime
>   Platforms         linux32
>   Continuous States 0
>   Event Indicators  0
>   Variables         1
>   Generation Tool   MATLAB 9.5.0.1067069 (R2018b) Update 4 
>   Generation Date   2019-07-18T09:24:57Z
> 
> Default Experiment
> 
>   Stop Time         100000
>   Step Size         0.001
> 
> Variables (input, output)
> 
> Name                Causality              Start Value  Unit     Description
> SimTime             output                              no_unit~none
> 
> 
> 

when i try to simulate this using : `fmpy simulate SimTime.fmu`, it cannot find the *.so file

`pi@raspberrypi:~ $ fmpy simulate SimTime.fmu
Traceback (most recent call last):
  File "/usr/local/bin/fmpy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/fmpy/command_line.py", line 114, in main
    fmi_call_logger=fmi_call_logger)
  File "/usr/local/lib/python2.7/dist-packages/fmpy/simulation.py", line 560, in simulate_fmu
    result = simulateCS(model_description, fmu_args, start_time, stop_time, relative_tolerance, start_values, apply_default_start_values, input, output, output_interval, timeout, callbacks, debug_logging, step_finished)
  File "/usr/local/lib/python2.7/dist-packages/fmpy/simulation.py", line 788, in simulateCS
    fmu = FMU2Slave(**fmu_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fmpy/fmi2.py", line 496, in __init__
    super(FMU2Slave, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fmpy/fmi2.py", line 85, in __init__
    super(_FMU2, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fmpy/fmi1.py", line 137, in __init__
    self.dll = cdll.LoadLibrary(libraryPath)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /tmp/tmpTEbe7v/binaries/linux32/SimTime.so: cannot open shared object file: No such file or directory`

I unzipped the fmu and checked for the *.so file and it is present under 

> Binaries->linux32->SimTime.so

Any leads regarding this ?

**Comment by t-sommer** [comment]
"linux32" implicitly means "Linux on x86 (32-bit Intel)" in FMI 1.0 and 2.0, which means you have to compile the FMU from source on the target platform (e.g. ARM) or cross-compile on your Desktop.
In FMI 3.0 there will be "platform tuples" (e.g. "x86_64-linux") to address this issue.
