### ISSUE TITLE
Partial checking of fmi-cross-check repo

### ISSUE THREAD

**Issue by ghorwin** [CATIA-Systems/FMPy#88]
It would be helpful to have two optional arguments to validate_repo() to allow for partial processing of the fmi-cross-check repository. You can either only process cs or me trees (filter by fmi_type) and/or by platform ID.

Background is that most vendors will typically only check FMUs for a specific platform at a time, and evaluating FMUs of other (unchanged) platforms is a waste of time and resouces. Considering the constantly growing repository and current evaluation time of the entire repo of more than 3 minutes, this filtering helps reduce this time to a few seconds. Of cource, partial checking should only be done locally before committing via pull-request to the cross-check repo.

Code suggestion:

```python
def validate_repo(vendor_dir, clean_up=False, platform_filter=None, fmi_type_filter=None):

    ...
        if platform not in ['c-code', 'darwin64', 'linux32', 'linux64', 'win32', 'win64']:
            continue

        # new code starts here
        if fmi_type_filter != None and fmi_type != fmi_type_filter:
            continue
        
        if platform_filter != None and platform != platform_filter:
            continue
        # new code ends here
        
        new_problems = validate_cross_check_result(subdir)
    ...


     # similar in the fmu check loop

```

Thanks,
Andreas

**Comment by t-sommer** [comment]
The script has been moved to https://github.com/modelica/fmi-cross-check/.
