### ISSUE TITLE
Variable name "time" crashes GUI

### ISSUE THREAD

**Issue by masoud-najafi** [CATIA-Systems/FMPy#95]
HI,
simulation of this FMU makes fmpy.gui crash with the following error message.

(base) E:\>python -m fmpy.gui
Traceback (most recent call last):
  File "e:\anaconda3\lib\site-packages\fmpy\gui\MainWindow.py", line 689, in updatePlotData
    self.result = np.array(self.simulationThread.rows, dtype=np.dtype(self.simulationThread.cols))
ValueError: field 'time' occurs more than once

[boocwen.zip](https://github.com/CATIA-Systems/FMPy/files/3706359/boocwen.zip)

it works fine in fmpy command line.
please rename  bookwen.zip into boocwen.fmu
thanks
Masoud

**Comment by t-sommer** [comment]
@masoud-najafi, is it really necessary to have a variable called "time"? This creates a lot of problems (also in other tools) since "time" is often used to log the simulation time (e.g. in CSVs).

**Comment by masoud-najafi** [comment]
I know it is really a bad choice, but it is not illegal in FMI-2. Indicating that this is not a good FMU would be sufficient to avoid the crash.
