### ISSUE TITLE
The unit '1' of variable 'd.k' is not defined.

### ISSUE THREAD

**Issue by dafred94** [CATIA-Systems/FMPy#96]
The error reported is:

> Failed to load ***.fmu. The unit '1' of variable 'd.k' is not defined.

It is reported when I try to load an FMU generated from OpenModelica using Reals without physical units. Is there a way to ignore the "illegal" unit of "1"?
When I load and execute the FMU with the normal FMPy interface (i.e. NOT the gui), it works just fine.

**Comment by t-sommer** [comment]
This is essentially the same issue as #81. Please open an issue with OpenModelica so they can improve their implemenation.
