### ISSUE TITLE
Let the user set the value of visible

### ISSUE THREAD

**Issue by vpollex** [CATIA-Systems/FMPy#97]
FMPy must supply an argument `visible` when it instantiates an FMU. Currently (v0.2.13), the value for `visible` is always `false`. To test an FMU that supports the value of `true` for the argument `visible`, it would be helpful if the user can specify the value of `visible`. For example, by a command line argument `--visible` and an additional QCheckBox in the GUI.

**Comment by t-sommer** [comment]
The FMI spec is a bit vague regarding the `visible` flag:

> Argument visible = fmi2False defines that the interaction with the user should be
reduced to a minimum (no application window, no plotting, no animation, etc.). In other
words, the FMU is executed in batch mode. If visible = fmi2True, the FMU is executed
in interactive mode, and the FMU might require to explicitly acknowledge start of simulation /
instantiation / initialization (acknowledgment is non-blocking).

Maybe `visible` should always be `fmi2True` for the CLI and GUI. I never came across an FMU that actually uses the flag. Can you describe your use case or share the FMU?

**Comment by vpollex** [comment]
> Maybe `visible` should always be `fmi2True` for the CLI and GUI. I never came across an FMU that actually uses the flag.

Since you never came across an FMU that uses the flag, I would expect that an FMU usually runs in batch mode. So, I argue for leaving `visible` to be `fmi2False` by default, and only set it to `fmi2True` when the user explicitly requests it.

> Can you describe your use case or share the FMU?

I currently work for [INCHRON](https://www.inchron.com) and we sell [chronSIM](https://www.inchron.com/tool-suite/chronsim/), a product that simulates the timing bahaviour of embedded systems. This simulator produces a trace file, something like a log file of what happens when during the simulation. We also supply [chronVIEW](https://www.inchron.com/tool-suite/chronview/), an application to inspect the trace file that the simulator produces. It is possible to inspect the trace while the simulator writes it to watch _live_ what is happening in the simulator.

As part of a research project we are implementing the FMI standard so that our simulator can be part of a co-simulation. When `visible` is `fmi2False`, then our simulator runs in batch mode, i.e. no application window, no plotting, no animation, etc. But, when `visible` is `fmi2True`, we go into an observation mode where we open chronVIEW (the application window), so that the user can observe the simulation _live_, of course only of what is happening in our simulator.

**Comment by t-sommer** [comment]
Does a8ec75e7a8659c72eec0a929bd8b89e1401b8cfc work for you?

**Comment by vpollex** [comment]
Yes, it works for me, thank you.
