### ISSUE TITLE
Disable 'Read Start Values' menu item when needed

### ISSUE THREAD

**Issue by munsivut** [CATIA-Systems/FMPy#98]
When i press 'Read Start Values' GUI crash if FMU file is not loaded or it not contain platform file (DLL -file).

**Comment by munsivut** [comment]
First case (FMU is not loaded) is closed, but second case still cause crash. When there no exists platform file (.dll) inside FMU then 'Load Start Values' pressing cause crash. I think enabling should behave as below (like simulate button).

```python
self.ui.actionLoadLoadStartValues.setEnabled(can_simulate)
```

**Comment by t-sommer** [comment]
Thanks for you help, @munsivut!
